[SPELL_HERO.MiniPekka_hero]
	CardForm                = "HeroForm"
	Stats                   = "minipekka_hero"
	SummonCharacter         = "MiniPekkaHero"
	IconSWF                 = "sc/ui_card_minipekka_hero.sc"
	IconFile                = "miniPekka_hero_card"
	HighresPlaceholderAsset = "sc/ui_card_info_fx.sc#card_info_fx_hero_small"
	HighresImageFilename    = "sc3d/characters/hero/hero_minipekka/hero_prefab_minipekka_collection"
	UnlockArena             = "TrainingCamp"
	Rarity                  = "Rare"
	ManaCost                = 4
	PrestigeCount           = 2
	Effect                  = "CharacterDeploy"
	OnlyOwnTroops           = true
	TID                     = "TID_SPELL_MINIPEKKA"
	TID_INFO                = "TID_SPELL_INFO_HERO_MINIPEKKA"
	PveDefenseType          = "Defender"

[SPELL_CHARACTER.MiniPekka]
	EvolvedSpells = ["MiniPekka_hero"]
