
[CHARACTER.Assassin]
AttackStartEffect = "assassin_attack_start"
AttacksGround = true
BlueExportName = "bandit"
CollisionRadius = 600
Damage = 76
DamageEffect = "assassin_hit"
DamageEffectSpecial = "assassin_hit_special_red"
DamageExportName = "filter_damage"
DashCooldown = 800
DashDamage = 152
DashEffect = "assassin_dashing"
DashFilter = "filter_bandit_charge"
DashImmuneToDamageTime = 150
DashMaxRange = 6000
DashMinRange = 3500
DashStartEffect = "assassin_dash_start"
DeathEffect = "assassin_die"
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
DeployTime = 1000
FileName = "sc/chr_bandit.sc"
HealthBar = "Medium"
HealthBarOffsetY = -10
HitSpeed = 1000
Hitpoints = 354
JumpSpeed = 500
LandingEffect = "assassin_dash_end"
LoadTime = 600
Mass = 3
MoveEffect = "assassin_steps"
Name = "Assassin"
PrestigeSWF = "sc/chr_prestige_dl.sc"
Range = 750
Rarity = "Common"
RedExportName = "bandit_red"
Scale = 110
ShadowScaleX = 85
ShadowScaleY = 85
ShadowSkew = 35
ShadowY = -10
SightRange = 6000
SpawnEffect = "assassin_deploy"
Speed = 90
TID = "TID_SPELL_ASSASSIN"
UseAnimator = true


