[PROJECTILE.BarbLogProjectile]
AoeToGround = true
DeflectBehaviour = "NoDeflect"
ExportName = "barb_barrel_roll_projectile_blue"
FileName = "sc/chr_barbarian_barrel_dl.sc"
Gravity = 30
HitEffect = "barb_barrel_hit"
MinDistance = 3000
Name = "BarbLogProjectile"
OnlyEnemies = true
PrestigeExportName2 = "barb_barrel_roll_projectile_blue_prestige"
PrestigeRedExportName2 = "barb_barrel_roll_projectile_red_prestige"
PrestigeSWF = "sc/chr_barbarian_barrel_dl.sc"
Radius = 1300
RadiusY = 600
Rarity = "Common"
ShadowExportName = "barb_barrel_projectile_shadow"
ShakesTargets = true
SpawnProjectile = "BarbLogProjectileRolling"
Speed = 360
TrailEffect = "barb_barrel_emitter"

[PROJECTILE.BarbLogProjectileRolling]
AoeToGround = true
Damage = 91
DeathEffect = "vfx_barbarian_barrel_explosion_polish"
DeflectBehaviour = "InvertDirection,UseSpellsTowerDamageMul"
ExportName = "barb_barrel_roll_projectile_blue"
FileName = "sc/chr_barbarian_barrel_dl.sc"
HitEffect = "barb_barrel_hit"
MinDistance = 2500
Name = "BarbLogProjectileRolling"
OnlyEnemies = true
PrestigeExportName2 = "barb_barrel_roll_projectile_blue_prestige"
PrestigeRedExportName2 = "barb_barrel_roll_projectile_red_prestige"
PrestigeSWF = "sc/chr_barbarian_barrel_dl.sc"
ProjectileRadius = 1300
ProjectileRadiusY = 600
ProjectileRange = 4500
Pushback = 0
Rarity = "Common"
RedExportName = "barb_barrel_roll_projectile_red"
ShadowExportName = "barb_barrel_projectile_shadow"
ShakesTargets = true
SpawnCharacter = "Barbarian"
SpawnCharacterDeployTime = 1000
SpawnDeployBaseAnim = "filter_deploy_unit_miner"
Speed = 200
TrailEffect = "barb_barrel_emitter"
