
[CHARACTER.BattleRam]
AttackShakeTime = 500
AttackStartEffect = "blowdart_goblin_atk_start"
AttacksGround = true
BlueExportName = "battle_ram"
ChargeEffect = "battleram_charge"
ChargeRange = 300
ChargeSpeedMultiplier = 200
CollisionRadius = 750
Damage = 112
DamageEffect = "battle_ram_hit_sfx"
DamageExportName = "filter_damage_wobble"
DamageSpecial = 224
DeathEffect = "battle_ram_die"
DeathSpawnCharacter = "Barbarian"
DeathSpawnCount = 2
DeathSpawnDeployTime = 1000
DeathSpawnRadius = 600
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployTime = 1000
FileName = "sc/chr_battle_ram.sc"
HealthBar = "Medium"
HitSpeed = 400
Hitpoints = 378
IgnoreBuff = ["VoodooCurse", "GoblinCurse"]
IgnoreResurrect = true
Kamikaze = true
LoadTime = 350
Mass = 6
MoveEffect = "barbarian_steps"
Name = "BattleRam"
PrestigeExportName2 = "battle_ram_prestige"
PrestigeSWF = "sc/chr_prestige3_dl.sc"
Range = 500
Rarity = "Common"
RedExportName = "battle_ram_red"
Scale = 92
ShadowScaleX = 80
ShadowScaleY = 80
ShadowSkew = 35
SightRange = 6500
SpawnAngleShift = 180
SpawnDeployBaseAnim = "filter_deploy_unit_miner"
SpawnEffect = "battleram_deploy_nodelay"
Speed = 60
TID = "TID_SPELL_BATTLE_RAM"
TargetOnlyBuildings = true
TargetedHitEffect = "battle_ram_hit"
UseAnimator = true
