
[EXT.Bomber_EV1]
Base = "CHARACTER.Bomber"
BlueExportName = "bomber_evolution"
ClonedVersion = "Bomber"
CustomSpawnFilter = "filter_card_evolution"
DeathEffect = "Death_card_evolution_S"
FileName = "sc/chr_bomber_evolution.sc"
HealthBar = "Small_EV1"
HealthBarOffsetY = 0
MoveEffect = "evo_bomber_steps"
PrestigeExportName2 = ""
PrestigeExportName3 = ""
PrestigeSWF = ""
Projectile = "BombSkeletonProjectile_EV1"
ProjectileStartZ = 4800
RedExportName = "bomber_evolution_enemy"
Scale = 52
SpawnEffect = "vfx_bomber_evo_deploy"

[PROJECTILE.BombSkeletonProjectile_EV1]
AoeToGround = true
Damage = 83
ExportName = "bomber_bomb"
FileName = "sc/chr_bomber_evolution.sc"
Gravity = 200
HitEffect = "vfx_bomber_evo_hit"
OnlyEnemies = true
Radius = 1500
Rarity = "Common"
Scale = 55
ShadowExportName = "bomber_bomb_shadow"
SpawnChain = 2
SpawnProjectile = "BombSkeletonProjectile_2_EV1"
Speed = 400
TrailEffect = "vfx_bomber_evo_pjt_fire"

[EXT.BombSkeletonProjectile_2_EV1]
Base = "PROJECTILE.BombSkeletonProjectile_EV1"
HitEffect = "vfx_bomber_evo_hit_02"
ProjectileRange = 3000
