
[CHARACTER.DarkWitch]
AttackStartEffect = "dark_witch_attack_start"
AttacksGround = true
BlueExportName = "dark_witch"
CollisionRadius = 500
CrowdEffects = true
Damage = 123
DamageEffect = "vfx_nightwitch_hit"
DamageExportName = "filter_damage_wobble"
DeathEffect = "dark_witch_die"
DeathSpawnCharacter = "Bat"
DeathSpawnCount = 1
DeathSpawnRadius = 500
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
DeployTime = 1000
FileName = "sc/chr_dark_witch.sc"
HealthBar = "Medium"
HealthBarOffsetY = 20
HitSpeed = 1300
Hitpoints = 354
LoadTime = 550
Mass = 4
MoveEffect = "dark_witch_steps"
Name = "DarkWitch"
PrestigeExportName2 = "dark_witch_prestige"
PrestigeSWF = "sc/chr_prestige3_dl.sc"
Range = 1600
Rarity = "Common"
RedExportName = "dark_witch_red"
Scale = 100
ShadowScaleX = 80
ShadowScaleY = 80
ShadowSkew = 35
SightRange = 5500
SpawnAngleShift = 90
SpawnCharacter = "Bat"
SpawnCharacterEffect = "bat_dark_witch_spawn"
SpawnEffect = "dark_witch_deploy"
SpawnNumber = 2
SpawnPauseTime = 5000
SpawnRadius = 1500
SpawnStartTime = 1000
Speed = 60
TID = "TID_SPELL_DARK_WITCH"
UseAnimator = true
