
[CHARACTER.DarkPrince]
AreaDamageRadius = 1100
AttackStartEffect = "dark_prince_attack_start"
AttacksGround = true
BlueExportName = "BlackKnight_blue"
BlueShieldExportName = "BlackKnight_shield_blue"
ChargeEffect = "dark_prince_charge"
ChargeRange = 300
ChargeSpeedMultiplier = 200
CollisionRadius = 600
Damage = 104
DamageEffect = "dark_prince_hit"
DamageEffectSpecial = "dark_prince_charge_hit"
DamageExportName = "filter_damage"
DamageSpecial = 208
DeathEffect = "dark_prince_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployTime = 1000
FileName = "sc/chr_black_knight.sc"
HealthBar = "Shield"
HealthBarOffsetY = -8
HealthBarOffsetYBlue = 15
HealthBarOffsetYRed = 10
HideHealthbar = true
HitSpeed = 1400
Hitpoints = 469
IgnorePushback = true
JumpEnabled = true
JumpHeight = 4000
JumpSpeed = 160
LandingEffect = "hog_rider_landing"
LoadTime = 1000
Mass = 6
MoveEffect = "dark_prince_steps"
Name = "DarkPrince"
NewHealthBarOffsetXBlue = 2
NewHealthBarOffsetXRed = 2
PrestigeSWF = "sc/chr_prestige_dl.sc"
ProjectileStartRadius = 450
ProjectileStartZ = 450
Range = 1200
Rarity = "Common"
RedExportName = "BlackKnight_red"
RedShieldExportName = "BlackKnight_shield_red"
Scale = 92
ShadowScaleX = 85
ShadowScaleY = 85
ShadowSkew = 35
ShadowY = -10
ShieldHitpoints = 94
ShieldLostEffect = "GuardShieldDown"
SightRange = 5500
SpawnEffect = "dark_prince_deploy"
Speed = 60
TID = "TID_CHARACTER_DARK_PRINCE"
UseAnimator = true
OnStartingClientActions = ["Healthbar_Medium"]
