
[CHARACTER.ElectroSpirit]
AttacksAir = true
AttacksGround = true
BlueExportName = "electrospirit"
CollisionRadius = 400
ContinuousEffect = "electrospirit_continuos_fx"
DamageExportName = "filter_damage"
DeathEffect = "electrospirit_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 400
DeployTime = 1000
FileName = "sc/chr_electro_spirit_dl.sc"
HealthBar = "Small"
HealthBarOffsetY = -10
HitSpeed = 300
Hitpoints = 84
Kamikaze = true
LoadTime = 100
Mass = 1
MoveEffect = "electrospirit_steps"
Name = "ElectroSpirit"
PrestigeSWF = "sc/chr_electro_spirit_dl.sc"
Projectile = "ElectroSpiritProjectile"
ProjectileEffect = "electrospirit_attack"
Range = 2500
Rarity = "Common"
RedExportName = "electrospirit"
Scale = 100
ShadowScaleX = 75
ShadowScaleY = 75
ShadowSkew = 25
ShadowY = -15
SightRange = 5500
SpawnEffect = "electrospirit_deploy"
SpawnRadius = 650
Speed = 120
TID = "TID_SPELL_ELECTRO_SPIRIT"
UseAnimator = true

[PROJECTILE.ElectroSpiritProjectile]
BuffTime = 500
ChainedHitCount = 9
ChainedHitRadius = 3000
Damage = 39
DeflectBehaviour = "NoDeflect"
ExportName = "electrospirit_projectile1_1"
FileName = "sc/chr_electro_spirit_dl.sc"
Gravity = 0
HitEffect = "electrospirit_hit"
Homing = true
Name = "ElectroSpiritProjectile"
OnlyEnemies = true
Rarity = "Common"
Scale = 80
Speed = 1000
TargetBuff = "ZapFreeze"
TargettedEffect = "electrospirit_trail_electric"
TrailEffect = "electrospirit_projectile_trail"
