
[CHARACTER.Fisherman]
AttackStartEffect = "fisherman_attack_start"
AttacksGround = true
BlueExportName = "fisherman"
CollisionRadius = 500
Damage = 76
DamageEffect = "fisherman_hit"
DamageExportName = "filter_damage"
DeathEffect = "fisherman_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 300
DeployTime = 1000
FileName = "sc/chr_fisherman_dl.sc"
HealthBar = "Medium"
HitSpeed = 1300
Hitpoints = 340
LoadTime = 1200
Mass = 10
MoveEffect = "fisherman_steps"
Name = "Fisherman"
ProjectileEffect = "fisherman_projectile_hit"
ProjectileSpecial = "FishermanProjectile"
ProjectileStartRadius = 450
ProjectileStartZ = 450
Range = 1200
Rarity = "Common"
RedExportName = "fisherman_red"
Scale = 100
ShadowScaleX = 80
ShadowScaleY = 80
ShadowSkew = 35
ShadowY = -10
SightRange = 7500
SpawnEffect = "fisherman_deploy"
SpawnRadius = 800
SpecialLoadTime = 1300
SpecialMinRange = 3500
SpecialRange = 7000
Speed = 60
TID = "TID_SPELL_KNIGHT"
UseAnimator = true

[PROJECTILE.FishermanProjectile]
DragBackAsAttractor = true
DragBackSpeed = 850
DragEffect = "hunter_rope_grab"
DragMargin = 200
DragSelfSpeed = 450
ExportName = "fisherman_anchor_projectile"
FileName = "sc/effects.sc"
Homing = true
HomingMinDistance = 5000
HomingTime = 100
Name = "FishermanProjectile"
OnlyEnemies = true
Rarity = "Common"
Scale = 100
ShadowExportName = "projectile_arrow_shadow"
Speed = 800
