
[CHARACTER.Ghost]
AllowAreaDmgWhenInvisible = true
AreaDamageRadius = 1000
AttachedCharacter = "GhostOverlay"
AttackStartEffect = "ghost_attack_start"
AttacksGround = true
BlueExportName = "ghost_blue"
BuffWhenNotAttacking = "Invisibility"
BuffWhenNotAttackingEffect = "BlowdartArrowHit"
BuffWhenNotAttackingRemoveEffect = "BlowdartArrowHit"
BuffWhenNotAttackingTime = 2000
BuffWhenNotAttackingUseAttackRange = true
CollisionRadius = 600
Damage = 102
DamageEffect = "assassin_hit"
DamageExportName = "filter_damage"
DeathEffect = "assassin_die"
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
DeployTime = 1000
FileName = "sc/chr_ghost_dl.sc"
HealthBar = "Medium"
HealthBarOffsetY = -10
HideTimeMs = 400
HitSpeed = 1800
Hitpoints = 473
Hovering = true
LoadTime = 1200
Mass = 3
MoveEffect = "assassin_steps"
Name = "Ghost"
PrestigeSWF = "sc/chr_prestige_dl.sc"
Range = 1200
Rarity = "Common"
RedExportName = "ghost_red"
Scale = 120
ShadowScaleX = 85
ShadowScaleY = 85
ShadowSkew = 35
ShadowY = -10
SightRange = 5500
SpawnEffect = "ghost_deploy"
Speed = 90
TID = "TID_SPELL_GHOST"
UseAnimator = true

[BUFF.Invisibility]
ContinuousEffect = "ghost_aura"
FilterExportName = "filter_invisible"
FilterFile = "sc/effects.sc"
Invisible = true
Name = "Invisibility"
Rarity = "Common"
ShadowAlpha = 20

[CHARACTER.GhostOverlay]
AreaDamageRadius = 1000
AttackStartEffect = "ghost_overlay_attack_start"
AttacksGround = true
BlueExportName = "ghost_blue_overlay"
BuffWhenNotAttacking = "Invisibility"
BuffWhenNotAttackingEffect = "BlowdartArrowHit"
BuffWhenNotAttackingRemoveEffect = "BlowdartArrowHit"
BuffWhenNotAttackingTime = 2000
BuffWhenNotAttackingUseAttackRange = true
CollisionRadius = 600
Damage = 102
DamageEffect = "assassin_hit"
DamageExportName = "filter_damage"
DeathEffect = "assassin_die"
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
DeployTime = 1000
FileName = "sc/chr_ghost_dl.sc"
HealthBar = "Medium"
HealthBarOffsetY = -10
HideTimeMs = 400
HitSpeed = 1800
Hitpoints = 473
Hovering = true
LoadTime = 1200
Mass = 3
MoveEffect = "assassin_steps"
Name = "GhostOverlay"
PrestigeSWF = "sc/chr_prestige_dl.sc"
Range = 1200
Rarity = "Common"
RedExportName = "ghost_red_overlay"
Scale = 100
ShadowScaleX = 85
ShadowScaleY = 85
ShadowSkew = 35
ShadowY = -10
SightRange = 5500
SpawnEffect = "ghost_overlay_deploy"
Speed = 90
TID = "TID_SPELL_GHOST"
UseAnimator = true


