[CHARACTER.GoblinMachine]
Rarity = "Common"
SightRange = 5500
DeployTime = 1000
Speed = 60
Hitpoints = 885
HitSpeed = 1200
LoadTime = 700
Damage = 91
Range = 1200
AttacksGround = true
FileName = "sc/chr_goblin_machine.sc"
BlueExportName = "goblin_machine"
RedExportName = "goblin_machine"
UseAnimator = true
DamageEffect = "Goblin_Machine_HIt"
DeathEffect = "Goblin_Machine_Die"
MoveEffect = "Goblin_Machine_Steps"
SpawnEffect = "Deploy_Goblin_Machine"
DeployBaseAnimExportName="filter_deploy_unit_legendary"
ShadowScaleX = 85
ShadowScaleY = 60
ShadowY = 10
ShadowSkew = 25
Scale = 74
CollisionRadius = 750
Mass = 18
HealthBar = "High"
HealthBarOffsetYRed = -20
HealthBarOffsetYBlue = -20
AttackStartEffect = "Goblin_Machine_Attack_Start"
DamageExportName = "filter_damage_wobble"
ProjectileStartRadius = 500
AttackStateCount = 2
AttackFinishTime = 500
ProjectileStartZ = 1900
TID = "TID_GOBLIN_MACHINE"
IgnorePushback = true
OnStartingAction="goblin_machine_rocket"
OnStartingClientActions=["goblin_machine_visual"]
StatsTags.Damage = "melee_damage"
StatsTags.HitSpeed = "melee_hit_speed"
StatsTags.Hitpoints = "hitpoints"
StatsTags.Speed = "speed"
StatsTags.Range = "melee_range"
StatsTags.Targets = "melee_targets"
StatsTags.Level = "level"
[ACTION.goblin_machine_rocket]
ClassType="ActionTargetIndicatorAttack"
TargetAoE="goblin_machine_rocket_target_signal"
Projectile="GoblinMachineRocketProjectile"
ProjectileOffsetToCharacterLookDirection=-1200
LoadTime=1500
TargetIndicatorDelay=0
AttackDelay=1000
AttackCooldown=4000
Range=5000
MinimumRange=2500
TargetFilter="DefaultCharacterTargets"
TargetStartIndicationAction = "goblin_machine_rocket_load"
GameTagsToSetToStopTargetIndication="UNIT_CUSTOM_TAG_1"
ProjectileStartZ=5000
OnProjectileShootAction="goblin_machine_rocket_hide"
StatsTags.MinRange = "ranged_min_range"
StatsTags.MaxRange = "ranged_max_range"
StatsTags.Cooldown = "cooldown"
[STATS.goblin_machine]
	[[STATS.goblin_machine.stats]]
		Value="melee_damage"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_DAMAGE"
		Icon = "icons_stats_dmg"
	[[STATS.goblin_machine.stats]]
		Value = "melee_damage"
        Value2 = "melee_hit_speed"
		Unit = "DPS"
		TID = "TID_SPELL_ATTRIBUTE_DPS"
		Icon = "icons_stats_dmg_dps"
	[[STATS.goblin_machine.stats]]
		Value = "hitpoints"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_HEALTH"
		Icon = "icons_stats_hp"
	[[STATS.goblin_machine.stats]]
		Value = "melee_hit_speed"
		Unit = "TIME_PRECISE"
		TID = "TID_SPELL_ATTRIBUTE_HIT_SPEED"
		Icon = "icons_stats_dmg_speed"
	[[STATS.goblin_machine.stats]]
		Value = "melee_targets"
		Unit = "TARGETS"
		TID = "TID_SPELL_ATTRIBUTE_TARGET"
		Icon = "icons_stats_target"
	[[STATS.goblin_machine.stats]]
		Value = "speed"
		Unit = "SPEED"
		TID = "TID_SPELL_ATTRIBUTE_SPEED"
		Icon = "icons_stats_speed"
	[[STATS.goblin_machine.stats]]
		Value = "melee_range"
		Unit = "MELEE_RANGE"
		TID = "TID_SPELL_ATTRIBUTE_RANGE"
		Icon = "icons_stats_range"
	[[STATS.goblin_machine.stats]]
		Value = "level"
		Unit = "INTEGER"
		TID = "TID_ROCKET_ATTACK_LEVEL"
		Icon = "icons_stats_rocket"
        InfoButtonStats = "goblin_machine_rocket"
		InfoPopoverTitle = "TID_ROCKET_ATTACK"
[STATS.goblin_machine_rocket]
    [[STATS.goblin_machine_rocket.stats]]
        Value = "ranged_damage"
        Unit = "INTEGER"
        TID = "TID_SPELL_ATTRIBUTE_AREA_DAMAGE"
    	Icon = "icons_stats_dmg_area"
    [[STATS.goblin_machine_rocket.stats]]
        Value = "cooldown"
        Unit = "TIME"
        TID = "TID_SPELL_ATTRIBUTE_HIT_SPEED"
        Icon = "icons_stats_dmg_speed"
    [[STATS.goblin_machine_rocket.stats]]
        Value = "ranged_min_range"
        Value2 = "ranged_max_range"
        Unit = "TILES"
        TID = "TID_SPELL_ATTRIBUTE_RANGE"
        Icon = "icons_stats_range"
    [[STATS.goblin_machine_rocket.stats]]
        Value = "ranged_targets"
        Unit = "TARGETS"
        TID = "TID_SPELL_ATTRIBUTE_TARGET"
        Icon = "icons_stats_target"
[AEO.goblin_machine_rocket_target_signal]
Rarity="Common"
LifeDuration=9999
OnStartingAction="goblin_machine_signal_set"
[ACTION.goblin_machine_signal_set]
	ClassType= "ActionGroup"
	SubActionsDelay = [0, 750]
	SubActions = [
		"goblin_machine_signal_intro",
		"goblin_machine_signal_core"
	]
[ACTION.goblin_machine_signal_intro]
	ClassType="ActionPlayEffect"
	Effect="vfx_goblinmachine_aiming_intro"
[ACTION.goblin_machine_signal_core]
	ClassType="ActionPlayEffect"
	Effect="vfx_goblinmachine_aiming_loop"
	EffectFlags="Looping"
[PROJECTILE.GoblinMachineRocketProjectile]
Name = "GoblinMachineRocketProjectile"
Rarity = "Common"
Speed = 350
FileName = "sc/effects.sc"
ExportName = "projectile_goblin_rocket"
RedExportName = "projectile_goblin_rocket_enemy"
ShadowExportName = "projectile_shadow_rocket"
Scale = 61
HitEffect = "vfx_goblinmachine_explosion"
Damage = 119
CrownTowerDamagePercent = -50
Radius = 1500
AoeToAir = true
AoeToGround = true
OnlyEnemies = true
Gravity = 44
TrailEffect = "vfx_goblinmachine_rocket_smoke"
use360Frames = true
StatsTags.Damage = "ranged_damage"
StatsTags.Targets = "ranged_targets"
[CLIENT_ACTION.goblin_machine_visual]
ClassType="ClientActionAnimatorLayer"
LayerName="goblin_machine_back_rocket"
Filename="sc/chr_goblin_machine.sc"
BlueExportName = "goblin_machine_rocket"
RedExportName = "goblin_machine_rocket_enemy"
Visible=true
[ACTION.goblin_machine_rocket_load]
ClassType="ActionPlayEffect"
Effect="Goblin_Machine_Rocket_Pulse"
SpriteName="goblin_machine_back_rocket"
EffectFlags="Looping"
ForceStopIfTrue="UNIT_CUSTOM_TAG_1"
[ACTION.goblin_machine_rocket_hide]
ClassType="ActionPlayEffect"
Effect="Goblin_Machine_Rocket_Visibility"
SpriteName="goblin_machine_back_rocket"
