
[CHARACTER.GoblinGiant]
AttackStartEffect = "goblin_giant_attack_start"
AttacksGround = true
BlueExportName = "goblin_giant"
CollisionRadius = 750
CrowdEffects = true
Damage = 69
DamageEffect = "goblin_giant_hit"
DamageExportName = "filter_damage_wobble"
DeathEffect = "goblin_giant_die"
DeathSpawnDeployTime = 700
DeathSpawnRadius = 500
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployTime = 1000
FileName = "sc/chr_goblin_giant_dl.sc"
HealthBar = "High"
HitSpeed = 1500
Hitpoints = 1215
IgnorePushback = true
LoadTime = 700
Mass = 18
MoveEffect = "goblin_giant_steps"
Name = "GoblinGiant"
PrestigeExportName2 = "goblin_giant_prestige"
PrestigeExportName3 = "goblin_giant_prestige2"
PrestigeSWF = "sc/chr_goblin_giant_dl.sc"
ProjectileStartRadius = 450
ProjectileStartZ = 450
Range = 1200
Rarity = "Common"
RedExportName = "goblin_giant_red"
Scale = 133
ShadowScaleX = 85
ShadowScaleY = 80
ShadowSkew = 25
SightClip = 2000
SightClipSide = 2000
SightRange = 7500
SpawnAttach = true
SpawnCharacter = "SpearGoblinGiant"
SpawnEffect = "goblin_giant_deploy"
SpawnNumber = 2
SpawnRadius = 900
Speed = 60
StopMovementAfterMS = 640
TID = "TID_SPELL_GIANT"
TargetOnlyBuildings = true
UseAnimator = true
WaitMS = 100

[CHARACTER.SpearGoblinGiant]
AttackStartEffect = "spear_goblin_attack_start"
AttacksAir = true
AttacksGround = true
BlueExportName = "goblin_bag_blue"
CollisionRadius = 500
DamageExportName = "filter_damage"
DeathEffect = "spear_goblin_die"
DeathInheritIgnoreList = true
DeathSpawnCharacter = "SpearGoblin"
DeathSpawnCount = 1
DeathSpawnDeployBaseAnim = "filter_deploy_unit_miner"
DeathSpawnDeployTime = 700
DeployDelay = 400
DeployTime = 1000
FileName = "sc/chr_goblin_giant_dl.sc"
FlyingHeight = 4000
HealthBar = "Small"
HealthBarOffsetY = -10
HitSpeed = 1600
Hitpoints = 52
IgnoreBuff = ["VoodooCurse", "GoblinCurse", "Event_Berserk_OnStartBuff"]
IgnoreResurrect = true
LoadTime = 1100
Mass = 1
MoveEffect = "spear_goblin_steps"
Name = "SpearGoblinGiant"
PrestigeExportName2 = "goblin_bag_prestige"
PrestigeExportName3 = "goblin_bag_prestige2"
PrestigeSWF = "sc/chr_goblin_giant_dl.sc"
Projectile = "SpearGoblinGiantProjectile"
ProjectileEffect = "spear_goblin_attack"
ProjectileStartZ = 600
Range = 5000
Rarity = "Common"
RedExportName = "goblin_bag_red"
Scale = 125
ShadowScaleX = 75
ShadowScaleY = 75
ShadowSkew = 25
ShadowY = -15
SightRange = 5000
SpawnAngleShift = -22
SpawnDeployBaseAnim = "filter_deploy_unit_default"
SpawnMaxAngle = 90
Speed = 120
TID = "TID_CHARACTER_SPEAR_GOBLIN"
UseAnimator = true

[PROJECTILE.SpearGoblinGiantProjectile]
Damage = 32
ExportName = "projectile_spear_360"
FileName = "sc/effects.sc"
Gravity = 150
HitEffect = "spear_goblin_projectile_hit"
Homing = true
Name = "SpearGoblinGiantProjectile"
OnlyEnemies = true
Rarity = "Common"
ShadowExportName = "projectile_arrow_shadow"
Speed = 500
use360Frames = true
