
[CHARACTER.Goblin]
AttackStartEffect = "goblins_attack_start"
AttacksGround = true
BlueExportName = "goblin1"
CollisionRadius = 500
Damage = 49
DamageEffect = "goblins_hit"
DamageExportName = "filter_damage"
DeathEffect = "goblins_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 400
DeployTime = 1000
FileName = "sc/chr_goblin.sc"
HealthBar = "Small"
HitSpeed = 1100
Hitpoints = 79
LoadTime = 700
Mass = 2
MoveEffect = "goblins_steps"
Name = "Goblin"
PrestigeExportName2 = "goblin_prestige"
PrestigeExportName3 = "goblin_prestige2"
PrestigeSWF = "sc/chr_prestige4_dl.sc"
ProjectileStartRadius = 350
ProjectileStartZ = 350
Range = 500
Rarity = "Common"
RedExportName = "goblin1_enemy"
Scale = 100
ShadowScaleX = 50
ShadowScaleY = 50
ShadowSkew = 35
ShadowX = -5
ShadowY = 5
SightRange = 5500
SpawnEffect = "goblins_deploy"
Speed = 120
TID = "TID_CHARACTER_GOBLIN"
UseAnimator = true


