[AEO.GoblinCurse]
    Rarity = "Common"
    LifeDuration = 6000
    Radius = 3000
    HitSpeed = -1
    Filter = "aeo_dummy_no_targets"
    OnStartingAction = "GoblinCurseSet"
[ACTION.GoblinCurseSet]
    ClassType= "ActionGroup"
    SubActionsDelay = [0, 0, 5950]
    SubActions = [
        "GoblinCurseIntro",
        "GoblinCurseCore",
        "GoblinCurseOutro"
    ]
[ACTION.GoblinCurseIntro]
    ClassType="ActionPlayEffect"
    Effect="spell_goblin_curse_intro_shorter"
[ACTION.GoblinCurseCore]
    ClassType = "ActionSpawn"
    SpawnType = "AreaEffectType"
    SpawnData = "GoblinCurseBase"
    
[AEO.GoblinCurseBase]
    Rarity = "Common"
    LifeDuration = 6000
    Radius = 3000
    ScaledEffect = "spell_goblin_curse"
    HitSpeed = 50
    Filter = "CommonAreaDamageFilter"
    OnHitAction="GoblinCurseCreateBuffs"
    StatsTags.LifeDuration="duration"
    StatsTags.Radius="radius"
[ACTION.GoblinCurseCreateBuffs]
    ClassType= "ActionGroup"
    SubActionsDelay = [ 0,0 ]
[[ACTION.GoblinCurseCreateBuffs.SubActions]]
    ClassType = "ActionSpawn"
    SpawnType = "BuffType"
    SpawnData = "GoblinCurse"
    SpawnTime = 100
[[ACTION.GoblinCurseCreateBuffs.SubActions]]
    ClassType = "ActionSpawn"
    SpawnType = "BuffType"
    SpawnData = "GoblinCurseDamage"
    SpawnTime = 100
[BUFF.GoblinCurse]
    Rarity = "Common"
    TID = "TID_GOBLIN_CURSE"
    DeathSpawn = "GoblinCurseGoblin"
    DeathSpawnIsEnemy = true
    DeathSpawnCount = 1
    DeathSpawnDeployDelay = true
    IgnoreBuildings = true
    OtherBuffDeathSpawnAllowed = true
    DeathEffectOverride = "effect_goblin_curse_transform"
    DeathSpawnSameLocation=true
[BUFF.GoblinCurseDamage]
    Rarity = "Common"
    TID = "TID_GOBLIN_CURSE"
    Effect = "PoisonSteam"
    FilterFile = "sc/effects.sc"
    FilterExportName = "filter_poison"
    DamagePerSecond = 14
    CrownTowerDamagePerHit = 4
    HitFrequency = 1000
    SpeedMultiplier = -15
EnableStacking = true
    StatsTags.DamagePerSecond="damagepersec"
    StatsTags.CrownTowerDamagePerHit="tower_damage"
    StatsTags.SpeedMultiplierForStats="speed_multiplier"
[EXT.GoblinCurseGoblin]
    Base = "CHARACTER.Goblin"
    DeathEffect = "Death_goblin_curse"
	StatsTags.Level="level"
    StatsTags.TID = "spawn_tid"
	StatsTags.Hitpoints = "spawn_hitpoints"
	StatsTags.Damage = "spawn_damage"
	StatsTags.HitSpeed = "spawn_hit_speed"
	StatsTags.Speed = "spawn_speed"
	StatsTags.Range = "spawn_range"
	StatsTags.Targets = "spawn_targets"
[ACTION.GoblinCurseOutro]
    ClassType="ActionPlayEffect"
    Effect="spell_goblin_curse_outro"
[STATS.goblin_curse]
	[[STATS.goblin_curse.stats]]
		Value = "damagepersec"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_DPS"
		Icon = "icons_stats_dmg_dps"
	[[STATS.goblin_curse.stats]]
		Value = "tower_damage"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_TOWER_DPS"
		Icon = "icons_stats_dmg_crown"
	[[STATS.goblin_curse.stats]]
		Value = "speed_multiplier"
		Unit = "PERCENT"
		TID = "TID_SPELL_ATTRIBUTE_SLOWDOWN_TROOPS"
		Icon = "icons_stats_speeddown"
    [[STATS.goblin_curse.stats]]
		Value = "level"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_SPAWN_CHARACTER_LEVEL"
		TIDReplacePlaceholders = ["<CHARACTER>"]
		TIDReplaceValues = ["spawn_tid"]
		Icon = "icons_stats_troop"
		InfoPopoverTitle = "spawn_tid"
		InfoButtonStats="goblin_curse_spawn_info"
    [[STATS.goblin_curse.stats]]
		Value = "duration"
		Unit = "TIME_PRECISE"
		TID = "TID_DURATION"
		Icon = "icons_stats_deploy_time"
    [[STATS.goblin_curse.stats]]
		Value = "radius"
		Unit = "TILES"
		TID = "TID_SPELL_ATTRIBUTE_RADIUS"
		Icon = "icons_stats_radius"
[STATS.goblin_curse_spawn_info]
	[[STATS.goblin_curse_spawn_info.stats]]
		Value = "spawn_hitpoints"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_HEALTH"
		Icon = "icons_stats_hp"
	[[STATS.goblin_curse_spawn_info.stats]]
		Value = "spawn_damage"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_DAMAGE"
		Icon = "icons_stats_dmg"
	[[STATS.goblin_curse_spawn_info.stats]]
		Value = "spawn_hit_speed"
		Unit = "TIME_PRECISE"
		TID = "TID_SPELL_ATTRIBUTE_HIT_SPEED"
		Icon = "icons_stats_dmg_speed"
	[[STATS.goblin_curse_spawn_info.stats]]
		Value = "spawn_speed"
		Unit = "SPEED"
		TID = "TID_SPELL_ATTRIBUTE_SPEED"
		Icon = "icons_stats_speed"
	[[STATS.goblin_curse_spawn_info.stats]]
		Value = "spawn_range"
		Unit = "MELEE_RANGE"
		TID = "TID_SPELL_ATTRIBUTE_RANGE"
		Icon = "icons_stats_range"
	[[STATS.goblin_curse_spawn_info.stats]]
		Value = "spawn_targets"
		Unit = "TARGETS"
		TID = "TID_SPELL_ATTRIBUTE_TARGET"
		Icon = "icons_stats_target"
