[EXT.GoblinQueenTower]
    Base = "CHARACTER.KingTower"
    SkinType = "NoSkin"
    FileName = "sc/building_throne_goblin_queen.sc"
    BlueExportName = "throne_queen_blue"
    BlueTopExportName = "throne_queen_blue_top"
    RedExportName = "throne_queen_red"
RedShadowExportName = "throne_queen_red_shadow"
    Scale = 134
    AttachedCharacter = "GoblinQueenTowerTopCharacter"
    ProjectileYOffset = 400
    Projectile = "GoblinQueenProjectile"
    OnStartingAction = "GoblinQueen_StartingAction"
    HealthBarOffsetY = 0
    HealthBarOffsetYRed = -55
    HealthBarOffsetYBlue = 140
    AttachedCharacterOffsetYRed = 1300
    AttachedCharacterOffsetYBlue = -400
    AttachedCharacterHeight = -500
    ShadowScaleX = 150
    ShadowScaleY = 100
    ShadowX = 0
    ShadowY = 60
    ShadowSkew = 25
    AbilityAnimationController = true
    ProjectileEffect = "GoblinQueen_attack"
    DeathEffect = "Goblin_Queen_Throne_Die"
    StatsTags.Hitpoints = "queen_hitpoints"
    StatsTags.HitSpeed = "queen_hit_speed"
    StatsTags.Range = "queen_range"
    
[EXT.GoblinQueenProjectile]
    Base = "PROJECTILE.KingProjectile"
    FileName = "sc/building_throne_goblin_queen.sc"
    ExportName = "Goblin_Queen_projectile"
    TrailEffect = "goblin_queen_projectile_trail"
    HitEffect = "GoblinQueen_Hit"
    Scale = 150
    StatsTags.Damage = "queen_damage"
[CHARACTER.GoblinQueenTowerTopCharacter]
    Rarity = "Common"
    FileName = "sc/chr_goblin_queen_troop.sc"
    BlueExportName = "goblin_queen"
    RedExportName = "goblin_queen_enemy"
    UseAnimator = true
    ShadowScaleX = 100
    ShadowScaleY = 100
    ShadowX = 100
    ShadowY = 100
    ShadowSkew = 25
    Scale = 70
    DamageExportName = "filter_damage"
[CHARACTER.GoblinQueenSecondaryTower]
    Rarity = "Common"
    IsBuilding = true
    IsSummonerTower = true
    SightRange = 7500
    Hitpoints = 1400
    HitSpeed = 800
    Range = 7500
    AttacksGround = true
    AttacksAir = true
    Projectile = "GoblinQueenSecondaryTowerProjectile"
    ProjectileStartRadius = 300
    ProjectileStartZ = 3000
    CollisionRadius = 1000
    NoDeploySizeW = 11
    NoDeploySizeH = 21
    FileName = "sc/chr_goblin_tower_mask.sc"
    BlueExportName = "goblin_mask_tower"
    RedExportName = "goblin_mask_tower_enemy"
    UseAnimator = true
	Scale = 50
    ShadowScaleX = 102
    ShadowScaleY = 70
    ShadowX = -5
    ShadowY = 5
    ShadowSkew = 13
    HealthBar = "Tower"
    ShowHealthNumber = true
    HealthBarOffsetYRed = 10
    HealthBarOffsetYBlue = 100
    DeathEffect = "Goblin_Mask_tower_explode"
    StatsTags.Hitpoints = "baby_tower_hitpoints"
    StatsTags.HitSpeed = "baby_tower_hit_speed"
    StatsTags.Range = "baby_tower_range"
    StatsTags.Targets = "baby_tower_targets"
[EXT.GoblinQueenSecondaryTowerProjectile]
    Base = "PROJECTILE.TowerPrincessProjectile"
    Gravity = 0
    StatsTags.Damage = "baby_tower_damage"
[ACTION.GoblinQueen_StartingAction]
    ClassType = "ActionGroup"
    SubActionsDelay = [0, 0]
    SubActions = ["GoblinQueen_WaitForTowerActivation", "GoblinQueen_AbilityActivator"]
[ACTION.GoblinQueen_WaitForTowerActivation]
    ClassType = "ActionWaitToActivate"
    Condition = "king_tower_damaged() || coop_king_tower_damaged() || tower_destroyed() || coop_tower_destroyed()"
    GameTagsToSet = "INACTIVE"
[ACTION.GoblinQueen_WaitForTowerActivation.OnActivateAction]
    ClassType = "ActionWithDuration"
    ActionDuration = 3300
    GameTagsToSet = "ACTIVATING"
    NextAction = "GoblinQueen_ActivationEffect"
[ACTION.GoblinQueen_ActivationEffect]
    ClassType = "ActionPlayEffect"
    Effect = "goblin_queen_activate"
[ACTION.GoblinQueen_AbilityActivator]
    ClassType = "ActionActivateOnCardDeploy"
    ElixirCost = 20
    CardGroup = "Goblins"
    EvaluateDeployedCard = false
    OnActivateAction = "GoblinQueen_AbilityTrigger"
    IndicatorFileName="sc/ui.sc"
    IndicatorExportName="goblin_queen_charge_counter"
    IndicatorOffsetYBlue=-65
    IndicatorOffsetYRed=38
    IndicatorPlaceholderInstanceName="icon_ability_placeholder"
    IndicatorReplacementFileName="sc/ui_spells.sc"
    IndicatorReplacementExportName="icon_goblin_queen_ability_baby"
    ShowCardEffect=true
    CardEffectUnderlayName="card_item_goblin_queen_fire"
    CardEffectOverlayName="card_item_goblin_queen_glow"
    ElixirGainEffect = "goblin_queen_elixir_gain"
    ElixirGainFullEffect = ""
    ElixirFullLoopEffect = "goblin_queen_elixir_gain_ability_ready"
    DeployElixirGainEffect = "Deploy_Goblin_Card_Elixir_Gain"
    DeployElixirGainFullEffect = "Deploy_Goblin_Card"
    DeployActivateEffect = "Deploy_Goblin_Card_Activate"
    IgnoreDeployEffectCards = ["GoblinBarrel","GoblinDrill","GoblinCurse"]
    GameTagsToSetOnReadyToActivate = "ABILITY_READY"
[ACTION.GoblinQueen_AbilityTrigger]
    ClassType = "ActionGroup"
    SubActionsDelay = [0, 0, 500, 500, 700, 700, 900, 900, 1100, 1100]
    SubActions = [ 
        "GoblinQueen_Ability_Set_Tags", 
        "GoblinQueen_Ability_Effect", 
        "GoblinQueen_Ability_BabyGoblin_L1",
        "GoblinQueen_Ability_BabyGoblin_R1", 
        "GoblinQueen_Ability_BabyGoblin_L2", 
        "GoblinQueen_Ability_BabyGoblin_R2", 
        "GoblinQueen_Ability_BabyGoblin_L3", 
        "GoblinQueen_Ability_BabyGoblin_R3", 
        "GoblinQueen_Ability_BabyGoblin_L4", 
        "GoblinQueen_Ability_BabyGoblin_R4" 
    ]
    StatsTags.ActionCount_GoblinQueen_Ability_BabyGoblin = "spawn_count"
[ACTION.GoblinQueen_Ability_Set_Tags]
    ClassType = "ActionWithDuration"
    ActionDuration = 1800
    GameTagsToSet = "ABILITY_ACTIVATION,NO_ATTACK" 
[ACTION.GoblinQueen_Ability_Effect]
    ClassType = "ActionPlayEffect"
    Effect = "goblin_queen_ability_activate"
[ACTION.GoblinQueen_Ability_BabyGoblin_L1]
    ClassType = "ActionSpawnToLocation"
    SpawnType = "ProjectileType"
    SpawnData = "BabyGoblin_Projectile"
    MirroredX = 1
    MirroredY = 0
    TargetExprX = "x-7000"
    TargetExprY = "y-17000*team_y_direction(team_index)"
[ACTION.GoblinQueen_Ability_BabyGoblin_L2]
    ClassType = "ActionSpawnToLocation"
    SpawnType = "ProjectileType"
    SpawnData = "BabyGoblin_Projectile"
    MirroredX = -1
    MirroredY = 2
    TargetExprX = "x-4500"
    TargetExprY = "y-17000*team_y_direction(team_index)"
[ACTION.GoblinQueen_Ability_BabyGoblin_L3]
    ClassType = "ActionSpawnToLocation"
    SpawnType = "ProjectileType"
    SpawnData = "BabyGoblin_Projectile"
    MirroredX = 1
    MirroredY = 2
    TargetExprX = "x-3000"
    TargetExprY = "y-17000*team_y_direction(team_index)"
[ACTION.GoblinQueen_Ability_BabyGoblin_L4]
    ClassType = "ActionSpawnToLocation"
    SpawnType = "ProjectileType"
    SpawnData = "BabyGoblin_Projectile"
    MirroredX = 1
    MirroredY = 0
    TargetExprX = "x-1000"
    TargetExprY = "y-17000*team_y_direction(team_index)"
[ACTION.GoblinQueen_Ability_BabyGoblin_R1]
    ClassType = "ActionSpawnToLocation"
    SpawnType = "ProjectileType"
    SpawnData = "BabyGoblin_Projectile"
    MirroredX = 0
    MirroredY = 0
    TargetExprX = "x+7000"
    TargetExprY = "y-17000*team_y_direction(team_index)"
[ACTION.GoblinQueen_Ability_BabyGoblin_R2]
    ClassType = "ActionSpawnToLocation"
    SpawnType = "ProjectileType"
    SpawnData = "BabyGoblin_Projectile"
    MirroredX = 1
    MirroredY = 0
    TargetExprX = "x+4500"
    TargetExprY = "y-17000*team_y_direction(team_index)"
[ACTION.GoblinQueen_Ability_BabyGoblin_R3]
    ClassType = "ActionSpawnToLocation"
    SpawnType = "ProjectileType"
    SpawnData = "BabyGoblin_Projectile"
    MirroredX = 1
    MirroredY = 0
    TargetExprX = "x+3000"
    TargetExprY = "y-17000*team_y_direction(team_index)"
[ACTION.GoblinQueen_Ability_BabyGoblin_R4]
    ClassType = "ActionSpawnToLocation"
    SpawnType = "ProjectileType"
    SpawnData = "BabyGoblin_Projectile"
    MirroredX = -1
    MirroredY = 2
    TargetExprX = "x+1000"
    TargetExprY = "y-17000*team_y_direction(team_index)"
[PROJECTILE.BabyGoblin_Projectile]
    Rarity = "Common"
    Speed = 400
    Scale = 60
    Gravity = 40
    FileName = "sc/chr_baby_goblin_dagger_troop.sc"
    ExportName = "baby_goblin_2_fly"
    RedExportName = "baby_goblin_2_fly_enemy"
    ShadowExportName = "baby_goblin_fly_nest_shadow"
    SpawnCharacter = "BabyGoblin"
    HitEffect = "BabyGoblin_land_effect"
    TrailEffect = "BabyGoblin_Fly_Emitter"
[CHARACTER.BabyGoblin]
    Rarity = "Common"
    TID = "TID_CHARACTER_BABY_GOBLIN"
    SightRange = 5500
    DeployTime = 1000
    Speed = 120
    Hitpoints = 59
    HitSpeed = 900
    LoadTime = 500
    Damage = 34
    Range = 500
    AttacksGround = true
    FileName = "sc/chr_baby_goblin_dagger_troop.sc"
    BlueExportName = "baby_goblin2"
    RedExportName = "baby_goblin2_red"
    UseAnimator = true
    ShadowScaleX = 85
    ShadowScaleY = 60
    ShadowY = 10
    ShadowSkew = 25
    Scale = 50
    CollisionRadius = 500
    Mass = 1
    HealthBar = "Small"
    DamageExportName = "filter_damage"
    DeployDelay = 400
    DeployBaseAnimExportName = "filter_deploy_unit_default"
    DeathEffect = "Death_goblin_curse"
    StatsTags.Hitpoints = "spawn_hitpoints"
    StatsTags.Damage = "spawn_damage"
    StatsTags.HitSpeed = "spawn_hit_speed"
    StatsTags.Speed = "spawn_speed"
    StatsTags.Range = "spawn_range"
    StatsTags.Targets = "spawn_targets"
    StatsTags.TID = "spawn_tid"
[STATS.goblin_queen]
    [[STATS.goblin_queen.stats]]
        Value = "queen_damage"
        Unit = "INTEGER"
        TID = "TID_SPELL_ATTRIBUTE_DAMAGE"
        Icon = "icons_stats_dmg"
    [[STATS.goblin_queen.stats]]
        Value = "queen_hitpoints"
        Unit = "INTEGER"
        TID = "TID_SPELL_ATTRIBUTE_HEALTH"
        Icon = "icons_stats_hp"
    [[STATS.goblin_queen.stats]]
        Value = "queen_hit_speed"
        Unit = "TIME_PRECISE"
        TID = "TID_SPELL_ATTRIBUTE_HIT_SPEED"
        Icon = "icons_stats_dmg_speed"
    [[STATS.goblin_queen.stats]]
        Value = "queen_range"
        Unit = "TILES"
        TID = "TID_SPELL_ATTRIBUTE_RANGE"
        Icon = "icons_stats_range"
[STATS.goblin_queen_ability]
    [[STATS.goblin_queen_ability.stats]]
		Value = "spawn_count"
		Unit = "COUNT"
		TID = "TID_SPELL_ATTRIBUTE_SPAWN_CHARACTER_COUNT"
		TIDReplacePlaceholders = ["<CHARACTER>"]
		TIDReplaceValues = ["spawn_tid"]
		Icon = "icons_stats_troop_count"
    [[STATS.goblin_queen_ability.stats]]
		Value = "spawn_hitpoints"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_HEALTH"
		Icon = "icons_stats_hp"
    [[STATS.goblin_queen_ability.stats]]
        Value = "spawn_hit_speed"
        Unit = "TIME_PRECISE"
        TID = "TID_SPELL_ATTRIBUTE_HIT_SPEED"
        Icon = "icons_stats_dmg_speed"
    [[STATS.goblin_queen_ability.stats]]
        Value = "spawn_damage"
        Unit = "INTEGER"
        TID = "TID_SPELL_ATTRIBUTE_DAMAGE"
        Icon = "icons_stats_dmg"
    [[STATS.goblin_queen_ability.stats]]
        Value = "spawn_damage"
        Value2 = "spawn_hit_speed"
        Unit = "DPS"
        TID = "TID_SPELL_ATTRIBUTE_DPS"
        Icon = "icons_stats_dmg_dps"
    [[STATS.goblin_queen_ability.stats]]
        Value = "spawn_targets"
        Unit = "TARGETS"
        TID = "TID_SPELL_ATTRIBUTE_TARGET"
        Icon = "icons_stats_target"
    [[STATS.goblin_queen_ability.stats]]
        Value = "spawn_speed"
        Unit = "SPEED"
        TID = "TID_SPELL_ATTRIBUTE_SPEED"
        Icon = "icons_stats_speed"
    [[STATS.goblin_queen_ability.stats]]
        Value = "spawn_range"
		Unit = "MELEE_RANGE"
		TID = "TID_SPELL_ATTRIBUTE_RANGE"
		Icon = "icons_stats_range"
[STATS.baby_goblin]
    [[STATS.baby_goblin.stats]]
        Value = "baby_tower_hitpoints"
        Unit = "INTEGER"
        TID = "TID_SPELL_ATTRIBUTE_HEALTH"
        Icon = "icons_stats_hp"
    [[STATS.baby_goblin.stats]]
        Value = "baby_tower_damage"
        Value2 = "baby_tower_hit_speed"
        Unit = "DPS"
        TID = "TID_SPELL_ATTRIBUTE_DPS"
        Icon = "icons_stats_dmg_dps"
    [[STATS.baby_goblin.stats]]
        Value = "baby_tower_damage"
        Unit = "INTEGER"
        TID = "TID_SPELL_ATTRIBUTE_DAMAGE"
        Icon = "icons_stats_dmg"
    [[STATS.baby_goblin.stats]]
        Value = "baby_tower_hit_speed"
        Unit = "TIME_PRECISE"
        TID = "TID_SPELL_ATTRIBUTE_HIT_SPEED"
        Icon = "icons_stats_dmg_speed"
    [[STATS.baby_goblin.stats]]
        Value = "baby_tower_targets"
        Unit = "TARGETS"
        TID = "TID_SPELL_ATTRIBUTE_TARGET"
        Icon = "icons_stats_target"
    [[STATS.baby_goblin.stats]]
        Value = "baby_tower_range"
        Unit = "TILES"
        TID = "TID_SPELL_ATTRIBUTE_RANGE"
        Icon = "icons_stats_range"
