[EXT.GoblinDrill_EV1]
    Base="BUILDING.GoblinDrill"
	FileName="sc/building_goblin_drill_evolution.sc"
	BlueExportName="goblin_drill_evolution"
	RedExportName="goblin_drill_evolution_enemy"
    HealthBar="High_3_Segments_EV1"
    OnStartingAction="GoblinDrill_EV1_start"
    Scale=110
    SpawnPathfindEffect ="vfx_goblindrill_evo_underground_trail"
    DeathEffect="goblin_drill_evolution_die"
    ClonedVersion="GoblinDrill"
    PrestigeSWF=""
    PrestigeExportName=""
    PrestigeExportName2=""
    PrestigeExportName3=""
    PrestigeRedExportName=""
    PrestigeRedExportName2=""
    PrestigeRedExportName3=""
[ACTION.GoblinDrill_EV1_start]
    ClassType="ActionGroup"
    SubActions = ["GoblinDrill_EV1_relocate", "GoblinDrill_EV1_appear_effect"]
    SubActionsDelay = [ 0, 0 ]
[ACTION.GoblinDrill_EV1_relocate]
    ClassType="ActionGoblinDrillEvoRelocate"
    HideTime=1000
    SpawnCharaterRadius = 200
    OnHideEffect="vfx_goblindrill_evo_hide"
    OnReappearEffect="vfx_goblindrill_evo_deploy"
    TargetEffectList=["Evo_Drill_target1", "Evo_Drill_target2"]
    HideHpThresholds=[66, 33]
    UseDistanceBasedPositioning=true
    FirstAppearAction="GoblinDrill_EV1_reappearDamage"
    HideActions = ["GoblinDrill_EV1_Hide_Group", "GoblinDrill_EV1_Hide_Group2"]
    [ACTION.GoblinDrill_EV1_Hide_Group]
	ClassType = "ActionGroup"
	SubActions = ["GoblinDrill_EV1_Disable_Physics", "GoblinDrill_EV1_Spawn_Goblin1", "GoblinDrill_EV1_Spawn_Goblin2"]
    SubActionsDelay = [0, 50, 50]
    [ACTION.GoblinDrill_EV1_Hide_Group2]
	ClassType = "ActionGroup"
SubActions = ["GoblinDrill_EV1_Disable_Physics", "GoblinDrill_EV1_Spawn_Goblin3"]
SubActionsDelay = [0, 50]
    [ACTION.GoblinDrill_EV1_Spawn_Goblin1] 
    ClassType = "ActionSpawnToLocation"
    SpawnType = "CharacterType"
    SpawnData = "Goblin"
    DeployTime = 500
    RelativeX = -1
RelativeY = 0
    [ACTION.GoblinDrill_EV1_Spawn_Goblin2]  
    ClassType = "ActionSpawnToLocation"
    SpawnType = "CharacterType"
    SpawnData = "Goblin"
    DeployTime = 500
    RelativeX = 1
    RelativeY = 0
[ACTION.GoblinDrill_EV1_Spawn_Goblin3]
    ClassType = "ActionSpawnToLocation"
    SpawnType = "CharacterType"
    SpawnData = "Goblin"
    DeployTime = 500
    RelativeX = -1
    RelativeY = 0
    [ACTION.GoblinDrill_EV1_Spawn_Goblin4]
    ClassType = "ActionSpawnToLocation"
    SpawnType = "CharacterType"
    SpawnData = "Goblin"
    DeployTime = 500
    RelativeX = 1
    RelativeY = 0
[ACTION.GoblinDrill_EV1_Disable_Physics]
	ClassType = "ActionWithDuration"
	ActionDuration = 1000
	GameTagsToSet = "DISABLE_PHYSICAL_INTERACTIONS_WITH_OBJECTS"
[ACTION.GoblinDrill_EV1_reappearDamage]
    ClassType="ActionSpawn"
    SpawnType = "AreaEffectType"
    SpawnData = "GoblinDrillDamageArea"
    ParentGOAsSource=true
    
[ACTION.GoblinDrill_EV1_appear_effect]
    ClassType="ActionPlayEffect"
    Effect = "goblin_drill_evolution_deploy"
[EXT.GoblinDrill_EV1_Dig]
	Base="CHARACTER.GoblinDrillDig"
	SpawnPathfindMorph="GoblinDrill_EV1"
	FileName="sc/building_goblin_drill_evolution.sc"
	BlueExportName="goblin_drill_evolution_ghost"
	RedExportName="goblin_drill_evolution_ghost"
	SpawnPathfindEffect ="vfx_goblindrill_evo_underground_trail"
    PrestigeSWF=""
    PrestigeExportName=""
    PrestigeExportName2=""
    PrestigeExportName3=""
    PrestigeRedExportName=""
    PrestigeRedExportName2=""
    PrestigeRedExportName3=""
