
[BUILDING.GoblinCage]
AttacksGround = true
BlueExportName = "cage_goblin_blue"
CollisionRadius = 1000
DamageExportName = "filter_damage_wobble"
DeathEffect = "goblin_cage_die"
DeathSpawnCharacter = "GoblinBrawler"
DeathSpawnCount = 1
DeathSpawnDeployBaseAnim = "filter_deploy_unit_miner"
DeathSpawnDeployTime = 500
DeployTime = 1000
FileName = "sc/chr_goblin_thug_dl.sc"
HealthBar = "Medium"
HitSpeed = 10000
Hitpoints = 305
IsBuilding = true
LifeTime = 20000
Name = "GoblinCage"
OnStartingAction = "goblin_cage_shake_when_target"
PrestigeExportName2 = "cage_goblin_prestige2_blue"
PrestigeExportName3 = "cage_goblin_prestige3_blue"
PrestigeRedExportName2 = "cage_goblin_prestige2_red"
PrestigeRedExportName3 = "cage_goblin_prestige3_red"
PrestigeSWF = "sc/chr_goblin_thug_dl.sc"
ProjectileStartRadius = 400
ProjectileStartZ = 400
Range = 5000
Rarity = "Common"
RedExportName = "cage_goblin_red"
Scale = 100
ShadowScaleX = 90
ShadowScaleY = 60
ShadowSkew = 5
ShadowX = -8
SightRange = 20000
SpawnEffect = "goblin_cage_deploy"
TID = "TID_BUILDING_GOBLINCAGE"

[ACTION.goblin_cage_shake_when_target]
ClassType = "ActionPlayAnimationIfHasTarget"
IdleEndFrame = "idle_stop"
IdleStartFrame = "idle_start"
Priority = 50
TargetEndFrame = "shake_end"
TargetStartFrame = "shake_start"

[CHARACTER.GoblinBrawler]
AttackFinishTime = 500
AttackStartEffect = "goblin_brawler_attack_start"
AttackStateCount = 2
AttacksGround = true
BlueExportName = "goblin_thug"
CollisionRadius = 500
Damage = 132
DamageEffect = "goblin_brawler_hit"
DamageExportName = "filter_damage"
DeathEffect = "goblin_brawler_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 400
DeployTime = 1000
FileName = "sc/chr_goblin_thug_dl.sc"
HealthBar = "Medium"
HitSpeed = 1100
Hitpoints = 438
LoadTime = 900
Mass = 2
MoveEffect = "goblin_brawler_steps"
Name = "GoblinBrawler"
PrestigeExportName2 = "goblin_thug_prestige2"
PrestigeExportName3 = "goblin_thug_prestige3"
PrestigeSWF = "sc/chr_goblin_thug_dl.sc"
ProjectileStartRadius = 350
ProjectileStartZ = 350
Range = 800
Rarity = "Common"
RedExportName = "goblin_thug_red"
Scale = 100
ShadowScaleX = 50
ShadowScaleY = 50
ShadowSkew = 35
ShadowX = -5
ShadowY = 5
SightRange = 5500
SpawnEffect = "goblin_brawler_deploy"
Speed = 90
TID = "TID_CHARACTER_GOBLINBRAWLER"
UseAnimator = true
