
[CHARACTER.HogRider]
AttackStartEffect = "hog_rider_attack_start"
AttacksGround = true
BlueExportName = "hog_rider"
CollisionRadius = 600
Damage = 124
DamageEffect = "hog_rider_hit"
DamageExportName = "filter_damage"
DeathEffect = "hog_rider_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 400
DeployTime = 1000
FileName = "sc/chr_hog_rider.sc"
HealthBar = "Medium"
HealthBarOffsetY = -15
HitSpeed = 1600
Hitpoints = 663
JumpEnabled = true
JumpHeight = 4000
JumpSpeed = 160
LandingEffect = "hog_rider_landing"
LoadTime = 1000
Mass = 4
MoveEffect = "hog_rider_steps"
Name = "HogRider"
PrestigeExportName2 = "hog_rider_prestige"
PrestigeExportName3 = "hog_rider_prestige2"
PrestigeSWF = "sc/chr_prestige4_dl.sc"
ProjectileStartRadius = 450
ProjectileStartZ = 450
Range = 800
Rarity = "Common"
RedExportName = "hog_rider_red"
Scale = 95
ShadowScaleX = 85
ShadowScaleY = 85
ShadowSkew = 35
ShadowY = -10
SightClip = 4000
SightClipSide = 4000
SightRange = 9500
SpawnEffect = "hog_rider_deploy"
Speed = 120
TID = "TID_SPELL_HOG_RIDER"
TargetOnlyBuildings = true
UseAnimator = true
OnStartingAction = "JumpHack_Check_Jump_Interval"
