
[CHARACTER.LavaHound]
AttacksAir = true
AttacksGround = true
BlueExportName = "lava_hound"
CollisionRadius = 750
CrowdEffects = true
DamageExportName = "filter_damage_wobble"
DeathEffect = "lava_hound_die"
DeathSpawnCharacter = "LavaPups"
DeathSpawnCount = 6
DeathSpawnPushback = true
DeathSpawnRadius = 2500
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
DeployTime = 1000
FileName = "sc/chr_lava_hound.sc"
FlyingHeight = 4000
HealthBar = "High"
HitSpeed = 1300
Hitpoints = 1399
IgnoreBuff = ["VoodooCurse", "GoblinCurse"]
IgnorePushback = true
IgnoreResurrect = true
LoadTime = 300
Mass = 5
MoveEffect = "lava_hound_steps"
Name = "LavaHound"
PrestigeExportName2 = "lava_hound_prestige"
PrestigeSWF = "sc/chr_prestige5_dl.sc"
Projectile = "LavaHoundProjectile"
ProjectileEffect = "lava_hound_attack_start"
ProjectileStartRadius = 1000
ProjectileStartZ = 1800
Range = 3500
Rarity = "Common"
RedExportName = "lava_hound_red"
Scale = 100
ShadowScaleX = 85
ShadowScaleY = -60
ShadowY = 20
SightRange = 5500
SpawnEffect = "lava_hound_deploy"
Speed = 45
TID = "TID_SPELL_LAVA_HOUND"
TargetOnlyBuildings = true
UseAnimator = true

[PROJECTILE.LavaHoundProjectile]
AoeToAir = true
AoeToGround = true
Damage = 21
ExportName = "particle_coal1"
FileName = "sc/effects.sc"
Gravity = 250
HitEffect = "lava_hound_projectile_hit"
Homing = true
Name = "LavaHoundProjectile"
OnlyEnemies = true
Rarity = "Common"
ShadowExportName = "projectile_arrow_shadow"
Speed = 400
TrailEffect = "vfx_lavahound_pjt"

[CHARACTER.LavaPups]
AttacksAir = true
AttacksGround = true
BlueExportName = "lava_pups"
CollisionRadius = 450
DamageExportName = "filter_damage_wobble"
DeathEffect = "lava_pups_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployTime = 1000
FileName = "sc/chr_lava_pups.sc"
FlyingHeight = 3500
HealthBar = "Small"
HitSpeed = 1700
Hitpoints = 84
LoadTime = 700
Mass = 5
MoveEffect = "lava_pups_steps"
Name = "LavaPups"
PrestigeSWF = "sc/chr_prestige_dl.sc"
Projectile = "LavaPupProjectile"
ProjectileEffect = "lava_pups_attack_start"
ProjectileStartRadius = 500
ProjectileStartZ = 100
Range = 1600
Rarity = "Common"
RedExportName = "lava_pups"
Scale = 80
ShadowScaleX = 85
ShadowScaleY = -60
ShadowY = 20
SightRange = 5500
SpawnEffect = "lava_pups_deploy"
Speed = 60
TID = "TID_CHARACTER_LAVA_PUPS"
UseAnimator = true

[PROJECTILE.LavaPupProjectile]
AoeToAir = true
AoeToGround = true
Damage = 32
ExportName = "particle_coal1"
FileName = "sc/effects.sc"
Gravity = 250
HitEffect = "lava_pups_projectile_hit"
Homing = true
Name = "LavaPupProjectile"
OnlyEnemies = true
Rarity = "Common"
ShadowExportName = "projectile_arrow_shadow"
Speed = 500
TrailEffect = "lava_pups_emitter"
