
[CHARACTER.MiniZapMachine]
AttacksAir = true
AttacksGround = true
BlueExportName = "zappie_blue"
BuffOnDamage = "ZapFreeze"
BuffOnDamageTime = 500
CollisionRadius = 600
Damage = 46
DamageEffect = "vfx_zappies_hit"
DeathEffect = "zapper_die"
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
DeployTime = 1000
FileName = "sc/chr_zappies_dl.sc"
HealthBar = "Medium"
HealthBarOffsetY = -10
HitSpeed = 2300
Hitpoints = 207
LoadAttackEffect1 = "zapper_load_1"
LoadAttackEffect2 = "zapper_load_2"
LoadAttackEffect3 = "zapper_load_3"
LoadTime = 1500
Mass = 4
MoveEffect = "zapper_steps"
Name = "MiniZapMachine"
OverrideAttackFinishTime = true
PrestigeExportName2 = "zappie_prestige"
PrestigeRedExportName2 = "zappie_prestige_red"
PrestigeSWF = "sc/chr_zappies_dl.sc"
ProjectileStartRadius = 1200
ProjectileStartZ = 1800
Range = 4500
Rarity = "Common"
RedExportName = "zappie_red"
RotateAngleSpeed = 600
Scale = 95
ShadowScaleX = 80
ShadowScaleY = -70
ShadowSkew = -15
ShadowX = -8
ShadowY = 15
SightRange = 5000
SpawnEffect = "zapper_deploy"
Speed = 60
TID = "TID_SPELL_MINI_ZAPMACHINE"
TargetEffectY = -20
TargetedEffectVisualPushback = 750
TargetedHitEffect = "zappie_beam"
UseAnimator = true
