[CHARACTER.Phoenix]
AttackStartEffect = "phoenix_attack_start"
AttacksAir = true
AttacksGround = true
BlueExportName = "Phoenix"
CollisionRadius = 500
ContinuousEffect = "phoenix_idle"
Damage = 85
DamageExportName = "filter_damage_wobble"
DeathEffect = "phoenix_die"
DeathSpawnProjectile = "PhoenixFireball"
DeathSpawnRadius = 1500
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployTime = 1000
FileName = "sc/chr_phoenix_dl.sc"
FlyingHeight = 3000
HealthBar = "Medium"
HitSpeed = 1000
Hitpoints = 411
LoadTime = 400
Mass = 2
MoveEffect = "Phoenix_Wing"
Name = "Phoenix"
ProjectileEffect = "phoenix_attack_start"
ProjectileStartRadius = 500
ProjectileStartZ = 1900
Range = 1600
Rarity = "Common"
RedExportName = "Phoenix"
Scale = 70
ShadowScaleX = 85
ShadowScaleY = -60
ShadowY = 15
SightRange = 5500
SpawnEffect = "phoenix_deploy"
Speed = 60
TID = "TID_SPELL_PHOENIX"
UseAnimator = true
[PROJECTILE.PhoenixFireball]
AoeToAir = true
AoeToGround = true
Damage = 64
DeflectBehaviour = "NoDeflect"
ExportName = "fireball_projectile1"
FileName = "sc/effects.sc"
Gravity = 50
HitEffect = "Blue_Phoenix_explosion"
Name = "PhoenixFireball"
OnlyEnemies = true
Pushback = 2000
Radius = 2500
Rarity = "Common"
ShadowExportName = "projectile_arrow_shadow"
SpawnCharacter = "PhoenixEgg"
Speed = 600
TrailEffect = "FireballEmitter"
[CHARACTER.PhoenixEgg]
AttacksGround = true
BlueExportName = "Egg_Phoenix_V2_Blue"
CollisionRadius = 600
ContinuousEffect = "Egg_blue_phoenix_idle"
DamageExportName = "filter_damage"
DeathEffect = "egg_phoenix_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 400
DeployTime = 1000
DestroyAtLimit = true
DestroyAtLimitEffect = "egg_phoenix_die"
FileName = "sc/chr_phoenix_dl.sc"
GameTagsToSet = "NO_GIANTBUFFER_CHEF_ENCHANTMENT,AVOIDANCE_AS_OBSTACLE,NO_MOVE_ALLOW_ATTRACT"
HealthBar = "Small"
HealthBarOffsetY = 45
HitSpeed = 1000
Hitpoints = 124
IgnoreBuff = ["VoodooCurse", "GoblinCurse"]
IgnoreResurrect = true
LoadTime = 500
Mass = 3
Name = "PhoenixEgg"
ProjectileStartRadius = 450
ProjectileStartZ = 450
Range = 5500
Rarity = "Common"
RedExportName = "Egg_Phoenix_V2"
Scale = 80
ShadowScaleX = 90
ShadowScaleY = 60
ShadowSkew = 35
SightRange = 5500
SpawnCharacter = "PhoenixNoRespawn"
SpawnCharacterEffect = "battle_healer_deploy_prestige"
SpawnCharacterWithDeploy = true
SpawnLimit = 1
SpawnNumber = 1
SpawnPauseTime = 4300
SpawnStartTime = 3800
Speed = 40
TID = "TID_SPELL_PHOENIX_EGG"
UntargetableWhenSpawned = true
[CHARACTER.PhoenixNoRespawn]
AttackStartEffect = "phoenix_attack_start"
AttacksAir = true
AttacksGround = true
BlueExportName = "Phoenix"
CollisionRadius = 500
ContinuousEffect = "phoenix_idle_reborn"
Damage = 85
DamageExportName = "filter_damage_wobble"
DeathEffect = "phoenix_die"
DeployAnimationOverride = "_reborn1_"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployTime = 733
FileName = "sc/chr_phoenix_dl.sc"
FlyingHeight = 3000
HealthBar = "Medium"
HitSpeed = 1000
Hitpoints = 411
LoadTime = 500
Mass = 2
MoveEffect = "Phoenix_Wing"
Name = "PhoenixNoRespawn"
ProjectileEffect = "phoenix_attack_start"
ProjectileStartRadius = 500
ProjectileStartZ = 1900
Range = 1600
Rarity = "Common"
RedExportName = "Phoenix"
Scale = 70
ShadowScaleX = 85
ShadowScaleY = -60
ShadowY = 15
SightRange = 5500
SpawnEffect = "phoenix_deploy"
Speed = 60
TID = "TID_SPELL_PHOENIX"
UseAnimator = true
