
[BUILDING.PrincessTower]
AttachedCharacter = "TowerPrincess"
AttachedCharacterHeight = 2200
AttacksAir = true
AttacksGround = true
BlueExportName = "StarTower_base_blue"
BlueTopExportName = "StarTower_top_blue"
CollisionRadius = 1000
CrowdEffects = true
DeathEffect = "TowerExplode"
FileName = "sc/building_tower.sc"
HealthBar = "Tower"
HealthBarOffsetYBlue = 62
HealthBarOffsetYRed = -12
HitSpeed = 800
Hitpoints = 1400
IgnoreBuff = ["Event_Berserk_OnStartBuff"]
IsBuilding = true
IsSummonerTower = true
Name = "PrincessTower"
NoDeploySizeH = 21
NoDeploySizeW = 11
PrestigeSWF = "sc/building_prestige_dl.sc"
Projectile = "TowerPrincessProjectile"
ProjectileEffect = "ArcherTowerAttack"
ProjectileStartRadius = 300
ProjectileStartZ = 3000
Range = 7500
Rarity = "Common"
RedExportName = "StarTower_base_red"
RedTopExportName = "StarTower_top_red"
Scale = 100
ShadowScaleX = 102
ShadowScaleY = 70
ShadowSkew = 13
ShadowX = -5
ShadowY = 5
ShowHealthNumber = true
SightRange = 7500
SkinType = "PrincessTower"
TID = "TID_BUILDING_ARCHER_TOWER"

[PROJECTILE.TowerPrincessProjectile]
Damage = 50
DamageScalingMode = "PrincessTower"
ExportName = "projectile_arrow_basic_enemy"
FileName = "sc/effects.sc"
Gravity = 60
HitEffect = "ArrowHit"
Homing = true
Name = "TowerPrincessProjectile"
OnlyEnemies = true
Rarity = "Common"
ShadowExportName = "projectile_arrow_shadow"
Speed = 600

[CHARACTER.TowerPrincess]
AttackStartEffect = "ArcherAttackStart"
AttacksAir = true
AttacksGround = true
BlueExportName = "princess_tower"
CollisionRadius = 500
DamageExportName = "filter_damage"
DeathEffect = "ArcherDie"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 400
DeployTime = 1000
FileName = "sc/chr_princess.sc"
HealthBar = "Small"
HealthBarOffsetY = -10
HitSpeed = 1200
Hitpoints = 5
LoadTime = 1000
Mass = 3
MoveEffect = "ArcherSteps"
Name = "TowerPrincess"
Projectile = "TowerPrincessProjectile"
ProjectileEffect = "ArcherAttack"
ProjectileStartRadius = 450
ProjectileStartZ = 450
Range = 5000
Rarity = "Common"
RedExportName = "princess_tower_red"
Scale = 100
ShadowScaleX = 75
ShadowScaleY = 75
ShadowSkew = 25
ShadowY = -15
SightRange = 5500
SpawnEffect = "ArcherDeploy"
Speed = 60
TID = "TID_CHARACTER_ARCHER"
UseAnimator = true
