[CHARACTER.RageBarbarian]
AttackStartEffect = "ragebarbarian_attack_start"
AttacksGround = true
BlueExportName = "rage_barbarian"
CollisionRadius = 500
Damage = 100
DamageEffect = "ragebarbarian_hit"
DamageExportName = "filter_damage"
DeathAreaEffect = "RageBarbarianDummyForSpawn"
DeathEffect = "barbarian_die"
DeathSpawnCharacter = ""
DeployDelay = 400
DeployTime = 1000
FileName = "sc/chr_rage_barbarian.sc"
HealthBar = "Medium"
HitSpeed = 800
Hitpoints = 501
LoadTime = 400
Mass = 4
MoveEffect = "ragebarbarian_steps"
Name = "RageBarbarian"
PrestigeSWF = "sc/chr_prestige_dl.sc"
ProjectileStartRadius = 450
ProjectileStartZ = 450
Range = 700
Rarity = "Common"
RedExportName = "rage_barbarian_red"
Scale = 100
ShadowScaleX = 85
ShadowScaleY = 85
ShadowSkew = 35
ShadowY = -10
SightRange = 5500
SpawnEffect = "ragebarbarian_deploy"
Speed = 120
TID = "TID_CHARACTER_RAGE_BARBARIAN"
UseAnimator = true
WalkingSpeedTweakPercentage = -20
[AEO.RageBarbarianDummyForSpawn]
LifeDuration = 50
OnStartingAction = "rage_barbarian_spawn_bottle"
Rarity = "Common"
[ACTION.rage_barbarian_spawn_bottle]
ClassType = "ActionSpawn"
SpawnData = "RageBarbarianBottle"
SpawnType = "CharacterType"
[BUILDING.RageBarbarianBottle]
BlueExportName = "rage_bottle_new"
DeathAreaEffect = "BarbarianRage"
DeathEffect = "rage_bottle_explode_02"
DeployTime = 500
FileName = "sc/building_rage_bottle.sc"
IgnoreBuff = ["Event_Berserk_OnStartBuff"]
IsBuilding = true
Name = "RageBarbarianBottle"
PrestigeSWF = "sc/building_prestige_dl.sc"
Rarity = "Common"
RedExportName = "rage_bottle_new"
Scale = 100
SpawnEffect = "GiantSkeleton_Bomb_deploy"
[AEO.BarbarianRage]
Buff = "Rage"
BuffTime = 1000
CapBuffTimeToAreaEffectTime = true
HitSpeed = 300
Filter = "all_friendly_troops"
LifeDuration = 5500
LoopingEffect = "Spell_rage_loop"
Name = "BarbarianRage"
OneShotEffect = "Spell_rage_effect"
Radius = 3000
Rarity = "Common"
ScaledEffect = "Spell_rage_ground"
SpawnAreaEffectObject = "BarbarianRageDamage"
[AEO.BarbarianRageDamage]
Filter = "aeo_enemy_affects_hidden"
LifeDuration = 1
Name = "BarbarianRageDamage"
Radius = 3000
Rarity = "Common"
Damage = "RageDamage"
