
[CHARACTER.Ram]
AttackStartEffect = "ram_attack_start"
AttacksGround = true
BlueExportName = "ram"
ChargeEffect = "ram_charge"
ChargeRange = 250
ChargeSpeedMultiplier = 200
CollisionRadius = 600
Damage = 98
DamageEffect = "ram_hit"
DamageEffectSpecial = "ram_charge_hit"
DamageExportName = "filter_damage"
DamageSpecial = 196
DeathEffect = "ram_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployTime = 1000
FileName = "sc/chr_ram_rider_dl.sc"
HealthBar = "Medium"
HealthBarOffsetY = -15
HitSpeed = 1700
Hitpoints = 690
JumpEnabled = true
JumpHeight = 4000
JumpSpeed = 160
LandingEffect = "ram_landing"
LoadTime = 1100
Mass = 4
MoveEffect = "ram_steps"
Name = "Ram"
ProjectileStartRadius = 450
ProjectileStartZ = 450
Range = 800
Rarity = "Common"
RedExportName = "ram_red"
Scale = 95
ShadowScaleX = 85
ShadowScaleY = 85
ShadowSkew = 35
ShadowY = -10
SightRange = 7500
SpawnAttach = true
SpawnCharacter = "RamRider"
SpawnEffect = "ramrider_deploy"
SpawnNumber = 1
Speed = 60
TID = "TID_SPELL_HOG_RIDER"
TargetOnlyBuildings = true
UseAnimator = true
OnStartingAction = "JumpHack_Check_Jump_Interval"

[CHARACTER.RamRider]
AttackStartEffect = "ramriderAttackStart"
AttacksAir = true
AttacksGround = true
BlueExportName = "rider"
CollisionRadius = 600
DamageExportName = "filter_damage"
DeployTime = 1000
DeprioritizeTargetsWithBuff = true
FileName = "sc/chr_ram_rider_dl.sc"
HealthBar = "Medium"
HealthBarOffsetY = -10
HitSpeed = 1100
Hitpoints = 232
IgnoreBuff = ["VoodooCurse", "GoblinCurse", "Event_Berserk_OnStartBuff", "VoodooCurse_crazy_3"]
IgnoreResurrect = true
IgnoreTargetsWithBuff = "BolaSnare"
LoadTime = 700
Mass = 3
Name = "RamRider"
Projectile = "RamRiderBola"
ProjectileStartRadius = 800
ProjectileStartZ = 500
Range = 5500
Rarity = "Common"
RedExportName = "rider"
Scale = 95
ShadowScaleX = 75
ShadowScaleY = 75
ShadowSkew = -1
ShadowY = -15
SightRange = 5500
SpawnAttachMaxRotation = 90
SpawnDeployBaseAnim = "filter_deploy_unit_default"
Speed = 60
TID = "TID_CHARACTER_RAMRIDER"
TargetOnlyTroops = true
UseAnimator = true

[PROJECTILE.RamRiderBola]
AoeToAir = true
AoeToGround = true
BuffTime = 2000
ConstantHeight = 3000
Damage = 41
ExportName = "bola_projectile"
FileName = "sc/chr_ram_rider_dl.sc"
HitEffect = "ramrider_bola_hit"
Homing = true
Name = "RamRiderBola"
OnlyEnemies = true
Rarity = "Common"
Scale = 100
ShadowExportName = "bola_projectile_shadow"
Speed = 600
TargetBuff = "BolaSnare"
TrailEffect = "BolaProjectileEmitter"

[BUFF.BolaSnare]
FilterExportName = "filter_trap_hit"
FilterFile = "sc/effects.sc"
MarkEffect = "Healing"
Name = "BolaSnare"
Rarity = "Common"
SpeedMultiplier = -70
TID = "TID_SPELL_ATTRIBUTE_SNARE"
