
[CHARACTER.Recruit_Chess]
AttackStartEffect = "recruit_attack_start"
AttacksGround = true
BlueExportName = "guard02_blue"
BlueShieldExportName = "guard02_blue_shiled"
CollisionRadius = 500
Damage = 52
DamageEffect = "recruit_hit"
DamageExportName = "filter_damage"
DeathEffect = "recruit_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 400
DeployTime = 1000
FileName = "sc/chr_guard02_dl.sc"
HealthBar = "Shield"
HealthBarOffsetY = -10
HealthBarOffsetYBlue = 15
HealthBarOffsetYRed = 10
HideHealthbar = true
HitSpeed = 1300
Hitpoints = 208
IgnoreClone = true
LoadTime = 800
Mass = 5
MoveEffect = "recruit_steps"
Name = "Recruit_Chess"
NewHealthBarOffsetXBlue = 2
NewHealthBarOffsetXRed = 2
PrestigeExportName2 = "guard02_prestige2"
PrestigeSWF = "sc/chr_guard02_dl.sc"
ProjectileStartRadius = 350
ProjectileStartZ = 350
Range = 1600
Rarity = "Common"
RedExportName = "guard02_red"
RedShieldExportName = "guard02_red_shield"
Scale = 100
ShadowScaleX = 50
ShadowScaleY = 50
ShadowSkew = 35
ShadowX = -5
ShadowY = 5
ShieldHitpoints = 94
ShieldLostEffect = "recruit_lose_shield"
SightRange = 1600
SpawnEffect = "recruit_deploy"
SpawnRadius = 800
TID = "TID_SPELL_GUARD_BATTALION"
UseAnimator = true
OnStartingClientActions = ["Healthbar_Medium"]
