
[CHARACTER.RoyalGiant]
AttackStartEffect = "royal_giant_attack_start"
AttacksGround = true
BlueExportName = "royalGiant"
CollisionRadius = 750
CrowdEffects = true
DamageExportName = "filter_damage_wobble"
DeathEffect = "royal_giant_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployTime = 1000
FileName = "sc/chr_royal_giant.sc"
HealthBar = "High"
HitSpeed = 1800
Hitpoints = 1236
IgnorePushback = true
LoadTime = 900
Mass = 18
MoveEffect = "royal_giant_steps"
Name = "RoyalGiant"
PrestigeExportName2 = "royal_giant_prestige"
PrestigeSWF = "sc/chr_prestige_dl.sc"
Projectile = "RoyalGiantProjectile"
ProjectileEffect = "royal_giant_projectile_fx"
ProjectileStartRadius = 1200
ProjectileStartZ = 2900
Range = 5000
Rarity = "Common"
RedExportName = "royalGiant_red"
Scale = 100
ShadowScaleX = 85
ShadowScaleY = 80
ShadowSkew = 25
SightClip = 2000
SightClipSide = 2000
SightRange = 7500
SpawnEffect = "royal_giant_deploy"
Speed = 45
StopMovementAfterMS = 640
TID = "TID_SPELL_ROYAL_GIANT"
TargetOnlyBuildings = true
UseAnimator = true
WaitMS = 100

[PROJECTILE.RoyalGiantProjectile]
ConstantHeight = 1500
Damage = 120
DeflectBehaviour = "IgnoreHeight"
ExportName = "projectile_cannonball_large"
FileName = "sc/effects.sc"
HitEffect = "royal_giant_projectile_hit"
Homing = true
Name = "RoyalGiantProjectile"
OnlyEnemies = true
Rarity = "Common"
ShadowExportName = "projectile_arrow_shadow"
Speed = 1000


