[SPELL_EVOLVED.RoyalHogs_EV1]
	StatsTags.SummonNumber = "summon_amount"
[EXT.RoyalHog_EV1]
	Base = "CHARACTER.RoyalHog"
	ClonedVersion = "RoyalHog"
	OnStartingClientActions = ["Healthbar_Medium_WithEvoBadge"]
	HideHealthbar = true
	FlyingHeight = 4000
	FileName="sc/chr_royal_hog_evolution.sc"
	BlueExportName="royal_hogs_evolution"
	RedExportName="royal_hogs_evolution_red"
	Scale = 57
	DeathEffect="Death_card_evolution_M"
	SpawnEffect="vfx_royal_hog_fly_evo_deploy"
	MoveEffect = "vfx_royal_hog_fly_evo_steps"
	DamageEffect = "vfx_royal_hog_fly_evo_damage"
	AttackStartEffect = "vfx_royal_hog_fly_evo_attack_start"
	CustomAnimationPostfix = "_landing1_"
	HealthBarOffsetYRed = 10
	HealthBarOffsetYBlue = 10
		DeployBaseAnimExportName="filter_deploy_unit_legendary"
		CustomSpawnFilter="filter_card_evolution"
	OnStartingAction = "RoyalHog_EV1_Start_Group"
	OnAttackAction = "RoyalHog_EV1_Fall_To_Ground_Group"
	StatsTags.Hitpoints = "hitpoints"
	StatsTags.Damage = "damage"
	StatsTags.HitSpeed = "hit_speed"
	StatsTags.Targets = "targets"
	StatsTags.Range = "range"
	StatsTags.Speed = "speed"
[EXT.RoyalHog_EV1_Grounded]
	Base = "CHARACTER.RoyalHog_EV1"
	ClonedVersion = "RoyalHog"
	OnStartingClientActions = ["Healthbar_Medium_WithEvoBadge"]
	HideHealthbar = true
	FileName = "sc/chr_royal_hog_evolution.sc"
	BlueExportName = "royal_hogs_evolution_ground"
	RedExportName = "royal_hogs_evolution_ground_red"
	Scale = 57
	DeathEffect="Death_card_evolution_M"
	MoveEffect = "vfx_royal_hog_evo_steps"
	DamageEffect = "vfx_royal_hog_evo_damage"
	AttackStartEffect = "vfx_royal_hog_evo_attack_start"
	OnStartingAction = ""
	OnAttackAction = ""
	JumpHeight = 4000
[ACTION.RoyalHog_EV1_Start_Group]
	ClassType = "ActionGroup"
	SubActions = ["JumpHack_Check_Jump_Interval", "RoyalHog_EV1_Health_Threshold"]
	SubActionsDelay = [0, 0]
[ACTION.RoyalHog_EV1_Health_Threshold]
	ClassType = "ActionRunActionAtHealth"
	HealthPercentages = [99]
	Actions = ["RoyalHog_EV1_Fall_To_Ground_Group"]
[ACTION.RoyalHog_EV1_Fall_To_Ground_Group]
	ClassType = "ActionGroup"
	SubActions = ["RoyalHog_EV1_To_Ground", "RoyalHog_EV1_Play_Falling_Animation", "RoyalHog_EV1_Play_Falling_Effect"]
	SubActionsDelay = [0, 0]
	ExecuteIfTrue = "!UNIT_CUSTOM_TAG_1"
[ACTION.RoyalHog_EV1_To_Ground]
	ClassType = "ActionAirToGround"
	TransitionDuration = 500
	TotalDuration = 999999
	Singleton = true
	ActionOnGround = "RoyalHog_EV1_Landed_Group"
	GameTagsToSet = "UNIT_CUSTOM_TAG_1"
	CloneTriggersLandingActions = false
[ACTION.RoyalHog_EV1_Play_Falling_Animation]
	ClassType = "ActionRunForcedAnimationOnce"
	PlaybackDuration = 1000
[ACTION.RoyalHog_EV1_Play_Falling_Effect]
	ClassType="ActionPlayEffect"
	Effect = "vfx_royale_hog_evo_falling"
[ACTION.RoyalHog_EV1_Landed_Group]
	ClassType = "ActionGroup"
	SubActions = ["RoyalHog_EV1_Transition_To_Ground_Unit", "RoyalHog_EV1_Spawn_Landing_Damage_Area", "RoyalHog_EV1_Reset_Path"]
	SubActionsDelay = [0, 0, 100]
[ACTION.RoyalHog_EV1_Reset_Path]
	ClassType = "ActionResetPath"
[ACTION.RoyalHog_EV1_Transition_To_Ground_Unit]
	ClassType = "ActionChangeGameObjectData"
	NewCharacterData = "RoyalHog_EV1_Grounded"
[ACTION.RoyalHog_EV1_Spawn_Landing_Damage_Area]
	ClassType="ActionSpawn"
	SpawnType = "AreaEffectType"
	SpawnData = "RoyalHog_EV1_Landing_Damage_Area"
	ParentGOAsSource = true
[AEO.RoyalHog_EV1_Landing_Damage_Area]
	Rarity = "Common"
	OneShotEffect = "vfx_royal_hog_evo_landing"
	LifeDuration = 100
	Radius = 2000
	Filter = "GroundCharacterTargets"
	HitSpeed = 0
    Damage = { BaseDamage = 17 }
	StatsTags.Damage = "fall_damage"
[STATS.royalhogs_ev1]
	[[STATS.royalhogs_ev1.stats]]
		Value = "damage"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_DAMAGE"
		Icon = "icons_stats_dmg"
	[[STATS.royalhogs_ev1.stats]]
		Value = "damage"
		Value2 = "hit_speed"
		Unit = "DPS"
		TID = "TID_SPELL_ATTRIBUTE_DPS"
		Icon = "icons_stats_dmg_dps"
	[[STATS.royalhogs_ev1.stats]]
		Value = "hitpoints"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_HEALTH"
		Icon = "icons_stats_hp"
	[[STATS.royalhogs_ev1.stats]]
		Value = "hit_speed"
		Unit = "TIME_PRECISE"
		TID = "TID_SPELL_ATTRIBUTE_HIT_SPEED"
		Icon = "icons_stats_dmg_speed"
	[[STATS.royalhogs_ev1.stats]]
		Value = "targets"
		Unit = "TARGETS"
		TID = "TID_SPELL_ATTRIBUTE_TARGET"
		Icon = "icons_stats_target"
    [[STATS.royalhogs_ev1.stats]]
		Value = "speed"
		Unit = "SPEED"
		TID = "TID_SPELL_ATTRIBUTE_SPEED"
		Icon = "icons_stats_speed"
	[[STATS.royalhogs_ev1.stats]]
		Value = "range"
		Unit = "MELEE_RANGE"
		TID = "TID_SPELL_ATTRIBUTE_RANGE"
		Icon = "icons_stats_range"
	[[STATS.royalhogs_ev1.stats]]
		Value = "summon_amount"
		Unit = "COUNT"
		TID = "TID_SPELL_ATTRIBUTE_COUNT"
		Icon = "icons_stats_troop_count"
	[[STATS.royalhogs_ev1.stats]]
		Value = "fall_damage"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_LANDING_DAMAGE"
		Icon = "icons_stats_dmg_area"
