
[CHARACTER.RoyalHog]
AttackStartEffect = "royal_hog_attack_start"
AttacksGround = true
BlueExportName = "royal_hog"
CollisionRadius = 600
Damage = 29
DamageEffect = "royal_hog_hit"
DamageExportName = "filter_damage"
DeathEffect = "royal_hog_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 400
DeployTime = 1000
FileName = "sc/chr_royal_hog_dl.sc"
HealthBar = "Medium"
HealthBarOffsetY = -15
HitSpeed = 1200
Hitpoints = 327
JumpEnabled = true
JumpHeight = 4000
JumpSpeed = 160
LandingEffect = "royal_hog_landing"
LoadTime = 800
Mass = 2
MoveEffect = "royal_hog_steps"
Name = "RoyalHog"
PrestigeExportName2 = "royal_hog_prestige"
PrestigeSWF = "sc/chr_royal_hog_dl.sc"
ProjectileStartRadius = 450
ProjectileStartZ = 450
Range = 750
Rarity = "Common"
RedExportName = "royal_hog_red"
Scale = 85
ShadowScaleX = 85
ShadowScaleY = 85
ShadowSkew = 35
ShadowY = -10
SightClip = 4000
SightClipSide = 4000
SightRange = 9500
SpawnEffect = "royal_hog_deploy"
Speed = 120
TID = "TID_SPELL_ROYAL_HOGS"
TargetOnlyBuildings = true
UseAnimator = true
OnStartingAction = "JumpHack_Check_Jump_Interval"

