[SPELL_CHARACTER.Skeletons]
	StatsTags.SummonNumber = "skeletons_summon_amount"

[CHARACTER.Skeleton]
AttackStartEffect = "skeleton_attack_start"
AttacksGround = true
BlueExportName = "skeleton1"
CollisionRadius = 500
Damage = 32
DamageEffect = "skeleton_hit"
DamageExportName = "filter_damage"
DeathEffect = "skeleton_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 400
DeployTime = 1000
FileName = "sc/chr_skeleton.sc"
HealthBar = "Small"
HitSpeed = 1100
Hitpoints = 32
LoadTime = 600
Mass = 1
MoveEffect = "skeleton_steps"
Name = "Skeleton"
PrestigeExportName2 = "skeleton_prestige"
PrestigeExportName3 = "skeleton_prestige2"
PrestigeSWF = "sc/chr_prestige2_dl.sc"
ProjectileStartRadius = 350
ProjectileStartZ = 350
Range = 500
Rarity = "Common"
RedExportName = "skeleton1"
Scale = 130
ShadowScaleX = 50
ShadowScaleY = 50
ShadowSkew = 35
ShadowX = -5
ShadowY = 5
SightRange = 5500
SpawnEffect = "skeleton_deploy"
Speed = 90
TID = "TID_CHARACTER_SKELETON"
UseAnimator = true

[CHARACTER.Skeleton.StatsTags]
Damage = "skeleton_damage"
Hitpoints = "skeleton_hitpoints"
Speed = "skeleton_speed"
HitSpeed = "skeleton_hit_speed"
Targets = "skeleton_targets"
Range = "skeleton_range"


[STATS.skeleton]
	[[STATS.skeleton.stats]]
		Value = "skeleton_damage"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_DAMAGE"
		Icon = "icons_stats_dmg"
	[[STATS.skeleton.stats]]
		Value = "skeleton_damage"
		Value2 = "skeleton_hit_speed"
		Unit = "DPS"
		TID = "TID_SPELL_ATTRIBUTE_DPS"
		Icon = "icons_stats_dmg_dps"
		PopupIgnoreFieldReferenceName = "skeleton_stat_dps"
	[[STATS.skeleton.stats]]
		Value = "skeleton_hitpoints"
		Unit = "INTEGER"
		TID = "TID_SPELL_ATTRIBUTE_HEALTH"
		Icon = "icons_stats_hp"
	[[STATS.skeleton.stats]]
		Value = "skeleton_hit_speed"
		Unit = "TIME_PRECISE"
		TID = "TID_SPELL_ATTRIBUTE_HIT_SPEED"
		Icon = "icons_stats_dmg_speed"
	[[STATS.skeleton.stats]]
		Value = "skeleton_targets"
		Unit = "TARGETS"
		TID = "TID_SPELL_ATTRIBUTE_TARGET"
		Icon = "icons_stats_target"
	[[STATS.skeleton.stats]]
		Value = "skeleton_speed"
		Unit = "SPEED"
		TID = "TID_SPELL_ATTRIBUTE_SPEED"
		Icon = "icons_stats_speed"
	[[STATS.skeleton.stats]]
		Value = "skeleton_range"
		Unit = "MELEE_RANGE"
		TID = "TID_SPELL_ATTRIBUTE_RANGE"
		Icon = "icons_stats_range"
	[[STATS.skeleton.stats]]
		Value = "skeletons_summon_amount"
		Unit = "COUNT"
		TID = "TID_SPELL_ATTRIBUTE_COUNT"
		Icon = "icons_stats_troop_count"
		PopupIgnoreFieldReferenceName = "skeleton_stat_count"
