
[CHARACTER.SkeletonWarrior]
AttackStartEffect = "skeleton_warrior_attack_start"
AttacksGround = true
BlueExportName = "skeletonWarrior_blue"
BlueShieldExportName = "skeletonWarrior_blue_shield"
CollisionRadius = 500
Damage = 46
DamageEffect = "skeleton_warrior_hit"
DamageExportName = "filter_damage"
DeathEffect = "skeleton_warrior_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 400
DeployTime = 1000
FileName = "sc/chr_skeleton_warrior.sc"
HealthBar = "Shield_small"
HealthBarOffsetY = -10
HealthBarOffsetYBlue = 15
HealthBarOffsetYRed = 10
HideHealthbar = true
HitSpeed = 1000
Hitpoints = 32
LoadTime = 500
Mass = 1
MoveEffect = "skeleton_warrior_steps"
Name = "SkeletonWarrior"
NewHealthBarOffsetXBlue = 2
NewHealthBarOffsetXRed = 2
PrestigeExportName2 = "skeletonwarrior_prestige"
PrestigeSWF = "sc/chr_prestige_dl.sc"
ProjectileStartRadius = 350
ProjectileStartZ = 350
Range = 1600
Rarity = "Common"
RedExportName = "skeletonWarrior"
RedShieldExportName = "skeletonWarrior_shield"
Scale = 95
ShadowScaleX = 50
ShadowScaleY = 50
ShadowSkew = 35
ShadowX = -5
ShadowY = 5
ShieldHitpoints = 100
ShieldLostEffect = "skeleton_warrior_lose_shield"
SightRange = 5500
SpawnEffect = "skeleton_warrior_deploy"
SpawnRadius = 800
Speed = 90
TID = "TID_CHARACTER_SKELETON_WARRIOR"
UseAnimator = true
OnStartingClientActions = ["Healthbar_Small"]
