
[CHARACTER.SuperLavaHound]
AttacksAir = true
AttacksGround = true
BlueExportName = "lava_hound"
CollisionRadius = 750
CrowdEffects = true
CustomSpawnFilter = "filter_super_lava_hound_deploy"
DamageExportName = "filter_damage_wobble"
DeathEffect = "lava_hound_die"
DeathSpawnCharacter = "SuperLavaHound2"
DeathSpawnCount = 2
DeathSpawnProjectile = "FireWallProjectile"
DeathSpawnPushback = true
DeathSpawnRadius = 1500
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
DeployTime = 1000
FileName = "sc/chr_lava_hound.sc"
FlyingHeight = 4000
HealthBar = "High"
HitSpeed = 1300
Hitpoints = 2800
IgnoreBuff = ["VoodooCurse", "GoblinCurse"]
IgnorePushback = true
IgnoreResurrect = true
LoadTime = 300
LoopingFilter = "filter_super_lava_hound"
Mass = 5
MoveEffect = "lava_hound_steps"
Name = "SuperLavaHound"
PrestigeExportName2 = "lava_hound_prestige"
PrestigeSWF = "sc/chr_prestige5_dl.sc"
Projectile = "LavaHoundProjectile"
ProjectileEffect = "lava_hound_attack_start"
ProjectileStartRadius = 1000
ProjectileStartZ = 1800
Range = 3500
Rarity = "Common"
RedExportName = "lava_hound_red"
Scale = 120
ShadowScaleX = 85
ShadowScaleY = -60
ShadowY = 20
SightRange = 5500
SpawnEffect = "super_lava_hound_deploy"
Speed = 45
TID = "TID_SPELL_SUPER_LAVA_HOUND"
TargetOnlyBuildings = true
UseAnimator = true

[CHARACTER.SuperLavaHound2]
AttacksAir = true
AttacksGround = true
BlueExportName = "lava_hound"
CollisionRadius = 750
CrowdEffects = true
DamageExportName = "filter_damage_wobble"
DeathEffect = "lava_hound_die"
DeathSpawnCharacter = "LavaPups"
DeathSpawnCount = 4
DeathSpawnPushback = true
DeathSpawnRadius = 2000
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
DeployTime = 1000
FileName = "sc/chr_lava_hound.sc"
FlyingHeight = 4000
HealthBar = "High"
HitSpeed = 900
Hitpoints = 1500
IgnoreBuff = ["VoodooCurse", "GoblinCurse"]
IgnorePushback = true
IgnoreResurrect = true
LoadTime = 300
Mass = 5
MoveEffect = "lava_hound_steps"
Name = "SuperLavaHound2"
PrestigeExportName2 = "lava_hound_prestige"
PrestigeSWF = "sc/chr_prestige5_dl.sc"
Projectile = "LavaHoundProjectile"
ProjectileEffect = "lava_hound_attack_start"
ProjectileStartRadius = 1000
ProjectileStartZ = 1800
Range = 3500
Rarity = "Common"
RedExportName = "lava_hound_red"
Scale = 85
ShadowScaleX = 85
ShadowScaleY = -60
ShadowY = 20
SightRange = 5500
SpawnEffect = "lava_hound_deploy"
Speed = 45
TID = "TID_SPELL_LAVA_HOUND"
TargetOnlyBuildings = true
UseAnimator = true


[PROJECTILE.FireWallProjectile]
AoeToAir = true
AoeToGround = true
CrownTowerDamagePercent = -70
Damage = 120
ExportName = "fireball_projectile1"
FileName = "sc/effects.sc"
Gravity = 50
HitEffect = "Fireball_explosion"
MinDistance = 2000
Name = "FireWallProjectile"
OnlyEnemies = true
Pushback = 500
Radius = 2500
Rarity = "Common"
ShadowExportName = "projectile_arrow_shadow"
SpawnAxisY = true
SpawnChain = 2
SpawnProjectile = "FireWallMovingProjectile"
Speed = 600
TrailEffect = "FireballEmitter"

[PROJECTILE.FireWallMovingProjectile]
AoeToAir = true
AoeToGround = true
CrownTowerDamagePercent = -70
Damage = 120
ExportName = "fireball_projectile1"
FileName = "sc/effects.sc"
Gravity = 50
HitEffect = "Fireball_explosion"
MinDistance = 2000
Name = "FireWallMovingProjectile"
OnlyEnemies = true
Pushback = 500
Radius = 2500
Rarity = "Rare"
ShadowExportName = "projectile_arrow_shadow"
SpawnAxisY = true
Speed = 600
TrailEffect = "FireballEmitter"

