
[EXT.Valkyrie_EV1]
AttackStartEffect = "vfx_valkyrie_evo_slash"
Base = "CHARACTER.Valkyrie"
BlueExportName = "valkyrie_evolution"
ClonedVersion = "Valkyrie"
CustomSpawnFilter = "filter_card_evolution"
DeathEffect = "Death_card_evolution_M"
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
FileName = "sc/chr_valkyrie_evolution.sc"
HealthBar = "Medium_EV1"
HealthBarOffsetY = -10
OnAttackAction = "Valkyrie_EV1_Tornado"
PrestigeExportName2 = ""
PrestigeExportName3 = ""
PrestigeSWF = ""
RedExportName = "valkyrie_evolution_enemy"
Scale = 84
SpawnEffect = "vfx_valkyrie_evo_deploy"

    [ACTION.Valkyrie_EV1_Tornado]
    ClassType = "ActionSpawn"
    ParentGOAsSource = true
    SpawnData = "Valkyrie_MiniTornado_EV1"
    SpawnType = "AreaEffectType"

        [EXT.Valkyrie_MiniTornado_EV1]
        Base = "AEO.Tornado"
        Buff = "Valkyrie_MiniTornado_EV1_BUFF"
        FollowBehaviour = "FollowParent"
        LifeDuration = 500
        Radius = 5000
        ScaledEffect = "Spell_evo_valk_tornado_deploy"


            [EXT.Valkyrie_MiniTornado_EV1_BUFF]
            AttractPercentage = 300
            Base = "BUFF.Tornado"
            DamagePerSecond = 42
            HitFrequency = 400
            Rarity = "Common"


        [ACTION.Valkyrie_EV1_Tornado.NextAction]
        ClassType = "ActionSpawn"
        SpawnType = "BuffType"
        SpawnData = "Valkyrie_NotPushed_BUF"
        SpawnTime = 500


            [BUFF.Valkyrie_NotPushed_BUF]
            GameTagsToSet = "NO_PUSHED_BY_ENEMY"
            Rarity = "Common"

