[EXT.Wallbreaker_EV1]
Base = "CHARACTER.Wallbreaker"
BlueExportName = "wall_breakers_evolution"
ClonedVersion = "Wallbreaker"
CustomSpawnFilter = "filter_card_evolution"
DeathEffect = "Death_card_evolution_S"
FileName = "sc/chr_wall_breakers_evolution.sc"
HealthBar = "Small_EV1"
IgnoreResurrect = true
MoveEffect = "evo_wall_breaker_steps"
OnKilledAction = "WallBreaker_EV1_SpawnMini"
PrestigeExportName2 = ""
PrestigeExportName3 = ""
PrestigeSWF = ""
Projectile = "WallbreakerProjectile_EV1"
RedExportName = "wall_breakers_evolution_enemy"
Scale = 64
SpawnEffect = "vfx_wallbreaker_evo_deploy"
[EXT.WallbreakerProjectile_EV1]
Base = "PROJECTILE.WallbreakerProjectile"
Damage = ["%", 100]
HitEffect = "vfx_wallbreaker_evo_explosion"
[ACTION.WallBreaker_EV1_SpawnMini]
ClassType = "ActionSpawn"
ParentGOAsSource = true
SpawnData = "Wallbreaker_mini"
SpawnType = "CharacterType"
[ACTION.WallBreaker_EV1_SpawnMini.NextAction]
ClassType = "ActionSpawn"
SpawnType = "ProjectileType"
SpawnData = "WallbreakerBarrelExplosion_EV1"
ParentGOAsSource = true
[PROJECTILE.WallbreakerBarrelExplosion_EV1]
AoeToAir = true
AoeToGround = true
CrownTowerDamagePercent = -50
Damage = 75
DeflectBehaviour = "NoDeflect"
ExportName = "fireball_projectile1"
FileName = "sc/effects.sc"
Gravity = 50
HitEffect = "vfx_wallbreaker_evo_explosion"
OnlyEnemies = true
Radius = 2000
Rarity = "Common"
Speed = 600
[CHARACTER.Wallbreaker_mini]
AreaDamageRadius = 1500
AttackStartEffect = "wall_breaker_attack_start"
AttacksGround = true
BlueExportName = "wall_breakers_solo_evolution"
CollisionRadius = 400
ContinuousEffect = "wall_breaker_cont_effect"
DamageEffect = "wall_breaker_explode"
DamageExportName = "filter_damage"
DeathEffect = "wall_breaker_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 400
DeployTime = 1000
FileName = "sc/chr_wall_breakers_evolution.sc"
HealthBar = "Small_EV1"
HealthBarOffsetY = -20
HitSpeed = 1200
Hitpoints = 64
Kamikaze = true
LoadTime = 1000
Mass = 4
MoveEffect = "wall_breaker_steps"
Name = "Wallbreaker_mini"
Projectile = "WallbreakerMiniProjectile"
Range = 500
Rarity = "Common"
RedExportName = "wall_breakers_solo_evolution_enemy"
Scale = 56
ShadowScaleX = 35
ShadowScaleY = 35
ShadowSkew = 35
ShadowY = -10
SightRange = 7000
SpawnEffect = "wall_breaker_deploy"
Speed = 120
TID = "TID_CHARACTER_WALLBREAKER_MINI"
TargetOnlyBuildings = true
UseAnimator = true
[PROJECTILE.WallbreakerMiniProjectile]
AoeToAir = true
AoeToGround = true
Damage = 72
DeflectBehaviour = "NoDeflect"
ExportName = "projectile_firespirit"
FileName = "sc/effects.sc"
Gravity = 400
HitEffect = "vfx_wallbreaker_evo_explosion_mini"
Name = "WallbreakerMiniProjectile"
OnlyEnemies = true
ProjectileRange = 1
Radius = 1500
Rarity = "Common"
ShadowExportName = "projectile_arrow_shadow"
Speed = 1000
TrailEffect = "PrincessArrowProjectileEmitter"
use360Frames = true
