
[CHARACTER.WitchMother]
AttackStartEffect = "motherwitch_attack_start"
AttacksAir = true
AttacksGround = true
BlueExportName = "motherwitch"
BuffOnDamage = "VoodooCurse"
BuffOnDamageTime = 5000
CollisionRadius = 500
DamageEffect = "motherwitch_hit"
DamageExportName = "filter_damage"
DeathEffect = "motherwitch_die"
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
DeployTime = 1000
FileName = "sc/chr_mother_witch_dl.sc"
HealthBar = "Medium"
HitSpeed = 1000
Hitpoints = 207
LoadTime = 700
Mass = 6
MoveEffect = "motherwitch_steps"
Name = "WitchMother"
PrestigeExportName2 = "motherwitch_prestige"
PrestigeExportName3 = "motherwitch_prestige2"
PrestigeSWF = "sc/chr_mother_witch_prestige_dl.sc"
Projectile = "VoodooProjectile"
ProjectileStartRadius = 1600
ProjectileStartZ = 1000
Range = 5500
Rarity = "Common"
RedExportName = "motherwitch_red"
Scale = 95
ShadowScaleX = 85
ShadowScaleY = 85
ShadowSkew = 35
ShadowY = -10
SightRange = 5500
SpawnEffect = "motherwitch_deploy"
Speed = 60
TID = "TID_SPELL_WITCHMOTHER"
UseAnimator = true

[PROJECTILE.VoodooProjectile]
ApplyBuffBeforeDamage = true
BuffTime = 5000
ConstantHeight = 1000
Damage = 52
ExportName = "mow_projectile"
FileName = "sc/chr_mother_witch_dl.sc"
Gravity = 20
Homing = true
Name = "VoodooProjectile"
OnlyEnemies = true
Rarity = "Common"
ShakesTargets = true
Speed = 600
TargetBuff = "VoodooCurse"
TrailEffect = "elixir_projectile_trail"

[BUFF.VoodooCurse]
ContinuousEffect = "motherwitch_curse_cont_effect"
DeathSpawn = "VoodooHog"
DeathSpawnCount = 1
DeathSpawnIsEnemy = true
FilterExportName = "filter_mw_curse"
FilterFile = "sc/effects.sc"
IgnoreBuildings = true
Name = "VoodooCurse"
OtherBuffDeathSpawnAllowed = true
Rarity = "Common"

[CHARACTER.VoodooHog]
AttackStartEffect = "mow_hog_attack_start"
AttacksGround = true
BlueExportName = "hog"
CollisionRadius = 600
Damage = 21
DamageEffect = "mow_hog_hit"
DamageExportName = "filter_damage"
DeathEffect = "mow_hog_die"
DeployBaseAnimExportName = "filter_deploy_unit_default"
DeployDelay = 400
DeployTime = 200
FileName = "sc/chr_mother_witch_dl.sc"
HealthBar = "Medium"
HealthBarOffsetY = -15
HitSpeed = 1200
Hitpoints = 246
IgnoreBuff = ["VoodooCurse", "GoblinCurse"]
JumpEnabled = true
JumpHeight = 4000
JumpSpeed = 160
LandingEffect = "mow_hog_landing"
LoadTime = 950
Mass = 2
MoveEffect = "mow_hog_steps"
Name = "VoodooHog"
ProjectileStartRadius = 450
ProjectileStartZ = 450
Range = 750
Rarity = "Common"
RedExportName = "hog_red"
Scale = 85
ShadowScaleX = 85
ShadowScaleY = 85
ShadowSkew = 35
ShadowY = -10
SightClip = 4000
SightClipSide = 4000
SightRange = 9500
SpawnEffect = "mow_hog_deploy"
Speed = 120
TID = "TID_SPELL_HOG"
TargetOnlyBuildings = true
UseAnimator = true
OnStartingAction = "JumpHack_Check_Jump_Interval"
