[CHARACTER.ZapMachine]
AttackPushBack = 750
AttacksGround = true
BlueExportName = "ZapMachine_Blue"
CollisionRadius = 1000
CrowdEffects = true
DeathEffect = "zapmachine_die"
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
DeployTime = 1000
FileName = "sc/chr_zap_machine.sc"
HealthBar = "Medium"
HealthBarOffsetY = -10
HitSpeed = 4000
Hitpoints = 567
IgnorePushback = true
LoadAttackEffect1 = "zapmachine_load_weapon_1"
LoadAttackEffect2 = "zapmachine_load_weapon_2"
LoadAttackEffect3 = "zapmachine_load_weapon_3"
LoadAttackEffectReady = "vfx_sparky_load_weapon_v2"
LoadFirstHit = true
LoadTime = 3000
Mass = 18
MoveEffect = "zapmachine_steps"
Name = "ZapMachine"
PrestigeSWF = "sc/chr_prestige_dl.sc"
Projectile = "ZapMachineProjectile"
ProjectileEffect = "vfx_sparky_attack_v2"
ProjectileEffectSpecial = "vfx_sparky_attack_v2"
ProjectileStartRadius = 1200
ProjectileStartZ = 1800
Range = 5000
Rarity = "Common"
RedExportName = "ZapMachine"
RotateAngleSpeed = 600
Scale = 85
ShadowScaleX = 100
ShadowScaleY = -90
ShadowSkew = -15
ShadowX = -8
ShadowY = 15
SightRange = 5000
SpawnEffect = "zapmachine_deploy"
Speed = 45
TID = "TID_SPELL_ZAPMACHINE"
UseAnimator = true
[PROJECTILE.ZapMachineProjectile]
AoeToGround = true
Damage = 520
ExportName = "zapMachine_projectile"
FileName = "sc/effects.sc"
HitEffect = "vfx_sparky_projectile_hit_v2"
Homing = true
Name = "ZapMachineProjectile"
OnlyEnemies = true
Radius = 1800
Rarity = "Common"
Speed = 1400
TrailEffect = "vfx_sparky_trail_emitter_v2"
