'use strict';
const {test,before}=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../src/core'),N=require('../src/native'),T=require('../src/text'),P=require('../assets/presentation/data.json');
before(async()=>{const previousImage=global.Image,previousDocument=global.document;global.Image=class{set src(value){queueMicrotask(()=>this.onload());}};global.document={baseURI:'http://qa.local/'};try{await T.load(P.text);}finally{global.Image=previousImage;global.document=previousDocument;}});
const I=[1,0,0,1,0,0],point=(m,x,y)=>[m[0]*x+m[2]*y+m[4],m[1]*x+m[3]*y+m[5]],box=pts=>({left:Math.min(...pts.map(p=>p[0])),right:Math.max(...pts.map(p=>p[0])),top:Math.min(...pts.map(p=>p[1])),bottom:Math.max(...pts.map(p=>p[1]))}),overlap=(a,b)=>a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;
function foreground(id){
 function context(){let m=I,setup=0,pts=[];const saved=[],painted=[],c={painted,save(){saved.push([...m]);},restore(){m=saved.pop();},scale(x,y){if(setup++===0)return;m=N.mul(m,[x,0,0,y,0,0]);},translate(x,y){if(setup++===1)return;m=N.mul(m,[1,0,0,1,x,y]);},transform(...mat){m=N.mul(m,mat);},beginPath(){pts=[];},closePath(){},moveTo(x,y){pts.push(point(m,x,y));},lineTo(x,y){pts.push(point(m,x,y));},bezierCurveTo(...xy){for(let i=0;i<xy.length;i+=2)pts.push(point(m,xy[i],xy[i+1]));},ellipse(x,y,rx,ry){for(const xx of [x-rx,x+rx])for(const yy of [y-ry,y+ry])pts.push(point(m,xx,yy));},fill(){if(pts.length)painted.push(box(pts));},stroke(){},fillRect(x,y,w,h){painted.push(box([point(m,x,y),point(m,x+w,y+h)]));},strokeRect(){},rect(){},clip(){},drawImage(){},createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})};return c;}
 const root={RoyaleGraphics:{current:{arenaScale:1,arenaAnimated:true}},document:{createElement(){const c=context();return{width:0,height:0,getContext:()=>c};}}};root.globalThis=root;vm.runInNewContext(fs.readFileSync(require.resolve('../src/custom-arena'),'utf8'),root);const battle=new C.Battle({mode:'Team3v3',arenaId:id,ai:false,headless:true});return{battle,painted:root.RoyaleCustomArena.prepare(battle,null).foreground.getContext().painted};
}
function sourceHpBox(tower){
 const config=P.healthBars.find(h=>h.Name===(tower.def.source.HealthBar||'Medium')),name=config[tower.team?'EnemyExportName':'PlayerExportName'];let field;
 function visit(id,m,path){if(P.hud.textFields[id]){if(path==='hpNumber.txt'){const f=P.hud.textFields[id],[l,t,r,b]=f.bounds,fit=T.fitText(T.metrics(String(Math.ceil(tower.hp))),f.fontSize,r-l),pad=5*fit.scaleX,x=f.align===2?(l+r-fit.width)/2:f.align===1?r-fit.width:l,y=(t+b-fit.height)/2;field=box([point(m,x-pad,y-pad),point(m,x+fit.width+pad,y+fit.height+pad)]);}return;}const clip=P.hud.clips[id];if(!clip)return;for(const [i,[child,mat]]of clip.frames[0].entries()){const next=clip.frameNames[0][i],p=path?path+'.'+next:next;visit(child,N.mul(m,mat===65535?I:P.hud.matrices[mat]),p);}}
 visit(P.hud.exports[name],I,'');A.ok(field,'Original HP number field exists');const anchor=N.towerArtPosition(tower),y=anchor.y+(tower.team?-62:-48);return{left:anchor.x+field.left*5/6,right:anchor.x+field.right*5/6,top:y+field.top*5/6,bottom:y+field.bottom*5/6};
}
for(const id of ['Team3v3','Team3v3Jungle','Team3v3Volcano'])test(id+' foreground leaves every Princess source HP field clear',()=>{const {battle,painted}=foreground(id);A.ok(painted.length>0||id==='Team3v3');for(const tower of battle.towers.filter(t=>!t.king)){const hp=sourceHpBox(tower),collisions=painted.filter(shape=>overlap(shape,hp));A.deepEqual(collisions,[],`${id} team ${tower.team}, slot ${tower.crownSlot}: foreground obscures original HP number`);}});
