const test=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const Core=require('../src/core'),D=require('../src/deck-manager'),R=require('../src/progression'),Forms=require('../src/card-forms');
function harness(){
 const F=Forms.createRegistry({forms:[{id:'qa-hero',baseCardId:'knight',kind:'hero',requiredShards:200,source:{...Core.CARD_BY_ID.knight.source}},{id:'qa-evo',baseCardId:'archers',kind:'evolution',requiredShards:6,cycles:2,source:{...Core.CARD_BY_ID.archers.source}}]}),deck=['archers','knight',...Core.DEFAULT_DECK.filter(id=>!['knight','archers'].includes(id))],forms=['qa-evo','qa-hero',null,null,null,null,null,null],p=Core.normalizeProfile({decks:[deck],unlockedForms:['qa-hero','qa-evo'],highestTrophies:R.ARENAS.find(a=>a.number===10).trophies,deckForms:{ranked:[forms],modes:{FourCardDeck:[[null,'qa-hero',null,null]]}}},{formRegistry:F,positionalSlots:true});
 let options;const element={classList:{add(){},remove(){}},style:{}},box={C:{...Core,normalizeProfile:p=>Core.normalizeProfile(p,{formRegistry:F}),Battle:class{constructor(opt){options=opt;return new Core.Battle({...opt,formRegistry:F,headless:true,recording:"compact"});}}},D,R,F,profile:p,preparing:false,trainingWorker:null,battle:null,learningReady:Promise.resolve(),learningStore:{refresh:async()=>({})},archivePending:Promise.resolve(),archiveBattle:async()=>{},toastTimer:0,loadToken:0,menuMode:null,clearTimeout(){},closeModal(){},toast(){},deckForms(){},specialDeckBuilder(){},generatedRandomLoadout(){throw Error('Unexpected generated deck');},save(){},sound(){},enterBattle:b=>{box.lastBattle=b;},$:()=>element,W:{matchOpponent:()=>({deck,levels:{},kingLevel:9}),recordOpponent:p=>p},native:{setArena(){},prepareBattle:async()=>{}},RoyaleArenaSelection:{choose:()=> 'training',base:id=>id},RoyaleTrainingDecks:{forMode:(seed,arena,mode)=>deck.slice(0,mode==='FourCardDeck'?4:8)},RoyaleLearning:require('../src/learning'),RoyalePlatform:{LocalMatchSession:class{}},Replay:{captureInitial(){}}};
 const s=fs.readFileSync(process.env.ROUTING_APP_PATH||path.join(__dirname,'../src/app.js'),'utf8'),a=s.indexOf('async function startBattle('),z=s.indexOf('async function playAgain(',a);A.ok(a>=0&&z>a);vm.createContext(box);vm.runInContext(s.slice(a,z)+'\nglobalThis.start=startBattle;',box);return{box,deck,forms,options:()=>options};
}
test('actual Default Training start keeps the selected ranked forms',async()=>{const h=harness();A.equal(await h.box.start('Default',true,{ai:false,seed:3}),true);A.deepEqual(h.options().deck,h.deck);A.deepEqual(Array.from(h.options().forms),h.forms);A.equal(h.options().formContext.casual,true);A.deepEqual(h.box.lastBattle.seatForms[0],h.forms);A.equal(h.box.lastBattle.formRegistry,h.box.F);});
test('actual special mode starts with its own deck/form bank',async()=>{const h=harness();A.equal(await h.box.start('FourCardDeck',true,{ai:false,seed:3}),true);A.deepEqual(Array.from(h.options().forms),[null,'qa-hero',null,null]);A.equal(h.options().deck.length,4);});
test('an unrelated explicit deck never inherits forms from the stored bank',async()=>{const h=harness(),deck=[...h.deck];[deck[0],deck[1]]=[deck[1],deck[0]];A.equal(await h.box.start('Default',true,{deck,ai:false,seed:3}),true);A.deepEqual(Array.from(h.options().forms),Array(8).fill(null));});
test('an unrelated explicit trophy deck does not leak mismatched ranked forms',async()=>{const h=harness(),deck=[...h.deck];[deck[0],deck[1]]=[deck[1],deck[0]];A.equal(await h.box.start('Default',false,{deck,ai:false,seed:3}),true);A.deepEqual(Array.from(h.options().forms),Array(8).fill(null));});
test('an explicit copy of the stored deck remains independent without supplied forms',async()=>{const h=harness();A.equal(await h.box.start('Default',true,{deck:[...h.deck],ai:false,seed:3}),true);A.deepEqual(Array.from(h.options().forms),Array(8).fill(null));});
test('an explicit empty forms array remains an intentional override',async()=>{const h=harness();A.equal(await h.box.start('Default',true,{deck:[...h.deck],forms:[],ai:false,seed:3}),true);A.deepEqual(Array.from(h.options().forms),Array(8).fill(null));});
test('Classic Challenge Default uses its own form bank instead of Training ranked forms',async()=>{const h=harness(),forms=[null,'qa-hero',null,null,null,null,null,null];h.box.profile.deckForms.modes.Default=[forms];A.equal(await h.box.start('Default',false,{queue:'challenge',ai:false,seed:3}),true);A.deepEqual(h.box.lastBattle.seatForms[0],forms);});
test('Default Training ignores validity of its unused challenge bank',async()=>{const h=harness();h.box.D={...h.box.D,modeState:()=>({valid:false})};A.equal(await h.box.start('Default',true,{ai:false,seed:3}),true);A.deepEqual(h.box.lastBattle.seatForms[0],h.forms);});
test('supplied explicit forms retain priority for an independent custom deck',async()=>{const h=harness();A.equal(await h.box.start('Default',true,{deck:[...h.deck],forms:h.forms,ai:false,seed:3}),true);A.deepEqual(h.box.lastBattle.seatForms[0],h.forms);});
test('generated RandomDeck forms retain priority over stored banks',async()=>{const h=harness();h.box.generatedRandomLoadout=()=>({ok:true,deck:h.deck,forms:h.forms});A.equal(await h.box.start('RandomDeck',false,{queue:'challenge',ai:false,seed:3}),true);A.deepEqual(h.box.lastBattle.seatForms[0],h.forms);});
test('a Default Training form error opens the actual ranked deck editor',async()=>{const h=harness();let editor;h.box.F={...h.box.F,qualify:()=>({ok:false,errors:[{reason:'Slot unavailable'}]})};h.box.deckForms=mode=>{editor=mode;};A.equal(await h.box.start('Default',true,{ai:false,seed:3}),false);A.equal(editor,'ranked');});
