'use strict';
// Actual shipped bundles only: never route requests or inject source modules.
// WEB_ROYALE_URL and EXPECTED_PROJECT_ID select Main or Custom. QA files stay
// outside dist; BROWSER_EXECUTABLE can select the installed browser.
const fs=require('node:fs'),path=require('node:path'),A=require('node:assert/strict'),crypto=require('node:crypto'),{chromium}=require('playwright');
const project=require('../project.json'),url=process.env.WEB_ROYALE_URL||'http://127.0.0.1:'+project.defaultPort,id=process.env.EXPECTED_PROJECT_ID||project.id,custom=id==='web-royale-custom',prefix=custom?'web-royale-custom':'web-royale-main';
const expected={id,name:custom?'Web Royale Custom':'Web Royale',version:process.env.EXPECTED_VERSION||project.version,defaultPort:custom?8082:8081,profileKey:prefix+'-profile-v1',learningKey:prefix+'-learning-v1',learningDatabase:prefix+'-learning-v1',replayDatabase:prefix+'-replays-v1',aiFolder:custom?'WebRoyaleCustom':'WebRoyaleMain'};
const out=path.resolve(process.env.BUILT_VARIANT_QA_OUT||path.join(__dirname,'../docs/qa/v051/built-'+id));fs.mkdirSync(out,{recursive:true});
const fixturePath=path.join(__dirname,'fixtures/replay-v046/3v3-rocket.json'),fixtureBytes=fs.readFileSync(fixturePath),fixture=JSON.parse(fixtureBytes),provenance=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/replay-v046/provenance.json')));
const report={url,expected,actualBundleOnly:true,errors:[],failedRequests:[],fixtureSha256:crypto.createHash('sha256').update(fixtureBytes).digest('hex')};
function savePng(name,data){fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(data.split(',')[1],'base64'));}
async function ready(page){await page.waitForFunction(()=>window.RoyaleDemo&&document.querySelector('#loading.hidden'),null,{timeout:60000});await page.evaluate(()=>Promise.all([RoyaleDemo.learningReady,RoyaleDemo.replayReady]));}

async function tesla(page){return page.evaluate(async()=>{
 const K=RoyaleCore,deck=['tesla','knight','archers','giant','musketeer','bomber','minions','cannon'],b=new K.Battle({ai:false,deck,enemyDeck:deck}),lib=RoyaleDemo.native;lib.setArena('royal');await lib.prepareBattle(b,K.DATA);b.towers=[];
 const u=b.spawn('Tesla',0,9*K.SX,22*K.SY,{wait:0}),expectedFirstDelay=u.def.interval-u.precharge;b.effects=[];const sc=lib.scenes.building_tesla,original=sc.draw,cv=document.createElement('canvas');cv.width=180;cv.height=150;const c=cv.getContext('2d'),samples=[],shots=[];let frame=-1;
 sc.draw=function(ctx,name,time,opt){const clip=this.clip(name);frame=opt.frame??RoyaleNative.frameAt(time,clip.fps,clip.frames.length,opt.loop);return original.call(this,ctx,name,time,opt);};
 const snap=phase=>{c.clearRect(0,0,180,150);c.fillStyle='#426a32';c.fillRect(0,0,180,150);lib.unit(c,'Tesla',90,110,u.team,b.time,u.visualState,u.heading,u.visualStarted,1,{elapsed:u.animationTime,idleTime:u.visualTime,attackDuration:u.visualDuration,entity:u});samples.push({time:b.time,phase,frame,hidden:u.hidden,progress:u.hideVisual?.progress,windup:u.windup?.remaining});shots.push(cv.toDataURL());};
 const advance=(seconds,phase)=>{for(let i=0;i<Math.round(seconds*60);i++){b.time+=1/60;b.tickEntity(u,1/60);if(i%6===0)snap(phase);}};
 try{advance(1.2,'idle');const target=b.spawn('Giant',1,9*K.SX,18*K.SY,{wait:0});target.hp=target.maxHp=100000;advance(3.8,'engaged');target.y=2*K.SY;advance(1.2,'idle-after');}finally{sc.draw=original;}
 return{expectedDamage:u.def.damage,expectedInterval:u.def.interval,expectedFirstDelay,samples,shots,hits:b.events.filter(e=>e.type==='damage'&&e.source===u.id).map(e=>({time:e.time,amount:e.amount})),labels:sc.clip('tesla1_blue').labels};
});}

async function machines(page){return page.evaluate(async()=>{
 const lib=RoyaleDemo.native;await lib.ensureScenes(['chr_movingcannon','chr_zap_machine','chr_flying_machine','building_basic_cannon','building_xbow','building_mortar',...['ElectroSpirit','HealSpirit'].map(id=>lib.data.units[id].scene)]);
 const ids=['MovingCannon','ZapMachine','flying-machine','BrokenCannon','DartBarrell','Cannon','Xbow','Mortar'],states=['idle','run','attack'],dirs=[['N',-90],['NE',-45],['E',0],['SE',45],['S',90],['SW',135],['W',180],['NW',-135]],sheets=[],records=[];
 for(const id of ids){const cfg=lib.data.units[id],sc=lib.scenes[cfg.scene],original=sc.draw;let current={};sc.draw=function(c,name,time,options){records.push({...current,id,name,time,frame:options.frame??null,loop:options.loop,reflected:c.getTransform().a<0});return original.call(this,c,name,time,options);};
  const cv=document.createElement('canvas');cv.width=1440;cv.height=1020;const c=cv.getContext('2d');c.fillStyle='#334052';c.fillRect(0,0,cv.width,cv.height);c.font='13px Arial';
  try{for(const team of [0,1])for(let si=0;si<3;si++)for(let di=0;di<8;di++){const [dir,degrees]=dirs[di],x=di*180+90,y=(team*3+si)*170+105;current={team,state:states[si],dir};c.save();c.translate(x,y);lib.unit(c,id,0,0,team,.08,states[si],degrees*Math.PI/180,0,1,{height:0});c.restore();c.strokeStyle='#75dbe2';c.beginPath();c.moveTo(x,y+32);c.lineTo(x+Math.cos(degrees*Math.PI/180)*30,y+32+Math.sin(degrees*Math.PI/180)*30);c.stroke();c.fillStyle='white';const r=records.at(-1);c.fillText((team?'red':'blue')+' '+states[si]+' '+dir,x-76,y+49);c.fillText(r.name.replace(cfg.prefix[team],'').slice(0,25)+(r.frame===null?'':' f'+r.frame),x-76,y+64);}}finally{sc.draw=original;}
  sheets.push({id,image:cv.toDataURL()});
 }
 const animationChecks=[];for(const id of ['MovingCannon','ZapMachine','flying-machine','BrokenCannon'])for(const team of [0,1])for(const state of states){if(id==='ZapMachine'&&state==='idle')continue;const hashes=[];for(const time of [.03,.19,.37]){const cv=document.createElement('canvas');cv.width=256;cv.height=256;const c=cv.getContext('2d');lib.unit(c,id,128,175,team,time,state,Math.PI/2,0,1,{height:0});let hash=2166136261;for(const byte of c.getImageData(0,0,256,256).data)hash=Math.imul(hash^byte,16777619);hashes.push(hash>>>0);}animationChecks.push({id,team,state,hashes,animated:new Set(hashes).size>1});}
 const spiritPoses=[],spiritCanvas=document.createElement('canvas');spiritCanvas.width=720;spiritCanvas.height=520;const spiritContext=spiritCanvas.getContext('2d');spiritContext.fillStyle='#334052';spiritContext.fillRect(0,0,720,520);spiritContext.font='13px Arial';
 for(const [index,id]of ['ElectroSpirit','HealSpirit'].entries()){const cfg=lib.data.units[id],sc=lib.scenes[cfg.scene],original=sc.draw;let current={};sc.draw=function(c,name,time,opt){spiritPoses.push({...current,id,name,expectedName:cfg.prefix[current.team]+'_attack1_1',time,frame:opt.frame??null,loop:opt.loop});return original.call(this,c,name,time,opt);};try{for(const team of [0,1])for(const [di,[dir,degrees]]of [['E',0],['S',90],['W',180]].entries()){current={team,dir};const x=di*240+120,y=(index*2+team)*130+80;lib.unit(spiritContext,id,x,y,team,.08,'attack',degrees*Math.PI/180,0,1,{height:0});spiritContext.fillStyle='white';spiritContext.fillText(id+' '+(team?'red':'blue')+' '+dir,x-100,y+32);}}finally{sc.draw=original;}}
 return{sheets,records,animationChecks,spiritPoses,spiritImage:spiritCanvas.toDataURL()};
});}

async function arenas(page){return page.evaluate(async()=>{
 const K=RoyaleCore,V=RoyaleBattleView,deck=['tesla','knight','archers','giant','musketeer','bomber','minions','cannon'],results=[];
 for(const id of ['Team3v3','Team3v3Jungle','Team3v3Volcano']){
  const started=await RoyaleDemo.startBattle('Team3v3',true,{arenaId:id,seed:17,ai:false,deck,enemyDeck:deck});if(!started)throw Error('Could not start '+id);const b=RoyaleDemo.battle;b.paused=true;const floor=RoyaleCustomArena.prepare(b,RoyaleDemo.native),layout=b.arenaLayout;
  const towers=b.towers.map(t=>({id:t.id,entity:t.entity,team:t.team,owner:t.owner,crownSlot:t.crownSlot,king:t.king,x:t.x,y:t.y,artX:RoyaleNative.towerArtPosition(t).x})),shots=[];
  for(const compact of [false,true]){V.configure({arenaId:id,compact});const cv=document.createElement('canvas');cv.width=V.layout.width;cv.height=V.layout.height;const c=cv.getContext('2d');RoyaleDraw.battle(c,b,b.time,null,null);const corners=[];for(const x of [layout.left+.05,layout.right-.05])for(const y of [layout.top+.05,layout.bottom-.05]){const point=V.toScreen({x:x*K.SX,y:y*K.SY});corners.push({x,y,point,onBoard:V.onBoard(point),alpha:c.getImageData(Math.floor(point.x),Math.floor(point.y),1,1).data[3]});}
   // Paint the actual source HP glyphs and the real foreground separately.
   // Their opaque pixels must not intersect, irrespective of camera scaling.
   const mask=document.createElement('canvas'),front=document.createElement('canvas');mask.width=front.width=cv.width;mask.height=front.height=cv.height;const m=mask.getContext('2d'),f=front.getContext('2d'),hud=RoyalePresentation.hud.data,I=[1,0,0,1,0,0];for(const ctx of [m,f]){ctx.translate(V.camera.x,V.camera.y);ctx.scale(V.camera.scale,V.camera.scale);}for(const t of b.towers.filter(t=>!t.king)){const anchor=RoyaleNative.towerArtPosition(t);m.save();m.translate(anchor.x,anchor.y+(t.team?-62:-48));m.scale(5/6,5/6);const name=t.team?'hp_enemy_tower_withNumber':'hp_player_tower_withNumber';function paint(idx,matrix,path){const field=hud.textFields[idx];if(field){if(path==='hpNumber.txt'){m.save();m.transform(...matrix);RoyaleText.field(m,field,String(Math.ceil(t.hp)));m.restore();}return;}const clip=hud.clips[idx];if(clip)for(const [i,[child,mat]]of clip.frames[0].entries()){const part=clip.frameNames[0][i];paint(child,RoyaleNative.mul(matrix,mat===65535?I:hud.matrices[mat]),path?path+'.'+part:part);}}paint(hud.exports[name],I,'');m.restore();}RoyaleCustomArena.drawForeground(f,b,RoyaleDemo.native,0);const glyphPixels=m.getImageData(0,0,cv.width,cv.height).data,foregroundPixels=f.getImageData(0,0,cv.width,cv.height).data;let foregroundHudPixels=0,hpPixels=0;for(let i=3;i<glyphPixels.length;i+=4)if(glyphPixels[i]>127){hpPixels++;if(foregroundPixels[i]>0)foregroundHudPixels++;}
   shots.push({compact,image:cv.toDataURL(),corners,camera:{...V.camera},hpPixels,foregroundHudPixels});}
  const rocketChecks=[];for(const team of [0,1])for(const pair of [[0,1],[1,2]]){const probe=new K.Battle({mode:'Team3v3',arenaId:id,ai:false,headless:true,seed:17}),row=probe.towers.filter(t=>!t.king&&t.team===team).sort((a,b)=>a.crownSlot-b.crownSlot),before=row.map(t=>t.hp);probe.projectileImpact({name:'RocketSpell',team:1-team,owner:1-team,x:(row[pair[0]].x+row[pair[1]].x)/2,y:row[0].y,level:9,vx:0,vy:team?-1:1,attacker:null},null);rocketChecks.push({team,pair,damage:row.map((t,i)=>before[i]-t.hp)});}
  results.push({id,mode:b.mode,seatCount:b.seatCount,seatSlots:b.seatSlots,bounds:[layout.left,layout.right,layout.top,layout.bottom],lanes:layout.lanes,towers,foundations:floor.foundations,shots,rocketChecks});
 }
 return results;
});}

(async()=>{const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{channel:process.env.BROWSER_CHANNEL||'msedge'})});try{
 const page=await browser.newPage({viewport:{width:1100,height:1300}});page.on('pageerror',e=>report.errors.push(e.message));page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));
 const foreignKeys=['web-royale-classic-v4','web-royale-main-profile-v1','web-royale-custom-profile-v1'].filter(k=>k!==expected.profileKey);
 await page.addInitScript(keys=>{for(const key of keys)if(localStorage.getItem(key)===null)localStorage.setItem(key,JSON.stringify({name:'Foreign sentinel '+key}));},foreignKeys);
 await page.goto(url);await ready(page);
 report.identity=await page.evaluate(async()=>{const demo=RoyaleDemo,link=document.querySelector('link[rel="manifest"]');return{version:RoyaleBundle.version,project:RoyaleBundle.project,title:document.title,manifest:link?await(await fetch(link.href)).json():null,profileKey:demo.repository.key,learningKey:demo.learningStore.fallback.key,learningDatabase:demo.learningStore.fallback.database,openedLearningDatabase:demo.learningStore.fallback.db?.name,learningMode:demo.learningStore.mode,replayDatabase:demo.replayStore.database,openedReplayDatabase:demo.replayStore.db?.name,databases:await indexedDB.databases(),scripts:[...document.scripts].map(s=>s.src).filter(Boolean)};});
 for(const [key,value]of Object.entries(expected))A.equal(report.identity.project[key],value,'Project '+key);A.equal(report.identity.version,expected.version);A.ok(report.identity.title.includes(expected.name));A.equal(report.identity.manifest.name,expected.name);A.equal(report.identity.manifest.short_name,expected.name);
 for(const key of ['profileKey','learningKey','learningDatabase','replayDatabase'])A.equal(report.identity[key],expected[key],key);A.equal(report.identity.openedLearningDatabase,expected.learningDatabase);A.equal(report.identity.openedReplayDatabase,expected.replayDatabase);A.ok(report.identity.scripts.some(s=>/\/app\.[a-f0-9]+\.js/.test(s)),'Runs the actual hashed application bundle');
 report.profile=await page.evaluate(({expected,foreignKeys})=>{const old=Object.fromEntries(foreignKeys.map(k=>[k,localStorage.getItem(k)])),p={...RoyaleDemo.profile,name:expected.name+' QA'};RoyaleDemo.applyProfile(p);return{old,savedName:JSON.parse(localStorage.getItem(expected.profileKey)).name,foreignAfter:Object.fromEntries(foreignKeys.map(k=>[k,localStorage.getItem(k)]))};},{expected,foreignKeys});A.deepEqual(report.profile.foreignAfter,report.profile.old);await page.reload();await ready(page);report.profile.reloadedName=await page.evaluate(()=>RoyaleDemo.profile.name);A.equal(report.profile.reloadedName,report.profile.savedName);

 report.tesla=await tesla(page);const labels=report.tesla.labels,raised=labels.indexOf('appear_end'),idle=labels.indexOf('idle'),steady=report.tesla.samples.filter(f=>f.phase==='engaged'&&f.time>2.1);A.ok(steady.length>20);A.ok(steady.every(f=>f.frame===raised&&!f.hidden),'Tesla stays raised during all attack cooldowns');A.ok(report.tesla.samples.filter(f=>f.phase==='idle').every(f=>f.frame===idle&&f.hidden));A.ok(report.tesla.samples.filter(f=>f.phase==='idle-after'&&f.time>5.9).every(f=>f.frame===idle&&f.hidden));A.ok(report.tesla.samples.some(f=>f.phase==='engaged'&&f.progress>0&&f.progress<1));A.ok(report.tesla.samples.some(f=>f.phase==='idle-after'&&f.progress>0&&f.progress<1));A.ok(report.tesla.hits.length>=3,'Sustained engagement delivers at least three attacks');A.ok(Math.abs(report.tesla.hits[0].time-1.2-report.tesla.expectedFirstDelay)<=2/60+1e-7,'First Tesla release respects the current source load time');A.ok(report.tesla.hits.every(h=>h.time<=5+1e-7),'Tesla stops shooting when the target leaves');A.ok(report.tesla.hits.every(h=>h.amount===report.tesla.expectedDamage));for(let i=1;i<report.tesla.hits.length;i++)A.ok(Math.abs(report.tesla.hits[i].time-report.tesla.hits[i-1].time-report.tesla.expectedInterval)<=1/60+1e-7,'Tesla attack cadence matches the current source within one fixed step');
 const samples=report.tesla.samples;for(const [name,index]of [['idle',3],['rising',samples.findIndex(f=>f.phase==='engaged'&&f.progress>.3&&f.progress<.7)],['raised',samples.findIndex(f=>f.phase==='engaged'&&f.time>2.8)],['lowering',samples.findIndex(f=>f.phase==='idle-after'&&f.progress>.3&&f.progress<.7)],['hidden',samples.length-1]])savePng('tesla-'+name,report.tesla.shots[index]);delete report.tesla.shots;

 report.machines=await machines(page);for(const sheet of report.machines.sheets)savePng('machine-'+sheet.id,sheet.image);delete report.machines.sheets;A.equal(report.machines.records.length,384);
 for(const r of report.machines.records.filter(r=>['N','E','S','W'].includes(r.dir))){A.equal(r.reflected,r.dir==='W',r.id+' '+r.dir+' reflection');if(['Cannon','Xbow'].includes(r.id))A.equal(r.frame,{N:0,E:9,S:18,W:9}[r.dir],r.id+' '+r.dir+' rotation');else{const n=r.id==='BrokenCannon'&&r.state==='run'?1:(r.id==='Mortar'?{N:1,E:3,S:5,W:3}:{N:1,E:10,S:18,W:10})[r.dir];A.ok(r.name.endsWith('_'+n),r.id+' '+r.dir+' source view '+r.name);A.equal(r.frame,null,r.id+' clock is not pinned');}}
 for(const r of report.machines.animationChecks)if((r.state!=='idle'&&!(r.id==='BrokenCannon'&&r.state==='run'))||r.id==='flying-machine')A.equal(r.animated,true,JSON.stringify(r));
 savePng('spirit-authored-attacks',report.machines.spiritImage);delete report.machines.spiritImage;A.equal(report.machines.spiritPoses.length,12);for(const r of report.machines.spiritPoses){A.equal(r.name,r.expectedName,'Spirit keeps its authored jump attack toward '+r.dir);A.equal(r.loop,false);A.equal(r.frame,null);A.ok(r.time>0&&Math.abs(r.time-.08)<=1/30,'Live spirit attack clock respects the active graphics frame rate');}

 report.arenas=await arenas(page);for(const arena of report.arenas){A.equal(arena.mode,'Team3v3');A.equal(arena.seatCount,6);A.deepEqual(arena.bounds,[0,18,-2,34]);A.deepEqual(arena.lanes,[3.5,9,14.5]);A.equal(arena.foundations.length,12);for(const team of [0,1]){const princess=arena.towers.filter(t=>!t.king&&t.team===team).sort((a,b)=>a.crownSlot-b.crownSlot);A.deepEqual(princess.map(t=>t.x/(480/18)),[1.5,9,16.5]);A.ok(princess.every(t=>t.y/20===(team?6.5:25.5)));}for(const t of arena.towers){A.equal(t.artX,t.x);A.equal(arena.seatSlots[t.owner],t.crownSlot);A.equal(t.owner%2,t.team);A.ok(arena.foundations.some(f=>f.entity===t.entity&&f.team===t.team&&Math.abs(f.x-t.x)<1e-9&&f.y===t.y),'Foundation follows tower '+t.id);}for(const shot of arena.shots){savePng(arena.id+'-'+(shot.compact?'compact':'full'),shot.image);delete shot.image;A.ok(shot.corners.every(c=>c.onBoard&&c.alpha===255),'Floor covers all playable corners');A.ok(shot.hpPixels>300,'Real source HP glyphs were painted');A.equal(shot.foregroundHudPixels,0,arena.id+' compact '+shot.compact+' foreground cannot paint over HP glyphs');}for(const check of arena.rocketChecks)A.deepEqual(check.damage,[0,0,0],'Adjacent midpoint Rocket misses both towers');}

 A.equal(report.fixtureSha256,provenance.fixtureSha256,'Fixture is the historical captured record');report.replay=await page.evaluate(async record=>{await RoyaleDemo.replayReady;await RoyaleDemo.replayStore.put(record);const stored=await RoyaleDemo.replayStore.get(record.id),started=await RoyaleDemo.playReplay(record.id);if(!started)throw Error('Historical replay failed to open');const session=RoyaleDemo.session;RoyaleDemo.step(record.duration+.1);session.battle.paused=true;RoyaleDemo.refreshHand(true);return{started,storedEngine:stored.engine,sessionEngine:session.record.engine,isReplay:session.battle.isReplay,usesLegacy046:session.battle instanceof RoyaleLegacyCore046.Battle,finished:session.finished,error:session.error,readOnly:session.command().ok===false,digest:RoyaleReplay.digest(session.battle),princessXs:session.battle.towers.filter(t=>!t.king&&t.team===1).map(t=>t.x/RoyaleCore.SX)};},fixture);
 A.equal(report.replay.sessionEngine,'0.46');A.equal(report.replay.storedEngine,'0.46');A.ok(report.replay.isReplay&&report.replay.usesLegacy046&&report.replay.finished&&report.replay.readOnly);A.equal(report.replay.error,null);A.deepEqual(report.replay.digest,fixture.expected,'Historical state including two-tower Rocket damage remains exact');A.deepEqual(report.replay.princessXs,[3.5,9,14.5]);await page.waitForFunction(()=>!document.getElementById('replayControls').hidden&&document.getElementById('replayTime').textContent.startsWith(Math.floor(RoyaleDemo.battle.time)+' / '+Math.ceil(RoyaleDemo.session.record.duration)+'s'));report.replay.displayedTime=await page.locator('#replayTime').textContent();await page.locator('#viewport').screenshot({path:path.join(out,'legacy-046-replay.png')});
 const fixture051=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/replay-v051/3v3-rocket-tesla.json'))),proof051=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/replay-v051/provenance.json')));A.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'fixtures/replay-v051/3v3-rocket-tesla.json'))).digest('hex'),proof051.fixtures.find(f=>f.file==='3v3-rocket-tesla.json').sha256);
 report.replay051=await page.evaluate(record=>{const session=new RoyaleReplay.Session(record);session.seek(record.duration);return{engine:session.record.engine,usesLegacy051:session.battle instanceof RoyaleLegacyCore051.Battle,finished:session.finished,error:session.error,digest:RoyaleReplay.digest(session.battle)};},fixture051);A.equal(report.replay051.engine,'0.51');A.ok(report.replay051.usesLegacy051&&report.replay051.finished);A.equal(report.replay051.error,null);A.deepEqual(report.replay051.digest,fixture051.expected);
 report.currentReplay=await page.evaluate(()=>{const K=RoyaleCore,R=RoyaleReplay,deck=['tesla','knight','archers','giant','musketeer','bomber','minions','cannon'],b=new K.Battle({queue:'challenge',deck,enemyDeck:deck,seed:520151,ai:false});R.captureInitial(b);const slot=b.hand[0].findIndex((_,i)=>b.card(0,i).cost<=b.elixir[0]),deployed=b.deploy(0,slot,4*K.SX,22*K.SY);if(!deployed.ok)throw Error(deployed.reason);for(let frame=0;frame<720;frame++)b.step(1/60);const record=R.pack(b),session=new R.Session(record);session.seek(record.duration);return{engine:record.engine,commands:record.commands.length,error:session.error,finished:session.finished,digest:R.digest(session.battle),expected:record.expected};});A.equal(report.currentReplay.engine,'0.52');A.equal(report.currentReplay.commands,1);A.ok(report.currentReplay.finished);A.equal(report.currentReplay.error,null);A.deepEqual(report.currentReplay.digest,report.currentReplay.expected);
 report.content=await page.evaluate(()=>({cards:RoyaleCore.CARDS.length,forms:RoyaleCardForms.defaultRegistry.forms.length,snapshot:RoyaleCore.DATA.snapshot,heroes:RoyaleCardForms.defaultRegistry.forms.filter(f=>f.kind==='hero').length,evolutions:RoyaleCardForms.defaultRegistry.forms.filter(f=>f.kind==='evolution').length}));A.equal(report.content.cards,custom?102:123);if(custom)A.equal(report.content.forms,0,'Custom ships an empty extension registry');
 A.deepEqual(report.errors,[]);report.passed=true;console.log(JSON.stringify({url,project:report.identity.project.id,version:report.identity.version,teslaSteadyFrames:[...new Set(steady.map(s=>s.frame))],teslaHits:report.tesla.hits,machinePoses:report.machines.records.length,animationProbes:report.machines.animationChecks.length,arenaCompositions:report.arenas.reduce((n,r)=>n+r.shots.length,0),legacyReplayExact:true,errors:report.errors,out},null,2));
}catch(error){report.failure=String(error.stack||error);throw error;}finally{fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2)+'\n');await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
