'use strict';
// Actual release bundle only. Fixture progress remains in an isolated browser;
// no source modules, renderers or asset replacements are injected.
const fs=require('node:fs'),path=require('node:path'),A=require('node:assert/strict'),crypto=require('node:crypto');
let chromium;try{({chromium}=require('playwright'));}catch(_){({chromium}=require('C:/Users/Oceyi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const project=require('../project.json'),url=(process.env.URL||'http://127.0.0.1:'+project.defaultPort+'/').replace(/\/?$/,'/'),version=process.env.VERSION||project.version,out=path.resolve(process.env.PROOF||'docs/qa/v523/acquisition-'+project.id);
fs.mkdirSync(out,{recursive:true});const report={url,version,actualBundleOnly:true,passed:false,errors:[],assets:[],screenshots:[]};
async function ready(p){await p.waitForFunction(()=>window.RoyaleDemo&&document.querySelector('#loading.hidden'),null,{timeout:240000});await p.evaluate(()=>Promise.all([RoyaleDemo.learningReady,RoyaleDemo.replayReady]));}
async function close(p){if(await p.locator('#modalPanel').isVisible())await p.locator('#modalPanel [data-action="close"]').first().click();}
async function shot(p,name){await p.waitForFunction(()=>{const t=document.querySelector('#toast');return!t||!t.classList.contains('show')&&Number(getComputedStyle(t).opacity)<.01;},null,{timeout:7000});await p.locator('#viewport').screenshot({path:path.join(out,name+'.png')});report.screenshots.push(name+'.png');}
async function art(p,selector){const rows=await p.locator(selector+' .card-visual').evaluateAll(nodes=>nodes.map(n=>({kind:n.dataset.cardKind,frame:n.dataset.cardFrame,source:n.dataset.sourceFrame,filter:getComputedStyle(n.querySelector('.card-frame')).filter,mask:getComputedStyle(n.querySelector('.card-portrait')).maskImage,ready:[...n.querySelectorAll('img')].every(i=>i.complete&&i.naturalWidth>0)})));A.ok(rows.length);A.ok(rows.every(r=>r.ready),'All original portraits and frames load');A.ok(rows.filter(r=>r.kind!=='standard').every(r=>r.filter==='none'),'Original type frames never inherit historical rarity recoloring');for(const r of rows.filter(r=>['hero','evolution','champion'].includes(r.kind))){A.equal(r.source,'true');A.notEqual(r.mask,'none','Source silhouettes must use their alpha masks');}return rows;}
async function contentTarget(p,kind,target){await close(p);await p.evaluate(()=>RoyaleDemo.show('shop'));await p.locator('[data-action="content-shop-kind"][data-kind="'+kind+'"]').click();for(let i=0;i<20;i++){const row=p.locator('[data-content-target="'+target+'"]');if(await row.count())return row;const next=p.locator('[data-action="content-shop-page"]',{hasText:'Next'});A.equal(await next.isEnabled(),true,'Offer appears in bounded original catalog');await next.click();}throw Error('Offer not found: '+target);}
async function currency(p){const images=await p.locator('[data-ui="reward-hero-coins"],[data-ui="reward-wild-shards"]').evaluateAll(nodes=>nodes.map(n=>({key:n.dataset.ui,ready:n.complete&&n.naturalWidth>0})));A.ok(images.every(r=>r.ready));return images;}
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files/Google/Chrome/Application/chrome.exe'}),context=await browser.newContext({viewport:{width:1000,height:1200},serviceWorkers:'block'}),page=await context.newPage();
 const watch=p=>{p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/Content Security Policy|violates.*policy/i.test(m.text()))report.errors.push(m.text());});p.on('response',r=>{if(r.status()>=400&&/\/(assets|app\.|runtime\.|bootstrap\.)/.test(r.url()))report.assets.push({url:r.url(),status:r.status()});});};watch(page);
 try{
  await page.goto(url);await ready(page);report.identity=await page.evaluate(()=>({version:RoyaleBundle.version,project:RoyaleBundle.project.id,cards:RoyaleCore.CARDS.length,forms:RoyaleCardForms.defaultRegistry.forms.length,towers:globalThis.RoyaleTowerTroops?.catalog.length||0,scripts:[...document.scripts].map(s=>s.src).filter(Boolean)}));A.equal(report.identity.version,version);A.equal(report.identity.project,project.id);
  const rr=await page.request.get(new URL('release.json',url).href),rb=await rr.body(),release=JSON.parse(rb),app=await page.request.get(new URL(release.app,url).href),ab=await app.body();A.equal(app.status(),200);A.equal(release.version,version);A.equal(crypto.createHash('sha256').update(ab).digest('hex'),release.files[release.app]);A.ok(report.identity.scripts.some(s=>new URL(s).pathname.endsWith('/'+release.app)));report.release={app:release.app,appSha256:release.files[release.app],manifestSha256:crypto.createHash('sha256').update(rb).digest('hex')};if(process.env.RELEASE_SHA)A.equal(report.release.manifestSha256,process.env.RELEASE_SHA);
  report.maskCoverage=await page.evaluate(()=>RoyaleBundle.cardMaskCoverage);A.equal(Object.keys(report.maskCoverage).length,3);A.ok(Object.values(report.maskCoverage).every(r=>r.normalized));
  const custom=report.identity.project==='web-royale-custom';
  const fixture=await page.evaluate(custom=>{const p=structuredClone(RoyaleDemo.profile),F=RoyaleCardForms.defaultRegistry;p.trophies=p.highestTrophies=RoyaleProgression.ARENAS.find(a=>a.number===10).trophies;p.gold=1000000;p.gems=10000;p.earnedCrowns=350;p.heroCoins=200;p.heroStarterGranted=true;p.evoWildShards=2;p.contentShopPurchases={};p.passClaimed=[];p.progressionRewardReceipts={};if(!custom){p.experience=RoyalePlayerXP.MAX_XP;const hero=F.forCard('knight').find(f=>f.kind==='hero'),evo=F.forCard('knight').find(f=>f.kind==='evolution'),archers=F.forCard('archers').find(f=>f.kind==='evolution');p.unlockedForms=[archers.id];p.formShards[evo.id]=4;const tower=RoyaleTowerTroops.catalog.find(c=>c.name==='Cannoneer');p.unlockedTowerTroops=['King_PrincessTowers'];p.towerTroopCopies[tower.id]=Math.max(0,RoyaleTowerTroops.upgradeQuote(p,tower.id).copies-1);RoyaleDemo.applyProfile(p);return{hero:hero.id,evo:evo.id,archers:archers.id,tower:tower.id};}RoyaleDemo.applyProfile(p);return{};},custom);report.fixture=fixture;
  await page.evaluate(()=>RoyaleDemo.show('shop'));
  if(custom){A.equal(report.identity.cards,102);A.equal(report.identity.forms,0);A.equal(report.identity.towers,0);A.equal(await page.locator('#contentShop').count(),0,'Empty Custom registries create no invented offers');await shot(page,'custom-shop-existing-content');}
  else{
   A.equal(report.identity.cards,123);A.equal(report.identity.forms,67);A.equal(report.identity.towers,4);
   let row=await contentTarget(page,'hero',fixture.hero);report.heroShopArt=await art(page,'#contentShop');report.shopIconClearance=await page.locator('#contentShop .content-shop-offer').evaluateAll(nodes=>nodes.map(n=>n.querySelector('.card-type-icon').getBoundingClientRect().top-n.querySelector('.offer-rarity').getBoundingClientRect().bottom));A.ok(report.shopIconClearance.every(gap=>gap>=3),'Source diamonds do not overlap shop descriptions');await shot(page,'shop-hero-before');const cost=await page.evaluate(()=>RoyaleDemo.profile.heroCoins);await row.locator('[data-action="buy-content-offer"]').click();await page.waitForSelector('[data-reward-kind="form"][data-reward-id="'+fixture.hero+'"]');report.heroPurchase=await page.evaluate(id=>({coins:RoyaleDemo.profile.heroCoins,owned:RoyaleDemo.profile.unlockedForms.includes(id),receipts:Object.keys(RoyaleDemo.profile.contentShopPurchases)}),fixture.hero);A.equal(report.heroPurchase.coins,cost-200);A.equal(report.heroPurchase.owned,true);report.heroReceiptArt=await art(page,'[data-reward-id="'+fixture.hero+'"]');await shot(page,'hero-unlocked-receipt');await page.locator('#modalPanel [data-action="use-form"][data-id="'+fixture.hero+'"]').click();await page.locator('.replace-grid [data-slot="1"]').click();await page.evaluate(()=>{RoyaleDemo.show('cards');RoyaleDemo.cardSection('decks');});A.equal(await page.evaluate(()=>RoyaleDemo.profile.deckForms.ranked[0][1]),fixture.hero);report.deckArt=await art(page,'#deckGrid');await shot(page,'deck-owned-evo-hero');
   for(const expected of [5,6]){row=await contentTarget(page,'evo-shard',fixture.evo);await row.locator('[data-action="buy-content-offer"]').click();await page.waitForSelector('[data-reward-kind="form-shard"][data-reward-id="'+fixture.evo+'"]');const state=await page.evaluate(id=>({shards:RoyaleDemo.profile.formShards[id],wild:RoyaleDemo.profile.evoWildShards,owned:RoyaleDemo.profile.unlockedForms.includes(id)}),fixture.evo);A.deepEqual(state,{shards:expected,wild:6-expected,owned:expected===6});report['evo'+expected]=state;await shot(page,'evolution-'+expected+'-shards');}A.equal(await page.locator('[data-reward-kind="form-shard"][data-reward-id="'+fixture.evo+'"]').count(),1,'Credited shard appears once in the receipt');A.equal(await page.locator('#modalPanel [data-action="use-form"][data-id="'+fixture.evo+'"]').isEnabled(),true,'The sixth shard immediately makes the Evolution usable');
   row=await contentTarget(page,'tower-troop',fixture.tower);report.towerShopArt=await art(page,'[data-content-target="'+fixture.tower+'"]');const before=await page.evaluate(id=>({gold:RoyaleDemo.profile.gold,copies:RoyaleDemo.profile.towerTroopCopies[id]}),fixture.tower);await row.locator('[data-action="buy-content-offer"]').click();await page.waitForSelector('[data-reward-kind="tower-troop"]');report.towerPurchase=await page.evaluate(id=>({gold:RoyaleDemo.profile.gold,copies:RoyaleDemo.profile.towerTroopCopies[id],owned:RoyaleDemo.profile.unlockedTowerTroops.includes(id)}),fixture.tower);A.equal(report.towerPurchase.owned,true);A.ok(report.towerPurchase.gold<before.gold);A.ok(report.towerPurchase.copies>before.copies);await shot(page,'tower-purchase-receipt');await page.locator('#modalPanel [data-action="tower-troops"]').click();let tq=await page.evaluate(id=>RoyaleTowerTroops.upgradeQuote(RoyaleDemo.profile,id),fixture.tower);A.equal(tq.canUpgrade,true);A.equal(await page.locator('.tower-troop-art .card-level').count(),0,'Tower levels remain outside the authored crown silhouette');await shot(page,'tower-troop-upgrade-preview');await page.locator('[data-action="upgrade-tower-troop"][data-id="'+fixture.tower+'"]').click();report.towerUpgrade=await page.evaluate(id=>({level:RoyaleDemo.profile.towerTroopLevels[id],gold:RoyaleDemo.profile.gold,copies:RoyaleDemo.profile.towerTroopCopies[id]}),fixture.tower);A.equal(report.towerUpgrade.level,tq.level+1);A.equal(report.towerUpgrade.copies,tq.haveCopies-tq.copies);await page.locator('[data-action="select-tower-troop"][data-id="'+fixture.tower+'"]').click();await page.waitForTimeout(100);A.equal(await page.evaluate(()=>RoyaleDemo.profile.selectedTowerTroop),fixture.tower);await close(page);
   await page.evaluate(()=>{RoyaleDemo.show('cards');RoyaleDemo.cardSection('collection');RoyaleDemo.librarySection('magic-items');});await page.locator('[data-action="form-inventory"]').first().click();await shot(page,'inventory-original-frames');await close(page);
  }
  // Supplemental progression previews and receipts use exactly the credited
  // typed items, including a playable cosmetic that can be equipped immediately.
  await close(page);await page.evaluate(()=>RoyaleDemo.show('home'));await page.locator('[data-action="menu"]:visible').first().click();await page.locator('#modalPanel [data-action="pass-rewards"]').first().click();const preview=await page.evaluate(()=>RoyaleEconomy.passReward(RoyaleDemo.profile,9));A.ok(preview.sourceCosmetics?.length);report.passPreview=preview;report.currencyIcons=await currency(page);if(!custom)A.ok(report.currencyIcons.length>0);await shot(page,'crown-rewards-preview');await page.locator('[data-pass-tier="9"] [data-action="claim-pass"]').click();await page.waitForSelector('.content-reward-item[data-reward-kind="emote"],.content-reward-item[data-reward-kind="tower-skin"]');const cosmetic=await page.locator('.content-reward-item[data-reward-kind="emote"],.content-reward-item[data-reward-kind="tower-skin"]').first().evaluate(n=>({kind:n.dataset.rewardKind,id:n.dataset.rewardId}));report.cosmeticReceipt=cosmetic;A.equal(await page.locator('.content-reward-item[data-reward-id="'+cosmetic.id+'"]').count(),1);await shot(page,'progression-cosmetic-receipt');await page.locator('[data-action="'+(cosmetic.kind==='tower-skin'?'select-tower-skin':'equip-emote')+'"][data-id="'+cosmetic.id+'"]').click();A.equal(await page.evaluate(c=>c.kind==='tower-skin'?RoyaleDemo.profile.selectedTowerSkin===c.id:RoyaleDemo.profile.equippedEmotes.includes(c.id),cosmetic),true);
  // Keep the established cosmetic shop path and prove its actual collection state.
  await close(page);await page.evaluate(()=>RoyaleDemo.show('shop'));const oldEmote=page.locator('#emoteShop [data-action="buy-emote"]:not(:disabled)').first(),oldSkin=page.locator('[data-action="buy-tower-skin"]:not(:disabled)').first();A.ok(await oldEmote.count()||await oldSkin.count());const old=await oldEmote.count()?oldEmote:oldSkin,oldId=await old.getAttribute('data-id'),oldAction=await old.getAttribute('data-action');await old.click();A.equal(await page.evaluate(x=>x.action==='buy-emote'?RoyaleDemo.profile.ownedEmotes.includes(x.id):RoyaleDemo.profile.ownedTowerSkins.includes(x.id),{action:oldAction,id:oldId}),true);report.existingCosmeticPurchase={id:oldId,action:oldAction};await close(page);
  const saved=await page.evaluate(()=>({forms:RoyaleDemo.profile.unlockedForms,shards:RoyaleDemo.profile.formShards,coins:RoyaleDemo.profile.heroCoins,wild:RoyaleDemo.profile.evoWildShards,deckForms:RoyaleDemo.profile.deckForms,tower:RoyaleDemo.profile.selectedTowerTroop,towerLevels:RoyaleDemo.profile.towerTroopLevels,towerCopies:RoyaleDemo.profile.towerTroopCopies,skins:RoyaleDemo.profile.ownedTowerSkins,skin:RoyaleDemo.profile.selectedTowerSkin,emotes:RoyaleDemo.profile.ownedEmotes,equipped:RoyaleDemo.profile.equippedEmotes,receipts:RoyaleDemo.profile.contentShopPurchases,pass:RoyaleDemo.profile.passClaimed}));await page.reload();await ready(page);const loaded=await page.evaluate(()=>({forms:RoyaleDemo.profile.unlockedForms,shards:RoyaleDemo.profile.formShards,coins:RoyaleDemo.profile.heroCoins,wild:RoyaleDemo.profile.evoWildShards,deckForms:RoyaleDemo.profile.deckForms,tower:RoyaleDemo.profile.selectedTowerTroop,towerLevels:RoyaleDemo.profile.towerTroopLevels,towerCopies:RoyaleDemo.profile.towerTroopCopies,skins:RoyaleDemo.profile.ownedTowerSkins,skin:RoyaleDemo.profile.selectedTowerSkin,emotes:RoyaleDemo.profile.ownedEmotes,equipped:RoyaleDemo.profile.equippedEmotes,receipts:RoyaleDemo.profile.contentShopPurchases,pass:RoyaleDemo.profile.passClaimed}));A.deepEqual(loaded,saved);report.reloadPreserved=true;
  if(!custom){
   await page.evaluate(()=>RoyaleDemo.show('shop'));const ordinary=await page.locator('.card-shop-offer .card-visual').evaluateAll(nodes=>nodes.map(n=>({id:n.querySelector('[data-card-image]')?.dataset.cardImage,kind:n.dataset.cardKind})));A.ok(ordinary.length);A.ok(ordinary.every(r=>['standard','champion'].includes(r.kind)),'Ordinary copies never imply form ownership');report.ordinaryCopies=ordinary;
   A.equal(await page.evaluate(()=>RoyaleDemo.startBattle('Default',true,{ai:false,seed:74})),true);
   report.trainingBank=await page.evaluate(()=>{const b=RoyaleDemo.battle,p=RoyaleDemo.profile;b.paused=true;return{queue:b.queueType,deck:b.initialDecks[0],forms:b.seatForms[0],storedDeck:p.decks[p.activeDeck],storedForms:p.deckForms.ranked[p.activeDeck]};});A.equal(report.trainingBank.queue,'training');A.deepEqual(report.trainingBank.deck,report.trainingBank.storedDeck);A.deepEqual(report.trainingBank.forms,report.trainingBank.storedForms);A.equal(report.trainingBank.forms.filter(Boolean).length,2,'Training starts with the selected Hero and Evolution');
   await page.evaluate(()=>{RoyaleDemo.battle.finish(-1,'QA training completion');RoyaleDemo.step(0);});A.equal(await page.evaluate(()=>RoyaleDemo.playAgain()),true);
   report.rematchForms=await page.evaluate(()=>{const b=RoyaleDemo.battle;b.paused=true;return{deck:b.initialDecks[0],forms:b.seatForms[0],queue:b.queueType};});A.equal(report.rematchForms.queue,'training');A.deepEqual(report.rematchForms.deck,report.trainingBank.deck);A.deepEqual(report.rematchForms.forms,report.trainingBank.forms);
   const started=await page.evaluate(()=>RoyaleDemo.startBattle('Default',false,{ai:false,seed:74}));A.equal(started,true);report.handCycling=await page.evaluate(()=>{const b=RoyaleDemo.battle,commands=[];for(let i=0;i<8;i++){if(b.hand[0].filter((id,slot)=>b.card(0,slot).selectedFormId).length>=2)break;const slot=b.hand[0].findIndex((id,j)=>!b.card(0,j).selectedFormId);b.paused=false;b.elixir[0]=10;const r=RoyaleDemo.session.command({type:'deploy',sequence:RoyaleDemo.session.sequence+1,slot,x:100,y:520});commands.push({card:b.lastCard[0]?.id,ok:r.ok,reason:r.reason});if(!r.ok)break;for(let tick=0;tick<90;tick++)b.step(1/60);}b.paused=true;RoyaleDemo.refreshHand(true);return commands;});A.ok(report.handCycling.every(c=>c.ok),'Real hand cycling commands succeed');report.hand=await art(page,'#hand');A.ok(report.hand.some(r=>r.kind==='hero'));A.ok(report.hand.some(r=>r.kind==='evolution'));await shot(page,'battle-hand-source-frames');await page.evaluate(()=>RoyaleDemo.show('home'));
  }
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1,storageState:await context.storageState(),serviceWorkers:'block'}),phone=await mobile.newPage();watch(phone);await phone.goto(url);await ready(phone);await phone.evaluate(()=>RoyaleDemo.show('shop'));await shot(phone,'phone-connected-shop');A.equal(await phone.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await phone.evaluate(()=>{RoyaleDemo.show('cards');RoyaleDemo.cardSection('collection');RoyaleDemo.librarySection('magic-items');});await phone.locator('[data-action="form-inventory"]').first().tap();await shot(phone,'phone-inventory');if(custom)A.equal(await phone.locator('.form-inventory-card').count(),0);await close(phone);await phone.evaluate(()=>RoyaleDemo.show('home'));await phone.locator('[data-action="menu"]:visible').first().tap();await phone.locator('#modalPanel [data-action="pass-rewards"]').first().tap();await shot(phone,'phone-progression-rewards');A.equal(await phone.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await mobile.close();
  A.deepEqual(report.errors,[]);A.deepEqual(report.assets,[]);report.passed=true;
 }catch(e){report.failure=e.stack||String(e);throw e;}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();}
 console.log(JSON.stringify({passed:report.passed,identity:report.identity,release:report.release,errors:report.errors,assets:report.assets,out},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
