'use strict';
// Inspect the actual release bundle in an isolated browser profile. No renderer or
// source overlays are injected. Test progress is local to this ephemeral context.
const fs=require('node:fs'),path=require('node:path'),A=require('node:assert/strict'),crypto=require('node:crypto');
let chromium;try{({chromium}=require('playwright'));}catch(_){({chromium}=require('C:/Users/Oceyi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}
const project=require('../project.json'),url=(process.env.URL||process.env.WEB_ROYALE_URL||'http://127.0.0.1:'+project.defaultPort+'/').replace(/\/?$/,'/'),version=process.env.VERSION||process.env.EXPECTED_VERSION||project.version,out=path.resolve(process.env.PROOF||path.join(__dirname,'../docs/qa/v522/form-slots-'+project.id));
fs.mkdirSync(out,{recursive:true});const report={url,version,actualBundleOnly:true,passed:false,errors:[],assets:[],screenshots:[]};
async function ready(page){await page.waitForFunction(()=>window.RoyaleDemo&&document.querySelector('#loading.hidden'),null,{timeout:240000});await page.evaluate(()=>Promise.all([RoyaleDemo.learningReady,RoyaleDemo.replayReady]));}
async function picture(page,name){await page.waitForFunction(()=>{const t=document.querySelector('#toast');return!t||!t.classList.contains('show')&&Number(getComputedStyle(t).opacity)<.01;},null,{timeout:6000});await page.locator('#viewport').screenshot({path:path.join(out,name+'.png')});report.screenshots.push(name+'.png');}
async function closeModal(page){if(await page.locator('#modalPanel').isVisible())await page.locator('#modalPanel [data-action="close"]').first().click();}
async function slots(page,selector='#deckGrid'){
 const state=await page.locator(selector+' > .special-slot').evaluateAll(rows=>rows.map(el=>({index:Number(el.dataset.formSlot),kind:el.dataset.slotKind,status:el.dataset.slotStatus,label:el.getAttribute('aria-label'),caption:el.querySelector('.slot-caption')?.innerText,cardId:el.dataset.id||null})));
 A.deepEqual(state.map(s=>[s.index,s.kind]),[[0,'evolution'],[1,'hero'],[2,'wild']]);A.ok(state.every(s=>s.label&&s.caption));return state;
}
async function inventoryLayout(page){const geometry=await page.evaluate(()=>({bars:[...document.querySelectorAll('.form-shard-track')].map(el=>Number.parseFloat(getComputedStyle(el).height)),nestedCurrencyBoxes:[...document.querySelectorAll('.form-currencies>span span')].filter(el=>Number.parseFloat(getComputedStyle(el).paddingTop)>0||Number.parseFloat(getComputedStyle(el).borderTopWidth)>0).length,titleContrast:[...document.querySelectorAll('.form-inventory-card h3,.empty-form-inventory h3,.form-currencies>span')].map(el=>{const luminance=c=>{const parts=c.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return parts[0]*.2126+parts[1]*.7152+parts[2]*.0722;},a=luminance(getComputedStyle(el).color),b=luminance(getComputedStyle(el.closest('.form-inventory-card,.empty-form-inventory,.form-currencies>span')).backgroundColor);return(Math.max(a,b)+.05)/(Math.min(a,b)+.05);})}));A.ok(geometry.bars.every(h=>h<=10),'Shard bars must remain compact progress indicators');A.equal(geometry.nestedCurrencyBoxes,0,'Currency labels do not inherit nested box styling');A.ok(geometry.titleContrast.every(r=>r>=4.5),'Inventory titles have readable contrast');return geometry;}
async function inventory(page){await page.evaluate(()=>{RoyaleDemo.cardSection('collection');RoyaleDemo.librarySection('magic-items');});await page.locator('#cosmeticCollection [data-action="form-inventory"]').click();}
async function swap(page,from,to){await page.locator('#deckToolbar [data-action="deck-swap"]').click();await page.locator('#deckGrid > [data-slot="'+from+'"]').click();await page.locator('#deckGrid > [data-slot="'+to+'"]').click();}
async function specialScreen(page,mode){
 await closeModal(page);await page.evaluate(()=>RoyaleDemo.show('events'));
 const target=page.locator('[data-action="special-deck-builder"][data-mode="'+mode+'"]');
 if(await target.count()){await target.first().click();}else{throw Error('No visible deck builder entry for '+mode);}
 await page.waitForFunction(()=>RoyaleDemo.screen==='modeDeck');const level=await page.evaluate(()=>new RoyaleCore.Battle({mode:'TwelveCardDeck',queue:'challenge',ai:false}).card(0,0).level);A.match(await page.locator('.mode-deck-summary').innerText(),new RegExp('Level '+level),'Mode caption matches actual standardized battle level');const s=await slots(page,'#modeDeckGrid');A.ok(s.every(x=>x.status!=='locked'),'Casual special slots are available');await picture(page,'mode-'+mode);return s;
}
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files/Google/Chrome/Application/chrome.exe'}),context=await browser.newContext({viewport:{width:1000,height:1200},serviceWorkers:'block'}),page=await context.newPage();
 const watch=p=>{p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/Content Security Policy|violates.*policy/i.test(m.text()))report.errors.push(m.text());});p.on('response',r=>{if(r.status()>=400&&/\/(assets|app\.|runtime\.|bootstrap\.)/.test(r.url()))report.assets.push({url:r.url(),status:r.status()});});};watch(page);
 try{
  await page.goto(url);await ready(page);report.identity=await page.evaluate(()=>({version:RoyaleBundle.version,project:RoyaleBundle.project.id,cards:RoyaleCore.CARDS.length,forms:RoyaleCardForms.defaultRegistry.forms.length,profileKey:RoyaleBundle.project.profileKey,scripts:[...document.scripts].map(s=>s.src).filter(Boolean)}));A.equal(report.identity.version,version);A.equal(report.identity.project,project.id);
  const releaseResponse=await page.request.get(new URL('release.json',url).href),releaseBytes=await releaseResponse.body(),release=JSON.parse(releaseBytes),appResponse=await page.request.get(new URL(release.app,url).href),appBytes=await appResponse.body();A.equal(appResponse.status(),200);A.equal(release.version,version);A.ok(report.identity.scripts.some(src=>new URL(src).pathname.endsWith('/'+release.app)));A.equal(crypto.createHash('sha256').update(appBytes).digest('hex'),release.files[release.app]);report.release={app:release.app,appSha256:release.files[release.app],manifestSha256:crypto.createHash('sha256').update(releaseBytes).digest('hex')};
  await page.evaluate(()=>RoyaleDemo.show('cards'));report.lockedSlots=await slots(page);A.ok(report.lockedSlots.every(s=>s.status==='locked'));A.equal(await page.locator('#deckGrid button:disabled').count(),0,'Arena locks do not disable standard cards');await picture(page,'desktop-locked-deck');
  const custom=report.identity.project==='web-royale-custom';
  if(custom){
   A.equal(report.identity.cards,102);A.equal(report.identity.forms,0);await page.evaluate(()=>{const p=structuredClone(RoyaleDemo.profile);p.trophies=p.highestTrophies=RoyaleProgression.ARENAS.find(a=>a.number===10).trophies;p.heroCoins=200;p.evoWildShards=3;RoyaleDemo.applyProfile(p);});report.unlockedSlots=await slots(page);A.ok(report.unlockedSlots.every(s=>s.status==='standard'));await inventory(page);A.equal(await page.locator('.form-inventory-card').count(),0);A.equal(await page.locator('.empty-form-inventory').count(),1);A.equal(await page.locator('[data-form-currency="hero"]').innerText(),'200');A.equal(await page.locator('[data-form-currency="wild"]').innerText(),'3');await picture(page,'custom-empty-inventory');await closeModal(page);await page.evaluate(()=>RoyaleDemo.cardSection('decks'));
  }else{
   A.equal(report.identity.cards,123);const fixture=await page.evaluate(()=>{const F=RoyaleCardForms.defaultRegistry,forms=F.forms,hero=F.forCard('knight').find(f=>f.kind==='hero'),evo=F.forCard('knight').find(f=>f.kind==='evolution'),archerEvo=F.forCard('archers').find(f=>f.kind==='evolution');if(!hero||!evo||!archerEvo)throw Error('Source Knight/Archer forms missing');const p=structuredClone(RoyaleDemo.profile);p.trophies=p.highestTrophies=RoyaleProgression.ARENAS.find(a=>a.number===10).trophies;p.heroStarterGranted=true;p.heroCoins=200;p.evoWildShards=2;p.formShards[evo.id]=4;p.unlockedForms=[archerEvo.id];RoyaleDemo.applyProfile(p);return{hero:hero.id,evo:evo.id,archerEvo:archerEvo.id};});report.fixture=fixture;
   await inventory(page);report.inventoryLayout=await inventoryLayout(page);await page.locator('[data-action="choose-hero"][data-id="'+fixture.hero+'"]').click();let after=await page.evaluate(()=>({coins:RoyaleDemo.profile.heroCoins,forms:RoyaleDemo.profile.unlockedForms}));A.equal(after.coins,0);A.ok(after.forms.includes(fixture.hero));A.ok(after.forms.every(id=>[fixture.hero,fixture.archerEvo].includes(id)));report.heroPurchase=after;await picture(page,'hero-chosen');
   await page.locator('[data-action="form-inventory"][data-kind="evolution"]').click();await page.locator('[data-action="apply-form-shard"][data-id="'+fixture.evo+'"]').click();after=await page.evaluate(id=>({shards:RoyaleDemo.profile.formShards[id],wild:RoyaleDemo.profile.evoWildShards,owned:RoyaleDemo.profile.unlockedForms.includes(id)}),fixture.evo);A.deepEqual(after,{shards:5,wild:1,owned:false});report.partialShard=after;await picture(page,'evo-one-shard');
   await page.locator('[data-action="apply-form-shard"][data-id="'+fixture.evo+'"]').click();after=await page.evaluate(id=>({shards:RoyaleDemo.profile.formShards[id],wild:RoyaleDemo.profile.evoWildShards,owned:RoyaleDemo.profile.unlockedForms.includes(id)}),fixture.evo);A.deepEqual(after,{shards:6,wild:0,owned:true});report.evolutionUnlock=after;A.equal(await page.locator('[data-action="apply-form-shard"][data-id="'+fixture.evo+'"]').isDisabled(),true);
   await page.locator('[data-action="form-inventory"][data-kind="hero"]').click();await page.locator('[data-action="use-form"][data-id="'+fixture.hero+'"]').click();A.equal(await page.locator('.replace-grid [data-slot="0"]').isDisabled(),true);A.equal(await page.locator('.replace-grid [data-slot="1"]').isDisabled(),false);await page.locator('.replace-grid [data-slot="1"]').click();report.dedicated=await page.evaluate(()=>({deck:RoyaleDemo.profile.decks[0],forms:RoyaleDemo.profile.deckForms.ranked[0]}));A.equal(report.dedicated.deck[1],'knight');A.equal(report.dedicated.forms[1],fixture.hero);A.equal(report.dedicated.deck[0],'archers');A.equal(report.dedicated.forms[0],fixture.archerEvo);await page.evaluate(()=>RoyaleDemo.cardSection('decks'));await picture(page,'desktop-filled-deck');
   await swap(page,1,2);await page.locator('#deckFormButton').click();const chooser=page.locator('[data-form-choice="2"]');A.equal(await chooser.locator('option[value="'+fixture.hero+'"]').count(),1);A.equal(await chooser.locator('option[value="'+fixture.evo+'"]').count(),1);await chooser.selectOption(fixture.evo);A.equal(await page.evaluate(()=>RoyaleDemo.profile.deckForms.ranked[0][2]),fixture.evo);await picture(page,'wild-evolution-selected');await page.locator('[data-form-choice="2"]').selectOption(fixture.hero);A.equal(await page.evaluate(()=>RoyaleDemo.profile.deckForms.ranked[0][2]),fixture.hero);await closeModal(page);
   await swap(page,2,4);A.equal(await page.evaluate(()=>RoyaleDemo.profile.deckForms.ranked[0][4]),null,'Moving a Hero into a regular slot deactivates it');await swap(page,4,2);await page.locator('#deckFormButton').click();await page.locator('[data-form-choice="2"]').selectOption(fixture.evo);await closeModal(page);report.wild=await slots(page);
  }
  const saved=await page.evaluate(()=>({deck:RoyaleDemo.profile.decks[0],forms:RoyaleDemo.profile.deckForms.ranked[0],coins:RoyaleDemo.profile.heroCoins,wild:RoyaleDemo.profile.evoWildShards,shards:RoyaleDemo.profile.formShards,version:RoyaleDemo.profile.positionalSlotsVersion}));A.equal(saved.version,1);await page.reload();await ready(page);await page.evaluate(()=>RoyaleDemo.show('cards'));const loaded=await page.evaluate(()=>({deck:RoyaleDemo.profile.decks[0],forms:RoyaleDemo.profile.deckForms.ranked[0],coins:RoyaleDemo.profile.heroCoins,wild:RoyaleDemo.profile.evoWildShards,shards:RoyaleDemo.profile.formShards,version:RoyaleDemo.profile.positionalSlotsVersion}));A.deepEqual(loaded,saved);report.reload={preserved:true,profile:loaded};
  await inventory(page);report.finalInventoryLayout=await inventoryLayout(page);await picture(page,'inventory-all-final');if(!custom){await page.locator('[data-action="form-inventory"][data-kind="hero"]').click();await inventoryLayout(page);await picture(page,'inventory-heroes-final');await page.locator('[data-action="form-inventory"][data-kind="evolution"]').click();await inventoryLayout(page);await picture(page,'inventory-evolutions-final');}await closeModal(page);report.modes={};for(const mode of ['FourCardDeck','TwelveCardDeck'])report.modes[mode]=await specialScreen(page,mode);
  report.randomDeck=[];for(const seed of [3,17]){const started=await page.evaluate(seed=>RoyaleDemo.startBattle('RandomDeck',false,{queue:'challenge',seed,ai:false}),seed);A.equal(started,true,'RandomDeck seed '+seed+' opens the actual battle');const row=await page.evaluate(()=>{const b=RoyaleDemo.battle;b.paused=true;return{deck:b.initialDecks[0],forms:b.seatForms[0],context:b.formContext,qualified:b.formRegistry.qualify(b.initialDecks[0],b.seatForms[0],b.formContext).ok};});A.equal(row.qualified,true);A.equal(row.deck.length,8);A.equal(row.context.positionalSlots,true);report.randomDeck.push({seed,...row});await page.evaluate(()=>RoyaleDemo.show('home'));}
  const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true,storageState:await context.storageState(),serviceWorkers:'block'}),phone=await mobile.newPage();watch(phone);await phone.goto(url);await ready(phone);await phone.evaluate(()=>RoyaleDemo.show('cards'));report.phone=await slots(phone);await picture(phone,'phone-deck');await phone.locator('#deckFormButton').tap();await picture(phone,'phone-slot-selector');await phone.locator('#modalPanel [data-action="form-inventory"]').tap();report.phoneInventoryLayout=await inventoryLayout(phone);await picture(phone,'phone-form-inventory');A.equal(await phone.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,'Phone layout has no horizontal overflow');await mobile.close();
  A.deepEqual(report.errors,[]);A.deepEqual(report.assets,[]);report.passed=true;
 }catch(e){report.failure=e.stack||String(e);throw e;}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();}
 console.log(JSON.stringify({passed:report.passed,identity:report.identity,release:report.release,errors:report.errors,assets:report.assets,out},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
