const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
function ui(){const s=fs.readFileSync(path.join(__dirname,'../src/app.js'),'utf8'),a=s.indexOf('// Card outline presentation'),z=s.indexOf('// End card outline presentation',a);assert.ok(a>=0&&z>a,'Card outlines must use one shared presentation resolver');const box={};vm.runInNewContext(s.slice(a,z)+'\nglobalThis.ui=CardOutlineUI;',box);return box.ui;}
const images=Object.fromEntries(['normal','legendary','champion','evolution','evolution-legendary','hero','hero-legendary','tower','tower-legendary'].map(k=>['card-frame-'+k,'source.png']));
test('owned collection badges reuse original unlocked category images',()=>{const s=fs.readFileSync(path.join(__dirname,'../src/app.js'),'utf8'),a=s.indexOf('function ownedFormBadges('),z=s.indexOf('\n',a),box={F:{forCard:()=>[{id:'owned',name:'Hero',kind:'hero'}]},C:{CARD_BY_ID:{knight:{rarity:'Common'}}},profile:{unlockedForms:['owned']},B:{uiImages:{'card-icon-hero-unlocked':'source.png'}},esc:String,icon:key=>'<img data-ui="'+key+'">'};vm.runInNewContext(s.slice(a,z)+'\nglobalThis.html=ownedFormBadges("knight");',box);assert.match(box.html,/card-icon-hero-unlocked/);assert.doesNotMatch(box.html,/♛/);});
test('the actual rewards modal labels credited modern currency once',()=>{const s=fs.readFileSync(path.join(__dirname,'../src/app.js'),'utf8'),a=s.indexOf('function rewards('),z=s.indexOf('\n',a);let html='';const box={U:{magicItems:[]},F:{get:()=>null},esc:String,fmt:String,modernLabel:String,icon:()=>'<img>',button:()=>'',contentRewardMarkup:()=>'<article>20 Hero Coins</article>',panel:(id,title,body)=>{html=body;},renderSkinPreviews(){},$(){}};vm.runInNewContext(s.slice(a,z)+'\nrewards({heroCoins:20});',box);assert.equal((html.match(/Hero Coins/g)||[]).length,1);});
test('source stencil opacity becomes CSS coverage without changing original pixels or RGB',()=>{const source=Uint8ClampedArray.from([10,20,30,169,40,50,60,84,70,80,90,0]),before=[...source],out=ui().coverageAlpha(source,169);assert.deepEqual([...source],before);assert.deepEqual([...out],[10,20,30,255,40,50,60,127,70,80,90,0]);});
test('normal card copies retain their rarity frame even when the player owns a form',()=>{const p=ui();assert.equal(p.resolve({rarity:'Common'},{},images).kind,'standard');assert.equal(p.resolve({rarity:'Legendary'},{},images).frame,'card-frame-legendary');});
test('explicit Evolution and Hero presentations use authored frames with rarity variants',()=>{const p=ui();for(const kind of ['evolution','hero']){assert.equal(p.resolve({rarity:'Common'},{kind},images).frame,'card-frame-'+kind);assert.equal(p.resolve({rarity:'Legendary'},{kind},images).frame,'card-frame-'+kind+'-legendary');}});
test('Champions and tower troops receive their inherent type frames',()=>{const p=ui();assert.equal(p.resolve({rarity:'Champion'},{},images).frame,'card-frame-champion');assert.equal(p.resolve({rarity:'Epic'},{kind:'tower'},images).frame,'card-frame-tower');assert.equal(p.resolve({rarity:'Legendary'},{kind:'tower'},images).frame,'card-frame-tower-legendary');});
test('missing source art preserves the known portrait frame and type label',()=>{const p=ui(),r=p.resolve({rarity:'Legendary'},{kind:'hero'},{'card-frame-legendary':'old.png'});assert.equal(r.kind,'hero');assert.equal(r.frame,'card-frame-legendary');assert.equal(r.fallback,true);assert.match(r.label,/Hero/);});
test('tower rarity and authored active states select their own source frame',()=>{const p=ui(),all={...images,'card-frame-tower-epic':'epic.png','card-frame-hero-active':'active.png'};assert.equal(p.resolve({rarity:'Epic'},{kind:'tower'},all).frame,'card-frame-tower-epic');assert.equal(p.resolve({rarity:'Common'},{kind:'hero',active:true},all).frame,'card-frame-hero-active');});
test('Mirror copies use ordinary artwork rather than implying an evolved or Hero copy',()=>{const p=ui(),r=p.resolve({rarity:'Legendary'},{kind:'evolution',mirrored:true},images);assert.equal(r.frame,'card-frame-normal');assert.equal(r.kind,'standard');});
test('unknown outline identifiers cannot produce arbitrary asset references',()=>{const p=ui(),r=p.resolve({rarity:'Rare'},{kind:'../../secret'},images);assert.equal(r.kind,'standard');assert.equal(r.frame,'card-frame-normal');});
test('portrait clipping uses the authored normalized mask including active-glow crop offsets',()=>{const p=ui(),style=p.portraitStyle({portraitRect:[.1,.2,.7,.6],portraitClipPolygon:[[0,0],[1,0],[.8,1],[.2,1]]});assert.match(style,/--card-portrait-left:10%/);assert.match(style,/--card-portrait-height:60%/);assert.match(style,/polygon\(0% 0%,100% 0%,80% 100%,20% 100%\)/);assert.equal(p.portraitStyle({portraitRect:[NaN,0,1,1]}),'');});
test('the real portrait renderer binds a form to its base card and supports a source tower portrait',()=>{const s=fs.readFileSync(path.join(__dirname,'../src/app.js'),'utf8'),a=s.indexOf('// Card outline presentation'),z=s.indexOf('function emoteVisual',a),K=require('../src/catalog'),Forms=require('../src/card-forms'),F=Forms.createRegistry({forms:[{id:'test-hero',baseCardId:'knight',kind:'hero',requiredShards:200,source:{...K.CARD_BY_ID.knight.source}}]}),box={C:K,F,B:{uiImages:images},esc:s=>String(s),icon:(id,cls)=>'<img class="'+cls+'" data-ui="'+id+'">'};vm.runInNewContext(s.slice(a,z)+'\nglobalThis.render=cardVisual;',box);assert.match(box.render('knight','',false,{formId:'test-hero'}),/data-card-frame="card-frame-hero"/);assert.match(box.render('archers','',false,{formId:'test-hero'}),/data-card-kind="standard"/);assert.match(box.render('tower','',false,{kind:'tower',rarity:'Epic',name:'Tower Troop',portraitKey:'source-tower'}),/data-ui="source-tower"/);});
test('receipts present real forms, tower troops and resolved cosmetics without inventing unavailable items',()=>{const s=fs.readFileSync(path.join(__dirname,'../src/app.js'),'utf8'),a=s.indexOf('// Connected content presentation'),z=s.indexOf('// End connected content presentation',a);assert.ok(a>=0&&z>a,'Reward receipts must present modern content');const box={F:{get:id=>id==='hero'?{name:'Hero Knight'}:null},MR:{resolveCosmetic:(kind,id)=>id==='original'?'skin':null},U:{towerSkins:[{id:'skin',name:'Original Skin'}],emotes:[]},RoyaleTowerTroops:{catalog:[{id:'tower',name:'Cannoneer'}]}};vm.runInNewContext(s.slice(a,z)+'\nglobalThis.rows=contentRewardEntries;',box);const rows=box.rows({unlockedForms:['hero','unknown'],towerTroops:{tower:2,unknown:2},sourceCosmetics:[{kind:'TowerSkins',id:'original'},{kind:'TowerSkins',id:'missing'}]});assert.deepEqual(Array.from(rows,x=>x.targetId),['hero','tower','skin']);});
test('the actual shop click submits the canonical receipt and spends only once',()=>{const C=require('../src/core'),E=require('../src/economy'),Forms=require('../src/card-forms'),Shop=require('../src/shop-model'),F=Forms.createRegistry({forms:[{id:'test-ui-hero',baseCardId:'knight',kind:'hero',requiredShards:200,source:{...C.CARD_BY_ID.knight.source}}]}),towers={catalog:[]},profile=C.normalizeProfile({heroCoins:200},{formRegistry:F}),offer=Shop.offers(profile,{registry:F,towerRegistry:towers}).find(o=>o.kind==='hero'),s=fs.readFileSync(path.join(__dirname,'../src/app.js'),'utf8'),a=s.indexOf("case 'buy-content-offer':"),z=s.indexOf("case 'pass-rewards':",a);assert.ok(a>=0&&z>a);const box={E,F,profile,RoyaleTowerTroops:towers,results:[],transaction(r){this.results.push(r);if(r.ok)this.profile=r.profile;}};box.transaction=r=>{box.results.push(r);if(r.ok)box.profile=r.profile;};vm.createContext(box);vm.runInContext('function click(id,el){switch("buy-content-offer"){'+s.slice(a,z)+'}}',box);box.click(offer.id,{dataset:{window:offer.window,fingerprint:offer.fingerprint}});assert.equal(box.results[0].ok,true);assert.equal(box.profile.heroCoins,0);assert.ok(box.profile.unlockedForms.includes(offer.targetId));box.click(offer.id,{dataset:{window:offer.window,fingerprint:offer.fingerprint}});assert.equal(box.results[1].ok,false);assert.equal(box.profile.heroCoins,0);});
