'use strict';
const test=require('node:test'),a=require('node:assert/strict'),C=require('../src/core'),R=require('../src/replay');
function battle(){const deck=['void','goblin-curse','vines','knight'];return new C.Battle({queue:'challenge',mode:'FourCardDeck',deck,enemyDeck:deck,ai:false,seed:52077});}
function advance(b,seconds){for(let i=0;i<Math.round(seconds*60);i++){b.time+=1/60;b.tickPending();b.tickAreas(1/60);b.modernActions.tickBattle(b,1/60);for(const u of b.active){b.modernActions.tickEntity(b,u,1/60);b.tickBuffs(u);}b.deaths();}}
function enemy(b,id='Knight',x=240,y=300){const u=b.spawn(id,1,x,y,{wait:0});u.hp=u.maxHp=10000;return u;}
test('modern spell source controllers pass deployment gates before spending elixir',()=>{for(const [id,slot]of [['void',0],['goblin-curse',1],['vines',2]]){const b=battle();b.elixir[0]=10;const result=b.deploy(0,slot,240,300);a.equal(result.ok,true,id+': '+result.reason);a.equal(b.elixir[0],10-C.CARD_BY_ID[id].cost);}});
test('Void source tier selects one, two-to-four or five-plus targets and delivers three delayed strikes',()=>{for(const [count,amount]of [[1,272],[3,115],[5,60]]){const b=battle();b.towers=[];const units=Array.from({length:count},()=>enemy(b)),field=b.createArea('DarkMagicAOE',0,240,300,1);advance(b,1.5);a.equal(units[0].hp,10000);advance(b,.15);a.equal(units[0].hp,10000-amount);advance(b,2);a.equal(field.modernLaser.hits,3);a.ok(units.every(u=>u.hp===10000-amount*3));}});
test('Void counts crown towers in source target tiers but applies its separate crown damage',()=>{for(const [others,amount]of [[0,38],[2,20],[4,14]]){const b=battle(),tower=b.towers.find(t=>!t.king&&t.team===1);b.towers=[tower];tower.x=240;tower.y=300;tower.hp=tower.maxHp=10000;for(let i=0;i<others;i++)enemy(b);b.createArea('DarkMagicAOE',0,240,300,1);advance(b,3.65);a.equal(tower.hp,10000-amount*3);}});
test('Goblin Curse source buffs slow enemies, retain refresh damage clocks, and transform deaths for the caster',()=>{const b=battle();b.towers=[];const u=enemy(b),friendly=b.spawn('Knight',0,240,300,{wait:0});b.createArea('GoblinCurse',0,240,300,1);advance(b,.1);a.ok(u.buffs.GoblinCurse);a.equal(b.buffs(u).speed,.85);a.equal(friendly.buffs.GoblinCurse,undefined);advance(b,1);a.equal(u.hp,9986);b.damage(u,20000,null,{team:0});b.deaths();const goblin=b.units.find(v=>v.entity==='GoblinCurseGoblin');a.ok(goblin);a.equal(goblin.team,0);a.equal(goblin.owner,0);});
test('Goblin Curse crown damage uses the source per-hit value and never converts towers',()=>{const b=battle(),tower=b.towers.find(t=>!t.king&&t.team===1);b.towers=[tower];tower.x=240;tower.y=300;tower.hp=tower.maxHp=10000;b.createArea('GoblinCurse',0,240,300,1);advance(b,1.1);a.equal(tower.hp,9996);b.damage(tower,20000,null,{team:0});b.deaths();a.equal(b.units.some(u=>u.entity==='GoblinCurseGoblin'),false);});
test('Vines selects the three largest distinct enemies at source intervals and grounds airborne targets temporarily',()=>{const b=battle();b.towers=[];const units=[enemy(b,'BabyDragon'),enemy(b),enemy(b),enemy(b)],friend=b.spawn('Knight',0,240,300,{wait:0});units.forEach((u,i)=>u.hp=u.maxHp=5000-i*1000);const field=b.createArea('Vines_AeO',0,240,300,1);advance(b,.85);a.equal(units[0].air,true);advance(b,.1);a.equal(units[0].air,false);a.equal(b.buffs(units[0]).attack,0);a.ok(Object.keys(units[0].buffs).some(n=>n.startsWith('Vines_Trap_Snare')));advance(b,.45);a.equal(field.hitTargets.length,3);a.ok(units.slice(0,3).every(u=>Object.keys(u.buffs).some(n=>n.startsWith('Vines_Trap_Snare'))));a.equal(Object.keys(units[3].buffs).length,0);a.equal(Object.keys(friend.buffs).length,0);advance(b,1.6);a.equal(units[0].air,true);a.equal(b.buffs(units[0]).attack,1);});
test('modern spell deployments and delayed source controllers reproduce across replay seeks',()=>{const b=battle();R.captureInitial(b);for(let i=0;i<360;i++){if(i===10)a.equal(b.deploy(0,0,3.5*C.SX,6.5*C.SY).ok,true);b.step(1/60);}const record=R.pack(b),s=new R.Session(record);for(const at of [record.duration,1,record.duration]){s.seek(at);a.equal(s.error,null);}a.deepEqual(R.digest(s.battle),record.expected);});
