'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),K=require('../src/catalog'),R=require('../src/progression'),P=require('../src/profile'),E=require('../src/economy'),M=require('../src/modern-rewards');
test('TrophyRoad choices are the original offered cards and cannot be rerolled',()=>{const p=P.normalizeProfile({trophies:100,highestTrophies:100});const step=R.ROAD_REWARDS.find(s=>s.trophies===50);assert.deepEqual(E.roadChoices(p,step),step.cards);const bad=E.claimRoad(p,step.id,'fireball');assert.equal(bad.ok,false);assert.equal(bad.profile.roadClaimed.includes(step.id),false);const result=E.claimRoad(p,step.id,'goblins');assert.equal(result.ok,true);assert.equal(result.reward.cards[0].count,20);assert.equal(E.claimRoad(result.profile,step.id,'spear-goblins').ok,false);});
test('five-star Evo source item pool grants six real named shards',()=>{const p=P.normalizeProfile({trophies:14000});const a=M.mysteryBox('EVO_Shard_5Star',{profile:p,arenaNumber:32,seed:'fixed-receipt'}),b=M.mysteryBox('EVO_Shard_5Star',{profile:p,arenaNumber:32,seed:'fixed-receipt'});assert.equal(a.ok,true);assert.deepEqual(a,b);const [[form,count]]=Object.entries(a.reward.formShards);assert.equal(count,6);assert.equal(K.DATA.forms.find(f=>f.id===form).kind,'evolution');E.grant(p,a.reward);assert.equal(p.formShards[form],6);});
test('modern consumable road rewards update hero/evolution and Champion inventories',()=>{const step=R.ROAD_REWARDS.find(s=>s.kind==='consumable');const p=P.normalizeProfile({trophies:14000});const r=E.claimRoad(p,step.id);assert.equal(r.ok,true);const result=P.normalizeProfile({...p,wildcards:{Champion:8}});assert.equal(result.wildcards.Champion,8);M.addHeroCoins(result,500);assert.equal(result.heroCoins,200);assert.ok(result.gems>p.gems);});
test('level15 to16 upgrade uses the exact source cost/materials and grants source XP',()=>{const p=P.normalizeProfile({trophies:14000,gold:9999999,cardLevels:{knight:15},copies:{knight:100000},unlockedCards:['knight']});const q=P.upgradeQuote(p,'knight'),source=K.DATA.rarities.Common;assert.equal(q.gold,source.UpgradeCost[14]);assert.equal(q.copies,source.UpgradeMaterialCount[14]);const r=P.upgrade(p,'knight');assert.equal(r.ok,true);assert.equal(r.profile.cardLevels.knight,16);assert.equal(P.upgradeQuote(r.profile,'knight').canUpgrade,false);});
test('Trophy Road emotes use both native index parts and persist the exact reward',()=>{
 const step=R.ROAD_REWARDS.find(s=>s.trophies===2200),p=P.normalizeProfile({trophies:14000}),r=E.claimRoad(p,step.id);
 assert.equal(r.ok,true);assert.equal(r.reward.emote,'Emote58');assert.ok(P.normalizeProfile(r.profile).ownedEmotes.includes('Emote58'));assert.equal(E.claimRoad(r.profile,step.id).ok,false);
});
test('all217 modern Road milestones grant a recorded reward once without changing the input save',()=>{
 assert.equal(R.ROAD_REWARDS.length,217);
 for(const step of R.ROAD_REWARDS){const p=P.normalizeProfile({trophies:14000}),before=JSON.stringify(p),choice=step.kind==='choice'?E.roadChoices(p,step)[0]:step.kind==='tower-troop'?step.supportCard:undefined,r=E.claimRoad(p,step.id,choice);
  assert.equal(r.ok,true,step.id+': '+r.reason);assert.equal(JSON.stringify(p),before,step.id);assert.ok(r.profile.roadClaimed.includes(step.id));assert.ok(r.reward&&Object.values(r.reward).some(v=>typeof v==='number'?v>0:Array.isArray(v)?v.length>0:v&&typeof v==='object'?Object.keys(v).length>0:!!v),step.id+' empty reward');assert.equal(E.claimRoad(P.normalizeProfile(r.profile),step.id,choice).ok,false,step.id);
 }
});
