[AutoChessArena1]
	Augments = []
[AutoChessArena2]
	Augments = ["logic/autochess/augments/augment_basic/big_fund/augment_big_fund","logic/autochess/augments/augment_basic/legacy_augment/augment_legacy_augment"]
[AutoChessArena3]
	Augments = ["logic/autochess/augments/augment_basic/rare_star/augment_rare_star","logic/autochess/augments/augment_basic/epic_star/augment_epic_star"]
[AutoChessArena4]
	Augments = ["logic/autochess/augments/augment_basic/legendary_star/augment_legendary_star","logic/autochess/augments/augment_basic/champion_star/augment_champion_star"]
[AutoChessArena5]
	Augments = ["logic/autochess/augments/augment_basic/freenzy/augment_freenzy","logic/autochess/augments/augment_basic/thornwall/augment_thornwall"]
[AutoChessArena6]
	Augments = ["logic/autochess/augments/augment_basic/you_are_mine/augment_you_are_mine","logic/autochess/augments/augment_basic/first_free/augment_first_free"]
[AutoChessArena7]
	Augments = ["logic/autochess/augments/augment_basic/bigger_pool/augment_bigger_pool","logic/autochess/augments/augment_basic/echo_bench/augment_echo_bench","logic/autochess/augments/augment_basic/pandora_bench/augment_pandora_bench"]
[AutoChessArena8]
	Augments = ["logic/autochess/augments/augment_basic/trait_dummy/augment_trait_dummy","logic/autochess/augments/augment_basic/unit_conference/augment_unit_conference"]
[AutoChessArena9]
	Augments = ["logic/autochess/augments/augment_basic/lucky_discount/augment_lucky_discount","logic/autochess/augments/augment_basic/clear_mind/augment_clear_mind","logic/autochess/augments/augment_basic/ascension/augment_ascension"]
[AutoChessArena10]
	Augments = ["logic/autochess/augments/augment_basic/smart_trade/augment_smart_trade","logic/autochess/augments/augment_basic/ascended_star/augment_ascended_star","logic/autochess/augments/augment_basic/first_pick/augment_first_pick"]
[AutoChessArena1_2025_Oct]
	Augments = []
[AutoChessArena2_2025_Oct]
	Augments = ["logic/autochess/augments/augment_basic/big_fund/augment_big_fund","logic/autochess/augments/augment_basic/legacy_augment/augment_legacy_augment"]
[AutoChessArena3_2025_Oct]
	Augments = ["logic/autochess/augments/augment_basic/elixir_festival/augment_elixir_festival","logic/autochess/augments/augment_basic/champion_star/augment_champion_star"]
[AutoChessArena4_2025_Oct]
	Augments = ["logic/autochess/augments/augment_basic/endurance_training/augment_endurance_training","logic/autochess/augments/augment_basic/you_are_mine/augment_you_are_mine"]
[AutoChessArena5_2025_Oct]
	Augments = ["logic/autochess/augments/augment_basic/freenzy/augment_freenzy"]
[AutoChessArena6_2025_Oct]
	Augments = ["logic/autochess/augments/augment_basic/last_stand/augment_last_stand","logic/autochess/augments/augment_basic/echo_bench/augment_echo_bench"]
[AutoChessArena7_2025_Oct]
	Augments = ["logic/autochess/augments/augment_basic/chaos_chaos/augment_chaos_chaos","logic/autochess/augments/augment_basic/master_arena/augment_master_arena"]
[AutoChessArena8_2025_Oct]
	Augments = ["logic/autochess/augments/augment_basic/ascension/augment_ascension","logic/autochess/augments/augment_basic/trait_dummy/augment_trait_dummy"]
[AutoChessArena9_2025_Oct]
	Augments = ["logic/autochess/augments/augment_basic/ultimate_origin/augment_ultimate_origin","logic/autochess/augments/augment_basic/ascended_star/augment_ascended_star"]
[AutoChessArena10_2025_Oct]
	Augments = ["logic/autochess/augments/augment_basic/coaching/augment_coaching","logic/autochess/augments/augment_basic/monster_drink/augment_monster_drink"]
[AutoChessArena1_2025_Nov]
	Augments = []
[AutoChessArena2_2025_Nov]
	Augments = ["logic/autochess/augments/augment_basic/big_fund/augment_big_fund","logic/autochess/augments/augment_basic/elixir_festival/augment_elixir_festival"]
[AutoChessArena3_2025_Nov]
	Augments = ["logic/autochess/augments/augment_basic/endurance_training/augment_endurance_training","logic/autochess/augments/augment_basic/trait_dummy/augment_trait_dummy"]
[AutoChessArena4_2025_Nov]
	Augments = ["logic/autochess/augments/augment_basic/monster_drink/augment_monster_drink","logic/autochess/augments/augment_basic/you_are_mine/augment_you_are_mine"]
[AutoChessArena5_2025_Nov]
	Augments = ["logic/autochess/augments/augment_basic/magic_tile/augment_magic_tile","logic/autochess/augments/augment_basic/echo_bench/augment_echo_bench"]
[AutoChessArena6_2025_Nov]
	Augments = ["logic/autochess/augments/augment_basic/last_stand/augment_last_stand","logic/autochess/augments/augment_basic/master_arena/augment_master_arena"]
[AutoChessArena7_2025_Nov]
	Augments = ["logic/autochess/augments/augment_basic/one_punch/augment_one_punch","logic/autochess/augments/augment_basic/ascension/augment_ascension"]
[AutoChessArena8_2025_Nov]
	Augments = ["logic/autochess/augments/augment_basic/clear_mind/augment_clear_mind","logic/autochess/augments/augment_basic/ultimate_origin/augment_ultimate_origin"]
[AutoChessArena9_2025_Nov]
	Augments = ["logic/autochess/augments/augment_basic/coaching/augment_coaching","logic/autochess/augments/augment_basic/ascended_star/augment_ascended_star"]
[AutoChessArena10_2025_Nov]
	Augments = ["logic/autochess/augments/augment_basic/mystery_shop/augment_mystery_shop","logic/autochess/augments/augment_basic/devil_snap/augment_devil_snap"]
[AutoChessArena1_2025_Dec]
	Augments = []
[AutoChessArena2_2025_Dec]
	Augments = ["logic/autochess/augments/augment_basic/rare_star/augment_rare_star","logic/autochess/augments/augment_25q4/elixir_collector/augment_elixir_collector"]
[AutoChessArena3_2025_Dec]
	Augments = ["logic/autochess/augments/augment_basic/endurance_training/augment_endurance_training","logic/autochess/augments/augment_basic/epic_star/augment_epic_star"]
[AutoChessArena4_2025_Dec]
	Augments = ["logic/autochess/augments/augment_basic/legendary_star/augment_legendary_star","logic/autochess/augments/augment_25q4/tesla/augment_tesla"]
[AutoChessArena5_2025_Dec]
	Augments = ["logic/autochess/augments/augment_basic/magic_tile/augment_magic_tile","logic/autochess/augments/augment_basic/last_stand/augment_last_stand"]
[AutoChessArena6_2025_Dec]
	Augments = ["logic/autochess/augments/augment_basic/one_punch/augment_one_punch","logic/autochess/augments/augment_25q4/xbow/augment_xbow"]
[AutoChessArena7_2025_Dec]
	Augments = ["logic/autochess/augments/augment_basic/clear_mind/augment_clear_mind","logic/autochess/augments/augment_basic/bigger_pool/augment_bigger_pool"]
[AutoChessArena8_2025_Dec]
	Augments = ["logic/autochess/augments/augment_basic/master_arena/augment_master_arena","logic/autochess/augments/augment_25q4/mortar/augment_mortar"]
[AutoChessArena9_2025_Dec]
	Augments = ["logic/autochess/augments/augment_basic/coaching/augment_coaching","logic/autochess/augments/augment_basic/mystery_shop/augment_mystery_shop"]
[AutoChessArena10_2025_Dec]
	Augments = ["logic/autochess/augments/augment_25q4/inferno_tower/augment_inferno_tower","logic/autochess/augments/augment_basic/devil_snap/augment_devil_snap"]
[AutoChessArena1_2026_Jan]
	Augments = []
[AutoChessArena2_2026_Jan]
	Augments = ["logic/autochess/augments/augment_basic/legacy_augment/augment_legacy_augment","logic/autochess/augments/augment_basic/big_fund/augment_big_fund"]
[AutoChessArena3_2026_Jan]
	Augments = ["logic/autochess/augments/augment_basic/freenzy/augment_freenzy","logic/autochess/augments/augment_25q4/damage_tile/augment_damage_tile"]
[AutoChessArena4_2026_Jan]
	Augments = ["logic/autochess/augments/augment_25q4/inferno_tower_2/augment_inferno_tower_2","logic/autochess/augments/augment_basic/magic_tile/augment_magic_tile"]
[AutoChessArena5_2026_Jan]
	Augments = ["logic/autochess/augments/augment_25q4/mortar_2/augment_mortar_2","logic/autochess/augments/augment_25q4/clone_tile/augment_clone_tile"]
[AutoChessArena6_2026_Jan]
	Augments = ["logic/autochess/augments/augment_25q4/elixir_collector_2/augment_elixir_collector_2"]
[AutoChessArena7_2026_Jan]
	Augments = ["logic/autochess/augments/augment_25q4/immune_tile/augment_immune_tile"]
[AutoChessArena8_2026_Jan]
	Augments = ["logic/autochess/augments/augment_25q4/xbow_2/augment_xbow_2","logic/autochess/augments/augment_basic/unit_conference/augment_unit_conference"]
[AutoChessArena9_2026_Jan]
	Augments = ["logic/autochess/augments/augment_basic/lucky_discount/augment_lucky_discount","logic/autochess/augments/augment_25q4/jump_tile/augment_jump_tile"]
[AutoChessArena10_2026_Jan]
	Augments = ["logic/autochess/augments/augment_basic/ascended_star/augment_ascended_star","logic/autochess/augments/augment_25q4/tesla_2/augment_tesla_2"]
[AutoChessArena1_2026_Feb]
	Augments = []
[AutoChessArena2_2026_Feb]
	Augments = ["logic/autochess/augments/augment_25q4/damage_tile_2/augment_damage_tile_2","logic/autochess/augments/augment_25q4/elixir_collector_3/augment_elixir_collector_3"]
[AutoChessArena3_2026_Feb]
	Augments = ["logic/autochess/augments/augment_25q4/star_advantage/augment_star_advantage","logic/autochess/augments/augment_basic/first_free/augment_first_free"]
[AutoChessArena4_2026_Feb]
	Augments = ["logic/autochess/augments/augment_25q4/xbow_3/augment_xbow_3","logic/autochess/augments/augment_25q4/domination/augment_domination"]
[AutoChessArena5_2026_Feb]
	Augments = ["logic/autochess/augments/augment_25q4/immune_tile_2/augment_immune_tile_2","logic/autochess/augments/augment_25q4/inferno_tower_3/augment_inferno_tower_3"]
[AutoChessArena6_2026_Feb]
	Augments = ["logic/autochess/augments/augment_basic/you_are_mine/augment_you_are_mine","logic/autochess/augments/augment_basic/echo_bench/augment_echo_bench"]
[AutoChessArena7_2026_Feb]
	Augments = ["logic/autochess/augments/augment_basic/smart_trade/augment_smart_trade","logic/autochess/augments/augment_25q4/clone_tile_2/augment_clone_tile_2"]
[AutoChessArena8_2026_Feb]
	Augments = ["logic/autochess/augments/augment_25q4/mortar_3/augment_mortar_3","logic/autochess/augments/augment_basic/unit_conference/augment_unit_conference"]
[AutoChessArena9_2026_Feb]
	Augments = ["logic/autochess/augments/augment_25q4/merge_bonus/augment_merge_bonus","logic/autochess/augments/augment_25q4/tesla_3/augment_tesla_3"]
[AutoChessArena10_2026_Feb]
	Augments = ["logic/autochess/augments/augment_basic/first_pick/augment_first_pick","logic/autochess/augments/augment_25q4/jump_tile_2/augment_jump_tile_2"]
[AutoChessArena1_2026_Mar]
	Augments = []
[AutoChessArena2_2026_Mar]
	Augments = ["logic/autochess/augments/augment_basic/elixir_festival/augment_elixir_festival","logic/autochess/augments/augment_basic/bigger_pool/augment_bigger_pool"]
[AutoChessArena3_2026_Mar]
	Augments = ["logic/autochess/augments/augment_basic/one_punch/augment_one_punch","logic/autochess/augments/augment_26q1/valkyrie_axe/augment_valkyrie_axe"]
[AutoChessArena4_2026_Mar]
	Augments = ["logic/autochess/augments/augment_basic/you_are_mine/augment_you_are_mine","logic/autochess/augments/augment_25q4/merge_bonus/augment_merge_bonus"]
[AutoChessArena5_2026_Mar]
	Augments = ["logic/autochess/augments/augment_26q1/fisherman_hook/augment_fisherman_hook","logic/autochess/augments/augment_basic/champion_star/augment_champion_star"]
[AutoChessArena6_2026_Mar]
	Augments = ["logic/autochess/augments/augment_25q4/star_advantage/augment_star_advantage","logic/autochess/augments/augment_basic/echo_bench/augment_echo_bench"]
[AutoChessArena7_2026_Mar]
	Augments = ["logic/autochess/augments/augment_25q4/damage_tile/augment_damage_tile","logic/autochess/augments/augment_26q1/prince_lance/augment_prince_lance"]
[AutoChessArena8_2026_Mar]
	Augments = ["logic/autochess/augments/augment_25q4/domination/augment_domination","logic/autochess/augments/augment_basic/devil_snap/augment_devil_snap"]
[AutoChessArena9_2026_Mar]
	Augments = ["logic/autochess/augments/augment_basic/mystery_shop/augment_mystery_shop","logic/autochess/augments/augment_26q1/maiden_shield/augment_maiden_shield"]
[AutoChessArena10_2026_Mar]
	Augments = ["logic/autochess/augments/augment_25q4/jump_tile/augment_jump_tile","logic/autochess/augments/augment_basic/coaching/augment_coaching"]
[AutoChessArena1_2026_Season_8]
	Augments = []
[AutoChessArena2_2026_Season_8]
	Augments = ["logic/autochess/augments/augment_basic/legacy_augment/augment_legacy_augment","logic/autochess/augments/augment_26q1/winner_wins/augment_winner_wins"]
[AutoChessArena3_2026_Season_8]
	Augments = ["logic/autochess/augments/augment_basic/rare_star/augment_rare_star","logic/autochess/augments/augment_26q1/rage_shield/augment_rage_shield"]
[AutoChessArena4_2026_Season_8]
	Augments = ["logic/autochess/augments/augment_26q1/three_star_fantasy/augment_three_star_fantasy","logic/autochess/augments/augment_basic/first_free/augment_first_free"]
[AutoChessArena5_2026_Season_8]
	Augments = ["logic/autochess/augments/augment_26q1/rainbow_gift/augment_rainbow_gift","logic/autochess/augments/augment_26q1/slow_shield/augment_slow_shield"]
[AutoChessArena6_2026_Season_8]
	Augments = ["logic/autochess/augments/augment_basic/last_stand/augment_last_stand","logic/autochess/augments/augment_basic/ultimate_origin/augment_ultimate_origin"]
[AutoChessArena7_2026_Season_8]
	Augments = ["logic/autochess/augments/augment_26q1/we_are_the_champion/augment_we_are_the_champion","logic/autochess/augments/augment_basic/trait_dummy/augment_trait_dummy"]
[AutoChessArena8_2026_Season_8]
	Augments = ["logic/autochess/augments/augment_basic/endurance_training/augment_endurance_training","logic/autochess/augments/augment_26q1/star_shield/augment_star_shield"]
[AutoChessArena9_2026_Season_8]
	Augments = ["logic/autochess/augments/augment_basic/master_arena/augment_master_arena","logic/autochess/augments/augment_basic/ascension/augment_ascension"]
[AutoChessArena10_2026_Season_8]
	Augments = ["logic/autochess/augments/augment_basic/monster_drink/augment_monster_drink","logic/autochess/augments/augment_26q1/lava_shield/augment_lava_shield"]
[AutoChessArena1_2026_Season_9]
	Augments = []
[AutoChessArena2_2026_Season_9]
	Augments = ["logic/autochess/augments/augment_26q2/last_survivor/augment_last_survivor","logic/autochess/augments/augment_basic/echo_bench/augment_echo_bench"]
[AutoChessArena3_2026_Season_9]
	Augments = ["logic/autochess/augments/augment_26q2/orb/augment_orb","logic/autochess/augments/augment_26q2/abyss_tile/augment_abyss_tile"]
[AutoChessArena4_2026_Season_9]
	Augments = ["logic/autochess/augments/augment_26q2/cursed_tile/augment_cursed_tile","logic/autochess/augments/augment_26q2/mine_field_tile/augment_mine_field_tile"]
[AutoChessArena5_2026_Season_9]
	Augments = ["logic/autochess/augments/augment_26q2/goblin_treasure/augment_goblin_treasure","logic/autochess/augments/augment_26q2/wormhole/augment_wormhole"]
[AutoChessArena6_2026_Season_9]
	Augments = ["logic/autochess/augments/augment_26q2/permanent_death/augment_permanent_death","logic/autochess/augments/augment_26q2/invisible_tile/augment_invisible_tile"]
[AutoChessArena7_2026_Season_9]
	Augments = ["logic/autochess/augments/augment_26q2/clash_of_legends/augment_clash_of_legends","logic/autochess/augments/augment_basic/ascended_star/augment_ascended_star"]
[AutoChessArena8_2026_Season_9]
	Augments = ["logic/autochess/augments/augment_26q2/equalization/augment_equalization","logic/autochess/augments/augment_basic/ascension/augment_ascension"]
[AutoChessArena9_2026_Season_9]
	Augments = ["logic/autochess/augments/augment_26q2/battle_royale/augment_battle_royale","logic/autochess/augments/augment_basic/first_pick/augment_first_pick"]
[AutoChessArena10_2026_Season_9]
	Augments = ["logic/autochess/augments/augment_25q4/jump_tile/augment_jump_tile","logic/autochess/augments/augment_26q1/star_shield/augment_star_shield"]
[AutoChessArena1_2026_Season_10]
	Augments = []
[AutoChessArena2_2026_Season_10]
	Augments = ["logic/autochess/augments/augment_26q2/battle_royale/augment_battle_royale","logic/autochess/augments/augment_26q2/invisible_tile/augment_invisible_tile"]
[AutoChessArena3_2026_Season_10]
	Augments = ["logic/autochess/augments/augment_26q2/permanent_death/augment_permanent_death","logic/autochess/augments/augment_26q2/wormhole/augment_wormhole"]
[AutoChessArena4_2026_Season_10]
	Augments = ["logic/autochess/augments/augment_26q2/goblin_treasure/augment_goblin_treasure","logic/autochess/augments/augment_26q2/abyss_tile/augment_abyss_tile"]
[AutoChessArena5_2026_Season_10]
	Augments = ["logic/autochess/augments/augment_26q2/clash_of_legends/augment_clash_of_legends","logic/autochess/augments/augment_26q1/rainbow_gift/augment_rainbow_gift"]
[AutoChessArena6_2026_Season_10]
	Augments = ["logic/autochess/augments/augment_basic/freenzy/augment_freenzy","logic/autochess/augments/augment_basic/first_free/augment_first_free"]
[AutoChessArena7_2026_Season_10]
	Augments = ["logic/autochess/augments/augment_26q2/equalization/augment_equalization","logic/autochess/augments/augment_basic/first_pick/augment_first_pick"]
[AutoChessArena8_2026_Season_10]
	Augments = ["logic/autochess/augments/augment_basic/legacy_augment/augment_legacy_augment","logic/autochess/augments/augment_26q2/mine_field_tile/augment_mine_field_tile"]
[AutoChessArena9_2026_Season_10]
	Augments = ["logic/autochess/augments/augment_26q2/orb/augment_orb","logic/autochess/augments/augment_25q4/merge_bonus/augment_merge_bonus"]
[AutoChessArena10_2026_Season_10]
	Augments = ["logic/autochess/augments/augment_26q2/last_survivor/augment_last_survivor","logic/autochess/augments/augment_26q2/cursed_tile/augment_cursed_tile"]
[AutoChessArena1_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_26q3/merge_training/augment_merge_training","logic/autochess/augments/augment_26q3/trait_training/augment_trait_training"]
[AutoChessArena2_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_26q3/trade_training/augment_trade_training","logic/autochess/augments/augment_26q3/equipment_training/augment_equipment_training"]
[AutoChessArena3_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_26q3/tile_training/augment_tile_training","logic/autochess/augments/augment_26q3/building_training/augment_building_training"]
[AutoChessArena4_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_25q4/merge_bonus/augment_merge_bonus","logic/autochess/augments/augment_25q4/domination/augment_domination"]
[AutoChessArena5_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_25q4/star_advantage/augment_star_advantage","logic/autochess/augments/augment_26q3/clashmini/augment_clashmini"]
[AutoChessArena6_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_26q2/orb/augment_orb","logic/autochess/augments/augment_26q1/three_star_fantasy/augment_three_star_fantasy"]
[AutoChessArena7_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_26q2/battle_royale/augment_battle_royale","logic/autochess/augments/augment_26q2/goblin_treasure/augment_goblin_treasure"]
[AutoChessArena8_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_26q3/clash_river/augment_clash_river_2","logic/autochess/augments/augment_26q1/rainbow_gift/augment_rainbow_gift"]
[AutoChessArena9_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_26q2/abyss_tile/augment_abyss_tile","logic/autochess/augments/augment_basic/ascended_star/augment_ascended_star"]
[AutoChessArena10_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_basic/bigger_pool/augment_bigger_pool","logic/autochess/augments/augment_26q2/wormhole/augment_wormhole"]
[AutoChessArena11_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_basic/trait_dummy/augment_trait_dummy","logic/autochess/augments/augment_basic/you_are_mine/augment_you_are_mine"]
[AutoChessArena12_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_basic/first_free/augment_first_free","logic/autochess/augments/augment_basic/echo_bench/augment_echo_bench"]
[AutoChessArena13_2026_Season_11]
	Augments = ["logic/autochess/augments/augment_25q4/jump_tile_2/augment_jump_tile_2","logic/autochess/augments/augment_26q2/cursed_tile/augment_cursed_tile"]
