[Royals]
SupportCards = ["King_PrincessTowers", "King_CannonTowers", "King_KnifeTowers", "King_ChefTowers"]
[Goblins]
PlayableCards = [
    "Goblins", 
    "SpearGoblins", 
    "BlowdartGoblin", 
    "GoblinGang", 
    "GoblinGiant", 
    "GoblinDemolisher", 
    "GoblinHut", 
    "GoblinCage", 
    "GoblinDrill", 
    "GoblinBarrel", 
    "SuspiciousBush", 
    "GoblinCurse",
    "GoblinMachine",
    "Goblinstein"
]
SupportCards = []
[UnavailableInPractice]
PlayableCards = []
SupportCards = []
[Event_Melee]
PlayableCards = [
    "Knight",
    "Goblins",
    "Giant",
    "Pekka",
    "Minions",
    "Balloon",
    "Barbarians",
    "Golem",
    "Skeletons",
    "Valkyrie",
    "SkeletonArmy",
    "Prince",
    "MiniPekka",
    "GiantSkeleton",
    "HogRider",
    "MinionHorde",
    "SkeletonWarriors",
    "DarkPrince",
    "Miner",
    "RageBarbarian",
    "BattleRam",
    "IceGolemite",
    "MegaMinion",
    "GoblinGang",
    "AngryBarbarians",
    "Assassin",
    "RoyalRecruits",
    "DarkWitch",
    "Bats",
    "Ghost",
    "Rascals",
    "MegaKnight",
    "Wallbreakers",
    "RoyalHogs",
    "GoblinGiant",
    "Fisherman",
    "MightyMiner",
    "ElixirGolem",
    "BattleHealer",
    "SkeletonKing",
    "GoldenKnight",
    "Monk",
    "ElectroGiant",
    "Phoenix",
    "GoblinMachine"
]
SupportCards = []
[Support_Cards_No_Goblins]
PlayableCards = [
	"Knight",
	"Archer",
	"Goblins",
	"Giant",
	"Pekka",
	"Minions",
	"Balloon",
	"Witch",
	"Barbarians",
	"Golem",
	"Skeletons",
	"Valkyrie",
	"SkeletonArmy",
	"Bomber",
	"Musketeer",
	"BabyDragon",
	"Prince",
	"Wizard",
	"MiniPekka",
	"SpearGoblins",
	"GiantSkeleton",
	"HogRider",
	"MinionHorde",
	"IceWizard",
	"RoyalGiant",
	"SkeletonWarriors",
	"Princess",
	"DarkPrince",
	"ThreeMusketeers",
	"LavaHound",
	"IceSpirits",
	"FireSpirits",
	"Miner",
	"ZapMachine",
	"Bowler",
	"RageBarbarian",
	"BattleRam",
	"InfernoDragon",
	"IceGolemite",
	"MegaMinion",
	"BlowdartGoblin",
	"GoblinGang",
	"ElectroWizard",
	"AngryBarbarians",
	"Hunter",
	"AxeMan",
	"Assassin",
	"RoyalRecruits",
	"DarkWitch",
	"Bats",
	"Ghost",
	"RamRider",
	"MiniSparkys",
	"Rascals",
	"MovingCannon",
	"MegaKnight",
	"SkeletonBalloon",
	"DartBarrell",
	"Wallbreakers",
	"RoyalHogs",
	"GoblinGiant",
	"Fisherman",
	"EliteArcher",
	"ElectroDragon",
	"Firecracker",
	"MightyMiner",
	"ElixirGolem",
	"BattleHealer",
	"SkeletonKing",
	"ArcherQueen",
	"GoldenKnight",
	"Monk",
	"SkeletonDragons",
	"WitchMother",
	"ElectroSpirit",
	"ElectroGiant",
	"Phoenix",
	"LittlePrince",
	"GoblinDemolisher",
	"GoblinMachine",
	"SuspiciousBush",
	"Goblinstein",
	"Cannon",
	"GoblinHut",
	"Mortar",
	"InfernoTower",
	"BombTower",
	"BarbarianHut",
	"Tesla",
	"Elixir Collector",
	"Xbow",
	"Tombstone",
	"FirespiritHut",
	"GoblinCage",
	"GoblinDrill",
	"Fireball",
	"Arrows",
	"Rage",
	"Rocket",
	"GoblinBarrel",
	"Freeze",
	"Mirror",
	"Lightning",
	"Zap",
	"Poison",
	"Graveyard",
	"Log",
	"Tornado",
	"Clone",
	"Earthquake",
	"BarbLog",
	"Heal",
	"Snowball",
	"RoyalDelivery",
	"DarkMagic",
	"GoblinCurse"
]
SupportCards = [
	"King_PrincessTowers",
	"King_CannonTowers",
	"King_KnifeTowers",
	"King_ChefTowers"
]
[Event_Troop]
PlayableCards = [
	"Golem",
	"ElectroGiant",
	"MegaKnight",
	"Pekka",
	"RoyalRecruits",
	"AngryBarbarians",
	"GiantSkeleton",
	"Balloon",
	"Barbarians",
	"Giant",
	"MinionHorde",
	"Monk",
	"Prince",
	"RoyalHogs",
	"BattleHealer",
	"BattleRam",
	"DarkPrince",
	"DarkWitch",
	"GoldenKnight",
	"HogRider",
	"MightyMiner",
	"MiniPekka",
	"Phoenix",
	"RageBarbarian",
	"SkeletonKing",
	"Valkyrie",
	"Assassin",
	"ElixirGolem",
	"Fisherman",
	"Ghost",
	"Knight",
	"MegaMinion",
	"Miner",
	"Minions",
	"SkeletonArmy",
	"SkeletonWarriors",
	"Bats",
	"Goblins",
	"IceGolemite",
	"SuspiciousBush",
	"Wallbreakers",
	"Skeletons",
	"GoblinGiant",
	"GoblinMachine",
	"Goblinstein",
	"Rascals",
	"GoblinGang",
	"ThreeMusketeers",
	"LavaHound",
	"RoyalGiant",
	"ZapMachine",
	"ArcherQueen",
	"AxeMan",
	"Bowler",
	"ElectroDragon",
	"MovingCannon",
	"RamRider",
	"Witch",
	"Wizard",
	"BabyDragon",
	"DartBarrell",
	"ElectroWizard",
	"EliteArcher",
	"GoblinDemolisher",
	"Hunter",
	"InfernoDragon",
	"MiniSparkys",
	"Musketeer",
	"SkeletonDragons",
	"WitchMother",
	"Archer",
	"BlowdartGoblin",
	"Firecracker",
	"IceWizard",
	"LittlePrince",
	"Princess",
	"Bomber",
	"SpearGoblins",
	"ElectroSpirit",
	"FireSpirits",
	"Heal",
	"IceSpirits",
	"SkeletonBalloon"
]
SupportCards = []
[Goblinstein]
	PlayableCards = ["Goblinstein"]
	SupportCards = []
	Heroes = []
