[ThreeMusketeer]
Rarity = "Common"
SightRange = 6000
DeployTime = 1000
Speed = 60
Hitpoints = 282
HitSpeed = 1000
LoadTime = 300
Projectile = "MusketeerProjectile"
Range = 6000
AttacksGround = true
AttacksAir = true
ProjectileEffect = "musketeer_attack"
FileName = "sc/chr_musketeer.sc"
BlueExportName = "chr_musketeer_blue"
RedExportName = "chr_musketeer"
PrestigeSWF = "sc/chr_prestige2_dl.sc"
PrestigeExportName2 = "musketeer_prestige2"
UseAnimator = true
DamageEffect = "musketeer_hit"
DeathEffect = "musketeer_die"
MoveEffect = "musketeer_steps"
SpawnEffect = "musketeer_deploy"
ShadowScaleX = 80
ShadowScaleY = 80
ShadowY = -10
ShadowSkew = 35
Scale = 100
CollisionRadius = 500
Mass = 5
HealthBar = "Medium"
DamageExportName = "filter_damage"
AttackStartEffect = "musketeer_attack_start"
SpawnRadius = 800
ProjectileStartRadius = 450
ProjectileStartZ = 450
TID = "TID_CHARACTER_MUSKETEER"
DeployDelay = 300
DeployBaseAnimExportName = "filter_deploy_unit_default"
[SpearGoblinParty]
Rarity = "Common"
SightRange = 5500
DeployTime = 1000
Speed = 120
Hitpoints = 52
HitSpeed = 1700
LoadTime = 1200
Projectile = "SpearGoblinPartyProjectile"
Range = 5000
AttacksGround = true
AttacksAir = true
ProjectileEffect = "spear_goblin_attack"
FileName = "sc/chr_goblin_archer.sc"
BlueExportName = "goblinArcher_blue"
RedExportName = "goblinArcher"
PrestigeSWF = "sc/chr_prestige_dl.sc"
PrestigeExportName2 = "spear_goblin_prestige"
PrestigeExportName3 = "spear_goblin_prestige2"
UseAnimator = true
DeathEffect = "spear_goblin_die"
MoveEffect = "spear_goblin_steps"
SpawnEffect = "spear_goblin_deploy"
ShadowScaleX = 75
ShadowScaleY = 75
ShadowY = -15
ShadowSkew = 25
Scale = 133
CollisionRadius = 500
Mass = 1
HealthBar = "Small"
HealthBarOffsetY = -10
DamageExportName = "filter_damage"
AttackStartEffect = "spear_goblin_attack_start"
ProjectileStartZ = 600
TID = "TID_CHARACTER_SPEAR_GOBLIN"
DeployDelay = 400
DeployBaseAnimExportName = "filter_deploy_unit_default"
[GoblinBrawlerParty]
Rarity = "Common"
SightRange = 5500
DeployTime = 1000
Speed = 90
Hitpoints = 422
HitSpeed = 1100
LoadTime = 900
Damage = 132
Range = 800
AttacksGround = true
FileName = "sc/chr_goblin_thug_dl.sc"
BlueExportName = "goblin_thug"
RedExportName = "goblin_thug_red"
PrestigeSWF = "sc/chr_goblin_thug_dl.sc"
PrestigeExportName2 = "goblin_thug_prestige2"
PrestigeExportName3 = "goblin_thug_prestige3"
UseAnimator = true
DamageEffect = "goblin_brawler_hit"
DeathEffect = "goblin_brawler_die"
MoveEffect = "goblin_brawler_steps"
SpawnEffect = "goblin_brawler_deploy"
ShadowScaleX = 50
ShadowScaleY = 50
ShadowX = -5
ShadowY = 5
ShadowSkew = 35
Scale = 100
CollisionRadius = 500
Mass = 2
HealthBar = "Medium"
DamageExportName = "filter_damage"
AttackStartEffect = "goblin_brawler_attack_start"
ProjectileStartRadius = 350
ProjectileStartZ = 350
TID = "TID_CHARACTER_GOBLINBRAWLER"
DeployDelay = 400
DeployBaseAnimExportName = "filter_deploy_unit_default"
AttackFinishTime = 500
AttackStateCount = 2
[Prince_Chess]
Rarity = "Epic"
SightRange = 5500
DeployTime = 1000
ChargeRange = 300
Speed = 60
Hitpoints = 1200
HitSpeed = 1400
LoadTime = 900
Damage = 245
DamageSpecial = 490
Range = 1600
AttacksGround = true
FileName = "sc/chr_prince.sc"
BlueExportName = "Prince"
RedExportName = "Prince_red"
PrestigeSWF = "sc/chr_prestige_dl.sc"
UseAnimator = true
DamageEffect = "prince_hit"
DamageEffectSpecial = "prince_charge_hit"
DeathEffect = "prince_die"
MoveEffect = "prince_steps"
SpawnEffect = "prince_deploy"
ShadowScaleX = 80
ShadowScaleY = 80
ShadowSkew = 35
IgnorePushback = true
Scale = 72
CollisionRadius = 600
Mass = 6
HealthBar = "Medium"
DamageExportName = "filter_damage_wobble"
AttackStartEffect = "prince_attack_start"
JumpHeight = 4000
LandingEffect = "hog_rider_landing"
JumpSpeed = 160
ChargeEffect = "prince_charge"
TID = "TID_SPELL_PRINCE"
ChargeSpeedMultiplier = 200
DeployBaseAnimExportName = "filter_deploy_unit_default"
JumpEnabled = true
[ArcherQueen_Chess]
Rarity = "Common"
SightRange = 5500
DeployTime = 1000
Speed = 60
Hitpoints = 1000
HitSpeed = 1200
LoadTime = 900
Projectile = "ArcherQueenArrow"
Range = 5000
AttacksGround = true
AttacksAir = true
ProjectileEffect = "arrows_trail"
FileName = "sc/chr_archer_queen_dl.sc"
BlueExportName = "ArcherQueen"
RedExportName = "ArcherQueen_enemy"
UseAnimator = true
DamageEffect = "archer_queen_hit"
DeathEffect = "archer_queen_die"
MoveEffect = "ArcherSteps"
SpawnEffect = "archer_queen_deploy"
ShadowScaleX = 75
ShadowScaleY = 75
ShadowY = -15
ShadowSkew = 25
Scale = 79
CollisionRadius = 500
Mass = 6
HealthBar = "Medium"
HealthBarOffsetY = -5
DamageExportName = "filter_damage"
AttackStartEffect = "archer_queen_attack_start"
ProjectileStartRadius = 1350
ProjectileStartZ = 800
TID = "TID_CHARACTER_ARCHER"
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
Ability = "ArcherQueenRapid"
AbilityPendingEffect = "Heal_aura"
CustomSpawnFilter = "filter_champion_archer_queen"
AllowAreaDmgWhenInvisible = true
[EliteArcher_Chess]
Rarity = "Common"
SightRange = 7500
DeployTime = 1000
Speed = 60
Hitpoints = 440
HitSpeed = 1100
LoadTime = 600
Projectile = "EliteArcherArrow"
Range = 7000
AttacksGround = true
AttacksAir = true
ProjectileEffect = "magic_archer_attack_start"
FileName = "sc/chr_magic_archer_dl.sc"
BlueExportName = "magic_archer"
RedExportName = "magic_archer_red"
PrestigeSWF = "sc/chr_magic_archer_dl.sc"
PrestigeExportName2 = "magic_archer_prestige"
PrestigeExportName3 = "magic_archer_prestige2"
PrestigeRedExportName2 = "magic_archer_red_prestige"
PrestigeRedExportName3 = "magic_archer_red_prestige2"
UseAnimator = true
DeathEffect = "ArcherDie"
MoveEffect = "MagicArcherSteps"
SpawnEffect = "MagicArcherDeploy"
ShadowScaleX = 75
ShadowScaleY = 75
ShadowY = -15
ShadowSkew = -1
Scale = 85
CollisionRadius = 600
Mass = 3
HealthBar = "Medium"
HealthBarOffsetY = -10
DamageExportName = "filter_damage"
AttackStartEffect = "ArcherAttackStart"
ProjectileStartRadius = 800
ProjectileStartZ = 500
TID = "TID_CHARACTER_ARCHER"
DeployDelay = 400
DeployBaseAnimExportName = "filter_deploy_unit_legendary"
[Bomber_Chess]
Rarity = "Common"
SightRange = 5500
DeployTime = 1000
Speed = 60
Hitpoints = 130
HitSpeed = 1800
LoadTime = 1600
Projectile = "BombSkeletonProjectile"
Range = 4500
AttacksGround = true
ProjectileEffect = "bomber_attack"
FileName = "sc/chr_bomber.sc"
BlueExportName = "chr_bomber"
RedExportName = "chr_bomber_RED"
PrestigeSWF = "sc/chr_bomber.sc"
PrestigeExportName2 = "chr_bomber_prestige2"
PrestigeRedExportName2 = "chr_bomber_prestige2"
UseAnimator = true
DeathEffect = "bomber_die"
MoveEffect = "bomber_steps"
SpawnEffect = "bomber_deploy"
ShadowScaleX = 50
ShadowScaleY = 50
ShadowX = -5
ShadowY = 5
ShadowSkew = 35
Scale = 80
CollisionRadius = 500
Mass = 4
HealthBar = "Small"
DamageExportName = "filter_damage"
AttackStartEffect = "bomber_attack_start"
ProjectileStartRadius = 350
ProjectileStartZ = 350
TID = "TID_SPELL_BOMBER"
DeployBaseAnimExportName = "filter_deploy_unit_default"
WalkingSpeedTweakPercentage = -10
[GoblinBrawlerDouble]
Rarity = "Rare"
SightRange = 5500
DeployTime = 1000
Speed = 90
Hitpoints = 510
HitSpeed = 1100
LoadTime = 900
Damage = 159
Range = 800
AttacksGround = true
FileName = "sc/chr_goblin_thug_dl.sc"
BlueExportName = "goblin_thug"
RedExportName = "goblin_thug_red"
PrestigeSWF = "sc/chr_goblin_thug_dl.sc"
PrestigeExportName2 = "goblin_thug_prestige2"
PrestigeExportName3 = "goblin_thug_prestige3"
UseAnimator = true
DamageEffect = "goblin_brawler_hit"
DeathEffect = "goblin_brawler_die"
MoveEffect = "goblin_brawler_steps"
SpawnEffect = "goblin_brawler_deploy"
ShadowScaleX = 50
ShadowScaleY = 50
ShadowX = -5
ShadowY = 5
ShadowSkew = 35
Scale = 100
CollisionRadius = 500
Mass = 2
HealthBar = "Medium"
DamageExportName = "filter_damage"
AttackStartEffect = "goblin_brawler_attack_start"
ProjectileStartRadius = 350
ProjectileStartZ = 350
TID = "TID_CHARACTER_GOBLINBRAWLER"
DeployDelay = 400
DeployBaseAnimExportName = "filter_deploy_unit_default"
AttackFinishTime = 500
AttackStateCount = 2
