[ArrowsSpellDeco]
Rarity = "Common"
Speed = 1100
FileName = "sc/effects.sc"
ExportName = "projectile_arrow_basic_enemy"
ShadowExportName = "projectile_arrow_shadow"
Homing = true
HitEffect = "ArrowHitGround"
AoeToAir = true
AoeToGround = true
OnlyEnemies = true
Gravity = 50
TrailEffect = "arrows_trail"
HideWhenDelayed = true
[SneakyArcherArrow]
Rarity = "Legendary"
Speed = 900
FileName = "sc/effects.sc"
ExportName = "projectile_arrow_basic_enemy"
ShadowExportName = "projectile_arrow_shadow"
Homing = true
HitEffect = "ArrowHit"
Damage = 65
OnlyEnemies = true
Gravity = 60
[BatProjectile]
Rarity = "Common"
Speed = 2000
FileName = "sc/effects.sc"
ExportName = "projectile_cannonball_small"
Homing = true
HitEffect = "ArrowHit"
Damage = 32
OnlyEnemies = true
[GunnerProjectile]
Rarity = "Legendary"
Speed = 1000
FileName = "sc/effects.sc"
ExportName = "projectile_cannonball_small"
ShadowExportName = "projectile_arrow_shadow"
Homing = true
HitEffect = "cannon_hit"
Damage = 220
OnlyEnemies = true
[ZapSpiritProjectile]
Rarity = "Common"
Speed = 800
FileName = "sc/chr_skeleton.sc"
ExportName = "skeleton1_idle1_1"
Homing = true
HitEffect = "Spell_zap2_effect_enemy"
Damage = 120
AoeToAir = true
AoeToGround = true
OnlyEnemies = true
TargetBuff = "ZapFreeze"
BuffTime = 500
TrailEffect = "zap_dashing"
use360Frames = true
ChainedHitRadius = 5500
ChainedHitCount = 3
DeflectBehaviour = "NoDeflect"
[MegaCannonProjectile]
Rarity = "Common"
Speed = 700
FileName = "sc/effects.sc"
ExportName = "projectile_cannonball_large"
Scale = 200
HitEffect = "megaCannon_hit"
DeathEffect = "megaCannon_hit"
Damage = 480
Pushback = 750
PushbackAll = true
Radius = 1000
AoeToAir = true
AoeToGround = true
OnlyEnemies = true
ProjectileRadius = 1500
ProjectileRange = 13500
use360Frames = true
ShakesTargets = true
ShakesShooter = 16000
[CaptureTowerProjectile]
Rarity = "Common"
Speed = 600
FileName = "sc/effects.sc"
ExportName = "projectile_arrow_basic_enemy"
ShadowExportName = "projectile_arrow_shadow"
Homing = true
HitEffect = "ArrowHit"
Damage = 50
OnlyEnemies = true
Gravity = 60
[MortarMultiProjectile]
Rarity = "Common"
Speed = 300
FileName = "sc/effects.sc"
ExportName = "catapult_projectile1"
ShadowExportName = "projectile_arrow_shadow"
HitEffect = "mortar_hit"
Damage = 104
Radius = 2000
AoeToGround = true
OnlyEnemies = true
Gravity = 60
[MonkPushback]
Rarity = "Common"
Speed = 800
FileName = "sc/spell_snowball_dl.sc"
ExportName = "snowball_projectile"
RedExportName = "snowball_projectile_enemy"
ShadowExportName = "snowball_shadow"
Scale = 95
HitEffect = "Snowball_ground"
Damage = 1
Pushback = 1800
PushbackAll = true
Radius = 1000
AoeToGround = true
OnlyEnemies = true
Gravity = 50
TrailEffect = "snowball_continuous"
[SpearGoblinPartyProjectile]
Rarity = "Common"
Speed = 500
FileName = "sc/effects.sc"
ExportName = "projectile_spear_360"
ShadowExportName = "projectile_arrow_shadow"
Homing = true
HitEffect = "spear_goblin_projectile_hit"
Damage = 32
OnlyEnemies = true
Gravity = 150
use360Frames = true
[AirBowProjectile]
Rarity = "Legendary"
Speed = 1400
FileName = "sc/effects.sc"
ExportName = "projectile_arrow_basic"
ShadowExportName = "projectile_arrow_shadow"
Homing = true
HitEffect = "ArrowHit"
Damage = 68
OnlyEnemies = true
[GoblinBarrel]
Rarity = "Common"
Speed = 400
FileName = "sc/spell_goblin_barrel.sc"
ExportName = "spell_goblin_barrel_projectile"
ShadowExportName = "Barrel_shadow"
PrestigeSWF = "sc/spell_prestige_dl.sc"
PrestigeExportName2 = "spell_goblin_barrel_projectile_prestige"
PrestigeExportName3 = "spell_goblin_barrel_projectile_prestige2"
HitEffect = "goblin_barrel_explosion"
Radius = 1500
AoeToGround = true
OnlyEnemies = true
Gravity = 40
SpawnCharacterDeployTime = 1200
SpawnCharacter = "Goblin"
SpawnConstPriority = true
SpawnCharacterCount = 1
TrailEffect = "goblin_barrel_trail"
[BalloonProjectile]
Rarity = "Common"
Speed = 1000
FileName = "sc/effects.sc"
ExportName = "projectile_bomb"
OnlyEnemies = true
SpawnCharacterDeployTime = 2500
SpawnCharacter = "CommonBomb"
SpawnConstPriority = true
SpawnCharacterCount = 2
[ThrowBombProjectile]
Rarity = "Common"
Speed = 1000
FileName = "sc/effects.sc"
ExportName = "projectile_bomb"
OnlyEnemies = true
SpawnCharacterDeployTime = 1000
SpawnCharacter = "ThrownBomb"
SpawnConstPriority = true
SpawnCharacterCount = 1
[ThrowBombProjectile2]
Rarity = "Rare"
Speed = 1000
FileName = "sc/effects.sc"
ExportName = "projectile_bomb"
OnlyEnemies = true
SpawnCharacterDeployTime = 1000
SpawnCharacter = "ThrownBomb"
SpawnConstPriority = true
SpawnCharacterCount = 1
[CWTXbowProjectile]
Rarity = "Common"
Speed = 1400
FileName = "sc/effects.sc"
ExportName = "projectile_cannonball_small"
ShadowExportName = "projectile_arrow_shadow"
Homing = true
HitEffect = "cannon_hit"
Damage = 12
OnlyEnemies = true
[ClanWarsSpawnFlareProjectile]
Rarity = "Epic"
Speed = 400
FileName = "sc/building_clanwars_towers.sc"
ExportName = "spawn_elixir_projectile"
ShadowExportName = "projectile_shadow"
HitEffect = "elixir_projectile_die"
OnlyEnemies = true
Gravity = 40
TrailEffect = "elixir_projectile_trail"
[SuperWitchProjectile]
Rarity = "Legendary"
Speed = 600
FileName = "sc/chr_mother_witch_dl.sc"
ExportName = "mow_projectile"
Homing = true
OnlyEnemies = true
Gravity = 20
SpawnAreaEffectObject = "SuperWitchCurse"
TrailEffect = "elixir_projectile_trail"
ConstantHeight = 1000
ShakesTargets = true
[FireballSpellRocketMan]
Rarity = "Champion"
Speed = 600
FileName = "sc/effects.sc"
ExportName = "fireball_projectile1"
ShadowExportName = "projectile_arrow_shadow"
HitEffect = "Fireball_explosion"
Damage = 325
CrownTowerDamagePercent = -70
Pushback = 1800
Radius = 2500
AoeToAir = true
AoeToGround = true
OnlyEnemies = true
Gravity = 50
TrailEffect = "FireballEmitter"
[ArcherQueenArrow_Chess]
Rarity = "Common"
Speed = 800
FileName = "sc/effects.sc"
ExportName = "archer_queen_projectile_arrow_elite"
ShadowExportName = "projectile_arrow_shadow"
Homing = true
HitEffect = "ArrowHit"
Damage = 88
OnlyEnemies = true
Gravity = 60
TrailEffect = "archer_queen_arrow_fx"
[EliteArcherArrow_Chess]
Rarity = "Champion"
Speed = 1000
FileName = "sc/chr_magic_archer_dl.sc"
ExportName = "magic_arrow_projectile_blue"
RedExportName = "magic_arrow_projectile_red"
ShadowExportName = "magic_arrow_projectile_blue"
HomingTime = 100
HomingMinDistance = 5000
HitEffect = "cannon_hit"
DeathEffect = "magic_archer_arrow_die"
Damage = 134
Radius = 250
AoeToAir = true
AoeToGround = true
OnlyEnemies = true
TrailEffect = "MagicArrowProjectile_blue"
ProjectileRadius = 250
ProjectileStartExtraRadius = 400
ProjectileRange = 7500
ConstantHeight = 2000
ShakesTargets = true
[BombTowerProjectile_Chess]
Rarity = "Champion"
Speed = 500
FileName = "sc/effects.sc"
ExportName = "projectile_bomb"
ShadowExportName = "projectile_arrow_shadow"
HitEffect = "BombTower_projectile_hit"
Damage = 222
Radius = 1500
AoeToGround = true
OnlyEnemies = true
Gravity = 200
TrailEffect = "BomberBomb_fire_emitter"
[MysteryBuff_WitchProjectile]
Rarity = "Epic"
Speed = 600
FileName = "sc/effects.sc"
ExportName = "Tower_projectile1"
Homing = true
HitEffect = "witch_hit"
Damage = 84
Radius = 1000
AoeToAir = true
AoeToGround = true
OnlyEnemies = true
TargetBuff = "ZapFreeze"
BuffTime = 500
[MysteryBuff_BombSkeletonProjectile]
Rarity = "Common"
Speed = 400
FileName = "sc/effects.sc"
ExportName = "projectile_bomb"
ShadowExportName = "projectile_arrow_shadow"
HitEffect = "Fireball_explosion"
Damage = 87
Pushback = 1000
PushbackAll = true
Radius = 1500
AoeToGround = true
OnlyEnemies = true
Gravity = 200
TrailEffect = "BomberBomb_fire_emitter"
[MysteryBuff_BombTowerProjectile]
Rarity = "Rare"
Speed = 500
FileName = "sc/effects.sc"
ExportName = "projectile_bomb"
ShadowExportName = "projectile_arrow_shadow"
HitEffect = "Fireball_explosion"
Damage = 105
Pushback = 1000
PushbackAll = true
Radius = 1500
AoeToGround = true
OnlyEnemies = true
Gravity = 200
TrailEffect = "BomberBomb_fire_emitter"
[MysteryBuff_SkeletonDragonProjectile]
Rarity = "Common"
Speed = 500
FileName = "sc/chr_skeleton_dragon_dl.sc"
ExportName = "skeletondragon_projectile"
Homing = true
HitEffect = "Fireball_explosion"
Damage = 63
Pushback = 1000
PushbackAll = true
Radius = 800
AoeToAir = true
AoeToGround = true
OnlyEnemies = true
Gravity = 250
TrailEffect = "Skeletondragon_emitter"
[MysteryBuff_AxeManProjectile]
Rarity = "Epic"
Speed = 550
FileName = "sc/effects.sc"
ExportName = "executioner_projectile"
ShadowExportName = "bowler_projectile_shadow"
HitEffect = "axe_man_projectile_hit"
Damage = 106
Radius = 1000
AoeToAir = true
AoeToGround = true
OnlyEnemies = true
TargetBuff = "ZapFreeze"
BuffTime = 500
TrailEffect = "AxeProjectileEmitter"
ProjectileRadius = 1000
ProjectileRange = 7500
MinDistance = 4500
ConstantHeight = 3000
PingpongDeathEffect = "axe_man_projectile_die"
ShakesTargets = true
PingpongVisualTime = 1500
[CannoneerProjectile_AoE]
Rarity = "Common"
Speed = 1000
FileName = "sc/chr_cannoneer_troop.sc"
ExportName = "Cannoneer_Projectile_ball"
ShadowExportName = "Cannoneer_Projectile_ball_shadow"
Scale = 36
Homing = true
HitEffect = "Cannoneer_explosion"
Damage = 165
Radius = 500
AoeToAir = true
AoeToGround = true
OnlyEnemies = true
Gravity = 400
TrailEffect = "CannoneerEmitter"
use360Frames = true
[MysteryBuff_SpearGoblinProjectile]
Rarity = "Common"
Speed = 500
FileName = "sc/effects.sc"
ExportName = "projectile_spear_360"
ShadowExportName = "projectile_arrow_shadow"
Homing = true
HitEffect = "spear_goblin_projectile_hit"
Damage = 32
OnlyEnemies = true
Gravity = 150
TargetBuff = "MysteryBuff_ZapFreeze"
BuffTime = 300
use360Frames = true
[MysteryBuff_BlowdartGoblinProjectile]
Rarity = "Rare"
Speed = 800
FileName = "sc/effects.sc"
ExportName = "projectile_arrow_basic"
ShadowExportName = "projectile_arrow_shadow"
Homing = true
HitEffect = "BlowdartArrowHit"
Damage = 62
OnlyEnemies = true
Gravity = 120
TargetBuff = "MysteryBuff_Poison"
BuffTime = 4000
ApplyBuffBeforeDamage = true
TrailEffect = "BlowdartProjectileEmitter"
[VineSpellBottle]
Rarity = "Common"
Speed = 400
FileName = "sc/spell_vine.sc"
ExportName = "vine_vial"
ShadowExportName = "projectile_arrow_shadow"
Homing = true
HitEffect = "mortar_hit"
Damage = 1
OnlyEnemies = true
Gravity = 50
TrailEffect = "elixir_projectile_trail"
