[Common]
TID = "TID_RARITY_COMMON"
SortOrder = 1
SortCapacity = 1
LevelCount = 16
RelativeLevel = 0
TournamentLevelIndex = 10
UpgradeExp = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
UpgradePrestige = [4, 5, 6, 10, 25, 50, 100, 200, 400, 600, 800, 1600, 2000, 0, 0, 0]
UpgradeCost = [5, 20, 50, 150, 400, 1000, 2000, 4000, 8000, 15000, 25000, 40000, 60000, 90000, 120000, 0]
UpgradeMaterialCount = [2, 4, 10, 20, 50, 100, 200, 400, 800, 1000, 1500, 2500, 3500, 5500, 7500, 0]
CardFileName = "sc/ui.sc"
CardExportName = "support_card_common"
CardTextBgExportName = "support_card_level_common"
CardCappedLevelBgFrameIdx = 0
InfoPageFilename = "sc/ui.sc"
InfoPageExportName = "support_card_ability_rarity_type_common"
TextColor = ["153-204-255"]
OverflowPrestige = 1
BlingTokenConversionValue = 1
GoldConversionValue = 5
AppearEffect = "openChest_get_common"
LoopEffect = "openChest_loop_common"
IconSWF = "sc/ui_card_items.sc"
IconExportName = "icon_btn_card_support"
GemCostPerCard100000th = [5000000, 2500000, 1000000, 500000, 200000, 100000, 50000, 32500, 36250, 36000, 36000, 36000, 35715, 36364, 36000]
GemCostForUnlock = 0
[Rare]
TID = "TID_RARITY_RARE"
SortOrder = 2
SortCapacity = 7
LevelCount = 14
RelativeLevel = 2
TournamentLevelIndex = 8
UpgradeExp = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
UpgradePrestige = [6, 10, 25, 50, 100, 200, 400, 600, 800, 1600, 2000, 0, 0, 0]
UpgradeCost = [50, 150, 400, 1000, 2000, 4000, 8000, 15000, 25000, 40000, 60000, 90000, 120000 ,0]
UpgradeMaterialCount = [2, 4, 10, 20, 50, 100, 200, 300, 400, 550, 750, 1000, 1400, 0]
CardFileName = "sc/ui.sc"
CardExportName = "support_card_rare"
CardTextBgExportName = "support_card_level_rare"
CardCappedLevelBgFrameIdx = 1
InfoPageFilename = "sc/ui.sc"
InfoPageExportName = "support_card_rarity_type_rare"
TextColor = ["255-204-102"]
OverflowPrestige = 10
BlingTokenConversionValue = 6
GoldConversionValue = 50
AppearEffect = "openChest_get_rare"
LoopEffect = "openChest_loop_rare"
IconSWF = "sc/ui_card_items.sc"
IconExportName = "icon_btn_card_support"
GemCostPerCard100000th = [5000000, 2500000, 1000000, 50000, 260000, 210000, 210000, 210000, 210000, 218182, 213334, 210000, 214286]
GemCostForUnlock = 0
[Epic]
TID = "TID_RARITY_EPIC"
SortOrder = 3
SortCapacity = 80
LevelCount = 11
RelativeLevel = 5
TournamentLevelIndex = 5
UpgradeExp = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
UpgradePrestige = [25, 100, 200, 400, 600, 800, 1600, 2000, 0, 0, 0]
UpgradeCost = [400, 2000, 4000, 8000, 15000, 25000, 40000, 60000, 90000, 120000,0]
UpgradeMaterialCount = [2, 4, 10, 20, 30, 50, 70, 100, 130, 180, 0]
CardFileName = "sc/ui.sc"
CardExportName = "support_card_epic"
CardTextBgExportName = "support_card_level_epic"
CardCappedLevelBgFrameIdx = 2
InfoPageFilename = "sc/ui.sc"
InfoPageExportName = "support_card_rarity_type_epic"
TextColor = ["255-153-255"]
OverflowPrestige = 100
BlingTokenConversionValue = 60
GoldConversionValue = 500
AppearEffect = "openChest_get_epic"
LoopEffect = "openChest_loop_epic"
IconSWF = "sc/ui_card_items.sc"
IconExportName = "icon_btn_card_support"
GemCostPerCard100000th = [5000000, 3250000, 2100000, 2100000, 2100000, 2200000, 2142858, 2100000, 1923077, 2166667]
GemCostForUnlock = 0
[Legendary]
TID = "TID_RARITY_LEGENDARY"
SortOrder = 4
SortCapacity = 2000
LevelCount = 8
RelativeLevel = 8
TournamentLevelIndex = 2
UpgradeExp = [0, 0, 0, 0, 0, 0, 0, 0]
UpgradePrestige = [250, 600, 800, 1600, 2000, 0, 0, 0]
UpgradeCost = [5000, 15000, 25000, 40000, 60000, 90000, 120000, 0]
UpgradeMaterialCount = [2, 4, 6, 9, 12, 14, 20, 0]
CardFileName = "sc/ui.sc"
CardExportName = "support_card_legendary"
CardTextBgExportName = "support_card_level_legendary"
CardCappedLevelBgFrameIdx = 3
InfoPageFilename = "sc/ui.sc"
InfoPageExportName = "support_card_rarity_type_legendary"
TextColor = ["255-153-255","255-153-255","255-255-153","153-255-102","153-255-102"]
OverflowPrestige = 1000
BlingTokenConversionValue = 600
GoldConversionValue = 2000
AppearEffect = "openChest_get_legendary"
LoopEffect = "openChest_loop_legendary"
IconSWF = "sc/ui_card_items.sc"
IconExportName = "icon_btn_card_support"
GemCostPerCard100000th = [21000000, 21000000, 21666667, 21111112, 20833334, 20714286, 21000000]
GemCostForUnlock = 0
[Champion]
TID = "TID_RARITY_CHAMPION"
SortOrder = 5
SortCapacity = 4000
LevelCount = 6
RelativeLevel = 10
TournamentLevelIndex = 0
UpgradeExp = [0, 0, 0, 0, 0, 0]
UpgradePrestige = [800, 1600, 2000, 0, 0, 0]
UpgradeCost = [25000, 40000, 60000, 90000, 120000, 0]
UpgradeMaterialCount = [2, 5, 8, 11, 15, 0]
CardFileName = "sc/ui.sc"
CardExportName = "support_card_champion"
CardTextBgExportName = "support_card_level_champion"
CardCappedLevelBgFrameIdx = 4
InfoPageFilename = "sc/ui.sc"
InfoPageExportName = "support_card_rarity_type_champion"
TextColor = ["255-222-0","255-217-100","253-251-222"]
OverflowPrestige = 2000
BlingTokenConversionValue = 1200
GoldConversionValue = 4000
AppearEffect = "openChest_get_champion"
LoopEffect = "openChest_loop_champion"
IconSWF = "sc/ui_card_items.sc"
IconExportName = "icon_btn_card_support"
GemCostPerCard100000th = [40000000, 40000000, 40000000, 40000000, 40000000]
GemCostForUnlock = 0
