[BUILDING.PrincessTower_SpookyChess]
    Rarity = "Common"
    IsBuilding = true
    SightRange = 7000
    Hitpoints = 1400
    HitSpeed = 900
    Projectile = "VoodooProjectile_SpookyChess"
    Range = 7000
    AttacksGround = true
    AttacksAir = true
    ProjectileEffect = "arrows_trail"
    FileName = "sc/building_tower.sc"
    BlueExportName = "StarTower_base_blue"
    BlueTopExportName = "StarTower_top_blue"
    RedExportName = "StarTower_base_red"
    RedTopExportName = "StarTower_top_red"
    AttachedCharacter = "WitchMother"
    AttachedCharacterHeight = 2800
    DeathEffect = "TowerExplode"
    CrowdEffects = true
    ShadowScaleX = 102
    ShadowScaleY = 70
    ShadowX = -5
    ShadowY = 5
    ShadowSkew = 13
    Scale = 90
    CollisionRadius = 900
    TileSizeOverride = 2
    HealthBar = "Tower"
    HealthBarOffsetY = 0
    HealthBarOffsetYRed = 58
    HealthBarOffsetYBlue = 100
    ShowHealthNumber = true
    ProjectileStartRadius = 1600
    ProjectileStartZ = 3000
    IsSummonerTower = true
    NoDeploySizeW = 11
    NoDeploySizeH = 21
    TID = "TID_BUILDING_ARCHER_TOWER"
    ProjectileYOffset = -800
    [PROJECTILE.VoodooProjectile_SpookyChess]
        Rarity = "Common"
        Speed = 600
        FileName = "sc/chr_mother_witch_dl.sc"
        ExportName = "mow_projectile"
        Homing = true
        Damage = 52
        OnlyEnemies = true
        Gravity = 20
        TargetBuff = "VoodooCurse"
        BuffTime = 5000
        ApplyBuffBeforeDamage = true
        TrailEffect = "elixir_projectile_trail"
        ConstantHeight = 1000
        ShakesTargets = true
[BUILDING.AxeManTower_SpookyChess]
    Rarity = "Champion"
    IsBuilding = true
    SightRange = 5500
    DeployTime = 1000
    Hitpoints = 1200
    HitSpeed = 1100
    Projectile = "AxeManProjectile_SpookyChess"
    Range = 5500
    AttacksGround = true
    AttacksAir = true
    ProjectileEffect = "magic_archer_attack_start"
    FileName = "sc/building_bomb_tower.sc"
    BlueExportName = "building_bomb_tower_blue"
    BlueTopExportName = "building_bomb_tower_top_blue"
    RedExportName = "building_bomb_tower_red"
    RedTopExportName = "building_bomb_tower_top_red"
    AttachedCharacter = "AxeMan_Small"
    AttachedCharacterHeight = 3200
    DeathEffect = "BombTower_die"
    SpawnEffect = "goblin_hut_deploy"
    ShadowScaleX = 100
    ShadowScaleY = 85
    ShadowX = -8
    ShadowSkew = 35
    Scale = 80
    TargetedHitEffect = "executioner_attack_start"
    CollisionRadius = 600
    TileSizeOverride = 2
    HealthBarOffsetY = -15
    DamageExportName = "filter_damage_wobble"
    TurretMovement = 5
    ProjectileYOffset = 200
[EXT.AxeMan_Small]
    Base = "CHARACTER.AxeMan"
    Scale = 90
    [PROJECTILE.AxeManProjectile_SpookyChess]
        Rarity = "Champion"
        Speed = 550
        FileName = "sc/effects.sc"
        ExportName = "executioner_projectile"
        ShadowExportName = "bowler_projectile_shadow"
        HitEffect = "axe_man_projectile_hit"
        Damage = 169
        Radius = 1000
        AoeToAir = true
        AoeToGround = true
        OnlyEnemies = true
        TrailEffect = "AxeProjectileEmitter"
        ProjectileRadius = 1000
        ProjectileRange = 7500
        MinDistance = 4500
        ConstantHeight = 3000
        PingpongDeathEffect = "axe_man_projectile_die"
        ShakesTargets = true
        PingpongVisualTime = 1500
    
[BUILDING.DarkPrinceTower_SpookyChess]
    Rarity = "Champion"
    IsBuilding = true
    SightRange = 6000
    DeployTime = 1000
    Hitpoints = 1200
    HitSpeed = 10000
    AttacksGround = true
    FileName = "sc/building_bomb_tower.sc"
    BlueExportName = "building_bomb_tower_blue"
    BlueTopExportName = "building_bomb_tower_top_blue"
    RedExportName = "building_bomb_tower_red"
    RedTopExportName = "building_bomb_tower_top_red"
    AttachedCharacter = "DarkPrince_Small"
    AttachedCharacterHeight = 3200
    DeathEffect = "BombTower_die"
    ShadowScaleX = 100
    ShadowScaleY = 85
    ShadowX = -8
    ShadowSkew = 35
    Scale = 80
    CollisionRadius = 600
    TileSizeOverride = 2
    HealthBarOffsetY = -15
    DamageExportName = "filter_damage_wobble"
    AttackStartEffect = "BombTower_attack_start"
    SpawnStartTime = 2500
    SpawnNumber = 1
    SpawnPauseTime = 15000
    SpawnCharacter = "DarkPrince"
    TID = "TID_BUILDING_BOMB_TOWER"
    [EXT.DarkPrince_Small]
    Base = "CHARACTER.DarkPrince"
    Scale = 80
[EXT.SkeletonWarrior_SpookyChess]
    Base = "CHARACTER.SkeletonWarrior"
    SightRange = 1600
    Speed = 0
[EXT.KingTower_SpookyChess]
    Base = "BUILDING.KingTower_chess"
    TileSizeOverride = 2
    HealthBarOffsetY = 0
    HealthBarOffsetYRed = 90
    HealthBarOffsetYBlue = 95
