/* Optional card-form content. An empty registry changes neither roster nor decks. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./catalog.js'):root.RoyaleCatalog);if(n)module.exports=api;else root.RoyaleCardForms=api;})(globalThis,function(K){'use strict';
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k),safeId=s=>typeof s==='string'&&s.length<=180&&/^[A-Za-z0-9_.:-]+$/.test(s)&&!['__proto__','constructor','prototype'].includes(s);
function copy(value){return JSON.parse(JSON.stringify(value));}
function freeze(value){if(value&&typeof value==='object'){for(const child of Object.values(value))freeze(child);Object.freeze(value);}return value;}
function canonical(v){return Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;}
function fingerprint(value){const s=JSON.stringify(canonical(value));let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return 'forms-'+(h>>>0).toString(16).padStart(8,'0');}
const DEFAULT_SLOT_TEMPLATE=freeze([{kind:'evolution',unlockArena:3},{kind:'hero',unlockArena:5},{kind:'wild',unlockArena:10}]);
const family=f=>f.kind==='champion'?'hero':f.kind,accepts=(s,f)=>!!s&&(s.kind==='wild'||s.kind===family(f));
function createRegistry({forms=[],loadouts={},catalog=K}={}){
 if(!Array.isArray(forms)||forms.length>1024)throw TypeError('Invalid form registry');
 const rows=forms.map(raw=>{if(!raw||!safeId(raw.id)||!catalog.CARD_BY_ID[raw.baseCardId])throw TypeError('Invalid form ID or base card');if(!['evolution','hero','champion'].includes(raw.kind))throw TypeError('Invalid form kind');const cycles=raw.kind==='evolution'?Number(raw.cycles):0;if(!Number.isInteger(cycles)||cycles<0||cycles>100||raw.kind==='evolution'&&cycles<1)throw TypeError('Invalid evolution cycles');if(!raw.source||typeof raw.source!=='object'||Array.isArray(raw.source))throw TypeError('Invalid form source');const ability=raw.ability?copy(raw.ability):null;if(ability){for(const key of ['ManaCost','CastTime','TriggerDelay','Cooldown','MaxCharges'])if(ability[key]!==undefined&&(!Number.isFinite(ability[key])||ability[key]<0||key==='MaxCharges'&&!Number.isInteger(ability[key])))throw TypeError('Invalid ability '+key);}return freeze({...copy(raw),cycles,requiredShards:Math.max(0,Math.floor(Number(raw.requiredShards)||0)),ability});});
 const byId=Object.create(null),byCard=Object.create(null);for(const f of rows){if(own(byId,f.id))throw TypeError('Duplicate form ID');byId[f.id]=f;(byCard[f.baseCardId]||(byCard[f.baseCardId]=[])).push(f);}
 const slots=(Array.isArray(loadouts.slots)?loadouts.slots:[]).map(s=>{if(!['evolution','hero','wild'].includes(s?.kind)||!Number.isInteger(s.unlockArena)||s.unlockArena<0)throw TypeError('Invalid form slot');return freeze({kind:s.kind,unlockArena:s.unlockArena});});
 // A content-free installation still exposes the shared deck layout. Its declared
 // source signature stays unchanged; replay context records the positional rule.
 const declaredPolicy=freeze({...copy(loadouts),slots}),policy=freeze({...copy(loadouts),slots:slots.length?slots:DEFAULT_SLOT_TEMPLATE,casualSlots:loadouts.casualSlots!==false}),get=id=>own(byId,id)?byId[id]:null,forCard=id=>byCard[id]||Object.freeze([]),champion=id=>forCard(id).find(f=>f.kind==='champion')||null;
 const availableSlots=context=>(context.positionalSlots===true?policy.slots:slots).map((s,index)=>({...s,index})).filter(s=>context.casual===true&&(context.positionalSlots===true?policy:declaredPolicy).casualSlots===true||Number(context.arena||0)>=s.unlockArena);
 function selections(deck,raw){return deck.map((base,index)=>{const f=get(raw?.[index]);return f&&f.baseCardId===base?f.id:champion(base)?.id||null;});}
 function qualify(deck,raw=[],context={}){
  const selected=selections(deck,raw),errors=[],available=availableSlots(context),assignments=[],used=new Set();
  for(let i=0;i<deck.length;i++){if(raw?.[i]&&!get(raw[i]))errors.push({index:i,reason:'Unknown form'});else if(raw?.[i]&&get(raw[i]).baseCardId!==deck[i])errors.push({index:i,reason:'Form belongs to another card'});const f=get(selected[i]);if(!f)continue;if(f.kind!=='champion'&&Array.isArray(context.unlockedForms)&&!context.unlockedForms.includes(f.id))errors.push({index:i,reason:'Form is locked'});}
  // Reserve dedicated slots first. A Hero or Champion can consume the Hero slot;
  // either family may consume a remaining Wild slot.
  const requests=selected.map((id,index)=>({form:get(id),index})).filter(x=>x.form);
  if(context.positionalSlots===true){for(const q of requests){const s=available.find(s=>s.index===q.index);if(!s)errors.push({index:q.index,reason:q.index>=policy.slots.length?'Use a special deck slot for this form':'Reach Arena '+policy.slots[q.index].unlockArena+' to use this form slot'});else if(!accepts(s,q.form))errors.push({index:q.index,reason:'This form does not fit the '+s.kind+' slot'});else assignments.push({index:q.index,slot:q.index,kind:s.kind,formId:q.form.id});}return{ok:errors.length===0,forms:selected,errors,slots:available,assignments};}
  for(const q of requests){const kind=q.form.kind==='champion'?'hero':q.form.kind,s=available.find(s=>!used.has(s.index)&&s.kind===kind);if(s){used.add(s.index);assignments.push({index:q.index,slot:s.index,kind:s.kind,formId:q.form.id});}}
  for(const q of requests.filter(q=>!assignments.some(a=>a.index===q.index))){const s=available.find(s=>!used.has(s.index)&&s.kind==='wild');if(s){used.add(s.index);assignments.push({index:q.index,slot:s.index,kind:s.kind,formId:q.form.id});}else errors.push({index:q.index,reason:'No eligible form slot'});}
  assignments.sort((a,b)=>a.index-b.index);return{ok:errors.length===0,forms:selected,errors,slots:available,assignments};
 }
 function migrateDeck(deck,raw=[],context={}){
  const selected=selections(deck,raw),positional={...context,positionalSlots:true};
  if(qualify(deck,selected,positional).ok)return{deck:[...deck],forms:selected,changed:false,errors:[]};
  const pairs=deck.map((card,index)=>({card,form:selected[index],original:index})),available=availableSlots(positional).filter(s=>s.index<deck.length),requests=pairs.map(p=>({...p,definition:get(p.form)})).filter(p=>p.definition&&(p.definition.kind==='champion'||!Array.isArray(context.unlockedForms)||context.unlockedForms.includes(p.form))),destinations=[],used=new Set();
  for(const q of requests){const s=available.find(s=>!used.has(s.index)&&s.kind===family(q.definition));if(s){used.add(s.index);destinations.push({original:q.original,slot:s.index});}}
  for(const q of requests.filter(q=>!destinations.some(d=>d.original===q.original))){const s=available.find(s=>!used.has(s.index)&&s.kind==='wild');if(s){used.add(s.index);destinations.push({original:q.original,slot:s.index});}}
  // Track original positions while swapping so two migrations produce identical
  // results even when a selected card initially occupies another target slot.
  for(const d of destinations.sort((a,b)=>a.slot-b.slot)){const at=pairs.findIndex(p=>p.original===d.original);[pairs[d.slot],pairs[at]]=[pairs[at],pairs[d.slot]];}
  const assigned=new Set(destinations.map(d=>d.original));for(const p of pairs)if(!assigned.has(p.original)&&get(p.form)?.kind!=='champion')p.form=null;
  const moved=pairs.map(p=>p.card),forms=pairs.map(p=>p.form),qualified=qualify(moved,forms,positional);return{deck:moved,forms:qualified.forms,changed:moved.some((id,i)=>id!==deck[i])||forms.some((id,i)=>id!==selected[i]),errors:qualified.errors};
 }
 function resolve(card,id){const form=get(id);if(!form||form.baseCardId!==card?.id)return card;const source={...card.source,...form.source},derived=catalog.cardDef({...card,source,cost:source.ManaCost??card.cost},card.level);return {...derived,id:card.id,baseCardId:card.id,formId:form.id,formKind:form.kind,form};}
 const signature=fingerprint({forms:rows,loadouts:declaredPolicy});freeze(byCard);freeze(byId);return Object.freeze({forms:Object.freeze(rows),loadouts:policy,declaredLoadouts:declaredPolicy,fingerprint:signature,get,forCard,champion,selections,qualify,migrateDeck,resolve});
}
const defaultRegistry=createRegistry({forms:K.DATA.forms||[],loadouts:K.DATA.loadouts||{}});
function normalizeInventory(raw,registry=defaultRegistry){const unlocked=[...new Set((Array.isArray(raw?.unlockedForms)?raw.unlockedForms:[]).filter(id=>registry.get(id)&&registry.get(id).kind!=='champion'))],formShards=Object.fromEntries(registry.forms.filter(f=>f.requiredShards>0).map(f=>[f.id,Math.min(f.requiredShards,Math.max(0,Math.floor(Number(raw?.formShards?.[f.id])||0)))]));for(const f of registry.forms)if(f.kind==='evolution'&&f.requiredShards>0&&formShards[f.id]>=f.requiredShards&&!unlocked.includes(f.id))unlocked.push(f.id);return{unlockedForms:unlocked,formShards,evoWildShards:Math.min(999999,Math.max(0,Math.floor(Number(raw?.evoWildShards)||0))),heroCoins:Math.min(9999999,Math.max(0,Math.floor(Number(raw?.heroCoins)||0)))};}
function normalizeDeckForms(raw,decks,modeDeckSets,registry=defaultRegistry){return{ranked:decks.map((d,i)=>registry.selections(d,raw?.ranked?.[i])),modes:Object.fromEntries(Object.entries(modeDeckSets||{}).map(([mode,set])=>[mode,set.decks.map((d,i)=>registry.selections(d,raw?.modes?.[mode]?.[i]))]))};}
function eligibleForms(cardId,index,context={},registry=defaultRegistry){const s=registry.loadouts.slots[index];if(!s||!(context.casual===true&&registry.loadouts.casualSlots===true||Number(context.arena||0)>=s.unlockArena))return[];return registry.forCard(cardId).filter(f=>accepts(s,f)&&(f.kind==='champion'||!Array.isArray(context.unlockedForms)||context.unlockedForms.includes(f.id)));}
function formCapability(id,registry=defaultRegistry){const form=registry.get(id);if(!form)return{ok:false,reason:'Unknown form'};const actions=typeof module==='object'&&module.exports?require('./modern-actions.js'):globalThis.RoyaleModernActions;if(!actions?.canDeployCard)return{ok:false,reason:'Card-form behavior is unavailable'};return actions.canDeployCard(null,registry.resolve(K.cardAt(form.baseCardId,9),id));}
function slotStates(deck,raw=[],context={},registry=defaultRegistry){const selected=registry.selections(deck,raw);return registry.loadouts.slots.map((s,index)=>{const available=context.casual===true&&registry.loadouts.casualSlots===true||Number(context.arena||0)>=s.unlockArena,cardId=deck[index]||null,selectedFormId=selected[index]||null,form=registry.get(selectedFormId),eligibleKinds=s.kind==='wild'?['evolution','hero','champion']:s.kind==='hero'?['hero','champion']:['evolution'];let status=!cardId?'empty':!available?'locked':!selectedFormId?'standard':'active',reason=!available?'Reach Arena '+s.unlockArena+' to use this form slot':'';if(available&&form&&(!accepts(s,form)||form.kind!=='champion'&&Array.isArray(context.unlockedForms)&&!context.unlockedForms.includes(form.id))){status='invalid';reason=!accepts(s,form)?'This form does not fit this slot':'Form is locked';}if(raw[index]&&(!registry.get(raw[index])||registry.get(raw[index]).baseCardId!==cardId)){status='invalid';reason='Form belongs to another card or is unknown';}return{...s,index,available,eligibleKinds,cardId,selectedFormId,status,reason};});}
return{createRegistry,defaultRegistry,DEFAULT_SLOT_TEMPLATE,normalizeInventory,normalizeDeckForms,eligibleForms,slotStates,formCapability,fingerprint};
});
