/* Paged named ranked decks and independent full-catalog casual decks. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./core.js'):root.RoyaleCore);if(n)module.exports=api;else root.RoyaleDeckManager=api;})(globalThis,function(C){'use strict';
const MAX_DECKS=C.MAX_DECKS,PAGE_SIZE=C.DECK_PAGE_SIZE,MODE_DECKS=C.MODE_DECKS;
function add(raw){const p=C.normalizeProfile(raw);if(p.decks.length>=MAX_DECKS)return{ok:false,profile:p,reason:'All '+MAX_DECKS+' deck slots are in use'};p.decks.push([...p.decks[p.activeDeck]]);p.deckNames.push(C.deckName('',p.decks.length-1));p.activeDeck=p.decks.length-1;return{ok:true,profile:p};}
function remove(raw,index){const p=C.normalizeProfile(raw);if(!Number.isInteger(index)||index<0||index>=p.decks.length)return{ok:false,profile:p,reason:'Deck not found'};if(p.decks.length<=1)return{ok:false,profile:p,reason:'Keep at least one battle deck'};p.decks.splice(index,1);p.deckNames.splice(index,1);if(index<p.activeDeck)p.activeDeck--;else if(index===p.activeDeck)p.activeDeck=Math.min(index,p.decks.length-1);return{ok:true,profile:p};}
function rename(raw,index,value){const p=C.normalizeProfile(raw);if(!Number.isInteger(index)||index<0||index>=p.decks.length||typeof value!=='string')return{ok:false,profile:p,reason:'Deck not found'};p.deckNames[index]=C.deckName(value,index);return{ok:true,profile:p};}
function page(raw,index){const decks=Array.isArray(raw?.decks)&&raw.decks.length?raw.decks:[C.DEFAULT_DECK],count=Math.ceil(decks.length/PAGE_SIZE),number=Math.max(0,Math.min(count-1,Number.isFinite(index)?Math.floor(index):Math.floor((raw?.activeDeck||0)/PAGE_SIZE)));return{page:number,count,indices:Array.from({length:Math.min(PAGE_SIZE,decks.length-number*PAGE_SIZE)},(_,i)=>number*PAGE_SIZE+i)};}
function random(raw,seed=1,size=8){const r=C.rng(seed),out=[...C.CARDS];for(let i=out.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out.slice(0,size).map(c=>c.id);}
function modeState(raw,mode){const p=C.normalizeProfile(raw),cfg=MODE_DECKS[mode];if(!cfg)return null;const eligible=C.CARDS.filter(c=>C.allowedInMode(c.id,mode)).map(c=>c.id),deck=[...p[cfg.key]],valid=C.validDeck(deck,{size:cfg.size})&&deck.every(id=>eligible.includes(id));return {...cfg,deck,eligible,eligibleCount:eligible.length,valid,missing:deck.filter(id=>!id).length};}
function setModeCard(raw,mode,slot,id){const p=C.normalizeProfile(raw),state=modeState(p,mode);if(!state||!Number.isInteger(slot)||slot<0||slot>=state.size||!state.eligible.includes(id))return{ok:false,profile:p,reason:'This card is not allowed in this mode'};const deck=p[state.key],other=deck.indexOf(id);if(other>=0&&other!==slot)[deck[slot],deck[other]]=[deck[other],deck[slot]];else deck[slot]=id;return{ok:true,profile:p};}
return{MAX_DECKS,PAGE_SIZE,add,remove,rename,page,random,MODE_DECKS,modeState,setModeCard};});
