/* Paged named ranked decks and independent full-catalog casual deck libraries. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./core.js'):root.RoyaleCore,n?require('./card-forms.js'):root.RoyaleCardForms);if(n)module.exports=api;else root.RoyaleDeckManager=api;})(globalThis,function(C,Forms){'use strict';
const MAX_DECKS=C.MAX_DECKS,PAGE_SIZE=C.DECK_PAGE_SIZE,MODE_DECKS=C.MODE_DECKS;
function add(raw,options={}){const p=C.normalizeProfile(raw,options);if(p.decks.length>=MAX_DECKS)return{ok:false,profile:p,reason:'All '+MAX_DECKS+' deck slots are in use'};p.deckForms.ranked.push([...p.deckForms.ranked[p.activeDeck]]);p.decks.push([...p.decks[p.activeDeck]]);p.deckNames.push(C.deckName('',p.decks.length-1));p.activeDeck=p.decks.length-1;return{ok:true,profile:p};}
function remove(raw,index,options={}){const p=C.normalizeProfile(raw,options);if(!Number.isInteger(index)||index<0||index>=p.decks.length)return{ok:false,profile:p,reason:'Deck not found'};if(p.decks.length<=1)return{ok:false,profile:p,reason:'Keep at least one battle deck'};p.deckForms.ranked.splice(index,1);p.decks.splice(index,1);p.deckNames.splice(index,1);if(index<p.activeDeck)p.activeDeck--;else if(index===p.activeDeck)p.activeDeck=Math.min(index,p.decks.length-1);return{ok:true,profile:p};}
function rename(raw,index,value){const p=C.normalizeProfile(raw);if(!Number.isInteger(index)||index<0||index>=p.decks.length||typeof value!=='string')return{ok:false,profile:p,reason:'Deck not found'};p.deckNames[index]=C.deckName(value,index);return{ok:true,profile:p};}
function page(raw,index){const decks=Array.isArray(raw?.decks)&&raw.decks.length?raw.decks:[C.DEFAULT_DECK],count=Math.ceil(decks.length/PAGE_SIZE),number=Math.max(0,Math.min(count-1,Number.isFinite(index)?Math.floor(index):Math.floor((raw?.activeDeck||0)/PAGE_SIZE)));return{page:number,count,indices:Array.from({length:Math.min(PAGE_SIZE,decks.length-number*PAGE_SIZE)},(_,i)=>number*PAGE_SIZE+i)};}
function random(raw,seed=1,size=8){const r=C.rng(seed),out=[...C.CARDS];for(let i=out.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out.slice(0,size).map(c=>c.id);}
function modeSet(p,mode){const cfg=MODE_DECKS[mode];if(!cfg)return null;const set=p.modeDeckSets?.[mode]||{active:0,decks:[p[cfg.key]],names:['Deck 1']};return{cfg,set};}
function modeState(raw,mode){const p=C.normalizeProfile(raw),m=modeSet(p,mode);if(!m)return null;const {cfg,set}=m,eligible=C.CARDS.filter(c=>C.allowedInMode(c.id,mode)).map(c=>c.id),active=Math.max(0,Math.min(set.decks.length-1,set.active||0)),deck=[...set.decks[active]],duplicates=p.cheats.duplicates,valid=C.validDeck(deck,{size:cfg.size,duplicates})&&deck.every(id=>eligible.includes(id));return {...cfg,deck,eligible,eligibleCount:eligible.length,valid,duplicates,missing:deck.filter(id=>!id).length,active,decks:set.decks.map(d=>[...d]),names:[...set.names],page:Math.floor(active/PAGE_SIZE),pageCount:Math.ceil(set.decks.length/PAGE_SIZE)};}
function syncMode(p,mode){const cfg=MODE_DECKS[mode],set=p.modeDeckSets[mode];p[cfg.key]=[...set.decks[set.active]];}
function formContext(p,mode,options){return{arena:options.arena??C.arenaNumber(p),casual:options.casual??mode!=='ranked',unlockedForms:p.unlockedForms,positionalSlots:options.positionalSlots===true||options.positionalSlots!==false&&p.positionalSlotsVersion===1};}
function commitCards(p,mode,index,deck,selected,changed,options={}){const r=options.formRegistry||Forms.defaultRegistry,context=formContext(p,mode,options);if(context.positionalSlots){for(const slot of changed){const candidates=Forms.eligibleForms(deck[slot],slot,context,r).filter(f=>Forms.formCapability(f.id,r).ok),old=r.get(selected[slot]);if(old?.kind!=='champion'&&!candidates.some(f=>f.id===old?.id))selected[slot]=null;if(!selected[slot]&&options.autoSelectForms!==false)selected[slot]=(candidates.find(f=>f.kind==='evolution')||candidates.find(f=>f.kind==='hero')||candidates[0])?.id||null;}if(Object.hasOwn(options,'formId')){if(options.formId){const support=Forms.formCapability(options.formId,r);if(!support.ok)return{ok:false,profile:p,reason:'Unavailable for battle: '+support.reason};}selected[options.targetSlot]=options.formId;}const q=r.qualify(deck,selected,context);if(!q.ok)return{ok:false,profile:p,reason:q.errors[0].reason};selected=q.forms;}else if(Object.hasOwn(options,'formId')){selected[options.targetSlot]=options.formId;const q=r.qualify(deck,selected,context);if(!q.ok)return{ok:false,profile:p,reason:q.errors[0].reason};selected=q.forms;}if(mode==='ranked'){p.decks[index]=deck;p.deckForms.ranked[index]=selected;}else{p.modeDeckSets[mode].decks[index]=deck;p.deckForms.modes[mode][index]=selected;syncMode(p,mode);}return{ok:true,profile:p};}
function setModeCard(raw,mode,slot,id,options={}){const p=C.normalizeProfile(raw,options),state=modeState(p,mode);if(!state||!Number.isInteger(slot)||slot<0||slot>=state.size||!state.eligible.includes(id))return{ok:false,profile:p,reason:'This card is not allowed in this mode'};const set=p.modeDeckSets[mode],deck=[...set.decks[set.active]],other=deck.indexOf(id),selected=[...p.deckForms.modes[mode][set.active]],changed=[slot];if(!state.duplicates&&other>=0&&other!==slot){[deck[slot],deck[other]]=[deck[other],deck[slot]];[selected[slot],selected[other]]=[selected[other],selected[slot]];changed.push(other);}else{deck[slot]=id;selected[slot]=(options.formRegistry||Forms.defaultRegistry).champion(id)?.id||null;}return commitCards(p,mode,set.active,deck,selected,changed,{...options,targetSlot:slot});}
function modeAdd(raw,mode,options={}){const p=C.normalizeProfile(raw,options),m=modeSet(p,mode);if(!m)return{ok:false,profile:p,reason:'Mode deck not found'};const set=p.modeDeckSets[mode];if(set.decks.length>=MAX_DECKS)return{ok:false,profile:p,reason:'All '+MAX_DECKS+' deck slots are in use'};p.deckForms.modes[mode].push([...p.deckForms.modes[mode][set.active]]);set.decks.push([...set.decks[set.active]]);set.names.push(C.deckName('',set.decks.length-1));set.active=set.decks.length-1;syncMode(p,mode);return{ok:true,profile:p};}
function modeRemove(raw,mode,index,options={}){const p=C.normalizeProfile(raw,options),m=modeSet(p,mode);if(!m)return{ok:false,profile:p,reason:'Mode deck not found'};const set=p.modeDeckSets[mode];if(set.decks.length<=1)return{ok:false,profile:p,reason:'Keep at least one deck'};if(!Number.isInteger(index)||index<0||index>=set.decks.length)return{ok:false,profile:p,reason:'Deck not found'};p.deckForms.modes[mode].splice(index,1);set.decks.splice(index,1);set.names.splice(index,1);set.active=Math.min(set.active,index,set.decks.length-1);syncMode(p,mode);return{ok:true,profile:p};}
function modeRename(raw,mode,index,value){const p=C.normalizeProfile(raw),m=modeSet(p,mode);if(!m||!Number.isInteger(index)||index<0||index>=p.modeDeckSets[mode].decks.length)return{ok:false,profile:p,reason:'Deck not found'};p.modeDeckSets[mode].names[index]=C.deckName(value,index);return{ok:true,profile:p};}
function modeSelect(raw,mode,index){const p=C.normalizeProfile(raw),m=modeSet(p,mode);if(!m||!Number.isInteger(index)||index<0||index>=p.modeDeckSets[mode].decks.length)return{ok:false,profile:p,reason:'Deck not found'};p.modeDeckSets[mode].active=index;syncMode(p,mode);return{ok:true,profile:p};}
function modePage(raw,mode,pageIndex){const p=C.normalizeProfile(raw),m=modeSet(p,mode);if(!m)return null;const set=p.modeDeckSets[mode],count=Math.ceil(set.decks.length/PAGE_SIZE),pg=Math.max(0,Math.min(count-1,Number(pageIndex)||0));return{page:pg,count,indices:Array.from({length:Math.min(PAGE_SIZE,set.decks.length-pg*PAGE_SIZE)},(_,i)=>pg*PAGE_SIZE+i)};}
function setCard(raw,slot,id,options={}){const p=C.normalizeProfile(raw,options),index=options.deckIndex??p.activeDeck,original=p.decks[index];if(!original||!Number.isInteger(slot)||slot<0||slot>=original.length||!C.canUseCard(p,id))return{ok:false,profile:p,reason:'This card is not available'};const deck=[...original],selected=[...p.deckForms.ranked[index]],other=deck.indexOf(id),changed=[slot];if(!p.cheats.duplicates&&other>=0&&other!==slot){[deck[slot],deck[other]]=[deck[other],deck[slot]];[selected[slot],selected[other]]=[selected[other],selected[slot]];changed.push(other);}else{deck[slot]=id;selected[slot]=(options.formRegistry||Forms.defaultRegistry).champion(id)?.id||null;}return commitCards(p,'ranked',index,deck,selected,changed,{...options,targetSlot:slot});}
function swapCards(raw,{mode='ranked',deckIndex,from,to,...options}={}){const p=C.normalizeProfile(raw,options),set=mode==='ranked'?{decks:p.decks,active:p.activeDeck}:p.modeDeckSets[mode],index=deckIndex??set?.active,original=set?.decks[index];if(!original||![from,to].every(i=>Number.isInteger(i)&&i>=0&&i<original.length))return{ok:false,profile:p,reason:'Deck slot not found'};const deck=[...original],selected=[...(mode==='ranked'?p.deckForms.ranked:p.deckForms.modes[mode])[index]];[deck[from],deck[to]]=[deck[to],deck[from]];[selected[from],selected[to]]=[selected[to],selected[from]];return commitCards(p,mode,index,deck,selected,[from,to],options);}
function setForm(raw,{mode='ranked',deckIndex,slot,formId=null,formRegistry=Forms.defaultRegistry,arena,casual,positionalSlots}={}){const p=C.normalizeProfile(raw,{formRegistry,positionalSlots}),set=mode==='ranked'?{decks:p.decks,active:p.activeDeck}:p.modeDeckSets[mode],index=deckIndex??set?.active,deck=set?.decks[index],bank=mode==='ranked'?p.deckForms.ranked:p.deckForms.modes[mode];if(!deck||!Number.isInteger(slot)||slot<0||slot>=deck.length)return{ok:false,profile:p,reason:'Deck slot not found'};if(formId){const support=Forms.formCapability(formId,formRegistry);if(!support.ok)return{ok:false,profile:p,reason:'Unavailable for battle: '+support.reason};}const selected=[...bank[index]];selected[slot]=formId;const qualified=formRegistry.qualify(deck,selected,formContext(p,mode,{arena,casual,positionalSlots}));if(!qualified.ok)return{ok:false,profile:p,reason:qualified.errors[0].reason};bank[index]=qualified.forms;return{ok:true,profile:p};}
return{MAX_DECKS,PAGE_SIZE,setCard,setForm,swapCards,add,remove,rename,page,random,MODE_DECKS,modeState,setModeCard,modeAdd,modeRemove,modeRename,modeSelect,modePage};});
