/* Per-match counters and unit-owned ability lifetimes; no content is registered here. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./card-forms.js'):root.RoyaleCardForms);if(n)module.exports=api;else root.RoyaleFormState=api;})(globalThis,function(Forms){'use strict';
const EPS=1e-7,seconds=x=>Math.max(0,Number(x)||0)/1000;
function setup(b,options){b.formRegistry=options.formRegistry||Forms.defaultRegistry;const context={arena:Number(options.arenaNumber)||Number(options.formContext?.arena)||1,casual:!!(b.practice||b.queueType&&b.queueType!=='trophy-road'),...options.formContext};b.formContext=context;const primary=options.seatForms?.[0]||options.forms||(b.queueType&&b.queueType!=='trophy-road'?b.profile.deckForms?.modes?.[b.mode]?.[b.profile.modeDeckSets?.[b.mode]?.active||0]:b.profile.deckForms?.ranked?.[b.profile.activeDeck]);b.seatForms=b.initialDecks.map((deck,seat)=>{const raw=options.seatForms?.[seat]||(seat===0?primary:(b.formRegistry===Forms.defaultRegistry?options.botForms:undefined)?.(deck,{arena:options.botArena||context.arena,casual:context.casual,seed:b.seed+seat*193})||[]),qualified=b.formRegistry.qualify(deck,raw,{...context,unlockedForms:seat===0?(options.formContext?.unlockedForms||b.profile.unlockedForms):undefined});if(!qualified.ok)throw Error('Invalid form loadout: '+qualified.errors.map(e=>e.reason).join(', '));return qualified.forms;});b.formState={cycles:b.initialDecks.map(d=>d.map(()=>0))};}
function resolveCard(b,seat,slot,card){
 if(!card)return card;
 const options=card.source?.Options;if(Array.isArray(options)&&options.length){const mana=b.elixir[seat]*1000,choice=[...options].sort((a,z)=>(z.AvailableManaTrigger||0)-(a.AvailableManaTrigger||0)).find(o=>mana+EPS>=(o.AvailableManaTrigger||0))||[...options].sort((a,z)=>(a.AvailableManaTrigger||0)-(z.AvailableManaTrigger||0))[0],source=choice&&b.catalog?.DATA.spellVariants?.[choice.SpellData];if(source)card=b.catalog.cardDef({...card,source:{...card.source,...source},cost:source.ManaCost??choice.AvailableManaTrigger/1000},card.level);}
 const deckSlot=b.handSlots?.[seat]?.[slot],form=b.formRegistry.get(b.seatForms?.[seat]?.[deckSlot]);if(!form)return card;const count=b.formState.cycles[seat][deckSlot]||0;if(form.kind==='evolution'&&count<form.cycles)return{...card,selectedFormId:form.id,evolutionCharge:count,evolutionCycles:form.cycles,deckSlot};return{...b.formRegistry.resolve(card,form.id),selectedFormId:form.id,evolutionCharge:count,evolutionCycles:form.cycles,deckSlot};
}
function commitDeploy(b,seat,card){const form=b.formRegistry.get(card?.selectedFormId);if(form?.kind==='evolution'){const index=card.deckSlot;b.formState.cycles[seat][index]=card.formId===form.id?0:(b.formState.cycles[seat][index]||0)+1;}}
function attach(b,u,card){const form=card?.form,config=form?.ability;if(!config)return;if(form.abilityCharacter&&form.abilityCharacter!==u.entity)return;if(!form.abilityCharacter&&card.source.LinkedChampionCharacter&&card.source.LinkedChampionCharacter!==u.entity)return;u.formId=form.id;u.abilityConfig=config;const support=b.modernActions?.canExecuteAbility?.(b,config,{unit:u,owner:u.owner,team:u.team,formId:form.id});u.abilitySupport=support||{ok:!config.OnActivationAction,reason:config.OnActivationAction?'Ability action is unavailable':null};u.abilityState={charges:config.MaxCharges===undefined?null:config.MaxCharges,cooldownUntil:u.readyAt||b.time,castingUntil:0,triggerAt:0,pending:false,activation:0};}
function status(b,u){if(!u?.abilityState)return null;const s=u.abilityState,override=s.sourceOverride,sourceTags=b.modernActions?.tags?.(u,b.time),sourceDisabled=sourceTags?.has('ABILITY_DISABLED')||override&&['AllChargesConsumed','ChampionAbsent','ChampionPending','OnCooldown','Disabled','NoYetAvailable'].includes(override.state)&&(override.until===undefined||override.until>b.time+EPS),alive=b.isPresent(u)&&!u.dead,stopped=b.buffs(u),ready=alive&&u.abilitySupport?.ok!==false&&!sourceDisabled&&!b.paused&&!b.result&&!b.tiebreaker&&b.time+EPS>=(u.readyAt||0)&&!s.pending&&b.time+EPS>=s.castingUntil&&b.time+EPS>=s.cooldownUntil&&(s.charges===null||s.charges>0)&&!!(stopped.speed||stopped.attack);return{...s,ready,supported:u.abilitySupport?.ok!==false,unsupportedReason:u.abilitySupport?.ok===false?u.abilitySupport.reason:null,cost:Number(u.abilityConfig.ManaCost)||0,entityId:u.id,owner:u.owner,formId:u.formId,abilityId:u.abilityConfig.id||null};}
function activate(b,seat,id){if(!Number.isInteger(seat)||b.teamOf(seat)<0||!Number.isSafeInteger(id))return{ok:false,reason:'Invalid ability command'};const u=b.getEntity(id),state=status(b,u);if(!u||u.owner!==seat||!state)return{ok:false,reason:'This unit has no owned ability'};if(!state.ready)return{ok:false,reason:'Ability is not ready'};if(b.elixir[seat]+EPS<state.cost)return{ok:false,reason:'Not enough elixir'};const actions=b.modernActions,config=u.abilityConfig,preflight=actions?.canExecuteAbility?.(b,config,{unit:u,owner:seat,team:u.team,formId:u.formId});if(preflight&&preflight.ok===false)return preflight;if(config.OnActivationAction&&!actions?.executeAbility)return{ok:false,reason:'Ability action is unavailable'};
 const s=u.abilityState;s.pending=true;s.triggerAt=b.time+seconds(config.TriggerDelay);s.castingUntil=b.time+seconds(config.CastTime);s.cooldownUntil=b.time+seconds(config.Cooldown);s.activation++;if(s.charges!==null)s.charges--;if(!(seat===0&&b.cheats.elixir)){b.elixir[seat]=Math.max(0,b.elixir[seat]-state.cost);b.metrics.spent[seat]+=state.cost;}u.windup=null;u.visualState='ability';u.visualStarted=b.time;u.animationTime=0;actions?.beginAbility?.(b,config,{unit:u,owner:seat,team:u.team,formId:u.formId});b.record({type:'ability',seat,owner:seat,team:u.team,entityId:u.id,abilityId:config.id||null,formId:u.formId,cost:state.cost});tickUnit(b,u,0);return{ok:true,entityId:u.id,abilityId:config.id||null};
}
function cancel(b,u){if(!u?.abilityState)return;b.modernActions?.endPendingAbility?.(b,u.abilityConfig,{unit:u});u.abilityState.pending=false;}
function tickUnit(b,u,dt){const s=u.abilityState;if(!s)return false;if(!b.isPresent(u)||u.dead){cancel(b,u);return false;}const tags=b.modernActions?.tags?.(u,b.time);if(tags?.has('ABILITY_COOLDOWN_PAUSED')&&(s.charges===null||s.charges>0||s.pending)&&s.cooldownUntil>b.time-dt+EPS)s.cooldownUntil+=dt;const rates=b.buffs(u);if(!rates.speed&&!rates.attack){if(s.pending)s.triggerAt+=dt;if(s.castingUntil>b.time-dt)s.castingUntil+=dt;return s.pending||s.castingUntil>b.time+EPS;}if(s.pending&&b.time+EPS>=s.triggerAt){s.pending=false;b.modernActions?.endPendingAbility?.(b,u.abilityConfig,{unit:u});const ctx={unit:u,owner:u.owner,team:u.team,targetId:u.targetId,formId:u.formId};if(b.modernActions?.executeAbility)b.modernActions.executeAbility(b,u.abilityConfig,ctx);else{const c=u.abilityConfig;if(c.Buff)b.addBuff(u,c.Buff,seconds(c.BuffTime),u.team,u.level);if(c.AreaEffectObject)b.createArea(c.AreaEffectObject,u.team,u.x,u.y,u.level);}}
 if(s.castingUntil>b.time+EPS){u.visualState='ability';return true;}if(u.visualState==='ability'){u.visualState='idle';u.visualStarted=b.time;u.animationTime=0;}return false;
}
return{setup,resolveCard,commitDeploy,attach,status,activate,tickUnit,cancel};
});
