/* Card-form inventory transactions. Source unlock amounts; no payment requests. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./catalog.js'):root.RoyaleCatalog,n?require('./card-forms.js'):root.RoyaleCardForms);if(n)module.exports=api;else root.RoyaleModernRewards=api;})(globalThis,function(K,Forms){'use strict';
const registry=Forms.defaultRegistry;
function addHeroCoins(p,count){const amount=Math.max(0,Math.floor(Number(count)||0)),before=p.heroCoins||0;p.heroCoins=Math.min(200,before+amount);p.gems=Math.min(9999999,(p.gems||0)+Math.max(0,before+amount-200));return amount;}
function addShards(p,id,count){const form=registry.get(id);if(!form||form.kind!=='evolution')return false;const n=Math.max(0,Math.floor(Number(count)||0));p.formShards||={};p.formShards[id]=Math.min(form.requiredShards,(p.formShards[id]||0)+n);return true;}
function unlock(p,id,{wild=false}={}){const form=registry.get(id);if(!form||form.kind==='champion')return{ok:false,reason:'Choose a Hero or Evolution'};if(p.unlockedForms?.includes(id))return{ok:false,reason:'Already unlocked'};if(form.kind==='hero'){if((p.heroCoins||0)<form.requiredShards)return{ok:false,reason:'Requires '+form.requiredShards+' Hero Coins'};p.heroCoins-=form.requiredShards;}else{const have=p.formShards?.[id]||0,need=Math.max(0,form.requiredShards-have);if(need>0&&(!wild||(p.evoWildShards||0)<need))return{ok:false,reason:'Requires '+form.requiredShards+' Evolution Shards'};p.evoWildShards=(p.evoWildShards||0)-need;p.formShards||={};p.formShards[id]=form.requiredShards;}p.unlockedForms||=[];p.unlockedForms.push(id);return{ok:true,form};}
function consumable(item,amount){const rarity=String(item).match(/^Wildcard(Common|Rare|Epic|Legendary|Champion)$/)?.[1];if(rarity)return{wildcards:{[rarity]:amount}};if(/Hero/i.test(item))return{heroCoins:amount};if(/Evolution|EvoShard/i.test(item))return{evoWildShards:amount};const book=String(item).match(/^Book(Common|Rare|Epic|Legendary)$/)?.[1];if(book)return{magicItems:{[book.toLowerCase()+'-book']:amount}};return null;}
function randomFor(seed){let h=2166136261;for(const c of String(seed))h=Math.imul(h^c.charCodeAt(0),16777619);return()=>{h|=0;h=h+0x6D2B79F5|0;let t=Math.imul(h^h>>>15,1|h);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
function pick(rows,random){const total=rows.reduce((s,r)=>s+Math.max(0,Number(r.weight)||0),0);if(!total)return null;let n=random()*total;for(const r of rows){n-=Math.max(0,Number(r.weight)||0);if(n<0)return r.value;}return rows.at(-1)?.value;}
function mergeRewards(a,b){for(const key of ['gold','gems','heroCoins','evoWildShards'])a[key]=(a[key]||0)+(b[key]||0);for(const key of ['wildcards','magicItems','formShards','towerTroops'])for(const [id,n]of Object.entries(b[key]||{})){a[key]||={};a[key][id]=(a[key][id]||0)+n;}for(const key of ['cards','sourceCosmetics','unlockedForms'])if(b[key]){a[key]||=[];a[key].push(...b[key]);}return a;}
function poolReward(row,random,profile,arena){const amount=row.Amount||1;
 if(row.CardEvoShards){const form=registry.forms.find(f=>f.kind==='evolution'&&f.source.Name.startsWith(row.CardEvoShards+'_'));return form?{formShards:{[form.id]:amount}}:null;}
 if(row.HeroForm){const form=registry.forms.find(f=>f.kind==='hero'&&(f.id===row.HeroForm||f.source.Name===row.HeroForm));return form?{unlockedForms:[form.id]}:null;}
 if(row.Consumables)return consumable(row.Consumables,amount);
 if(row.Resource)return row.Resource==='Gold'?{gold:amount}:row.Resource==='Diamonds'?{gems:amount}:null;
 if(row.Cards){const card=K.CARDS.find(c=>c.source.Name===row.Cards);return card?{cards:[{id:card.id,count:amount}]}:null;}
 if(row.SpellRarity){const pool=K.CARDS.filter(c=>c.rarity===row.SpellRarity);const card=pool[Math.floor(random()*pool.length)];return card?{cards:[{id:card.id,count:amount}]}:null;}
 for(const key of ['Banners','Emotes','TowerSkins','AlbumSnippets'])if(row[key])return{sourceCosmetics:[{kind:key,id:row[key],count:amount}]};return null;
}
function mysteryBox(name,{profile={},arenaNumber=1,seed='',random=randomFor(seed)}={}){const m=K.DATA.modernProgression,box=m?.mysteryBoxes?.[name];if(!box||!Array.isArray(box.Rarities)||!box.Rarities.length)return{ok:false,reason:'Unknown reward chest'};let rank=0;for(let i=0;i<(box.SpinCount||0);i++)if(rank<box.Rarities.length-1&&random()*100<(box.UpgradeProbabilities?.[rank]||0))rank++;
 const rarityId=box.Rarities[rank],rarity=m.mysteryRarities[rarityId],arena=m.arenas.find(a=>a.number===arenaNumber)||m.arenas[0],rows=m.mysteryArenaRows.filter(r=>r.Rarity===(rarity?.ArenaData||rarityId)),amounts=rows.find(r=>r.Arena===arena.sourceName)||rows.find(r=>r.Arena==='TrainingCamp');if(!rarity||!amounts)return{ok:false,reason:'Reward chest data unavailable'};
 const categories=['Gold','RandomCard','ItemPool','WildcardCommon','WildcardRare','WildcardEpic','WildcardLegendary','WildcardChampion','WildcardShard','FullEvolution','HeroCoin','Gems','BookCardCommon','BookCardRare','BookCardEpic','BookCardLegendary','BookCardAll','Emote'],kind=pick(categories.filter(k=>rarity[k]>0).map(k=>({value:k,weight:rarity[k]})),random);let reward=null;
 if(kind==='Gold')reward={gold:amounts.Gold||0};else if(kind==='Gems')reward={gems:amounts.Gems||0};else if(kind==='HeroCoin')reward={heroCoins:amounts.HeroCoin||0};else if(kind==='WildcardShard')reward={evoWildShards:amounts.WildcardShard||0};else if(kind?.startsWith('Wildcard'))reward=consumable(kind,amounts[kind]||0);
 else if(kind?.startsWith('BookCard'))reward={magicItems:{[kind==='BookCardAll'?'all-book':kind.slice(8).toLowerCase()+'-book']:amounts[kind]||1}};
 else if(kind==='ItemPool'){const pool=m.itemPoolRows.filter(r=>r.PoolName===amounts.ItemPool),row=pick(pool.map(r=>({value:r,weight:r.Weight})),random);reward=row&&poolReward(row,random,profile,arena);}
 else if(kind==='FullEvolution'){const forms=registry.forms.filter(f=>f.kind==='evolution'&&!profile.unlockedForms?.includes(f.id)),form=forms[Math.floor(random()*forms.length)];reward=form?{formShards:{[form.id]:6}}:{evoWildShards:6};}
 else if(kind==='RandomCard'){const options=['Common','Rare','Epic','Legendary','Champion'].flatMap(r=>[{value:{type:'card',rarity:r},weight:rarity['Card'+r]||0},{value:{type:'support',rarity:r},weight:rarity['SupportCard'+r]||0}]),selection=pick(options,random);if(selection?.type==='card'){const eligible=K.CARDS.filter(c=>c.rarity===selection.rarity&&(!K.DATA.arenas.find(a=>a.Name===c.arena)||K.DATA.arenas.find(a=>a.Name===c.arena).Arena<=arenaNumber));const c=pick(eligible.map(c=>({value:c,weight:profile.unlockedCards?.includes(c.id)?1:Number(rarity.CardNewWeightFactor)||1})),random);if(c)reward={cards:[{id:c.id,count:Math.max(1,Math.floor((amounts['Card'+selection.rarity]||1)*((rarity.CardAmountMinFactor||1)+random()*((rarity.CardAmountMaxFactor||1)-(rarity.CardAmountMinFactor||1))))) }]};}else if(selection){const pool=Object.entries(m.supportCards).filter(([,r])=>!r.NotInUse&&!r.NotVisible&&r.Rarity===selection.rarity),entry=pool[Math.floor(random()*pool.length)];if(entry)reward={towerTroops:{[entry[0]]:amounts['SupportCard'+selection.rarity]||1}};}}
 if(!reward)return{ok:false,reason:'This chest reward is not available yet'};return{ok:true,reward,box:name,rarity:rarityId,rank};}
return{addHeroCoins,addShards,unlock,consumable,mysteryBox,mergeRewards};
});
