/* Source-authored 16.402.2 action interpreter. Unsupported graphs fail before
   mutation. Native-only controllers remain explicitly unsupported. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./catalog.js'):root.RoyaleCatalog,n?require('./navigation.js'):root.RoyaleNavigation);if(n)module.exports=api;else root.RoyaleModernActions=api;})(globalThis,function(K,Nav){'use strict';
const EPS=1e-7,MAX_STEPS=256,MAX_DEPTH=64,SX=K.SX,SY=K.SY;
const ModernSpells=K.DATA.modernProgression&&(typeof module==='object'&&module.exports?require('./modern-spells.js'):globalThis.RoyaleModernSpells);
const Resolvers=typeof module==='object'&&module.exports?require('./source-resolvers.js'):globalThis.RoyaleSourceResolvers;
const list=v=>Array.isArray(v)?v:v===undefined||v===null||v===''?[]:[v];
const flags=v=>list(v).flatMap(x=>String(x).split(',')).map(x=>x.trim()).filter(Boolean);
const ms=v=>Math.max(0,Number(v)||0)/1000;
const dataFor=c=>c?.data||K.DATA;
const state=u=>u.modernActions||(u.modernActions={variables:{},timers:[],tags:[],listeners:[],serial:0});
const alive=u=>!!u&&u.hp!==0&&!u.dead;
const distance=(a,b)=>Math.hypot((a.x-b.x)/SX,(a.y-b.y)/SY);
const direction=t=>t===0?-1:1;
const SUBJECTS=new Set(['x','y','map_width','hp','max_hp','shield_hp','max_shield_hp','team_index','owner_index','source_team_index','level','is_clone','is_active_or_secondary_champion','ability_charges_left','target_distance','target_hp','target_max_hp','is_kamikazing','is_moving','is_deploying','target_is_ground','is_dodging_damage','is_combat_enabled','#damage','#hp']);
const BUILTIN_TAGS=new Set(['ATTACKING','DASHING','MOVING','WARP','COMBAT_DISABLED','CAPTURED','NO_MOVE','NO_ATTACK','NO_MOVE_ALLOW_ATTRACT','UNKILLABLE','DEFLECTING_PROJECTILES','INACTIVE','ACTIVATING','ABILITY_PENDING','ABILITY_COOLDOWN_PAUSED','ABILITY_CASTED','CASTING_ABILITY']);
const MATH_FUNCTIONS={as_int:Math.trunc,as_float:Number,min:Math.min,max:Math.max,abs:Math.abs,floor:Math.floor,ceil:Math.ceil,sqrt:Math.sqrt,clamp:(n,a,b)=>Math.max(a,Math.min(b,n)),select:(condition,yes,no)=>condition?yes:no};
const exprCache=new Map(),tagCache=new WeakMap();
function knownTags(data){if(tagCache.has(data))return tagCache.get(data);const out=new Set(BUILTIN_TAGS);for(const table of [data.actions,data.buffs,data.entities])for(const r of Object.values(table||{}))for(const key of ['GameTagsToSet','GameTagsWhileAbilityActive','GameTagsToSetOnToAirState','GameTagsToSetOnToGroundState'])for(const tag of flags(r[key]))out.add(tag);tagCache.set(data,out);return out;}
function tokenize(text){const tokens=[];let i=0;while(i<text.length){if(/\s/.test(text[i])){i++;continue;}const part=text.slice(i),number=/^(?:\d+(?:\.\d*)?|\.\d+)/.exec(part),name=/^#?[A-Za-z_][A-Za-z_0-9]*/.exec(part),operator=/^(?:&&|\|\||==|!=|<=|>=|[()+\-*/%!,<>?:])/.exec(part);if(number){tokens.push({type:'number',value:Number(number[0])});i+=number[0].length;}else if(name){tokens.push({type:'name',value:name[0]});i+=name[0].length;}else if(operator){tokens.push({type:'op',value:operator[0]});i+=operator[0].length;}else throw Error('Invalid source expression token');if(tokens.length>256)throw Error('Unsupported source expression length');}return tokens;}
const precedence={'||':1,'&&':2,'==':3,'!=':3,'<':4,'>':4,'<=':4,'>=':4,'+':5,'-':5,'*':6,'/':6,'%':6};
function parseExpression(text){if(typeof text==='number'||typeof text==='boolean')return{kind:'literal',value:text};if(typeof text!=='string'||!text.trim())throw Error('Invalid source expression');if(exprCache.has(text))return exprCache.get(text);const tokens=tokenize(text);let pos=0,depth=0;
 function read(min=0){if(++depth>MAX_DEPTH)throw Error('Unsupported expression nesting');let token=tokens[pos++],left;if(!token)throw Error('Invalid incomplete source expression');if(token.type==='number')left={kind:'literal',value:token.value};else if(['!','-','+'].includes(token.value))left={kind:'unary',op:token.value,value:read(7)};else if(token.value==='('){left=read();if(tokens[pos++]?.value!==')')throw Error('Invalid expression parentheses');}else if(token.type==='name'){if(tokens[pos]?.value==='('){pos++;const args=[];if(tokens[pos]?.value!==')'){do{args.push(read());if(tokens[pos]?.value!==',')break;pos++;}while(true);}if(tokens[pos++]?.value!==')')throw Error('Invalid function arguments');left={kind:'call',name:token.value,args};}else left={kind:'name',name:token.value};}else throw Error('Invalid source expression');while(tokens[pos]&&precedence[tokens[pos].value]>=min){const op=tokens[pos++].value;left={kind:'binary',op,left,right:read(precedence[op]+1)};}if(min===0&&tokens[pos]?.value==='?'){pos++;const yes=read();if(tokens[pos++]?.value!==':')throw Error('Invalid conditional expression');left={kind:'conditional',condition:left,yes,no:read()};}depth--;return left;}
 const ast=read();if(pos!==tokens.length)throw Error('Invalid trailing expression tokens');if(exprCache.size>=512)exprCache.delete(exprCache.keys().next().value);exprCache.set(text,ast);return ast;
}
const contextCache=new WeakMap();
function contextInfo(data){if(contextCache.has(data))return contextCache.get(data);const keys=new Set(['damage','hp']),defaults={};for(const r of Object.values(data.actions||{})){for(const field of ['HitpointsKey','ShieldHitpointsKey','DamageKey','Key','ContextKey','ResultName','WarpWindowActiveKey','WarpWindowOriginXKey','WarpWindowOriginYKey'])if(typeof r[field]==='string')keys.add(r[field]);if(r.ClassType==='ActionWriteResolverResultToContext'&&r.ResultName)defaults[r.ResultName]=r.DefaultValue??-1;}const info={keys,defaults};contextCache.set(data,info);return info;}
const contextKeys=data=>contextInfo(data).keys;
function validateAst(ast,data){if(ast.kind==='name'){if(!['true','false'].includes(ast.name)&&!SUBJECTS.has(ast.name)&&!(ast.name.startsWith('#')&&contextKeys(data).has(ast.name.slice(1)))&&!Object.hasOwn(data.variables||{},ast.name)&&!knownTags(data).has(ast.name))throw Error('Unknown source variable '+ast.name);}else if(ast.kind==='call'){if(ast.name==='has_data'){if(ast.args.length!==1||ast.args[0].kind!=='name'||![data.entities,data.areas,data.projectiles].some(t=>t?.[ast.args[0].name]))throw Error('Unknown has_data source');return;}if(!MATH_FUNCTIONS[ast.name]&&!['target_in_range','team_y_direction','has_buff','get_radius','is_clone','HAS_SHIELD','is_valid_position','is_moving','has_crown_tower_in_range','should_hide'].includes(ast.name)&&!knownTags(data).has(ast.name))throw Error('Unsupported source function '+ast.name);if(ast.name==='has_buff'){if(ast.args.length!==1||ast.args[0].kind!=='name'||!data.buffs?.[ast.args[0].name])throw Error('Unknown has_buff source');return;}for(const x of ast.args)validateAst(x,data);}else for(const value of Object.values(ast))if(value&&typeof value==='object'&&!Array.isArray(value))validateAst(value,data);}
function tags(u,time){const s=u?.modernActions,out=new Set();if(u?.abilityState?.pending)out.add('ABILITY_PENDING');if(u?.abilityState?.pending||(u?.abilityState?.castingUntil||0)>time+EPS)out.add('CASTING_ABILITY');if(u?.windup)out.add('ATTACKING');if(u?.dash||u?.modernDash||u?.modernGuardDash)out.add('DASHING');for(const entry of s?.tags||[])if(entry.until>time+EPS)for(const tag of entry.tags)out.add(tag);return out;}
function values(b,c){const u=c.unit||b.getEntity?.(c.sourceId),source=c.instigator||b.getEntity?.(c.instigatorId)||u,target=c.target||b.getEntity?.(c.targetId??u?.targetId),d=dataFor(c),s=u?state(u):{variables:{}};const tagSet=tags(u,b.time);if(u?.windup)tagSet.add('ATTACKING');if(u?.dash)tagSet.add('DASHING');if(u?.drag)tagSet.add('MOVING');if(u?.modernWarpUntil>b.time)tagSet.add('WARP');if(u?.hidden)tagSet.add('CAPTURED');for(const {record}of activeBuffs(b,u,d))for(const tag of flags(record.GameTagsToSet))tagSet.add(tag);return{u,source,target,data:d,state:s,tags:tagSet,context:c.context||{},
  map_width:18000,x:(u?.x||0)/SX*1000,y:(u?.y||0)/SY*1000,hp:u?.hp||0,max_hp:u?.maxHp||0,shield_hp:u?.shield||0,max_shield_hp:u?.maxShield||0,team_index:u?.team??c.team??0,owner_index:u?.owner??c.owner??0,source_team_index:source?.team??c.team??0,level:u?.level??c.level??9,is_clone:!!u?.cloned,is_combat_enabled:!tagSet.has('COMBAT_DISABLED')&&!tagSet.has('CAPTURED'),is_dodging_damage:tagSet.has('NO_DAMAGE')||tagSet.has('DASHING'),is_active_or_secondary_champion:!!u?.abilityState||!!u?.def?.source?.Ability,ability_charges_left:u?.abilityState?.remainingCharges??u?.abilityState?.charges??b.getEntity?.(u?.attachedTo)?.abilityState?.charges??1,target_distance:target&&u?distance(u,target)*1000:Infinity,target_hp:target?.hp||0,target_max_hp:target?.maxHp||0,is_deploying:(u?.readyAt||0)>b.time,is_kamikazing:!!u?.def?.source?.Kamikaze,is_moving:u?.visualState==='run'||!!u?.modernDash,target_is_ground:!!target&&!target.air,'#damage':c.damage??c.context?.damage??0,'#hp':c.context?.hp??target?.hp??0};}
function evalAst(ast,v){switch(ast.kind){case'literal':return ast.value;case'name':{if(ast.name==='true')return true;if(ast.name==='false')return false;if(Object.hasOwn(v,ast.name))return v[ast.name];if(ast.name.startsWith('#')&&contextKeys(v.data).has(ast.name.slice(1)))return Number(v.context[ast.name.slice(1)]??contextInfo(v.data).defaults[ast.name.slice(1)]??0)||0;if(Object.hasOwn(v.state.variables,ast.name))return v.state.variables[ast.name];if(Object.hasOwn(v.data.variables||{},ast.name))return Number(v.data.variables[ast.name].DefaultValue)||0;if(knownTags(v.data).has(ast.name))return v.tags.has(ast.name);throw Error('Unknown source variable '+ast.name);}case'unary':{const n=evalAst(ast.value,v);return ast.op==='!'?!n:ast.op==='-'?-n:+n;}case'conditional':return evalAst(ast.condition,v)?evalAst(ast.yes,v):evalAst(ast.no,v);case'call':{if(ast.name==='has_data')return (v.u?.entity||v.u?.name)===ast.args[0].name;if(ast.name==='has_buff')return (v.u?.buffs?.[ast.args[0].name]?.until||0)>v.time;if(ast.name==='is_clone')return !!v.u?.cloned;if(ast.name==='is_moving')return v.is_moving;if(ast.name==='should_hide')return !alive(v.target)||v.target_distance>(Number(v.u?.def?.source?.Range)||0);if(ast.name==='HAS_SHIELD')return (v.u?.shield||0)>0;if(ast.name==='get_radius')return (v.u?.def?.radiusTiles??v.u?.radius??0)*1000;const a=ast.args.map(x=>evalAst(x,v));if(MATH_FUNCTIONS[ast.name])return MATH_FUNCTIONS[ast.name](...a);if(ast.name==='is_valid_position'){const obstacles=(v.battle.active||[]).filter(u=>u.id!==v.u.id&&u.building&&!u.air).map(u=>({x:u.x/SX,y:u.y/SY,radius:u.def?.radiusTiles||.5}));return Nav.pointClear({x:Number(a[0])/1000,y:Number(a[1])/1000},v.u.def?.radiusTiles||0,obstacles,{air:v.u.air,water:v.u.air,layout:v.battle.arenaLayout?.id})?1:0;}if(ast.name==='has_crown_tower_in_range')return(v.battle.towers||[]).some(t=>alive(t)&&t.team!==v.u.team&&distance(v.u,t)<=(Number(a[0])||Number(v.u.def?.source?.Range)||0)/1000+(t.def?.radiusTiles||0));if(ast.name==='target_in_range')return v.target_distance<=Number(a[0])+EPS;if(ast.name==='team_y_direction')return direction(Number(a[0]));if(knownTags(v.data).has(ast.name)&&a.length===0)return v.tags.has(ast.name);throw Error('Unsupported source function '+ast.name);}case'binary':{const a=evalAst(ast.left,v);if(ast.op==='&&')return !!a&&!!evalAst(ast.right,v);if(ast.op==='||')return !!a||!!evalAst(ast.right,v);const z=evalAst(ast.right,v);switch(ast.op){case'+':return a+z;case'-':return a-z;case'*':return a*z;case'/':if(z===0)throw Error('Invalid source division by zero');return a/z;case'%':if(z===0)throw Error('Invalid source modulo by zero');return a%z;case'==':return a===z;case'!=':return a!==z;case'<':return a<z;case'>':return a>z;case'<=':return a<=z;case'>=':return a>=z;}}}throw Error('Unsupported source expression');}
function evaluate(expression,b,c={}){const ast=parseExpression(expression),d=dataFor(c);validateAst(ast,d);const v=values(b,c);v.time=b.time;v.battle=b;const n=evalAst(ast,v);if(typeof n==='number'&&!Number.isFinite(n))throw Error('Invalid non-finite source expression result');return n;}
const CLASSES=new Set(['ActionGroup','ActionSpawn','ActionSpawnToLocation','ActionTakeDamage','ActionHeal','ActionSetShield','ActionChangeGameObjectData','ActionSetVariable','ActionFilter','ActionSelect','ActionInterval','ActionWaitToActivate','ActionRunActionAtHealth','ActionWithDuration','ActionPlayEffect','ActionResetTarget','ActionResetPath','ActionSetAttackSequenceIndex','ActionSetAnimationModifier','ActionRunForcedAnimationOnce','ActionStopForcedAnimation','ActionKill','ActionHide','ActionSetInstantHit','ActionSetCharge','ActionBossBanditAbility','ActionWarpCharacter','ActionRunActionOnTroopDestroyed','ActionSoulDrain','ActionRunOnInstigator','ActionRunActionOnShooter','ActionTaunt','ActionSetCharacterLevel','ActionGroundToAir','ActionActivateOnCardDeploy','ActionOverrideAbilityButtonState','ActionMiniPekkaHeroQuest']);
for(const type of ['ActionRunActionListOnObjectsInShapeWithPrio','ActionDashingAttackChain','ActionGoblinsteinAbility','ActionEnabbleHPBarConditionForDuration','ActionRunIfGameObjectExists','ActionRunIfInstigatorMatches','ActionPlayAnimationIfHasTarget','ActionAirToGround','ActionClone','ActionBurstAttack','ActionChefTower','ActionTimerQuest','ActionRunActionIfUnitGroupContains','ActionRunOnMatchingUnitsInGroup','ActionWriteInstigatorInfoToContext','ActionSpawnGuard','ActionBlackboardSetInt','ActionContextToVariable','ActionCounter','ActionGoblinHutLifeState','ActionTargetIndicatorAttack','ActionWriteResolverResultToContext','ActionRunActionOnResolvedGameObjects','ActionRunOnAttached','ActionDoPushbackFromInstigator','ActionKnockback','ActionRunActionOnCallbackWithThreshold','ActionFlipFlop','ActionHunterNetAttack','ActionSpawnResetableAeO','ActionFilterByEnemy','ActionAeoRunActionAtAliveTimer','ActionCreateParallelProjectiles','ActionSetIndicatorOnTarget','ActionMegaMinionHeroAbility','ActionReadyChampionAbility','ActionSkeletonBarrelPopBalloon','ActionAttackChain'])CLASSES.add(type);
const CHILD_FIELDS=['SubActions','Actions','NextAction','OnTrueAction','OnFalseAction','ActionToExecute','OnActivateAction','WarpAction','OnWarpEndAction','ActionToRun','ActionToRunIfNoMatch','ActionOnTargetReached','ActionToRunOnSpawned','ActionOnFlyHeightReached','ActionOnStartDescending','OnIntervalReachedAction','OnMaxResetsReachedAction','ActionOnSelfWhenTriggered','ActionOnSelfWhenTriggeredLeft','ActionOnSelfWhenTriggeredRight','OnFinishedAction','OnClonedAction','ActionOnGround','OnTetherActivationAction','OnTetherActivationActionOnConnectedUnit','TetherHitAction','Action','ActionIfNoMatch','SelfAction','InstigatorAction','OnStartWaitingAction','OnStartSpawningAction','OnSpawnAction','TargetStartIndicationAction','OnProjectileShootAction','ActionToRunOnSelfIfNoObjectsFound','SuccessAction','SuccessActionOnInstigator','FailureActionOnInstigator','ActionOnLanding','OnActivatedAction','OnDeactivatedAction','ActionOnCooldownReady','ActionOnShot','IsEnemyAction','IsSameTeamAction','OnPickNewTargetAction','OnTargetDiedAction','HasTargetOnDeployAction','NoTargetOnDeployAction','ReturnWarpAction','OnChainBegan'];
const EXPRESSION_FIELDS=['ExecuteIfTrue','ForceStopIfTrue','Condition','Value','TargetExprX','TargetExprY','AddedDamage','RelativeLevelAdjustmentExpression','ResurrectChargesExpression','XPositionExpression','YPositionExpression','PinnedActiveExpression','PinnedPositionXExpression','PinnedPositionYExpression','ChainCompleteIfTrue'];
function sourceAction(ref,data){return typeof ref==='string'?data.actions?.[ref]:ref;}
function reasonReport(errors,count=0){return{ok:errors.length===0,reason:errors.join('; '),unsupported:errors,visited:count};}
function canExecuteAction(b,ref,c={}){const data=dataFor(c),seen=new Set(),errors=[],tablesSeen=new Set();let count=0;
 function invalid(message){if(!errors.includes(message)&&errors.length<20)errors.push(message);}
 function dependency(kind,name){if(!name)return;const key=kind+':'+name;if(tablesSeen.has(key))return;tablesSeen.add(key);const r=data[kind]?.[name];if(!r){invalid('Missing source '+kind+' '+name);return;}for(const [f,value]of Object.entries(r))if(/^On.*Action(s)?$/.test(f)&&!f.includes('Client'))for(const action of list(value))visit(action);if(kind==='areas')areaCheck(r);for(const f of ['ExecuteIfTrue','AliveIfTrue'])if(r[f])expression(r[f]);}
 function areaCheck(r){if(r.Shape){const p=Resolvers?.shapePreflight(r.Shape,{data});if(!p?.ok)invalid(p?.reason||'Unsupported source area shape');}if(r.TargetFilter||r.Filter){const p=Resolvers?.filterPreflight(r.TargetFilter||r.Filter,{data});if(!p?.ok)invalid(p?.reason||'Unsupported source area filter');}}
 function expression(value){try{validateAst(parseExpression(value),data);}catch(e){invalid(e.message);}}
 function visit(action,depth=0){if(depth>MAX_DEPTH){invalid('Unsupported action graph depth');return;}const r=sourceAction(action,data);if(!r||typeof r!=='object'){invalid('Missing source action '+String(action));return;}if(seen.has(r))return;seen.add(r);count++;const delegated=ModernSpells?.canExecuteAction?.(b,action,{...c,data});if(delegated?.handled){for(const error of delegated.unsupported||[])invalid(error);return;}if(action==='KingTower_StartingGroup'||action==='WaitForKingTowerActivation')return;const type=r.ClassType;if(!CLASSES.has(type)){invalid('Unsupported native action '+String(type));return;}
  for(const f of EXPRESSION_FIELDS)if(r[f]!==undefined&&!(type==='ActionEnabbleHPBarConditionForDuration'&&f==='Condition'))expression(r[f]);for(const value of list(r.PerActionConditions))expression(value);
  if((type==='ActionSpawn'||type==='ActionSpawnToLocation')){const table={BuffType:'buffs',AreaEffectType:'areas',CharacterType:'entities',ProjectileType:'projectiles'}[r.SpawnType];if(!table)invalid('Unsupported spawn type '+r.SpawnType);else dependency(table,r.SpawnData);if(r.SpawnPushback&&(r.SpawnType!=='CharacterType'||!(r.SpawnRadius>0)))invalid('Unsupported native spawn placement/controller');}
  if(type==='ActionChangeGameObjectData'){if(r.NewProjectileData)invalid('Unsupported live projectile data replacement');if(r.NewCharacterData)dependency('entities',r.NewCharacterData);}
  if((type==='ActionSetVariable'||type==='ActionContextToVariable')&&!Object.hasOwn(data.variables||{},r.Variable||r.OutputVariable))invalid('Unknown source variable '+r.Variable);
  if(type==='ActionWarpCharacter'&&r.WarpMode&&!['RelativeWarp','InjectedCharacter'].includes(r.WarpMode))invalid('Unsupported warp mode '+r.WarpMode);
  if(type==='ActionSoulDrain'&&!r.ActionOnTargetReached)invalid('Unsupported native soul-drain health controller');
  if(type==='ActionRunActionOnTroopDestroyed'&&r.TroopFilter&&!data.gameObjectFilters?.[r.TroopFilter]&&!data.filters?.[r.TroopFilter])invalid('Missing source filter '+r.TroopFilter);
  if(type==='ActionMiniPekkaHeroQuest'&&r.UpgradeBarIfTrue)expression(r.UpgradeBarIfTrue);
  if(type==='ActionRunActionListOnObjectsInShapeWithPrio'&&(!data.shapes?.[r.Shape]||!['Circle','Rectangle'].includes(data.shapes[r.Shape].ClassType)))invalid('Unsupported or missing source shape '+r.Shape);
  if(type==='ActionDashingAttackChain'||type==='ActionWriteResolverResultToContext'||type==='ActionRunActionOnResolvedGameObjects'||type==='ActionSetIndicatorOnTarget'||type==='ActionAttackChain'){const p=Resolvers?.preflight(r.TargetResolver||r.Resolver,{data});if(!p?.ok)invalid(p?.reason||'Unsupported source target resolver');}
  if(type==='ActionActivateOnCardDeploy'&&r.CardGroup&&!data.cardGroups?.[r.CardGroup])invalid('Missing source card group '+r.CardGroup);
  if(type==='ActionTaunt'&&r.ValidTargetBuff)dependency('buffs',r.ValidTargetBuff);
  if(type==='ActionSkeletonBarrelPopBalloon'&&r.UseSpecialKamikaze)invalid('Unsupported native Skeleton Barrel evolution containers');
  if(type==='ActionDoPushbackFromInstigator'&&r.DirectionMode!=='ToHorizontalCenterFromInstigator')invalid('Unsupported native push direction '+r.DirectionMode);
  if(type==='ActionChefTower')dependency('projectiles',r.BuffProjectile);
  if(type==='ActionAttackChain'&&r.ChainPhaseBuff)dependency('buffs',r.ChainPhaseBuff);
  if(type==='ActionSpawnGuard'){dependency('entities',r.SpawnData);dependency('areas',r.SpawnAEO);}
  if(type==='ActionGoblinHutLifeState')dependency('entities',r.SpawnData);
  if(type==='ActionSpawnResetableAeO')dependency('areas',r.Aeo);
  if(type==='ActionHunterNetAttack')dependency('projectiles',r.Projectile);
  if(type==='ActionCreateParallelProjectiles')dependency('projectiles',r.ProjectileType);
  if(type==='ActionTargetIndicatorAttack'){dependency('projectiles',r.Projectile);dependency('areas',r.TargetAoE);}
  for(const key of CHILD_FIELDS)for(const child of list(r[key]))visit(child,depth+1);
 }
 visit(ref);return reasonReport(errors,count);
}
function canExecuteAbility(b,config,c={}){if(!config||typeof config!=='object')return reasonReport(['Missing source ability']);const data=dataFor(c),errors=[];for(const key of ['OnActivationAction','SpawnCountResetAction'])if(config[key]){const r=canExecuteAction(b,config[key],c);errors.push(...r.unsupported);}for(const [field,table]of [['Buff','buffs'],['PendingBuff','buffs'],['AreaEffectObject','areas'],['ActivationSpawnCharacter','entities']])if(config[field]){const source=data[table]?.[config[field]];if(!source)errors.push('Missing source '+table+' '+config[field]);else for(const key of ['OnStartingAction','OnStartAction','OnRemoveAction','OnHitAction'])if(source[key])errors.push(...canExecuteAction(b,source[key],c).unsupported);}if(config.ResurrectChargesExpression){try{validateAst(parseExpression(config.ResurrectChargesExpression),data);}catch(e){errors.push(e.message);}}if(!config.OnActivationAction&&!config.Buff&&!config.AreaEffectObject&&!config.ActivationSpawnCharacter&&!config.SwitchLanes)errors.push('Unsupported source ability with no interpreted action');return reasonReport([...new Set(errors)]);}
const capabilityCache=new WeakMap();
function canDeployCard(b,card,c={}){const data=dataFor(c),source=card?.source||card;if(!source||typeof source!=='object')return reasonReport(['Missing source card']);const cache=capabilityCache.get(data)||new Map();capabilityCache.set(data,cache);const key=JSON.stringify([source,card?.form?.ability]);if(cache.has(key))return cache.get(key);const errors=[],visited=new Set();
 const fail=message=>{if(!errors.includes(message)&&errors.length<30)errors.push(message);};
 function action(ref){const r=canExecuteAction(b,ref,{...c,data});for(const error of r.unsupported)fail(error);}
 function record(row){for(const [field,value]of Object.entries(row||{}))if(/^On.*Action(s)?$/.test(field)&&!field.includes('Client'))for(const ref of list(value))action(ref);}
 function dep(table,name){if(!name)return;const id=table+':'+name;if(visited.has(id))return;visited.add(id);const r=data[table]?.[name];if(!r){fail('Missing source '+id);return;}record(r);
  if(table==='entities'){
   for(const field of ['SpawnCharacter','DeathSpawnCharacter','ClonedVersion'])dep('entities',r[field]);
   for(const field of ['Projectile','CustomFirstProjectile','DeathSpawnProjectile'])dep('projectiles',r[field]);
   for(const field of ['SpawnAreaObject','DeathAreaEffect','AreaEffectOnHit'])dep('areas',r[field]);
   for(const field of ['BuffOnDamage','BuffWhenNotAttacking','SpawnBuff','Buff'])dep('buffs',r[field]);
   for(const attack of list(r.AttackSequenceList)){if(attack?.DoAttackAction)action(attack.DoAttackAction);if(attack?.Projectile)dep('projectiles',attack.Projectile);if(attack?.BuffOnDamage)dep('buffs',attack.BuffOnDamage);record(attack);}
   if(r.Ability){const ability=data.abilities?.[r.Ability];if(!ability)fail('Missing source ability '+r.Ability);else for(const error of canExecuteAbility(b,ability,{...c,data}).unsupported)fail(error);}
  }else if(table==='buffs'){dep('projectiles',r.OverrideProjectile);
  }else if(table==='projectiles'){
   dep('entities',r.SpawnCharacter);dep('entities',r.DeflectedCharacterSpawn);dep('projectiles',r.SpawnProjectile);dep('areas',r.SpawnAreaEffectObject);dep('buffs',r.TargetBuff);
  }else if(table==='areas'){
   for(const [field,check]of [['Shape','shapePreflight'],['TargetFilter','filterPreflight'],['Filter','filterPreflight']])if(r[field]){const p=Resolvers?.[check](r[field],{data});if(!p?.ok)fail(p?.reason||'Unsupported source area '+field);}
   dep('entities',r.SpawnCharacter);dep('projectiles',r.Projectile);dep('buffs',r.Buff);
  }
 }
 record(source);for(const field of ['SummonCharacter','SummonCharacterSecond','LinkedChampionCharacter'])dep('entities',source[field]);for(const name of list(source.SummonCharactersList))dep('entities',typeof name==='string'?name:name?.Character||name?.Name);for(const field of ['Projectile','CustomFirstProjectile'])dep('projectiles',source[field]);dep('areas',source.AreaEffectObject);
 if(card?.form?.ability)for(const error of canExecuteAbility(b,card.form.ability,{...c,data}).unsupported)fail(error);
 const result={...reasonReport(errors),dependencies:[...visited]};if(cache.size>=512)cache.delete(cache.keys().next().value);cache.set(key,result);return result;
}
function coverage(data=K.DATA){const cards=(data.cards||[]).map(card=>({id:card.id,name:card.name,kind:'base',...canDeployCard(null,card,{data})})),forms=(data.forms||[]).map(form=>({id:form.id,baseCardId:form.baseCardId,kind:form.kind,...canDeployCard(null,{source:form.source,form},{data})}));return{snapshot:data.snapshot,cards:{total:cards.length,supported:cards.filter(x=>x.ok).length,unsupported:cards.filter(x=>!x.ok).length,rows:cards},forms:{total:forms.length,supported:forms.filter(x=>x.ok).length,unsupported:forms.filter(x=>!x.ok).length,rows:forms}};}
function serialized(c){return{sourceId:c.unit?.id??c.sourceId,instigatorId:c.instigator?.id??c.instigatorId,targetId:c.target?.id??c.targetId,parentAreaId:c.parentAreaId,owner:c.owner??c.unit?.owner??c.unit?.team??c.team,team:c.team??c.instigator?.team??c.unit?.team,level:c.level??c.unit?.level,formId:c.formId,context:c.context,damage:c.damage,melee:c.melee,abilityActivation:c.abilityActivation,warpPosition:c.warpPosition,megaPhase:c.megaPhase};}
function context(b,p,data){const u=b.getEntity?.(p.sourceId)||b.areas?.find(a=>a.id===p.sourceId)||b.projectiles?.find(a=>a.id===p.sourceId);return{...p,unit:u,instigator:b.getEntity?.(p.instigatorId),data:data||K.DATA};}
function later(b,action,c,delay,extra={}){b.schedule({type:'modern-action',action,due:b.time+delay,...serialized(c),...extra});}
function predicate(r,key,b,c){return r[key]===undefined||!!evaluate(r[key],b,c);}
function setTags(u,value,until,token){if(!u)return;const s=state(u);s.tags.push({tags:flags(value),until,token});}
function effect(b,name,c,options={}){if(name)b.effect?.({kind:'source',sourceEffect:name,x:c.unit?.x??0,y:c.unit?.y??0,team:c.team??c.unit?.team,ttl:options.ttl??4,...options});}
function addBuff(b,u,name,duration,c){const data=dataFor(c),r=data.buffs[name];if(!r||r.NotCloned&&u.cloned)return;b.addBuff(u,name,duration,c.team??c.unit?.team,c.level??c.unit?.level??9,c.instigator?.id??c.unit?.id);for(const [key,v]of Object.entries(u.buffs||{}))if((v.name||key)===name&&v.until>b.time)onBuffAdded(b,u,name,v,data,c);}
function createArea(b,name,c,x=c.unit?.x,y=c.unit?.y){const a=b.createArea(name,c.team??c.unit?.team,x,y,c.level??c.unit?.level??9);if(a){a.owner=c.owner??c.unit?.owner??a.owner;a.modernSourceId=c.instigator?.id??c.unit?.id;a.formId=c.formId??c.unit?.formId;}return a;}
function clearTarget(u){u.targetId=null;u.windup=null;u.hook=null;u.dash=null;u.precharge=0;u.nextAttackAt=0;u.navPath=null;}
function shapeContains(data,name,parent,target){if(Resolvers)return Resolvers.contains(data,name,parent,target);const shape=data.shapes?.[name];if(!shape)return false;if(shape.ClassType==='Circle')return distance(parent,target)<=(Number(shape.Radius)||0)/1000+(target.def?.radiusTiles||0)+EPS;if(shape.ClassType==='Rectangle'){const x=Math.abs((target.x-parent.x)/SX),y=(target.y-parent.y)/SY*direction(parent.team),radius=target.def?.radiusTiles||0;return x<=(Number(shape.Width)||0)/2000+radius&&y>=-(Number(shape.BackwardLength)||0)/1000-radius&&y<=(Number(shape.Length)||Number(shape.Height)||0)/1000+radius;}return false;}
function resolveTargets(b,data,parent,shape,filter,mode='Closest',visited=[]){return(b.active||[]).filter(u=>u.id!==parent.id&&!visited.includes(u.id)&&alive(u)&&(!filter||matchesFilter(data,filter,parent,u))&&shapeContains(data,shape,parent,u)).sort((a,z)=>mode==='HighestCurrentHpIncludeShields'?(z.hp+(z.shield||0))-(a.hp+(a.shield||0))||a.id-z.id:distance(parent,a)-distance(parent,z)||a.id-z.id);}
function segmentDistance(p,a,z){const dx=(z.x-a.x)/SX,dy=(z.y-a.y)/SY,px=(p.x-a.x)/SX,py=(p.y-a.y)/SY,len=dx*dx+dy*dy,q=len?Math.max(0,Math.min(1,(px*dx+py*dy)/len)):0;return Math.hypot(px-dx*q,py-dy*q);}
function finishDash(u,b){const dash=u.modernDash;if(!dash)return;for(const entry of state(u).tags)if(entry.token===dash.token)entry.until=b.time;delete u.modernDash;u.visualState='idle';u.nextAttackAt=b.time+(u.def?.interval||0);}
function groupMembers(b,u){return(b.units||[]).filter(v=>v.id!==u.id&&alive(v)&&v.owner===u.owner&&(u.levelGroupId?v.levelGroupId===u.levelGroupId:false));}
function relocate(b,u,x,y){const radius=u.def?.radiusTiles||.4,obstacles=(b.active||[]).filter(v=>v.id!==u.id&&v.building&&!v.air).map(v=>({x:v.x/SX,y:v.y/SY,radius:v.def?.radiusTiles||.5})),point=Nav?.nearestClearPoint?.({x:x/SX,y:y/SY},radius,obstacles,{air:u.air,water:u.air||u.def?.hover||u.def?.source?.JumpEnabled,layout:b.arenaLayout?.id});if(point){u.x=point.x*SX;u.y=point.y*SY;}else{u.x=Math.max(.5*SX,Math.min(17.5*SX,x));u.y=Math.max(.5*SY,Math.min(31.5*SY,y));}u.navPath=null;if(b.navigator)b.navigator.sampleTime=-1;}
function morph(b,u,name){const def=b.entityDefinition(name,u.level);u.entity=name;u.def=def;u.radius=def.radius;u.building=def.building;u.air=def.air;u.maxHp=def.hp||u.maxHp;u.maxShield=def.shield;u.shield=Math.min(u.shield||0,u.maxShield||0);u.navPath=null;u.visualState='idle';u.animationTime=0;u.visualStarted=b.time;for(const entry of state(u).tags)if(entry.token==='source-data')entry.until=b.time;setTags(u,def.source.GameTagsToSet,Infinity,'source-data');}
function timer(u,r,c,b,type){const s=state(u),key=typeof c.actionId==='string'?c.actionId:JSON.stringify(r);if(r.Singleton&&s.timers.some(t=>t.key===key))return;s.timers.push({key,type,record:r,context:serialized(c),nextAt:b.time+ms(r.StartCounterAt??r.Interval??0),count:0,fired:[],token:++s.serial});}
function run(b,ref,c,depth=0){if(depth>MAX_DEPTH)throw Error('Unsupported action graph depth');const data=dataFor(c),r=sourceAction(ref,data),u=c.unit||b.getEntity?.(c.sourceId);c={...c,unit:u,actionId:typeof ref==='string'?ref:c.actionId};if(!r)return;const delegated=ModernSpells?.executeAction?.(b,ref,{...c,data});if(delegated?.handled){if(!delegated.ok)throw Error(delegated.reason);return;}if(ref==='KingTower_StartingGroup'||ref==='WaitForKingTowerActivation')return; // Battle owns the identical 3300ms crown activation controller.
 if(!predicate(r,'ExecuteIfTrue',b,c))return;if(r.ActionDelay&&!c.skipDelay){later(b,ref,c,ms(r.ActionDelay),{skipDelay:true});return;}if(!u&&r.ClassType!=='ActionPlayEffect')return;const t=r.ClassType;let nextDelay=0;
 switch(t){
  case'ActionGroup':if(r.ContextMode==='Create'||!c.context)c.context={};for(const [i,child]of list(r.SubActions).entries()){const delay=ms(r.SubActionsDelay?.[i]);if(delay)later(b,child,c,delay);else run(b,child,{...c,skipDelay:false},depth+1);}break;
  case'ActionSpawn':case'ActionSpawnToLocation':{let x=u.x,y=u.y;if(t==='ActionSpawnToLocation'){if((r.TargetExprX??r.XPositionExpression)!==undefined)x=evaluate(r.TargetExprX??r.XPositionExpression,b,c)/1000*SX;else x+=(Number(r.RelativeX)||0)*SX+(Number(r.MirroredX)||0)*SX*direction(c.team??u.team);if((r.TargetExprY??r.YPositionExpression)!==undefined)y=evaluate(r.TargetExprY??r.YPositionExpression,b,c)/1000*SY;else y+=(Number(r.RelativeY)||0)*SY+(Number(r.MirroredY)||0)*SY*direction(c.team??u.team);}if(r.OffsetY)y+=r.OffsetY/1000*SY*direction(c.team??u.team);
   if(r.SpawnType==='BuffType')addBuff(b,u,r.SpawnData,ms(r.SpawnTime),c);
   else if(r.SpawnType==='AreaEffectType'){const area=createArea(b,r.SpawnData,c,x,y);if(area&&r.ActionToRunOnSpawned)run(b,r.ActionToRunOnSpawned,{...c,unit:area,instigator:u,parentAreaId:area.id},depth+1);}
   else if(r.SpawnType==='CharacterType'){const count=Math.max(1,Math.min(30,Number(r.Count)||1)),options={owner:c.owner??u.owner,wait:r.DeployTime!==undefined?ms(r.DeployTime):r.UseDeploy?undefined:0,card:u.card,formId:c.formId??u.formId,levelGroupId:u.levelGroupId,spawnPushback:!!r.SpawnPushback,spawnConstPriority:!!r.IsSpawnConstPriority},children=count>1&&r.SpawnRadius&&b.spawnGroup?b.spawnGroup(r.SpawnData,count,c.team??u.team,x,y,c.level??u.level,{...options,formation:'barrel',radius:Number(r.SpawnRadius)/1000}):[];if(!children.length)for(let i=0;i<count;i++){const offset=count>1?(i-(count-1)/2)*(Number(r.SpawnRadius)||400)/1000*SX:0;const child=b.spawn(r.SpawnData,c.team??u.team,x+offset,y,{owner:c.owner??u.owner,level:c.level??u.level,wait:r.DeployTime!==undefined?ms(r.DeployTime):r.UseDeploy?undefined:0,card:u.card,formId:c.formId??u.formId,levelGroupId:u.levelGroupId});if(child)children.push(child);}if(r.ActionToRunOnSpawned)for(const child of children)run(b,r.ActionToRunOnSpawned,{...c,unit:child,instigator:u},depth+1);}
   else if(r.SpawnType==='ProjectileType'){const target=r.TargetFromContextName?b.getEntity?.(c.context?.[r.TargetFromContextName]):t==='ActionSpawnToLocation'?null:b.getEntity?.(c.targetId??u.targetId),source=c.instigator||u,startOffset=(Number(r.ProjectileStartOffset)||0)/1000,angle=source.heading??(source.team===0?-Math.PI/2:Math.PI/2),p=b.fireProjectile(r.SpawnData,source,target||null,{x,y,originX:source.x+Math.cos(angle)*startOffset*SX,originY:source.y+Math.sin(angle)*startOffset*SY,startZ:r.StartPositionZOffset,level:c.level??u.level,formId:c.formId??u.formId});if(p&&r.ActionToRunOnSpawned)run(b,r.ActionToRunOnSpawned,{...c,unit:p,instigator:source},depth+1);}break;}
  case'ActionTakeDamage':{const damage=r.Damage||{},raw=Number(damage.BaseDamage)||0,amount=(flags(damage.Flags).includes('NoScaling')?raw:b.scaleStat(raw,u.def?.rarity||u.def?.source?.Rarity||'Common',c.level??u.level))+(r.AddedDamage===undefined?0:Number(evaluate(r.AddedDamage,b,c)));b.damage(u,amount,c.instigator||null,{team:c.team,melee:c.melee,affectsHidden:flags(damage.Flags).includes('DamagesHidden'),reflected:flags(damage.Flags).includes('Reflected')});effect(b,damage.Effect,c);break;}
  case'ActionHeal':if(r.MaxOverHealPercent!==undefined)u.modernOverhealPercent=Number(r.MaxOverHealPercent);b.heal(u,Math.max(0,Number(evaluate(r.Value,b,c))));break;
  case'ActionSetShield':u.shield=Math.max(0,(u.maxShield||0)*Number(r.ShieldPercent||0)/100);break;
  case'ActionChangeGameObjectData':if(r.NewCharacterData)morph(b,u,r.NewCharacterData);if(r.ResetTarget)clearTarget(u);break;
  case'ActionSetVariable':state(u).variables[r.Variable]=evaluate(r.Value,b,c);break;
  case'ActionSetCharacterLevel':{const ratio=u.hp/Math.max(1,u.maxHp),shieldRatio=(u.shield||0)/Math.max(1,u.maxShield||0);u.level=Math.max(1,Math.min(30,u.level+Math.floor(Number(evaluate(r.RelativeLevelAdjustmentExpression,b,c)))));const def=b.entityDefinition(u.entity,u.level);u.def=def;u.maxHp=def.hp;u.hp=Math.max(1,Math.min(u.maxHp,Math.floor(u.maxHp*ratio+EPS)));u.maxShield=def.shield||0;u.shield=Math.floor(u.maxShield*shieldRatio+EPS);break;}
  case'ActionSkeletonBarrelPopBalloon':{if(!state(u).timers.some(v=>v.type===t)){u.modernFrameRange={start:r.BalloonFlyStartFrameList?.[0],end:r.BalloonFlyEndFrameList?.[0],born:b.time};state(u).timers.push({type:t,record:r,context:serialized(c),stage:0});}break;}
  case'ActionFilterByEnemy':{const child=u.team===(c.team??c.instigator?.team)?r.IsSameTeamAction:r.IsEnemyAction;if(child)run(b,child,c,depth+1);break;}
  case'ActionCreateParallelProjectiles':{const count=Math.max(0,Math.min(20,Number(r.ProjectileCount)||0)),source=u.attacker||c.instigator;if(!source)break;for(let i=0;i<count;i++){const offset=(i-(count-1)/2)*Number(r.ProjectileDistance)/1000*2,ox=u.x-u.vy*offset*SX,oy=u.y+u.vx*offset*SY;b.fireProjectile(r.ProjectileType,source,null,{x:u.tx-u.vy*offset*SX,y:u.ty+u.vx*offset*SY,originX:ox,originY:oy,level:u.level,formId:u.formId});}break;}
  case'ActionFlipFlop':state(u).timers.push({type:t,record:r,context:serialized(c),trueSince:null,activated:false});break;
  case'ActionHunterNetAttack':state(u).timers.push({type:t,record:r,context:serialized(c),nextAt:b.time+ms(r.InitialCooldown),ready:false,shootAt:null,target:null});break;
  case'ActionSpawnResetableAeO':{const s=state(u),existing=r.Singleton&&s.timers.find(v=>v.type===t&&v.record.Aeo===r.Aeo),old=existing&&(b.areas||[]).find(a=>a.id===existing.areaId&&a.ends>b.time);if(old){old.born=b.time;old.ends=b.time+ms(data.areas[r.Aeo].LifeDuration);for(const timer of old.modernActions?.timers||[])if(timer.type==='ActionAeoRunActionAtAliveTimer')timer.fired=[];break;}const a=createArea(b,r.Aeo,c,u.x+(Number(r.OffsetX)||0)/1000*SX,u.y+direction(u.team)*(Number(r.OffsetY)||0)/1000*SY);if(a){a.modernFollowOffset={x:(Number(r.OffsetX)||0)/1000*SX,y:direction(u.team)*(Number(r.OffsetY)||0)/1000*SY};s.timers.push({type:t,record:r,context:serialized(c),areaId:a.id});}break;}
  case'ActionAeoRunActionAtAliveTimer':timer(u,r,c,b,t);break;
  case'ActionFilter':{const child=predicate(r,'Condition',b,c)?r.OnTrueAction:r.OnFalseAction;if(child)run(b,child,c,depth+1);break;}
  case'ActionSelect':for(const [i,child]of list(r.SubActions).entries())if(!r.PerActionConditions?.[i]||evaluate(r.PerActionConditions[i],b,c)){run(b,child,c,depth+1);break;}break;
  case'ActionInterval':case'ActionWaitToActivate':case'ActionRunActionAtHealth':timer(u,r,c,b,t);break;
  case'ActionWithDuration':{const s=state(u),token=++s.serial,until=b.time+ms(r.ActionDuration);setTags(u,r.GameTagsToSet,until,token);s.timers.push({type:t,record:r,context:serialized(c),until,token});nextDelay=ms(r.ActionDuration);break;}
  case'ActionPlayEffect':effect(b,r.Effect,c,{ttl:ms(r.OverrideDuration)||4,follow:flags(r.EffectFlags).includes('FollowParent')?u?.id:undefined,scale:r.OverrideScale===undefined?undefined:r.OverrideScale/100,loop:flags(r.EffectFlags).includes('Looping')});if(r.GameTagsToSet)setTags(u,r.GameTagsToSet,b.time+(ms(r.OverrideDuration)||4),'effect');break;
  case'ActionResetTarget':clearTarget(u);break;
  case'ActionResetPath':u.navPath=null;if(b.navigator)b.navigator.sampleTime=-1;break;
  case'ActionSetAttackSequenceIndex':u.attackSequenceIndex=Math.max(0,Math.floor(Number(r.AttackIndex)||0));if(r.ResetRealHitStarted)u.windup=null;break;
  case'ActionSetAnimationModifier':u.modernAnimationModifier=r.Modifier??r.AnimationModifier??null;break;
  case'ActionRunForcedAnimationOnce':u.modernForcedAnimationUntil=b.time+ms(r.ForcedDuration??r.PlaybackDuration);u.modernCustomStateNumber=r.CustomStateNumber;u.visualState='ability';u.animationTime=0;break;
  case'ActionStopForcedAnimation':u.modernForcedAnimationUntil=0;break;
  case'ActionKill':u.hp=0;break;
  case'ActionHide':u.hidden=true;state(u).timers.push({type:t,record:r,context:serialized(c),until:r.Duration===undefined?Infinity:b.time+ms(r.Duration)});break;
  case'ActionSetInstantHit':u.nextAttackAt=b.time;u.precharge=u.def?.interval||0;break;
  case'ActionSetCharge':u.charged=true;break;
  case'ActionBossBanditAbility':u.modernWarpUntil=b.time+ms(r.WarpDelay);if(r.WarpAction)later(b,r.WarpAction,c,ms(r.WarpDelay));break;
  case'ActionSetIndicatorOnTarget':{if(!u.modernIndicator){u.modernIndicator={record:r,context:serialized(c),target:null,nextSearch:b.time,token:++state(u).serial};setTags(u,r.GameTagsToSetWhileHasNotTarget,Infinity,u.modernIndicator.token);}break;}
  case'ActionReadyChampionAbility':{if(u.abilityState){if(r.RecoverCharge&&u.abilityState.charges!==null)u.abilityState.charges=Math.min(Number(u.abilityConfig?.MaxCharges)||1,u.abilityState.charges+1);if(r.ForceCooldown)u.abilityState.cooldownUntil=b.time+ms(u.abilityConfig?.Cooldown);if(r.ReadyAbility)delete u.abilityState.sourceOverride;}break;}
  case'ActionMegaMinionHeroAbility':{if(!u.modernMegaAbility){u.modernMegaAbility={record:r,context:serialized(c),phase:'idle',target:null,origin:null,returnAt:Infinity};const child=u.modernIndicator?.target?r.HasTargetOnDeployAction:r.NoTargetOnDeployAction;if(child)run(b,child,c,depth+1);}if(c.abilityActivation&&u.modernMegaAbility.phase==='idle'){const ability=u.modernMegaAbility,target=b.getEntity?.(u.modernIndicator?.target);if(!alive(target))break;const inherited=context(b,ability.context,data);inherited.context||(inherited.context={});inherited.context[r.WarpWindowActiveKey]=1;inherited.context[r.WarpWindowOriginXKey]=u.x/SX*1000;inherited.context[r.WarpWindowOriginYKey]=u.y/SY*1000;ability.context=serialized(inherited);ability.origin={x:u.x,y:u.y};ability.target=target.id;ability.phase='out';u.targetId=target.id;run(b,r.ActionToExecute,{...c,context:inherited.context,targetId:target.id,warpPosition:{x:target.x,y:target.y},megaPhase:'out'},depth+1);}break;}
  case'ActionWarpCharacter':{if(r.WarpMode==='InjectedCharacter'){const target=c.target||b.getEntity?.(c.targetId??u.targetId),to=c.warpPosition||target&&{x:target.x,y:target.y};if(!to)break;const token=++state(u).serial;u.modernInjectedWarp={record:r,context:serialized(c),to,from:{x:u.x,y:u.y},speed:(Number(r.Speed)||1500)/60,acceleration:(Number(r.Acceleration)||0)/60,token};u.windup=null;setTags(u,'NO_MOVE,NO_ATTACK,WARP',Infinity,token);effect(b,r.WarpTargetEffect,c);break;}effect(b,r.WarpPositionEffect,c);relocate(b,u,u.x+(Number(r.WarpX)||0)/1000*SX,u.y+(Number(r.WarpY)||0)/1000*SY*direction(c.team??u.team));if(r.ResetTarget)clearTarget(u);effect(b,r.WarpTargetEffect,c);if(r.OnWarpEndAction)run(b,r.OnWarpEndAction,c,depth+1);break;}
  case'ActionRunActionOnTroopDestroyed':state(u).listeners.push({type:'troop-death',record:r,context:serialized(c)});break;
  case'ActionSoulDrain':effect(b,r.Effect,c);later(b,r.ActionOnTargetReached,c,ms(r.ConstantFlightDuration));break;
  case'ActionRunOnAttached':{let children=b.attachedControllers?.(u)||(b.units||[]).filter(v=>v.attachedTo===u.id&&alive(v));if(!children.length&&u.def?.source?.SpawnAttach&&u.def.source.SpawnCharacter&&b.spawnAttachedController){const child=b.spawnAttachedController(u.def.source.SpawnCharacter,u);if(child)children=[child];}for(const child of children)run(b,r.ActionToRun,{...c,unit:child,instigator:u},depth+1);break;}
  case'ActionDoPushbackFromInstigator':{if(r.PushbackDelay&&!c.pushbackReady){later(b,ref,c,ms(r.PushbackDelay),{pushbackReady:true});return;}const parent=c.instigator,blocked=!alive(u)||u.building||flags(r.GameTagsToDisallowPush).some(t=>tags(u,b.time).has(t));if(blocked||!parent){if(parent&&r.FailureActionOnInstigator)run(b,r.FailureActionOnInstigator,{...c,unit:parent,instigator:u},depth+1);break;}const from={x:u.x,y:u.y},dx=parent.x<=9*SX?1:-1;b.push?.(u,dx*SX,0,Number(r.PushbackStrength)/1000,true);const to={x:u.x,y:u.y};u.x=from.x;u.y=from.y;u.modernPendingPush={from,to};if(r.SuccessAction)run(b,r.SuccessAction,c,depth+1);if(r.SuccessActionOnInstigator)run(b,r.SuccessActionOnInstigator,{...c,unit:parent,instigator:u},depth+1);break;}
  case'ActionKnockback':{const pending=u.modernPendingPush;if(!pending)break;delete u.modernPendingPush;const token=++state(u).serial;u.modernKnockback={...pending,starts:b.time,duration:ms(r.Duration),height:Number(r.Height)||0,record:r,context:serialized(c),token};setTags(u,'NO_MOVE,NO_ATTACK,NO_CHECKCOLLISIONS',b.time+ms(r.Duration),token);break;}
  case'ActionRunActionOnCallbackWithThreshold':state(u).listeners.push({type:'parent-damage',record:r,context:serialized(c),lastAt:-Infinity});break;
  case'ActionRunOnInstigator':case'ActionRunActionOnShooter':{const target=c.instigator||b.getEntity?.(c.instigatorId);if(target&&(r.ActionToRun||r.ActionToExecute))run(b,r.ActionToRun||r.ActionToExecute,{...c,unit:target,instigator:u},depth+1);break;}
  case'ActionTaunt':{const target=c.instigator||b.getEntity?.(c.instigatorId);if(target&&target.team!==u.team){u.targetId=target.id;u.windup=null;if(r.ValidTargetBuff)addBuff(b,u,r.ValidTargetBuff,ms(u.king!==undefined?r.CrownTowerDuration:r.ValidDuration),c);state(u).timers.push({type:t,record:r,context:serialized(c),until:b.time+ms(u.king!==undefined?r.CrownTowerDuration:r.ValidDuration),target:target.id});}break;}
  case'ActionGroundToAir':{const s=state(u),token=++s.serial;setTags(u,r.GameTagsToSetOnToAirState,b.time+ms(r.TransitionDuration),token);s.timers.push({type:t,record:r,context:serialized(c),airAt:b.time+ms(r.TransitionDuration),groundAt:b.time+ms(r.TotalDuration),ascended:false,token});break;}
  case'ActionActivateOnCardDeploy':state(u).listeners.push({type:'card-deploy',record:r,context:serialized(c)});break;
  case'ActionOverrideAbilityButtonState':if(u.abilityState){u.abilityState.sourceOverride={state:r.StateToSet,record:r,context:serialized(c)};if(r.StateToSet==='AllChargesConsumed')u.abilityState.charges=0;}break;
  case'ActionMiniPekkaHeroQuest':state(u).timers.push({type:t,record:r,context:serialized(c),starts:b.time+ms(r.StartTimerDelay),elapsed:0,count:0,lastUpgrade:false});break;
  case'ActionRunActionListOnObjectsInShapeWithPrio':{timer(u,r,c,b,t);const entry=state(u).timers[state(u).timers.length-1];if(entry)setTags(u,r.GameTagsToSet,Infinity,entry.token);break;}
  case'ActionWriteResolverResultToContext':{c.context||(c.context={});const target=Resolvers.resolve(b,r.Resolver,{data,unit:u,amount:1,tags})[0];c.context[r.ResultName]=target?.id??r.DefaultValue??-1;break;}
  case'ActionRunActionOnResolvedGameObjects':{const targets=Resolvers.resolve(b,r.Resolver,{data,unit:u,amount:r.Amount,tags});if(!targets.length&&r.ActionToRunOnSelfIfNoObjectsFound)run(b,r.ActionToRunOnSelfIfNoObjectsFound,c,depth+1);for(const target of targets)if(r.Action)run(b,r.Action,{...c,unit:r.RunActionsOnSelf?u:target,instigator:r.RunActionsOnSelf?target:u,targetId:target.id},depth+1);break;}
  case'ActionAttackChain':{if(u.modernAttackChain)break;const token=++state(u).serial;u.modernAttackChain={record:r,context:serialized(c),token,target:c.targetId??null,count:0,contact:null};setTags(u,[...flags(r.GameTagsToSet),'NO_MOVE'],Infinity,token);if(r.ChainPhaseBuff)addBuff(b,u,r.ChainPhaseBuff,99999,c);if(r.OnChainBegan)run(b,r.OnChainBegan,c,depth+1);break;}
  case'ActionDashingAttackChain':{const s=state(u),token=++s.serial,source=u.def.source,request=Math.max(1,Number(r.DashCount)||1);u.modernDash={record:r,context:serialized(c),visited:[],max:request*Math.max(1,Number(source.DashCount)||1),target:c.targetId??u.targetId,nextAt:b.time,token,startedAt:b.time};setTags(u,'NO_MOVE,NO_ATTACK,DASHING',Infinity,token);break;}
  case'ActionGoblinsteinAbility':timer(u,r,c,b,t);break;
  case'ActionEnabbleHPBarConditionForDuration':u.modernHealthbarBadge={condition:r.Condition,until:b.time+ms(r.ActionDuration),showBadge:r.RequestShowBadge};break;
  case'ActionRunIfGameObjectExists':{const found=(b.active||[]).filter(v=>matchesFilter(data,r.GameObjectFilter,u,v)&&(!r.MatchName||list(r.MatchName).includes(v.entity))&&!list(r.ExcludeName).includes(v.entity));const child=found.length>=(r.NumMatchesNeeded||1)?r.ActionToRun:r.ActionToRunIfNoMatch;if(child)run(b,child,c,depth+1);break;}
  case'ActionRunIfInstigatorMatches':{const instigator=c.instigator||u,matches=(!r.GameObjectFilter||matchesFilter(data,r.GameObjectFilter,u,instigator))&&(!r.MatchName||list(r.MatchName).includes(instigator.entity));const child=matches?r.ActionToRun:r.ActionToRunIfNoMatch;if(child)run(b,child,c,depth+1);break;}
  case'ActionPlayAnimationIfHasTarget':state(u).timers.push({type:t,record:r,context:serialized(c)});break;
  case'ActionAirToGround':state(u).timers.push({type:t,record:r,context:serialized(c),groundAt:b.time+ms(r.TransitionDuration),until:b.time+ms(r.TotalDuration),wasAir:!!u.air,landed:false});break;
  case'ActionClone':{const parent=b.areas?.find(a=>a.id===c.parentAreaId);if(parent&&data.areas[parent.name]?.Clone)break;if(!u.building&&!u.cloned){const clone=b.spawn(u.def.source.ClonedVersion||u.entity,u.team,u.x+.7*SX,u.y,{owner:u.owner,level:u.level,wait:.5,cloned:true,card:u.card,formId:u.formId,levelGroupId:u.levelGroupId});if(clone&&r.OnClonedAction)run(b,r.OnClonedAction,{...c,unit:clone},depth+1);}break;}
  case'ActionBurstAttack':u.modernBurst={record:r,charges:Math.max(1,Number(r.MaxChargeCount)||1),maximum:Math.max(1,Number(r.MaxChargeCount)||1),reloadAt:Infinity,depleted:false};break;
  case'ActionChefTower':state(u).timers.push({type:t,record:r,context:serialized(c),starts:b.time+ms(r.StartCookingDelay),contribution:0,throwAt:null,target:null});break;
  case'ActionTimerQuest':state(u).timers.push({type:t,record:r,context:serialized(c),starts:b.time,elapsed:Number(r.IntervalStartAt)||0,count:0,lastUpgrade:false});break;
  case'ActionRunActionIfUnitGroupContains':{const members=groupMembers(b,u).filter(v=>matchesFilter(data,r.ObjectFilter,u,v,b.time)),child=members.length?r.Action:r.ActionIfNoMatch;if(child)run(b,child,c,depth+1);break;}
  case'ActionRunOnMatchingUnitsInGroup':for(const target of groupMembers(b,u))if(matchesFilter(data,r.ObjectFilter,u,target,b.time))run(b,r.ActionToRun,{...c,unit:target,instigator:u},depth+1);break;
  case'ActionWriteInstigatorInfoToContext':{const source=c.instigator||b.getEntity?.(c.instigatorId);if(!source)break;c.context||(c.context={});const def=r.HitpointsLevelIndex!==undefined?b.entityDefinition(source.entity,Number(r.HitpointsLevelIndex)+1):source.def;if(r.HitpointsKey)c.context[r.HitpointsKey]=def.hp??source.maxHp;if(r.ShieldHitpointsKey)c.context[r.ShieldHitpointsKey]=def.shield??source.maxShield??0;break;}
  case'ActionCounter':state(u).counter={record:r,context:serialized(c),readyAt:r.DeployActive?b.time:b.time+ms(r.Cooldown)};break;
  case'ActionGoblinHutLifeState':state(u).timers.push({type:t,record:r,context:serialized(c),spawning:false,nextSpawn:b.time,token:++state(u).serial});if(r.OnStartWaitingAction)run(b,r.OnStartWaitingAction,c,depth+1);break;
  case'ActionTargetIndicatorAttack':state(u).timers.push({type:t,record:r,context:serialized(c),nextAt:b.time+ms(r.LoadTime),shootAt:null,target:null,indicator:null,token:++state(u).serial});break;
  case'ActionContextToVariable':state(u).variables[r.OutputVariable]=Number(c.context?.[r.BlackboardKey])||0;break;
  case'ActionBlackboardSetInt':c.context||(c.context={});c.context[r.Key]=Math.trunc(Number(evaluate(r.Value,b,c)));break;
  case'ActionSpawnGuard':{const parent=c.instigator||u,forward=direction(parent.team),target=(b.active||[]).filter(v=>alive(v)&&matchesFilter(data,r.HitFilter,parent,v,b.time)&&distance(parent,v)<=(Number(r.TargetRadius)||4000)/1000+(v.def?.radiusTiles||0)).sort((a,z)=>distance(parent,a)-distance(parent,z)||a.id-z.id)[0],x=parent.x,y=parent.y-forward*(Number(r.AppearBehindAtDistance)||0)/1000*SY,guard=b.spawn(r.SpawnData,parent.team,x,y,{owner:parent.owner,level:parent.level,formId:parent.formId,card:parent.card,levelGroupId:parent.levelGroupId});if(guard){const token=++state(guard).serial;guard.modernGuardDash={record:r,starts:b.time+ms(data.entities[r.SpawnData].DeployTime),from:{x:guard.x,y:guard.y},to:target?{x:target.x,y:target.y}:{x:parent.x,y:parent.y+forward*(Number(r.TargetRadius)||4000)/1000*SY},progress:0,area:null,token};setTags(guard,'NO_MOVE,NO_ATTACK,DASHING',Infinity,token);}break;}
 }
 if(r.NextAction&&t!=='ActionWithDuration'){if(nextDelay||r.NextActionWait&&r.DeployTime)later(b,r.NextAction,c,nextDelay||ms(r.DeployTime));else run(b,r.NextAction,{...c,skipDelay:false},depth+1);}
}
function executeAction(b,ref,c={}){const check=canExecuteAction(b,ref,c);if(!check.ok)return check;try{const owner=c.owner??c.unit?.owner??c.unit?.team??c.team;const exec=()=>run(b,ref,{...c,owner});if(b.withOwner)b.withOwner(owner,exec);else exec();return check;}catch(e){return reasonReport([e.message]);}}
function resolvePending(b,p,data){if(p.type!=='modern-action')return false;const c=context(b,p,data);if(!c.unit||!alive(c.unit)&&sourceAction(p.action,c.data)?.AbortIfInstigatorDies!==false)return true;try{run(b,p.action,c);}catch(e){b.record?.({type:'modern-action-unsupported',action:typeof p.action==='string'?p.action:p.action?.ClassType,reason:e.message});}return true;}
function executeAbility(b,config,c={}){const check=canExecuteAbility(b,config,c);if(!check.ok)return check;const u=c.unit||b.getEntity?.(c.sourceId);if(!alive(u))return reasonReport(['Ability caster is no longer alive']);c={...c,unit:u,abilityActivation:true,owner:c.owner??u.owner,team:c.team??u.team,level:c.level??u.level};const exec=()=>{if(config.Buff)addBuff(b,u,config.Buff,ms(config.BuffTime),c);if(config.ActivationSpawnCharacter)b.spawn(config.ActivationSpawnCharacter,c.team,u.x,u.y,{owner:c.owner,level:c.level,wait:ms(config.ActivationSpawnDeployTime)});if(config.AreaEffectObject){const a=createArea(b,config.AreaEffectObject,c);if(a&&config.ResurrectBaseCount!==undefined){const charges=config.ResurrectChargesExpression?Number(evaluate(config.ResurrectChargesExpression,b,c)):0;a.modernSpawnLimit=Math.max(0,Math.min(Number(config.SpawnLimit)||Infinity,Number(config.ResurrectBaseCount)+charges));if(config.SpawnCountResetAction)run(b,config.SpawnCountResetAction,c);}}if(config.SwitchLanes){relocate(b,u,18*SX-u.x,u.y);clearTarget(u);}if(config.OnActivationAction)run(b,config.OnActivationAction,c);};if(b.withOwner)b.withOwner(c.owner,exec);else exec();return check;}
function beginAbility(b,config,c={}){const u=c.unit||b.getEntity?.(c.sourceId);if(!u||!config.PendingBuff)return;u.modernPendingBuff={name:config.PendingBuff,previous:u.buffs?.[config.PendingBuff]||null};addBuff(b,u,config.PendingBuff,Math.max(ms(config.CastTime),ms(config.TriggerDelay),.001),{...c,unit:u});}
function endPendingAbility(b,config,c={}){const u=c.unit||b.getEntity?.(c.sourceId),pending=u?.modernPendingBuff;if(!pending)return;if(pending.previous?.until>b.time)u.buffs[pending.name]=pending.previous;else delete u.buffs[pending.name];delete u.modernPendingBuff;}
function onSpawn(b,u,data=K.DATA){const r=u.def?.source||{},c={unit:u,data};if(u.modernStarted)return;u.modernStarted=true;setTags(u,r.GameTagsToSet,Infinity,'source-data');if(r.OnStartingAction){const result=executeAction(b,r.OnStartingAction,c);if(!result.ok)u.modernUnsupported=result.reason;}}
function activeBuffs(b,u,data){return Object.entries(u?.buffs||{}).filter(([,v])=>v.until>b.time+EPS).map(([name,v])=>({name,record:data.buffs?.[v.name||name]||{},state:v}));}
function tickEntity(b,u,dt=0,data=K.DATA){if(!u)return;u.modernTime=b.time;for(const [key,v]of Object.entries(u.buffs||{}))if(data.buffs?.[v.name||key.split('@')[0]]?.ControlledByParent&&v.sourceId!=null){const parent=b.getEntity?.(v.sourceId)||b.areas?.find(a=>a.id===v.sourceId)||b.projectiles?.find(p=>p.id===v.sourceId);if(!parent||!alive(parent)||(parent.ends!==undefined&&parent.ends<=b.time+EPS))delete u.buffs[key];}const s=u.modernActions;if(s){for(const [key,entry]of Object.entries(s.buffLifecycles||{})){const current=u.buffs?.[key];if(current&&current.until>b.time+EPS){entry.until=current.until;continue;}delete s.buffLifecycles[key];const r=data.buffs?.[entry.name];if(r?.OnRemoveAction)run(b,r.OnRemoveAction,{...context(b,entry.context,data),unit:u});}let steps=0;for(const timer of [...s.timers]){if(++steps>MAX_STEPS)break;const r=timer.record,c={...context(b,timer.context,data),unit:u},stopped=r.ForceStopIfTrue!==undefined&&evaluate(r.ForceStopIfTrue,b,c);if(stopped){timer.done=true;if(timer.type==='ActionHide')u.hidden=false;for(const tag of s.tags)if(tag.token===timer.token)tag.until=b.time;}
  if(timer.done)continue;if(timer.type==='ActionInterval'){if(flags(r.PauseTag).some(tag=>tags(u,b.time).has(tag))){timer.nextAt+=dt;continue;}if(r.AffectedByHitSpeed||r.AffectedBySpawnSpeed){const rates=b.buffs?.(u)||{attack:1,spawn:1};timer.nextAt+=dt*(1-(r.AffectedByHitSpeed?rates.attack:rates.spawn));}let bursts=0;while(timer.nextAt<=b.time+EPS&&bursts++<MAX_STEPS){if(flags(r.PauseTag).some(tag=>tags(u,b.time).has(tag))){timer.nextAt=b.time+ms(r.Interval);break;}run(b,r.ActionToExecute,c);timer.count++;timer.nextAt+=Math.max(.001,ms(r.Interval));if(r.MaxRepetitions&&timer.count>=r.MaxRepetitions){timer.done=true;break;}}}
  else if(timer.type==='ActionSkeletonBarrelPopBalloon'){const percentage=u.hp/Math.max(1,u.maxHp)*100;while(timer.stage<list(r.DropBalloonAtHpList).length&&percentage<=r.DropBalloonAtHpList[timer.stage]+EPS){const i=timer.stage++;effect(b,r.OnPopBalloonEffectList?.[i],c);u.modernFrameRange={start:r.BalloonFlyStartFrameList?.[timer.stage],end:r.BalloonFlyEndFrameList?.[timer.stage],born:b.time,transition:{start:r.BalloonPopStartFrameList?.[i],end:r.BalloonPopEndFrameList?.[i],born:b.time,until:b.time+ms(r.TransitionTime)}};}}
  else if(timer.type==='ActionFlipFlop'){const condition=!!evaluate(r.Condition,b,c);if(!condition){if(timer.activated&&r.OnDeactivatedAction)run(b,r.OnDeactivatedAction,c);timer.trueSince=null;timer.activated=false;}else{if(timer.trueSince===null)timer.trueSince=b.time;if(!timer.activated&&b.time+EPS>=timer.trueSince+ms(r.ActivationTime)){timer.activated=true;if(r.OnActivatedAction)run(b,r.OnActivatedAction,c);}}}
  else if(timer.type==='ActionSpawnResetableAeO'){const a=(b.areas||[]).find(v=>v.id===timer.areaId);if(!a||a.ends<=b.time+EPS)timer.done=true;else if(r.StopAeoIfParentHasCombatDisabled&&tags(u,b.time).has('COMBAT_DISABLED')){a.ends=b.time;timer.done=true;}}
  else if(timer.type==='ActionAeoRunActionAtAliveTimer'){for(const[i,time]of list(r.AliveTimeList).entries())if(!timer.fired.includes(i)&&b.time+EPS>=(u.born??0)+ms(time)){timer.fired.push(i);if(r.Actions?.[i])run(b,r.Actions[i],c);}}
  else if(timer.type==='ActionHunterNetAttack'){const rates=b.buffs?.(u)||{attack:1};if(!rates.attack){timer.nextAt+=dt;if(timer.shootAt!==null)timer.shootAt+=dt;continue;}const legal=v=>alive(v)&&matchesFilter(data,r.TargetFilter,u,v,b.time)&&distance(u,v)<=Number(r.Range)/1000+(v.def?.radiusTiles||0)&&distance(u,v)>=Math.max(0,Number(r.MinRange)/1000)+(v.def?.radiusTiles||0);if(timer.shootAt!==null&&b.time+EPS>=timer.shootAt){const target=b.getEntity?.(timer.target);if(legal(target)){const angle=Math.atan2((target.y-u.y)/SY,(target.x-u.x)/SX),offset=(Number(u.def.source.ProjectileStartRadius)||0)/1000+(Number(r.ProjectileStartExtraRadius)||0)/1000;b.fireProjectile(r.Projectile,u,target,{originX:u.x+Math.cos(angle)*offset*SX,originY:u.y+Math.sin(angle)*offset*SY,level:u.level,formId:u.formId});if(r.ActionOnShot)run(b,r.ActionOnShot,{...c,targetId:target.id});}timer.shootAt=null;timer.target=null;timer.nextAt=b.time+ms(r.Cooldown);timer.ready=false;}if(timer.shootAt===null&&b.time+EPS>=timer.nextAt){if(!timer.ready){timer.ready=true;if(r.ActionOnCooldownReady)run(b,r.ActionOnCooldownReady,c);}const target=(b.active||[]).filter(legal).sort((a,z)=>distance(u,a)-distance(u,z)||a.id-z.id)[0];if(target){timer.target=target.id;timer.shootAt=b.time+ms(r.TrapCastTime);}}}
  else if(timer.type==='ActionWaitToActivate'&&predicate(r,'Condition',b,c)){run(b,r.OnActivateAction,c);timer.done=true;}
  else if(timer.type==='ActionGroundToAir'){if(!timer.ascended&&b.time+EPS>=timer.airAt){timer.ascended=true;u.air=true;u.navPath=null;if(r.ActionOnFlyHeightReached)run(b,r.ActionOnFlyHeightReached,c);}if(b.time+EPS>=timer.groundAt){u.air=false;u.navPath=null;setTags(u,r.GameTagsToSetOnToGroundState,b.time+ms(r.TransitionDuration),timer.token);if(r.ActionOnStartDescending)run(b,r.ActionOnStartDescending,c);timer.done=true;}}
  else if(timer.type==='ActionMiniPekkaHeroQuest'||timer.type==='ActionTimerQuest'){if(b.time+EPS>=timer.starts){timer.elapsed+=Math.max(0,Math.min(dt,b.time-timer.starts))*1000;const upgraded=r.UpgradeBarIfTrue!==undefined&&!!evaluate(r.UpgradeBarIfTrue,b,c);if(upgraded&&!timer.lastUpgrade)timer.elapsed+=Number(r.AmountToIncreaseOnUpgradeBarList?.[Math.min(timer.count,(r.AmountToIncreaseOnUpgradeBarList?.length||1)-1)])||0;timer.lastUpgrade=upgraded;let guard=0;while(guard++<32){const interval=Number(r.Intervals?.[Math.min(timer.count,(r.Intervals?.length||1)-1)]);if(!(interval>0)||timer.elapsed+EPS<interval)break;timer.elapsed-=interval;timer.count++;if(r.OnIntervalReachedAction)run(b,r.OnIntervalReachedAction,c);if(r.MaxResets&&timer.count>=r.MaxResets){if(r.OnMaxResetsReachedAction)run(b,r.OnMaxResetsReachedAction,c);timer.done=true;break;}}}}
  else if(timer.type==='ActionRunActionListOnObjectsInShapeWithPrio'){if(flags(r.PauseTags).some(tag=>tags(u,b.time).has(tag)))continue;const target=resolveTargets(b,data,u,r.Shape,r.TargetFilter,r.TargetSelectionMode,timer.fired)[0];if(target){timer.fired.push(target.id);for(const entry of s.tags)if(entry.token===timer.token)entry.until=b.time;for(const [i,ref]of list(r.Actions).entries()){const tc={...c,unit:target,instigator:u,targetId:target.id};if(r.Delays?.[i])later(b,ref,tc,ms(r.Delays[i]));else run(b,ref,tc);}const own=r.ActionOnSelfWhenTriggered||((target.x-u.x)<0?r.ActionOnSelfWhenTriggeredLeft:r.ActionOnSelfWhenTriggeredRight);if(own)run(b,own,{...c,targetId:target.id});timer.done=true;}else if(!r.WaitForTarget){for(const entry of s.tags)if(entry.token===timer.token)entry.until=b.time;if(r.OnFinishedAction)run(b,r.OnFinishedAction,c);timer.done=true;}}
  else if(timer.type==='ActionGoblinsteinAbility'){const caster=c.instigator||b.getEntity?.(u.modernSourceId)||u,aura=(caster.buffs?.goblinstein_doctor_aura?.until||0)>b.time;if(aura&&!timer.auraActive){timer.until=b.time+ms(r.TetherDuration);timer.nextHit=b.time;timer.connected=(b.units||[]).filter(v=>v.entity==='goblinstein'&&v.owner===caster.owner&&(!caster.levelGroupId||v.levelGroupId===caster.levelGroupId)).sort((a,z)=>z.born-a.born||a.id-z.id)[0]?.id;setTags(caster,r.GameTagsToSetDutingTether,timer.until,timer.token);const connected=b.getEntity?.(timer.connected);if(connected)setTags(connected,r.ConnectedCharacterGameTagsToSetDutingTether,timer.until,timer.token);if(r.OnTetherActivationAction)run(b,r.OnTetherActivationAction,{...c,unit:caster});if(connected&&r.OnTetherActivationActionOnConnectedUnit)run(b,r.OnTetherActivationActionOnConnectedUnit,{...c,unit:connected,instigator:caster});}timer.auraActive=aura;
   if(timer.until>b.time+EPS&&alive(caster)){const connected=b.getEntity?.(timer.connected)||b.modernCorpses?.find(v=>v.id===timer.connected);if(connected){if(b.time+EPS>=timer.nextHit){for(const target of b.active||[]){if(!matchesFilter(data,r.TetherDamageTargets,caster,target)||segmentDistance(target,caster,connected)>r.TetherWidth/2000+(target.def?.radiusTiles||0)+EPS)continue;const raw=target.king!==undefined?r.TetherCrownTowerDamage:r.TetherDamage;b.damage(target,b.scaleStat(raw,'Common',caster.level),caster,{team:caster.team});if(r.TetherHitAction)run(b,r.TetherHitAction,{...c,unit:target,instigator:caster});}timer.nextHit+=ms(r.TetherHitInterval)||.5;}b.effect?.({kind:'beam',sourceBeam:r.TetherEffect,x:caster.x,y:caster.y,tx:connected.x,ty:connected.y,source:caster.id,target:connected.id,team:caster.team,ttl:Math.max(.05,dt*2)});}}
  }
  else if(timer.type==='ActionPlayAnimationIfHasTarget')u.modernTargetAnimation=b.getEntity?.(u.targetId)?{start:r.TargetStartFrame,end:r.TargetEndFrame}:{start:r.IdleStartFrame,end:r.IdleEndFrame};
  else if(timer.type==='ActionAirToGround'){if(!timer.landed&&b.time+EPS>=timer.groundAt){timer.landed=true;u.air=false;u.navPath=null;if(r.GameTagsToSet)setTags(u,r.GameTagsToSet,timer.until,timer.token);if(r.ActionOnGround&&(!u.cloned||r.CloneTriggersLandingActions!==false))run(b,r.ActionOnGround,c);}if(b.time+EPS>=timer.until){u.air=timer.wasAir;u.navPath=null;timer.done=true;}}
  else if(timer.type==='ActionChefTower'){if(b.time+EPS<timer.starts)continue;const towers=(b.towers||[]).filter(v=>v.team===u.team&&!v.king);let contribution=Number(r.ContributionBaseline)||0;for(const tower of towers)contribution+=!alive(tower)?Number(r.ContributionDestroyed)||0:tower.windup||tower.nextAttackAt>b.time+EPS?Number(r.ContributionAttacking)||0:Number(r.ContributionIdle)||0;
   timer.contribution=Math.min(Number(r.ContributionNeeded),timer.contribution+contribution*Math.max(0,Math.min(dt,b.time-timer.starts)));if(timer.throwAt!==null&&b.time+EPS>=timer.throwAt){const target=b.getEntity?.(timer.target);if(alive(target)){b.fireProjectile(r.BuffProjectile,u,target,{x:u.x,y:u.y+direction(u.team)*(Number(r.PancakeStartOffset)||0)/1000*SY,level:u.level});timer.contribution=0;timer.lastThrow=b.time;u.modernForcedAnimationUntil=b.time+ms(r.PancakeThrowDuration);}timer.throwAt=null;timer.target=null;}
   if(timer.contribution+EPS>=r.ContributionNeeded&&timer.throwAt===null){const target=(b.units||[]).filter(v=>alive(v)&&matchesFilter(data,r.TargetFilter,u,v)&&v.maxHp>=(Number(r.MinMaxHpThreshold)||0)&&v.hp>=(Number(r.MinCurrentHpThreshold)||0)&&v.hp/Math.max(1,v.maxHp)*100+EPS>=(Number(r.MinCurrentHpPercentageThreshold)||0)).sort((a,z)=>{const an=Object.values(a.buffs||{}).some(v=>v.name==='ChefTower_increase_level_buff'&&v.until>b.time),zn=Object.values(z.buffs||{}).some(v=>v.name==='ChefTower_increase_level_buff'&&v.until>b.time);return(r.DeprioritizeBuffed?Number(an)-Number(zn):0)||z.hp-a.hp||a.id-z.id;})[0];if(target){timer.target=target.id;timer.throwAt=b.time+ms(r.PancakeThrowDelay);}}
  }
  else if(timer.type==='ActionGoblinHutLifeState'){const available=(b.active||[]).filter(v=>alive(v)&&matchesFilter(data,r.ObjectFilter,u,v,b.time)&&distance(u,v)<=(Number(u.def.source.Range)||6000)/1000+(v.def?.radiusTiles||0)),spawning=available.length>0,rates=b.buffs?.(u)||{spawn:1};if(spawning!==timer.spawning){timer.spawning=spawning;for(const tag of s.tags)if(tag.token===timer.token)tag.until=b.time;if(spawning){setTags(u,r.ToggleEffectTag,Infinity,timer.token);timer.nextSpawn=b.time;if(r.OnStartSpawningAction)run(b,r.OnStartSpawningAction,c);}else if(r.OnStartWaitingAction)run(b,r.OnStartWaitingAction,c);}if(spawning){timer.nextSpawn+=dt*(1-(rates.spawn??1));if(b.time+EPS>=timer.nextSpawn&&(rates.spawn??1)>0){const angle=(u.team===0?-Math.PI/2:Math.PI/2)+(Number(r.SingleDeployOffsetAngle)||0)*Math.PI/180;for(let i=0;i<Math.max(1,Math.min(30,Number(r.SpawnNumber)||1));i++)b.spawn(r.SpawnData,u.team,u.x+Math.cos(angle)*(Number(r.SpawnOffset)||0)/1000*SX,u.y+Math.sin(angle)*(Number(r.SpawnOffset)||0)/1000*SY,{owner:u.owner,level:u.level,card:u.card,formId:u.formId,levelGroupId:u.levelGroupId});timer.nextSpawn=b.time+ms(r.SpawnInterval);if(r.OnSpawnAction)run(b,r.OnSpawnAction,c);}}}
  else if(timer.type==='ActionTargetIndicatorAttack'){const rates=b.buffs?.(u)||{attack:1};if(!rates.attack){timer.nextAt+=dt;if(timer.shootAt!==null)timer.shootAt+=dt;continue;}const legal=v=>alive(v)&&matchesFilter(data,r.TargetFilter,u,v,b.time)&&distance(u,v)<=(Number(r.Range)||0)/1000+(v.def?.radiusTiles||0)&&distance(u,v)>=(Number(r.MinimumRange)||0)/1000+(v.def?.radiusTiles||0);if(timer.shootAt!==null&&b.time+EPS>=timer.shootAt){const target=b.getEntity?.(timer.target);if(legal(target)){const angle=u.heading??(u.team===0?-Math.PI/2:Math.PI/2),offset=(Number(r.ProjectileOffsetToCharacterLookDirection)||0)/1000;b.fireProjectile(r.Projectile,u,target,{originX:u.x+Math.cos(angle)*offset*SX,originY:u.y+Math.sin(angle)*offset*SY,level:u.level,startZ:r.ProjectileStartZ,formId:u.formId});if(r.OnProjectileShootAction)run(b,r.OnProjectileShootAction,c);setTags(u,r.GameTagsToSetToStopTargetIndication,b.time+.05,timer.token);}const area=(b.areas||[]).find(a=>a.id===timer.indicator);if(area)area.ends=b.time;timer.nextAt=b.time+ms(r.AttackCooldown);timer.shootAt=null;timer.target=null;timer.indicator=null;}if(timer.shootAt===null&&b.time+EPS>=timer.nextAt){const target=(b.active||[]).filter(legal).sort((a,z)=>distance(u,a)-distance(u,z)||a.id-z.id)[0];if(target){timer.target=target.id;timer.shootAt=b.time+ms(r.TargetIndicatorDelay)+ms(r.AttackDelay);const area=createArea(b,r.TargetAoE,{...c,unit:target,instigator:u},target.x,target.y);if(area){area.modernSourceId=target.id;area.ends=timer.shootAt;timer.indicator=area.id;}if(r.TargetStartIndicationAction)run(b,r.TargetStartIndicationAction,{...c,targetId:target.id});}}}
  else if(timer.type==='ActionRunActionAtHealth'){const percentage=u.hp/Math.max(1,u.maxHp)*100;for(const [i,pct]of list(r.HealthPercentages).entries())if(!timer.fired.includes(i)&&percentage<=pct+EPS){timer.fired.push(i);if(r.Actions?.[i])run(b,r.Actions[i],c);}}
  else if(timer.until!==undefined&&b.time+EPS>=timer.until){timer.done=true;if(timer.type==='ActionHide')u.hidden=false;if(timer.type==='ActionWithDuration'&&r.NextAction)run(b,r.NextAction,{...c,skipDelay:false});}
  else if(timer.type==='ActionTaunt'){const target=b.getEntity?.(timer.target);if(alive(target))u.targetId=target.id;else timer.done=true;}
 }s.timers=s.timers.filter(t=>!t.done);s.tags=s.tags.filter(t=>t.until>b.time+EPS);}
 if(u.modernAttackChain){const chain=u.modernAttackChain,r=chain.record,c={...context(b,chain.context,data),unit:u},done=r.ChainCompleteIfTrue&&evaluate(r.ChainCompleteIfTrue,b,c)||chain.count>=Number(r.ChainCount)||!alive(u);if(done){for(const t of state(u).tags)if(t.token===chain.token)t.until=b.time;for(const[key,v]of Object.entries(u.buffs||{}))if((v.name||key)===r.ChainPhaseBuff)delete u.buffs[key];delete u.modernAttackChain;if(r.ResetTargetAfterReach)clearTarget(u);if(r.OnFinishedAction)run(b,r.OnFinishedAction,c);}else{const buffs=activeBuffs(b,u,data),paused=tags(u,b.time).has('COMBAT_DISABLED')||tags(u,b.time).has('CAPTURED')||r.PauseIfAttackSpeedZero&&buffs.some(v=>Number(v.record.HitSpeedMultiplier)<=-100);if(!paused){let target=b.getEntity?.(chain.target);if(!alive(target)){target=Resolvers.resolve(b,r.TargetResolver,{data,unit:u,amount:1,tags})[0];chain.target=target?.id;chain.contact=null;}if(target){const len=distance(u,target),contact=(u.def?.radiusTiles||0)+(target.def?.radiusTiles||0),rate=buffs.some(v=>Number(v.record.SpeedMultiplier)<=-100)?0:Math.max(0,1+buffs.reduce((n,v)=>n+(Number(v.record.SpeedMultiplier)||0)/100,0)),step=(Number(u.def?.source?.JumpSpeed)||100)/60*rate*dt;u.targetId=target.id;if(len>contact+EPS&&step>0){const move=Math.min(step,len-contact);u.x+=(target.x-u.x)/len*move;u.y+=(target.y-u.y)/len*move;u.heading=Math.atan2((target.y-u.y)/SY,(target.x-u.x)/SX);u.visualState='ability';u.navPath=null;}else if(chain.contact!==target.id){chain.contact=target.id;chain.count++;if(r.PerformAttackOnReach)b.strike?.(u,target);}}}}}
 if(u.modernIndicator){const indicator=u.modernIndicator,r=indicator.record,c={...context(b,indicator.context,data),unit:u};if(r.ForceStopIfTrue!==undefined&&evaluate(r.ForceStopIfTrue,b,c)){for(const t of state(u).tags)if(t.token===indicator.token)t.until=b.time;delete u.modernIndicator;}else{const old=b.getEntity?.(indicator.target);if(indicator.target&&!alive(old)){indicator.target=null;indicator.nextSearch=b.time+ms(r.DelayBeforeSearchForNextTarget);if(r.OnTargetDiedAction)run(b,r.OnTargetDiedAction,c);}if(!indicator.target&&b.time+EPS>=indicator.nextSearch&&(!r.PauseIfInCooldown||!(u.abilityState?.cooldownUntil>b.time))){const target=Resolvers.resolve(b,r.TargetResolver,{data,unit:u,amount:1,tags})[0];if(target){indicator.target=target.id;for(const t of state(u).tags)if(t.token===indicator.token)t.until=b.time;if(r.OnPickNewTargetAction)run(b,r.OnPickNewTargetAction,{...c,instigator:target,targetId:target.id});effect(b,u.team?r.EnemyTargetterEffect:r.PlayerTargetterEffect,c);const index=Math.max(0,r.RadiusListForEffectSelection?.findIndex(v=>(target.def?.radiusTiles||0)*1000<=v)??0);effect(b,(u.team?r.EnemyTargettedEffectList:r.PlayerTargettedEffectList)?.[index],{...c,unit:target});}else if(!tags(u,b.time).has('ABILITY_DISABLED'))setTags(u,r.GameTagsToSetWhileHasNotTarget,Infinity,indicator.token);}}}
 if(u.modernMegaAbility){const ability=u.modernMegaAbility,r=ability.record,target=b.getEntity?.(ability.target);if(ability.phase==='active'&&r.ReturnToOrigin&&(b.time+EPS>=ability.returnAt||r.ReturnOnTargetDeath&&!alive(target))){ability.phase='return';run(b,r.ReturnWarpAction,{...context(b,ability.context,data),unit:u,warpPosition:ability.origin,megaPhase:'return'});}}
 if(u.modernInjectedWarp){const warp=u.modernInjectedWarp,len=distance(u,warp.to);warp.speed+=warp.acceleration*dt;const step=Math.max(0,warp.speed*dt);u.visualState='dash';if(len<=step+EPS){u.x=warp.to.x;u.y=warp.to.y;u.navPath=null;delete u.modernInjectedWarp;for(const tag of state(u).tags)if(tag.token===warp.token)tag.until=b.time;const c={...context(b,warp.context,data),unit:u},ability=u.modernMegaAbility;if(ability&&c.megaPhase==='out'){ability.phase='active';ability.returnAt=b.time+ms(ability.record.ReturnDelay);}else if(ability&&c.megaPhase==='return'){ability.phase='returned';if(ability.context.context)ability.context.context[ability.record.WarpWindowActiveKey]=0;}if(warp.record.OnWarpEndAction)run(b,warp.record.OnWarpEndAction,c);u.visualState='idle';}else{u.x+=(warp.to.x-u.x)/len*step;u.y+=(warp.to.y-u.y)/len*step;u.navPath=null;}}
 if(u.modernKnockback){const k=u.modernKnockback,q=b.time+EPS>=k.starts+k.duration?1:Math.min(1,Math.max(0,(b.time-k.starts)/Math.max(.001,k.duration)));u.x=q===1?k.to.x:k.from.x+(k.to.x-k.from.x)*q;u.y=q===1?k.to.y:k.from.y+(k.to.y-k.from.y)*q;u.modernKnockbackHeight=k.height*4*q*(1-q);u.navPath=null;if(q>=1){delete u.modernKnockback;u.modernKnockbackHeight=0;if(k.record.ActionOnLanding)run(b,k.record.ActionOnLanding,{...context(b,k.context,data),unit:u});}}
 if(u.modernGuardDash){const dash=u.modernGuardDash;if(b.time+EPS>=dash.starts){if(dash.area===null){const a=createArea(b,dash.record.SpawnAEO,{unit:u,owner:u.owner,team:u.team,level:u.level,data});dash.area=a?.id;effect(b,u.def.source.DashEffect,{unit:u,team:u.team});}const len=distance(dash.from,dash.to),duration=Math.max(.001,len/((u.def.source.JumpSpeed||400)/60));dash.progress=Math.min(1,dash.progress+dt/duration);u.x=dash.from.x+(dash.to.x-dash.from.x)*dash.progress;u.y=dash.from.y+(dash.to.y-dash.from.y)*dash.progress;u.visualState='dash';if(dash.progress>=1){const a=(b.areas||[]).find(v=>v.id===dash.area);if(a)a.ends=b.time;for(const tag of state(u).tags)if(tag.token===dash.token)tag.until=b.time+ms(u.def.source.DashLandingTime);delete u.modernGuardDash;relocate(b,u,u.x,u.y);u.visualState='idle';}}}
 const burst=u.modernBurst;if(burst){let guard=0;while(burst.charges<burst.maximum&&b.time+EPS>=burst.reloadAt&&guard++<MAX_STEPS){burst.charges=Math.min(burst.maximum,burst.charges+Math.max(1,Number(burst.record.RechargeIncrement)||1));burst.reloadAt+=Math.max(.001,ms(burst.record.RechargeTime));}if(burst.charges===burst.maximum){burst.depleted=false;burst.reloadAt=Infinity;}}
 if(u.modernDash){const dash=u.modernDash,r=dash.record,source=u.def.source;if(!alive(u)){finishDash(u,b);}else if(b.time+EPS>=dash.nextAt){let target=b.getEntity?.(dash.target);if(!alive(target)||dash.visited.includes(target.id)){const resolver=data.targetResolvers[r.TargetResolver],first=dash.visited.length===0;target=resolveTargets(b,data,u,resolver.Shape,resolver.Filter,'Closest',dash.visited).filter(v=>first||distance(u,v)<=(source.DashSecondaryRange||5500)/1000+(v.def?.radiusTiles||0))[0];dash.target=target?.id;}if(!target||dash.visited.length>=dash.max)finishDash(u,b);else{const len=distance(u,target),contact=source.DashToTargetRadius?(u.def.radiusTiles||0)+(target.def?.radiusTiles||0):0,step=Math.max(.001,(source.JumpSpeed||400)/60)*dt;u.visualState='dash';if(len<=step+contact+EPS){if(len>contact){u.x=target.x+(u.x-target.x)/Math.max(EPS,len)*contact;u.y=target.y+(u.y-target.y)/Math.max(EPS,len)*contact;}b.damage(target,b.scaleStat(source.DashDamage,source.Rarity||'Common',u.level),u);if(source.DashPushBack)b.push?.(target,target.x-u.x,target.y-u.y,source.DashPushBack/1000);effect(b,source.DashHitEffect,{unit:target,team:u.team});dash.visited.push(target.id);dash.target=null;dash.nextAt=b.time+ms(source.DashLandingTime);if(dash.visited.length>=dash.max)finishDash(u,b);}else{u.x+=(target.x-u.x)/len*step;u.y+=(target.y-u.y)/len*step;}}}}
 if(u.abilityState?.sourceOverride?.record?.ForceStopIfTrue&&evaluate(u.abilityState.sourceOverride.record.ForceStopIfTrue,b,{unit:u,data}))delete u.abilityState.sourceOverride;
 const buffs=activeBuffs(b,u,data),invisible=buffs.some(x=>x.record.Invisible);if(invisible){u.modernBuffInvisible=true;u.invisible=true;}else if(u.modernBuffInvisible){u.invisible=false;u.modernBuffInvisible=false;}
 for(const {name,record}of buffs)if(record.AliveIfTrue!==undefined&&!evaluate(record.AliveIfTrue,b,{unit:u,data})){delete u.buffs[name];}
 const t=tags(u,b.time);if(t.has('NO_ATTACK')||t.has('COMBAT_DISABLED')||u.modernForcedAnimationUntil>b.time){u.windup=null;u.nextAttackAt=Math.max(u.nextAttackAt||0,b.time+dt);}
}
function attackProfile(b,u,data=K.DATA){let profile=u?.def?.source?.AttackSequenceList?.[u.attackSequenceIndex||0]||{};for(const{record}of activeBuffs(b,u,data))if(record.OverrideProjectile)profile={...profile,Projectile:record.OverrideProjectile,CustomFirstProjectile:null};return profile;}
function rates(b,u,data=K.DATA){const t=tags(u,b.time);for(const {record}of activeBuffs(b,u,data))for(const tag of flags(record.GameTagsToSet))t.add(tag);return{speed:t.has('NO_MOVE')||t.has('NO_MOVE_ALLOW_ATTRACT')||t.has('COMBAT_DISABLED')?0:1,attack:t.has('NO_ATTACK')||t.has('COMBAT_DISABLED')||u.modernForcedAnimationUntil>b.time||u.modernBurst?.charges===0?0:(attackProfile(b,u).HitSpeedMultiplier||100)/100,spawn:1};}
function damageModifier(b,target,amount,source,opt={},data=K.DATA){if(tags(target,b.time).has('NO_DAMAGE'))return 0;const counter=target.modernActions?.counter;if(counter&&!opt.reflected&&opt.melee&&!opt.projectile&&alive(source)&&source.team!==target.team&&b.time+EPS>=counter.readyAt){const r=counter.record,c={...context(b,counter.context,data),unit:target,instigator:source,damage:amount,context:{[r.DamageKey||'damage']:amount},team:target.team,data},rates=b.buffs?.(target)||{speed:1,attack:1};if(rates.speed||rates.attack){counter.readyAt=b.time+ms(r.Cooldown);if(r.SelfAction)run(b,r.SelfAction,c);if(r.InstigatorAction)run(b,r.InstigatorAction,{...c,unit:source,instigator:target});return amount*(Number(r.DefenseScalar)||0);}}if(target.modernGuardDash&&b.time<target.modernGuardDash.starts+ms(target.def.source.DashImmuneToDamageTime)&&!opt.ignoreImmunity)return 0;if(target.modernDash&&b.time<target.modernDash.startedAt+ms(target.def.source.DashImmuneToDamageTime)&&!opt.ignoreImmunity)return 0;let value=amount;for(const {record}of activeBuffs(b,source,data)){if(record.DamageMultiplier!==undefined)value*=record.DamageMultiplier/100;if(target.king!==undefined&&record.CharacterCrownTowerDamagePercent!==undefined)value*=record.CharacterCrownTowerDamagePercent/100;}let reduction=0;for(const {record}of activeBuffs(b,target,data))reduction=Math.max(reduction,Number(record.DamageReduction)||0);value*=Math.max(0,100-reduction)/100;const unkillable=tags(target,b.time).has('UNKILLABLE')||activeBuffs(b,target,data).some(x=>flags(x.record.GameTagsToSet).includes('UNKILLABLE'));if(unkillable&&!(target.shield>0))value=Math.min(value,Math.max(0,target.hp-1));return Math.max(0,value);}
function onDamage(b,u,amount,source,opt={},data=K.DATA){for(const child of [u])for(const listener of child.modernActions?.listeners||[])if(listener.type==='parent-damage'&&listener.record.TriggerOnParentDamaged&&b.time+EPS>=listener.lastAt+ms(listener.record.TimeThreshold)){listener.lastAt=b.time;run(b,listener.record.ActionToRun,{...context(b,listener.context,data),unit:child,instigator:u});}if(source)u.modernLastAttacker=source.id;for(const [name,v]of Object.entries(u.buffs||{}))if(v.until>b.time&&data.buffs?.[v.name||name]?.RemoveOnHit)delete u.buffs[name];const r=u.def?.source;for(const key of ['OnDamagedAction','OnDamageTakenAction'])if(r?.[key])executeAction(b,r[key],{unit:u,instigator:r.OnDamageTakenActionInstigatorAsSelf?u:source,damage:amount,team:source?.team,data});}
function onAttack(b,u,target,data=K.DATA){const burst=u.modernBurst;if(burst){burst.charges=Math.max(0,burst.charges-1);burst.reloadAt=b.time+ms(burst.record.RechargeTime);if(burst.charges===0)burst.depleted=true;}for(const [name,v]of Object.entries(u.buffs||{}))if(v.until>b.time&&data.buffs?.[v.name||name]?.RemoveOnAttack)delete u.buffs[name];for(const field of ['OnAttackAction','OnAttackSelfAction'])if(u.def?.source?.[field])executeAction(b,u.def.source[field],{unit:u,targetId:target?.id,data});}
function onAttackStart(b,u,target,data=K.DATA){const burst=u.modernBurst;if(burst)u.attackSequenceIndex=burst.depleted?Number(burst.record.DepletedAttackSequenceIndex)||0:Number(burst.record.AttackSequenceIndices?.[Math.max(0,burst.charges-1)])||0;if(u?.def?.source?.OnStartingAttackAction)executeAction(b,u.def.source.OnStartingAttackAction,{unit:u,targetId:target?.id,data});}
function onHit(b,u,target,data=K.DATA){if(u?.def?.source?.OnHitTargetAction)executeAction(b,u.def.source.OnHitTargetAction,{unit:u,targetId:target?.id,instigator:target,data});}
function onAreaStart(b,a,data=K.DATA){if(a.modernStarted)return;a.modernStarted=true;const source=b.getEntity?.(a.modernSourceId);if(data.areas?.[a.name]?.OnStartingAction)executeAction(b,data.areas[a.name].OnStartingAction,{unit:a,instigator:source,parentAreaId:a.id,team:a.team,owner:a.owner,level:a.level,data});}
function onAreaHit(b,a,u,data=K.DATA){const r=data.areas?.[a.name];if(!r?.OnHitAction)return;const source=b.getEntity?.(a.modernSourceId);executeAction(b,r.OnHitAction,{unit:u,instigator:source,parentAreaId:a.id,team:a.team,owner:a.owner,level:a.level,data});}
function onAreaEnd(b,a,data=K.DATA){if(a.modernEnded)return;a.modernEnded=true;const r=data.areas?.[a.name];if(r?.OnLifeTimeEndAction)executeAction(b,r.OnLifeTimeEndAction,{unit:a,instigator:b.getEntity?.(a.modernSourceId),owner:a.owner,team:a.team,level:a.level,parentAreaId:a.id,data});}
function matchesFilter(data,name,parent,u,time=parent?.modernTime??u?.modernTime??0){if(Resolvers&&data.gameObjectFilters?.[name])return Resolvers.matchesFilter(data,name,parent,u,time,{tags});const r=data.gameObjectFilters?.[name]||data.filters?.[name];if(!r)return false;if(r.MatchTeamEnemy&&!r.MatchTeamOwn&&u.team===parent.team||r.MatchTeamOwn&&!r.MatchTeamEnemy&&u.team!==parent.team)return false;if(r.MatchSelf&&u.id!==parent.id)return false;if(r.MatchTypeBuildings&&!r.MatchTypeCharacters&&!u.building)return false;if(r.IncludeCharactersWithData&&!list(r.IncludeCharactersWithData).includes(u.entity))return false;if(r.ExcludeCharactersWithData&&list(r.ExcludeCharactersWithData).includes(u.entity))return false;const tagSet=tags(u,time);if(flags(r.FilterTags).some(tag=>tagSet.has(tag)))return false;for(const f of flags(r.Filters)){if(f==='Buildings'&&u.building||f==='Summoner'&&u.king||f==='PrincessTowers'&&u.king===false||f==='Clones'&&u.cloned||f==='Flying'&&u.air||f==='Hidden'&&u.hidden||f==='Invisible'&&u.invisible||f==='IgnoreResurrect'&&u.def?.source?.IgnoreResurrect||f==='NoHitpointComponent'&&!u.maxHp||f==='Jumping'&&u.riverJump||f==='Dragging'&&u.drag||f==='DashImmune'&&(u.dash||u.modernDash)||f==='Underground'&&u.hidden||f==='Towers'&&u.king!==undefined)return false;}return true;}
function onDeath(b,victim,data=K.DATA){if(victim.modernDeathHandled)return;victim.modernDeathHandled=true;for(const timer of victim.modernActions?.timers||[])if(timer.type==='ActionSpawnResetableAeO'){const a=(b.areas||[]).find(v=>v.id===timer.areaId);if(a)a.ends=b.time+ms(timer.record.StayAliveAfterParentDiesDuration);}const killer=b.getEntity?.(victim.modernLastAttacker);for(const field of ['OnKilledAction','OnDeathAction'])if(victim.def?.source?.[field])executeAction(b,victim.def.source[field],{unit:victim,instigator:killer,data});if(killer?.def?.source?.OnKilledDoneAction)executeAction(b,killer.def.source.OnKilledDoneAction,{unit:killer,instigator:victim,context:{hp:victim.maxHp},data});b.modernCorpses||(b.modernCorpses=[]);b.modernCorpses.push({id:victim.id,entity:victim.entity,owner:victim.owner,team:victim.team,card:victim.card,levelGroupId:victim.levelGroupId,x:victim.x,y:victim.y,born:b.time});if(b.modernCorpses.length>500)b.modernCorpses.splice(0,b.modernCorpses.length-500);for(const u of b.units||[]){if(!alive(u))continue;for(const listener of state(u).listeners){if(listener.type!=='troop-death')continue;const r=listener.record;if(r.MatchOnlyOwnSpawnedTroops&&victim.owner!==u.owner||r.MatchOnlyFromSameOwnerIndex&&victim.owner!==u.owner)continue;if(r.TroopFilter&&!matchesFilter(data,r.TroopFilter,u,victim,b.time))continue;executeAction(b,r.ActionToRun,{...context(b,listener.context,data),unit:u,instigator:victim,targetId:victim.id,context:{hp:victim.maxHp},data});}}}
function onCardDeploy(b,card,seat,data=K.DATA){for(const u of b.units||[]){if(!alive(u)||u.owner!==seat)continue;for(const listener of state(u).listeners){if(listener.type!=='card-deploy')continue;const r=listener.record,group=data.cardGroups?.[r.CardGroup],names=[...list(group?.PlayableCards),...list(group?.SupportCards)];if(r.CardGroup&&!names.includes(card.source?.Name)&&!names.includes(card.id))continue;executeAction(b,r.OnActivateAction,{...context(b,listener.context,data),unit:u,data});}}}
function onProjectileSpawn(b,p,data=K.DATA){p.formId=p.formId??p.attacker?.formId;const r=data.projectiles?.[p.name];if(r?.OnStartingAction)executeAction(b,r.OnStartingAction,{unit:p,instigator:p.attacker,owner:p.owner,team:p.team,level:p.level,data});}
function onProjectileHit(b,p,target,data=K.DATA){const r=data.projectiles?.[p.name];if(r?.OnHitTargetAction&&target)executeAction(b,r.OnHitTargetAction,{unit:target,instigator:p.attacker,targetId:target.id,owner:p.owner,team:p.team,level:p.level,data});}
function onProjectileReached(b,p,data=K.DATA){const r=data.projectiles?.[p.name];for(const field of ['OnTargetReachedAction','OnReachedTargetAction','OnDestroyedAction'])if(r?.[field])executeAction(b,r[field],{unit:p,instigator:p.attacker,owner:p.owner,team:p.team,level:p.level,data});}
function onBuffAdded(b,u,name,buffState,data=K.DATA,c={}){if(buffState?.buffs){data=buffState;buffState=null;}const r=data.buffs?.[name];if(!r)return;const entries=Object.entries(u.buffs||{}),entry=entries.find(([key,v])=>v===buffState)||entries.find(([key,v])=>(v.name||key)===name&&v.until>b.time);if(!entry)return;const [key,v]=entry,s=state(u);s.buffLifecycles||(s.buffLifecycles={});const previous=s.buffLifecycles[key];if(previous&&previous.until>b.time+EPS){previous.until=v.until;return;}const ctx={...c,unit:u,team:c.team??v.sourceTeam??u.team,level:c.level??v.level??u.level,data};s.buffLifecycles[key]={name,until:v.until,context:serialized(ctx)};if(r.OnStartAction)executeAction(b,r.OnStartAction,ctx);}
function ignoresPushback(b,u,data=K.DATA){return tags(u,b.time).has('NO_PUSHBACK')||activeBuffs(b,u,data).some(({record})=>record.IgnorePushback||record.IgnorePushBack);}
function healingLimit(b,u,data=K.DATA){let percent=Math.max(100,u.modernOverhealPercent||100);for(const {record}of activeBuffs(b,u,data))percent=Math.max(percent,Number(record.AllowedOverHealPerc)||100);return(u.maxHp||0)*percent/100;}
function refreshAreas(b,data=K.DATA){for(const a of b.areas||[]){const r=data.areas?.[a.name],source=b.getEntity?.(a.modernSourceId);if(r?.LinkToInstigatorLife&&a.modernSourceId!=null&&!alive(source))a.ends=Math.min(a.ends,b.time);if(r?.FollowBehaviour==='FollowParent'&&alive(source)){a.x=source.x+(a.modernFollowOffset?.x||0);a.y=source.y+(a.modernFollowOffset?.y||0);}}}
function handlePending(b,p,data=K.DATA){if(p.type==='modern-action')return resolvePending(b,p,data);if(p.type!=='impact'||p.modernDeflected)return false;const pr=data.projectiles?.[p.name];if(!flags(pr?.DeflectBehaviour).includes('CheckOnlyTargetPosition'))return false;const a=(b.areas||[]).find(a=>a.team!==p.team&&a.ends>b.time&&data.areas?.[a.name]?.DeflectProjectilesEnabled&&distance(a,p)<=(data.areas[a.name].Radius+(pr.DeflectRadius||0))/1000);if(!a)return false;const target=(b.active||[]).filter(u=>u.king&&u.team===p.team).sort((x,y)=>Math.abs(x.x-p.x)-Math.abs(y.x-p.x)||x.id-y.id)[0];if(!target)return false;b.resolvePending({...p,team:a.team,owner:a.owner,x:target.x,y:target.y,modernDeflected:true});return true;}
function tickBattle(b,dt=0,data=K.DATA){refreshAreas(b,data);for(const p of b.projectiles||[])if(p.modernActions)tickEntity(b,p,dt,data);for(const a of b.areas||[]){const r=data.areas?.[a.name],source=b.getEntity?.(a.modernSourceId);if(a.modernSpawnLimit!==undefined&&a.spawned>=a.modernSpawnLimit)a.modernSpawningComplete=true;if(a.modernActions)tickEntity(b,a,dt,data);if(!r?.DeflectProjectilesEnabled||a.ends<=b.time||!alive(source))continue;
 for(const p of b.projectiles||[]){if(p.done||p.team===a.team||p.modernDeflected)continue;const pr=data.projectiles?.[p.name]||{},behaviour=flags(pr.DeflectBehaviour);if(behaviour.includes('NoDeflect')||pr.CustomDeflectAction&&!canExecuteAction(b,pr.CustomDeflectAction,{data}).ok)continue;const point=behaviour.includes('CheckOnlyTargetPosition')?{x:p.tx,y:p.ty}:p,radius=(Number(r.Radius)||0)/1000+(Number(pr.DeflectRadius)||0)/1000;if(distance(point,a)>radius+EPS)continue;const original=p.attacker,target=alive(original)?original:(b.active||[]).filter(u=>u.king!==undefined&&u.team===p.team).sort((x,y)=>distance(x,original||p)-distance(y,original||p)||x.id-y.id)[0];p.modernDeflected=true;p.team=a.team;p.owner=source.owner;p.source=source.id;p.attacker=source;p.hit?.clear();if(behaviour.includes('InvertDirection')){p.vx=-p.vx;p.vy=-p.vy;const remaining=Math.max(.5,(p.range||10)-(p.travel||0));p.tx=p.x+p.vx*remaining*SX;p.ty=p.y+p.vy*remaining*SY;p.travel=0;p.target=null;}else if(target){p.target=target.id;p.tx=target.x;p.ty=target.y;}else{p.tx=p.startX??p.x;p.ty=p.startY??p.y;}effect(b,r.DeflectedProjectileEffect,{unit:source,team:a.team});if(pr.ActionOnDeflector)executeAction(b,pr.ActionOnDeflector,{unit:source,instigator:original,team:p.team,level:p.level,data});if(pr.CustomDeflectAction)executeAction(b,pr.CustomDeflectAction,{unit:p,instigator:source,team:p.team,level:p.level,data});if(pr.DeflectedCharacterSpawn)p.modernSpawnCharacter=pr.DeflectedCharacterSpawn;
 }}}
function audit(data=K.DATA){const supported=[],unsupported=[],reasons={};for(const id of Object.keys(data.actions||{})){const r=canExecuteAction(null,id,{data});(r.ok?supported:unsupported).push(id);if(!r.ok)reasons[id]=r.reason;}const abilities={};for(const [id,config]of Object.entries(data.abilities||{}))abilities[id]=canExecuteAbility(null,config,{data});return{snapshot:data.snapshot,actions:{total:supported.length+unsupported.length,supported:supported.length,unsupported:unsupported.length,supportedIds:supported,unsupportedIds:unsupported,reasons},abilities};}
return{executeAction,canExecuteAction,executeAbility,canExecuteAbility,canDeployCard,coverage,beginAbility,endPendingAbility,resolvePending,handlePending,onSpawn,tickEntity,rates,attackProfile,damageModifier,onDamage,onAttackStart,onAttack,onHit,onDeath,onAreaStart,onAreaHit,onAreaEnd,onCardDeploy,onProjectileSpawn,onProjectileHit,onProjectileReached,onBuffAdded,ignoresPushback,healingLimit,refreshAreas,tickBattle,tags,matchesFilter,evaluate,audit};
});
