/* Card-form inventory transactions. Source unlock amounts; no payment requests. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./catalog.js'):root.RoyaleCatalog,n?require('./card-forms.js'):root.RoyaleCardForms);if(n)module.exports=api;else root.RoyaleModernRewards=api;})(globalThis,function(K,Forms){'use strict';
const registry=Forms.defaultRegistry;
const integer=v=>Math.max(0,Math.min(9999999,Math.floor(Number(v)||0))),clone=p=>JSON.parse(JSON.stringify(p||{})),required=f=>f.requiredShards||(f.kind==='hero'?200:6);
function heroCoinPolicy(){const source=K.DATA.modernProgression?.consumables?.HeroCoin;return{cap:source?.MaxAmountValue?.[0]||200,gems:source?.OnOverflowGemValue??1};}
// Native OverflowOnce and the current official conversion rule allow the receipt
// which crosses the cap. The next receipt converts only its new coins to gems.
function addHeroCoins(p,count){const amount=integer(count),before=integer(p.heroCoins),policy=heroCoinPolicy();if(before<policy.cap)p.heroCoins=Math.min(9999999,before+amount);else{p.heroCoins=before;p.gems=Math.min(9999999,integer(p.gems)+amount*policy.gems);}return amount;}
const SHARD_COPIES=Object.freeze([{max:10,Common:100,Rare:15,Epic:1,Legendary:0},{max:12,Common:140,Rare:30,Epic:2,Legendary:1},{max:15,Common:170,Rare:40,Epic:3,Legendary:1},{max:18,Common:250,Rare:55,Epic:6,Legendary:1},{max:21,Common:420,Rare:75,Epic:8,Legendary:1},{max:24,Common:590,Rare:100,Epic:12,Legendary:1},{max:27,Common:1000,Rare:135,Epic:16,Legendary:2},{max:Infinity,Common:1250,Rare:190,Epic:21,Legendary:2}]);
function shardConversion(p,form,count){if(!count)return 0;const trophies=Math.max(integer(p.trophies),integer(p.highestTrophies)),arenas=K.DATA.modernProgression?.arenas,arena=arenas?.filter(a=>a.trophies<=trophies).at(-1)?.number||K.DATA.arenas.filter(a=>a.IsInUse!==false&&a.TrophyLimit<=trophies).sort((a,b)=>a.Arena-b.Arena).at(-1)?.Arena||1,card=K.CARD_BY_ID[form.baseCardId],per=SHARD_COPIES.find(r=>arena<=r.max)?.[card?.rarity]||0,copies=per*count;p.copies||={};p.copies[form.baseCardId]=Math.min(100000,integer(p.copies[form.baseCardId])+copies);return copies;}
function addShards(p,id,count,{registry:r=registry}={}){const form=r.get(id);if(!form||form.kind!=='evolution')return false;const n=integer(count),need=required(form);p.formShards||={};p.unlockedForms||=[];const before=p.unlockedForms.includes(id)?need:Math.min(need,integer(p.formShards[id])),credited=Math.min(n,need-before);p.formShards[id]=before+credited;if(p.formShards[id]>=need&&!p.unlockedForms.includes(id))p.unlockedForms.push(id);shardConversion(p,form,n-credited);return true;}
function formQuote(p,id,{registry:r=registry}={}){const form=r.get(id),owned=!!form&&(form.kind==='champion'||p.unlockedForms?.includes(id)||form.kind==='evolution'&&integer(p.formShards?.[id])>=required(form)),amount=form?.kind==='hero'?integer(p.heroCoins):integer(p.formShards?.[id]),need=form?required(form):0,capability=form?Forms.formCapability(id,r):{ok:false,reason:'Unknown form'},supported=capability.ok,canUnlock=!!form&&!owned&&supported&&form.kind==='hero'&&amount>=need,canApplyWild=!!form&&!owned&&supported&&form.kind==='evolution'&&integer(p.evoWildShards)>0&&amount<need;return{form,owned,amount,required:need,wild:integer(p.evoWildShards),supported,canUnlock,canApplyWild,reason:!form?'Unknown form':!supported?'Unavailable for battle: '+capability.reason:owned?'Already unlocked':form.kind==='hero'&&!canUnlock?'Requires '+need+' Hero Coins':form.kind==='evolution'&&!canApplyWild?'Collect Evolution Shards or a Wild Shard':''};}
function chooseHero(profile,id,{registry:r=registry}={}){const p=clone(profile),q=formQuote(p,id,{registry:r});if(q.form?.kind!=='hero'||!q.canUnlock)return{ok:false,profile:p,reason:q.form?.kind!=='hero'?'Choose a Hero':q.reason};p.heroCoins=integer(p.heroCoins)-q.required;p.unlockedForms||=[];p.unlockedForms.push(id);return{ok:true,profile:p,form:q.form};}
function applyWildShard(profile,id,count=1,{registry:r=registry}={}){const p=clone(profile),q=formQuote(p,id,{registry:r});if(!Number.isInteger(count)||count<1||!q.canApplyWild||count>q.wild||count>q.required-q.amount)return{ok:false,profile:p,reason:!q.form?'Unknown form':q.owned?'Already unlocked':!q.supported?q.reason:'Choose available Wild Shards for an Evolution'};p.evoWildShards=q.wild-count;addShards(p,id,count,{registry:r});return{ok:true,profile:p,form:q.form};}
function unlock(p,id,{wild=false,registry:r=registry}={}){const form=r.get(id);if(!form||form.kind==='champion')return{ok:false,reason:'Choose a Hero or Evolution'};if(p.unlockedForms?.includes(id))return{ok:false,reason:'Already unlocked'};if(form.kind==='hero'){const result=chooseHero(p,id,{registry:r});if(result.ok){p.heroCoins=result.profile.heroCoins;p.unlockedForms=result.profile.unlockedForms;}return{ok:result.ok,form,reason:result.reason};}const support=Forms.formCapability(id,r);if(!support.ok)return{ok:false,reason:'Unavailable for battle: '+support.reason};const have=integer(p.formShards?.[id]),need=Math.max(0,required(form)-have);if(need>0&&(!wild||integer(p.evoWildShards)<need))return{ok:false,reason:'Requires '+required(form)+' Evolution Shards'};p.evoWildShards=integer(p.evoWildShards)-need;addShards(p,id,need,{registry:r});return{ok:true,form};}
function grantForm(p,id,{registry:r=registry}={}){const f=r.get(id);if(!f||f.kind==='champion')return false;p.unlockedForms||=[];if(p.unlockedForms.includes(id)){if(f.kind==='hero')addHeroCoins(p,20);return true;}if(f.kind==='evolution')return addShards(p,id,required(f),{registry:r});p.unlockedForms.push(id);return true;}
function consumable(item,amount){const rarity=String(item).match(/^Wildcard(Common|Rare|Epic|Legendary|Champion)$/)?.[1];if(rarity)return{wildcards:{[rarity]:amount}};if(/Hero/i.test(item))return{heroCoins:amount};if(/Evolution|EvoShard|WildcardShard/i.test(item))return{evoWildShards:amount};const book=String(item).match(/^Book(Common|Rare|Epic|Legendary)$/)?.[1];if(book)return{magicItems:{[book.toLowerCase()+'-book']:amount}};return null;}
function randomFor(seed){let h=2166136261;for(const c of String(seed))h=Math.imul(h^c.charCodeAt(0),16777619);return()=>{h|=0;h=h+0x6D2B79F5|0;let t=Math.imul(h^h>>>15,1|h);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
function pick(rows,random){const total=rows.reduce((s,r)=>s+Math.max(0,Number(r.weight)||0),0);if(!total)return null;let n=random()*total;for(const r of rows){n-=Math.max(0,Number(r.weight)||0);if(n<0)return r.value;}return rows.at(-1)?.value;}
function mergeRewards(a,b){for(const key of ['gold','gems','heroCoins','evoWildShards'])a[key]=(a[key]||0)+(b[key]||0);for(const key of ['wildcards','magicItems','formShards','towerTroops'])for(const [id,n]of Object.entries(b[key]||{})){a[key]||={};a[key][id]=(a[key][id]||0)+n;}for(const key of ['cards','sourceCosmetics','unlockedForms'])if(b[key]){a[key]||=[];a[key].push(...b[key]);}return a;}
function poolReward(row,random,profile,arena){const amount=row.Amount||1;
 if(row.CardEvoShards){const form=registry.forms.find(f=>f.kind==='evolution'&&f.source.Name.startsWith(row.CardEvoShards+'_'));return form?{formShards:{[form.id]:amount}}:null;}
 if(row.HeroForm){const form=registry.forms.find(f=>f.kind==='hero'&&(f.id===row.HeroForm||f.source.Name===row.HeroForm||K.CARD_BY_ID[f.baseCardId]?.source.Name===row.HeroForm));return form?{unlockedForms:[form.id]}:null;}
 if(row.Consumables)return consumable(row.Consumables,amount);
 if(row.Resource)return row.Resource==='Gold'?{gold:amount}:row.Resource==='Diamonds'?{gems:amount}:null;
 if(row.Cards){const card=K.CARDS.find(c=>c.source.Name===row.Cards);return card?{cards:[{id:card.id,count:amount}]}:null;}
 if(row.SpellRarity){const pool=K.CARDS.filter(c=>c.rarity===row.SpellRarity);const card=pool[Math.floor(random()*pool.length)];return card?{cards:[{id:card.id,count:amount}]}:null;}
 for(const key of ['Banners','Emotes','TowerSkins','AlbumSnippets'])if(row[key])return{sourceCosmetics:[{kind:key,id:row[key],count:amount}]};return null;
}
function mysteryBox(name,{profile={},arenaNumber=1,seed='',random=randomFor(seed)}={}){const m=K.DATA.modernProgression,box=m?.mysteryBoxes?.[name];if(!box||!Array.isArray(box.Rarities)||!box.Rarities.length)return{ok:false,reason:'Unknown reward chest'};let rank=0;for(let i=0;i<(box.SpinCount||0);i++)if(rank<box.Rarities.length-1&&random()*100<(box.UpgradeProbabilities?.[rank]||0))rank++;
 const rarityId=box.Rarities[rank],rarity=m.mysteryRarities[rarityId],arena=m.arenas.find(a=>a.number===arenaNumber)||m.arenas[0],rows=m.mysteryArenaRows.filter(r=>r.Rarity===(rarity?.ArenaData||rarityId)),amounts=rows.find(r=>r.Arena===arena.sourceName)||rows.find(r=>r.Arena==='TrainingCamp');if(!rarity||!amounts)return{ok:false,reason:'Reward chest data unavailable'};
 const categories=['Gold','RandomCard','ItemPool','WildcardCommon','WildcardRare','WildcardEpic','WildcardLegendary','WildcardChampion','WildcardShard','FullEvolution','HeroCoin','Gems','BookCardCommon','BookCardRare','BookCardEpic','BookCardLegendary','BookCardAll','Emote'],kind=pick(categories.filter(k=>rarity[k]>0).map(k=>({value:k,weight:rarity[k]})),random);let reward=null;
 if(kind==='Gold')reward={gold:amounts.Gold||0};else if(kind==='Gems')reward={gems:amounts.Gems||0};else if(kind==='HeroCoin')reward={heroCoins:amounts.HeroCoin||0};else if(kind==='WildcardShard')reward={evoWildShards:amounts.WildcardShard||0};else if(kind?.startsWith('Wildcard'))reward=consumable(kind,amounts[kind]||0);
 else if(kind?.startsWith('BookCard'))reward={magicItems:{[kind==='BookCardAll'?'all-book':kind.slice(8).toLowerCase()+'-book']:amounts[kind]||1}};
 else if(kind==='ItemPool'){const pool=m.itemPoolRows.filter(r=>r.PoolName===amounts.ItemPool),row=pick(pool.map(r=>({value:r,weight:r.Weight})),random);reward=row&&poolReward(row,random,profile,arena);}
 else if(kind==='FullEvolution'){const forms=registry.forms.filter(f=>f.kind==='evolution'&&!profile.unlockedForms?.includes(f.id)),form=forms[Math.floor(random()*forms.length)];reward=form?{formShards:{[form.id]:required(form)}}:{evoWildShards:6};}
 else if(kind==='RandomCard'){const options=['Common','Rare','Epic','Legendary','Champion'].flatMap(r=>[{value:{type:'card',rarity:r},weight:rarity['Card'+r]||0},{value:{type:'support',rarity:r},weight:rarity['SupportCard'+r]||0}]),selection=pick(options,random);if(selection?.type==='card'){const eligible=K.CARDS.filter(c=>c.rarity===selection.rarity&&(!K.DATA.arenas.find(a=>a.Name===c.arena)||K.DATA.arenas.find(a=>a.Name===c.arena).Arena<=arenaNumber));const c=pick(eligible.map(c=>({value:c,weight:profile.unlockedCards?.includes(c.id)?1:Number(rarity.CardNewWeightFactor)||1})),random);if(c)reward={cards:[{id:c.id,count:Math.max(1,Math.floor((amounts['Card'+selection.rarity]||1)*((rarity.CardAmountMinFactor||1)+random()*((rarity.CardAmountMaxFactor||1)-(rarity.CardAmountMinFactor||1))))) }]};}else if(selection){const pool=Object.entries(m.supportCards).filter(([,r])=>!r.NotInUse&&!r.NotVisible&&r.Rarity===selection.rarity),entry=pool[Math.floor(random()*pool.length)];if(entry)reward={towerTroops:{[entry[0]]:amounts['SupportCard'+selection.rarity]||1}};}}
 if(!reward)return{ok:false,reason:'This chest reward is not available yet'};return{ok:true,reward,box:name,rarity:rarityId,rank};}
return{addHeroCoins,addShards,grantForm,formQuote,chooseHero,applyWildShard,unlock,consumable,mysteryBox,mergeRewards};
});
