/* Account XP and tower strength read from the imported client experience table. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./catalog.js'):root.RoyaleCatalog);if(n)module.exports=api;else root.RoyalePlayerXP=api;})(globalThis,function(K){'use strict';
const rows=K.DATA.modernProgression.expLevels,MAX_KING_LEVEL=rows.length,MAX_TOWER_LEVEL=K.MAX_CARD_LEVEL,clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const CUMULATIVE={},TO_NEXT={};let total=0;for(const row of rows){const level=Number(row.Name);CUMULATIVE[level]=total;TO_NEXT[level]=level===MAX_KING_LEVEL?0:row.ExpToNextLevel;total+=row.ExpToNextLevel;}
Object.freeze(CUMULATIVE);Object.freeze(TO_NEXT);const MAX_XP=CUMULATIVE[MAX_KING_LEVEL];
function levelFromTotalXp(value){const xp=clamp(Math.floor(Number(value)||0),0,MAX_XP);let level=1;for(let i=2;i<=MAX_KING_LEVEL;i++){if(xp>=CUMULATIVE[i])level=i;else break;}return level;}
function progressFromTotalXp(value){const totalXp=clamp(Math.floor(Number(value)||0),0,MAX_XP),level=levelFromTotalXp(totalXp),row=rows[level-1],maxLevel=level===MAX_KING_LEVEL,need=TO_NEXT[level],into=maxLevel?0:clamp(totalXp-CUMULATIVE[level],0,need);return{level,kingLevel:level,towerLevel:row.TowerLevel,totalXp,xpIntoLevel:into,xpNeededForNextLevel:need,xpRemaining:maxLevel?0:need-into,progress01:maxLevel?1:into/Math.max(1,need),maxLevel};}
function legacyTotalXp(raw,fresh=false){if(Number.isFinite(Number(raw?.experience)))return clamp(Math.floor(Number(raw.experience)),0,MAX_XP);if(fresh)return 0;const tower=clamp(Math.floor(Number(raw?.level)||9),1,MAX_TOWER_LEVEL),candidate=rows.find(r=>r.TowerLevel>=tower),level=clamp(Math.floor(Number(raw?.kingLevel)||Number(candidate?.Name)||1),1,MAX_KING_LEVEL);return CUMULATIVE[level]+clamp(Math.floor(Number(raw?.xp)||0),0,Math.max(0,TO_NEXT[level]-1));}
function sync(profile){const p=progressFromTotalXp(profile.experience);profile.experience=p.totalXp;profile.kingLevel=p.kingLevel;profile.level=p.towerLevel;profile.xp=p.xpIntoLevel;profile.starPoints=Math.max(0,Math.floor(Number(profile.starPoints)||0));return p;}
function grant(profile,amount,reason='generic'){const add=Math.max(0,Math.floor(Number(amount)||0)),before=sync(profile),xpApplied=Math.min(add,MAX_XP-profile.experience),overflowToStarPoints=add-xpApplied;profile.experience+=xpApplied;profile.starPoints+=overflowToStarPoints;const p=sync(profile);return{amount:add,xpApplied,overflowToStarPoints,oldKingLevel:before.kingLevel,newKingLevel:p.kingLevel,leveledUp:p.kingLevel>before.kingLevel,reason,...p};}
function rarityRow(card){return K.DATA.rarities[typeof card==='string'?card:card?.rarity];}
function upgradeXp(card,level){const row=rarityRow(card),base=K.baseLevel(typeof card==='string'?card:card.rarity);return Math.max(0,Math.floor(Number(row?.UpgradeExp?.[Math.max(0,Math.floor(level)-base)])||0));}
function donationXp(card,count=1){return Math.max(0,Math.floor(Number(rarityRow(card)?.DonateXP)||0))*Math.max(0,Math.floor(Number(count)||0));}
return{MAX_KING_LEVEL,MAX_TOWER_LEVEL,MAX_XP,CUMULATIVE,TO_NEXT,levelFromTotalXp,progressFromTotalXp,legacyTotalXp,sync,grant,upgradeXp,donationXp};
});
