/* Shared offline offers. Prices below retain this game's local economy;
   source unlock costs and rewards never imply a live cash offer. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./catalog.js'):root.RoyaleCatalog,n?require('./progression.js'):root.RoyaleProgression,n?require('./card-forms.js'):root.RoyaleCardForms,n?require('./modern-rewards.js'):root.RoyaleModernRewards,n?require('./cosmetics.js'):root.RoyaleCosmetics);if(n)module.exports=api;else root.RoyaleShopModel=api;})(globalThis,function(K,R,F,MR,Cos){'use strict';
const DAY=86400000,integer=v=>Math.max(0,Math.floor(Number(v)||0)),hash=s=>{let h=2166136261;for(const c of String(s))h=Math.imul(h^c.charCodeAt(0),16777619);return(h>>>0).toString(16).padStart(8,'0');};
const freeze=o=>{if(o&&typeof o==='object'){for(const v of Object.values(o))freeze(v);Object.freeze(o);}return o;};
function windowFor(now=Date.now()){const day=Math.floor(now/DAY);return typeof now==='number'&&Number.isFinite(now)&&now>=0&&Number.isSafeInteger(day)&&day<=99999999?'content-shop-'+day:null;}
function towerQuantity(card){return({Common:20,Rare:5,Epic:1,Legendary:1,Champion:1})[card.rarity]||1;}
// Existing card shop packs are Common20/100gold, Rare5/250gold,
// Epic1/500gold, Legendary1/1000gold. Support copies share that policy.
function towerPrice(card,count){return count*({Common:5,Rare:50,Epic:500,Legendary:1000,Champion:1000}[card.rarity]||1000);}
function offers(profile={},options={}){const window=windowFor(options.now),r=options.registry||F.defaultRegistry,t=MR.towerRegistry(options),out=[];if(!window)return freeze(out);const arena=R.highestArena(profile).number;
 function add(kind,targetId,quantity,currency,price,item,{owned=false,supported=true,gate=true,reason='',provenance='local-adaptation',step=0,name=targetId}={}){const id=kind+':'+targetId,canonical={id,window,kind,targetId,quantity,currency,price,step,arena},fingerprint=hash(JSON.stringify(canonical)),receiptKey=window+':'+id+':'+step,bought=profile.contentShopPurchases?.[receiptKey]===1,affordable=integer(profile[currency])>=price,available=!owned&&!bought&&supported&&gate&&affordable,blocked=owned?'Already owned':bought?'Offer already purchased':!supported?reason||'Unavailable for battle':!gate?reason||'Reach the required arena':!affordable?'Not enough '+({heroCoins:'Hero Coins',evoWildShards:'Wild Shards',gold:'gold',gems:'gems'}[currency]||currency):'';const preview=MR.previewTyped(profile,[item],{...options,voluntary:true});out.push({id,window,fingerprint,receiptKey,kind,targetId,name,quantity,currency,price,owned,bought,supported:supported&&preview.ok,available:available&&preview.ok,reason:blocked||(!preview.ok?preview.reason:''),provenance,reward:preview.ok?preview.reward:null,items:[item]});}
 for(const form of r.forms){if(form.kind==='hero'){const q=MR.formQuote(profile,form.id,{registry:r});add('hero',form.id,1,'heroCoins',q.required,{kind:'form',formId:form.id},{owned:q.owned,supported:q.supported,reason:q.reason,provenance:'source-unlock-cost',name:(K.CARD_BY_ID[form.baseCardId]?.name||form.baseCardId)+' Hero'});}else if(form.kind==='evolution'){const q=MR.formQuote(profile,form.id,{registry:r});add('evo-shard',form.id,1,'evoWildShards',1,{kind:'form-shard',formId:form.id,count:1},{owned:q.owned,supported:q.supported,reason:q.reason,step:q.amount,provenance:'source-shard-exchange',name:(K.CARD_BY_ID[form.baseCardId]?.name||form.baseCardId)+' Evolution Shard'});}}
 for(const card of t.catalog||[]){const support=t.capability?.(card.id)||{ok:false,reason:'Tower behavior is unavailable'},quantity=towerQuantity(card);add('tower-troop',card.id,quantity,'gold',towerPrice(card,quantity),{kind:'tower-troop',towerTroopId:card.id,count:quantity},{supported:support.ok,gate:arena>=(card.unlockArena||0),reason:support.ok?'Reach Arena '+card.unlockArena:support.reason,name:card.name});}
 for(const emote of Cos.emotes.filter(e=>!e.free))add('emote',emote.id,1,'gems',emote.cost,{kind:'cosmetic',cosmeticKind:'Emotes',id:emote.id,count:1},{owned:profile.ownedEmotes?.includes(emote.id),name:emote.name});
 for(const skin of Cos.towerSkins.filter(s=>!s.free))add('tower-skin',skin.id,1,'gems',skin.cost,{kind:'cosmetic',cosmeticKind:'TowerSkins',id:skin.id,count:1},{owned:profile.ownedTowerSkins?.includes(skin.id),name:skin.name});
 return freeze(out);
}
function progressionItems(profile,channel,index,options={}){const r=options.registry||F.defaultRegistry,t=MR.towerRegistry(options),n=channel==='pass'?index+1:index,arena=R.highestArena(profile).number,seed=profile.world?.seed||0,items=[];if(!Number.isSafeInteger(n)||n<1||!['pass','crown'].includes(channel))return items;
 const supported=r.forms.filter(f=>f.kind!=='champion'&&F.formCapability(f.id,r).ok);
 if(n%5===0&&supported.some(f=>f.kind==='hero'&&!profile.unlockedForms?.includes(f.id)))items.push({kind:'hero-coins',count:20});
 if(n%10===0&&supported.some(f=>f.kind==='evolution'&&!profile.unlockedForms?.includes(f.id)))items.push({kind:'wild-shards',count:1});
 if(n%7===0){const pool=(t.catalog||[]).filter(c=>arena>=(c.unlockArena||0)&&t.capability?.(c.id)?.ok);if(pool.length){const c=pool[parseInt(hash(seed+':'+channel+':tower:'+n),16)%pool.length];items.push({kind:'tower-troop',towerTroopId:c.id,count:towerQuantity(c)});}}
 if(n%(channel==='pass'?10:25)===0){const pool=[...Cos.emotes.filter(e=>!e.free&&!profile.ownedEmotes?.includes(e.id)).map(e=>({kind:'cosmetic',cosmeticKind:'Emotes',id:e.id,count:1})),...Cos.towerSkins.filter(s=>!s.free&&!profile.ownedTowerSkins?.includes(s.id)).map(s=>({kind:'cosmetic',cosmeticKind:'TowerSkins',id:s.id,count:1}))];if(pool.length)items.push(pool[parseInt(hash(seed+':'+channel+':cosmetic:'+n),16)%pool.length]);}
 return items;
}
return{DAY,windowFor,offers,progressionItems,towerQuantity,towerPrice};
});
