/* Main source tower troops. Optional content is separate from base-card decks. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./catalog.js'):root.RoyaleCatalog,()=>n?require('./modern-actions.js'):root.RoyaleModernActions);if(n)module.exports=api;else root.RoyaleTowerTroops=api;})(globalThis,function(K,actions){'use strict';
const DEFAULT='King_PrincessTowers',source=K.DATA.modernProgression?.supportCards||{},groups=K.DATA.sourceSpawnGroups||{},names={King_PrincessTowers:'Tower Princess',King_CannonTowers:'Cannoneer',King_KnifeTowers:'Dagger Duchess',King_ChefTowers:'Royal Chef'},num=(n,d=0,max=999999)=>Number.isFinite(n)?Math.min(max,Math.max(0,Math.floor(n))):d;
const catalog=Object.freeze(Object.entries(source).filter(([id,r])=>!r.NotVisible&&!r.NotInUse&&K.DATA.entities[r.StatCharacter]).map(([id,r])=>Object.freeze({id,name:names[id]||id,rarity:r.Rarity,entity:r.StatCharacter,source:r,unlockArena:K.DATA.modernProgression.arenas.find(a=>a.sourceName===r.UnlockArena)?.number??K.DATA.arenas.find(a=>a.Name===r.UnlockArena)?.Arena??0})));
const byId=Object.fromEntries(catalog.map(c=>[c.id,c]));
function normalize(raw={}){const unlockedTowerTroops=[...new Set([DEFAULT,...(Array.isArray(raw.unlockedTowerTroops)?raw.unlockedTowerTroops:[]).filter(id=>byId[id])])],towerTroopLevels=Object.fromEntries(catalog.map(c=>[c.id,Math.max(K.baseLevel(c.rarity),num(raw.towerTroopLevels?.[c.id],K.baseLevel(c.rarity),K.MAX_CARD_LEVEL||13))])),towerTroopCopies=Object.fromEntries(catalog.map(c=>[c.id,num(raw.towerTroopCopies?.[c.id],0,100000)]));return{unlockedTowerTroops,towerTroopLevels,towerTroopCopies,selectedTowerTroop:byId[raw.selectedTowerTroop]&&unlockedTowerTroops.includes(raw.selectedTowerTroop)?raw.selectedTowerTroop:DEFAULT};}
function capability(id,duo=false){const c=byId[id];if(!c)return{ok:false,reason:'Unknown tower troop'};const group=groups[duo?c.source.SpawnGroup2v2:c.source.SpawnGroup],objects=group?.Objects;if(!Array.isArray(objects)||!objects.length)return{ok:false,reason:'Tower troop source group is unavailable'};for(const item of objects){if(item.Data==='KingTower')continue;const r=actions()?.canDeployCard?.(null,{source:{SummonCharacter:item.Data}});if(!r?.ok)return{ok:false,reason:'Tower troop unsupported: '+(r?.reason||item.Data)};}return{ok:true,objects};}
function quote(profile,id,{casual=false,duo=false}={}){const card=byId[id],owned=id===DEFAULT||profile?.unlockedTowerTroops?.includes(id),arena=K.DATA.modernProgression?.arenas?.filter(a=>(profile?.highestTrophies??profile?.trophies??0)>=a.trophies).at(-1)?.number||1,support=capability(id,duo),unlocked=casual||owned&&arena>=(card?.unlockArena||0);return{card,unlocked,supported:support.ok,reason:support.reason||(!unlocked?'Unlock this tower troop first':''),canUse:!!card&&unlocked&&support.ok,level:profile?.towerTroopLevels?.[id]||K.baseLevel(card?.rarity)};}
function select(profile,id,options={}){const q=quote(profile,id,options);return q.canUse?{ok:true,profile:{...profile,selectedTowerTroop:id}}:{ok:false,profile,reason:q.reason};}
function upgradeQuote(profile,id){const card=byId[id];if(!card)return{canUpgrade:false,reason:'Unknown tower troop'};const inv=normalize(profile),level=inv.towerTroopLevels[id],rarity=K.DATA.rarities[card.rarity],idx=level-K.baseLevel(card.rarity),maxLevel=K.maxLevel(card.rarity),kingLevel=num(profile?.level,1,K.MAX_CARD_LEVEL),levelCap=Math.min(maxLevel,kingLevel),gold=rarity?.UpgradeCost?.[idx]||0,copies=rarity?.UpgradeMaterialCount?.[idx]||0,haveCopies=inv.towerTroopCopies[id],q=quote({...profile,...inv},id),reason=!q.canUse?q.reason:level>=maxLevel?'Maximum level':level>=levelCap?'Upgrade your King Tower first':!Number.isSafeInteger(profile.gold)||profile.gold<gold||haveCopies<copies?'Not enough gold or tower copies':'';return{card,level,nextLevel:Math.min(maxLevel,level+1),maxLevel,kingLevel,levelCap,gold,copies,haveCopies,unlocked:q.unlocked,supported:q.supported,canUpgrade:!reason,reason};}
function upgrade(profile,id,expectedLevel){const p=JSON.parse(JSON.stringify(profile||{})),q=upgradeQuote(p,id);if(!Number.isInteger(expectedLevel)||expectedLevel!==q.level)return{ok:false,profile:p,reason:'The tower upgrade changed. Refresh its details.'};if(!q.canUpgrade)return{ok:false,profile:p,reason:q.reason};p.gold-=q.gold;p.towerTroopCopies||={};p.towerTroopLevels||={};p.towerTroopCopies[id]=q.haveCopies-q.copies;p.towerTroopLevels[id]=q.level+1;return{ok:true,profile:p,quote:q,xpEarned:0};}
function setup(b,options){b.seatTowerTroops=b.seats.map(seat=>options.seatTowerTroops?.[seat]||(seat===0?b.profile.selectedTowerTroop:DEFAULT)||DEFAULT);b.seatTowerTroopLevels=b.seats.map(seat=>Math.min(b.kingLevels[seat],num(options.seatTowerTroopLevels?.[seat],seat===0&&!b.syntheticProfile&&!b.queueType?b.profile.towerTroopLevels?.[b.seatTowerTroops[seat]]||b.kingLevels[seat]:b.queueType==='trophy-road'&&seat===0?b.profile.towerTroopLevels?.[b.seatTowerTroops[seat]]||b.kingLevels[seat]:b.kingLevels[seat],K.MAX_CARD_LEVEL||13)));for(const [seat,id]of b.seatTowerTroops.entries()){const q=quote(b.profile,id,{casual:seat!==0||b.queueType&&b.queueType!=='trophy-road'||b.practice,duo:b.is2v2});if(!q.canUse)throw Error(q.reason||'Invalid tower troop selection');}}
function entity(b,owner,king){const card=byId[b.seatTowerTroops?.[owner]],group=groups[b.is2v2?card?.source.SpawnGroup2v2:card?.source.SpawnGroup],objects=group?.Objects||[];return king?objects.find(o=>K.DATA.entities[o.Data]?.SkinType==='KingTower'||o.Data==='KingTower'||o.Data==='ChefTowerKing')?.Data||'KingTower':card?.entity||'PrincessTower';}
return{DEFAULT,catalog,get:id=>byId[id]||null,normalize,capability,quote,select,upgradeQuote,upgrade,setup,entity};
});
