/* One registry/factory for the Learning Center and headless workers. No silent
   mode substitution; the real arena, team size and rules run in self-play. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./core.js'):root.RoyaleCore,n?require('./training-decks.js'):root.RoyaleTrainingDecks,n?require('./boat-battle.js'):root.RoyaleBoatBattle);if(n)module.exports=api;else root.RoyaleTrainingModes=api;})(globalThis,function(C,D,Boat){'use strict';
const modes=Object.freeze([['Default','1v1'],['TeamVsTeam','2v2'],['Team3v3','3v3'],['TeamRumble','5v5 Team Rumble'],['BridgeBattle','Bridge'],['FourCardDeck','4 Card Deck'],['TwelveCardDeck','12 Card Deck'],['TwentyElixir','20 Elixir'],['OneShot','One Shot'],['RandomDeck','Random Deck'],['DoubleElixir','Double Elixir'],['TripleElixir','Triple Elixir'],['RampUp','Ramp Up'],['SuddenDeath','Sudden Death'],['7xElixir','Infinite Elixir'],['ClanWar_BoatBattle','Boat Battle']].map(([id,name])=>Object.freeze({id,name})));
function name(id){return modes.find(m=>m.id===id)?.name||String(id);}
function create(mode,options={}){if(!modes.some(m=>m.id===mode))throw Error('Unsupported training mode: '+mode);const seed=Number.isFinite(options.seed)?options.seed:1,arenaNumber=14,count=mode==='TeamRumble'?10:mode==='Team3v3'?6:mode==='TeamVsTeam'?4:2,level9=Object.fromEntries(C.CARDS.map(c=>[c.id,9])),decks=Array.from({length:count},(_,i)=>D.forMode(seed+11+i*97,arenaNumber,mode));if(mode==='FourCardDeck')for(let i=0;i<decks.length;i++)decks[i]=decks[i].slice(0,4);
 const b=new C.Battle({...options,seed,mode,arenaNumber,shuffleDeck:true,practice:true,queue:'self-play',recording:'compact',headless:true,decks,deck:decks[0],enemyDeck:decks[1],seatLevels:Array.from({length:count},()=>level9),kingLevels:Array(count).fill(9),kingLevel:9});
 if(mode==='ClanWar_BoatBattle'){const troops=C.CARDS.filter(c=>c.kind==='Troop'&&c.entity);Boat.configure(b,{hp:[1e9,1e9,1e9],cards:Array.from({length:3},(_,i)=>Array.from({length:4},(_,j)=>troops[(Math.abs(seed)+i*13+j*7)%troops.length].id))});}return b;}
return{modes,name,create};});
