/* One registry/factory for the Learning Center and headless workers. No silent
   mode substitution; the real arena, team size and rules run in self-play. */
(function(root,factory){const n=typeof module==='object'&&module.exports,api=factory(n?require('./core.js'):root.RoyaleCore,n?require('./training-decks.js'):root.RoyaleTrainingDecks,n?require('./boat-battle.js'):root.RoyaleBoatBattle,n?require('./progression.js'):root.RoyaleProgression);if(n)module.exports=api;else root.RoyaleTrainingModes=api;})(globalThis,function(C,D,Boat,R){'use strict';
const modes=Object.freeze([['Default','1v1'],['TeamVsTeam','2v2'],['Team3v3','3v3'],['TeamRumble','5v5 Team Rumble'],['BridgeBattle','Bridge'],['Touchdown','Touchdown'],['Touchdown2v2','2v2 Touchdown'],['Touchdown3v3','3v3 Touchdown'],['FourCardDeck','4 Card Deck'],['SixCardDeck','6 Card Deck'],['TwelveCardDeck','12 Card Deck'],['TwentyElixir','20 Elixir'],['UncappedElixir','Uncapped Elixir'],['OneShot','One Shot'],['RandomDeck','Random Deck'],['DoubleElixir','Double Elixir'],['TripleElixir','Triple Elixir'],['RampUp','Ramp Up'],['SuddenDeath','Sudden Death'],['7xElixir','Infinite Elixir'],['ClanWar_BoatBattle','Boat Battle']].map(([id,name])=>Object.freeze({id,name})));
function name(id){return modes.find(m=>m.id===id)?.name||String(id);}
function countFor(mode){return mode==='TeamRumble'?10:['Team3v3','Touchdown3v3'].includes(mode)?6:['TeamVsTeam','Touchdown2v2'].includes(mode)?4:2;}
function create(mode,options={}){if(!modes.some(m=>m.id===mode))throw Error('Unsupported training mode: '+mode);const seed=Number.isFinite(options.seed)?options.seed:1,arenaNumber=R.ARENAS.length,count=countFor(mode),tournamentLevel=C.DATA.rarities.Common.RelativeLevel+C.DATA.rarities.Common.TournamentLevelIndex+1,levels=Object.fromEntries(C.CARDS.map(c=>[c.id,Math.max(C.baseLevel(c.rarity),tournamentLevel)])),decks=Array.from({length:count},(_,i)=>D.forMode(seed+11+i*97,arenaNumber,mode));if(mode==='FourCardDeck')for(let i=0;i<decks.length;i++)decks[i]=decks[i].slice(0,4);
 const arenaId=options.arenaId||globalThis.RoyaleArenaSelection?.choose?.({mode,queue:'self-play',seed})||mode;
 const seatForms=options.seatForms||decks.map((deck,i)=>D.formsForDeck(deck,{arena:arenaNumber,casual:true,seed:seed+i*193}));
 const b=new C.Battle({...options,arenaId,seed,mode,arenaNumber,shuffleDeck:true,practice:true,queue:'self-play',recording:'compact',headless:true,decks,deck:decks[0],enemyDeck:decks[1],seatForms,formContext:{arena:arenaNumber,casual:true,unlockedForms:(C.DATA.forms||[]).map(f=>f.id)},seatLevels:Array.from({length:count},()=>levels),kingLevels:Array(count).fill(tournamentLevel),kingLevel:tournamentLevel});
 if(mode==='ClanWar_BoatBattle'){const troops=C.CARDS.filter(c=>c.kind==='Troop'&&c.entity);Boat.configure(b,{hp:[1e9,1e9,1e9],cards:Array.from({length:3},(_,i)=>Array.from({length:4},(_,j)=>troops[(Math.abs(seed)+i*13+j*7)%troops.length].id))});}return b;}
return{modes,name,countFor,create};});
